/* ===================== CASETRENING · DYBDETRENING =====================
   Selvrettet trening. Du skriver svaret, avslører fasiten, og markerer selv
   om du kunne det. Rene data — visningen ligger i js/bundle-dybde.js.

   To banker:
     struktur  — k3, k4, k5: nedbrytning, MECE, hypoteser, casetypene
     grunnlag  — k0, k1, k2: vurderingen, formatet, husene

   Fasiten skal si hva som skiller et sterkt svar fra et middels. Et riktig
   svar alene er ikke nok — det er forskjellen han skal se.
   ====================================================================== */
window.EDU_DATA = window.EDU_DATA || {};
window.EDU_DATA._dybdeA = {

  /* ==================================================================
     BANK 1 · STRUKTUR (k3, k4, k5)
     ================================================================== */
  "struktur": {
    "cats": ["Nedbrytning", "Hypotese", "MECE", "Casetyper"],
    "lvl": {
      "1": ["Nivå 1", "Definisjoner — si hva det er"],
      "2": ["Nivå 2", "Anvendelse — bruk det på et konkret tilfelle"],
      "3": ["Nivå 3", "Skreddersøm — bygg strukturen fra bunnen"],
      "4": ["Nivå 4", "Under press — gjør det på tid, høyt"]
    },
    "items": [

      /* --- de tre som allerede fantes, uendret --- */
      { "n": 1, "k": "Nedbrytning", "lvl": 1,
        "s": "Hva betyr MECE, og hvorfor er den andre halvdelen av kravet vanskeligere enn den første?",
        "f": "<b>Mutually Exclusive, Collectively Exhaustive</b> — grenene skal ikke overlappe, og til sammen skal de dekke hele problemet.<br><br>Den første halvdelen er lett å sjekke: legger to grener beslag på det samme? Den andre er vanskelig, for den krever at du vet hva du <i>ikke</i> har tenkt på. Den praktiske testen er å spørre: «hvis alle grenene mine var uendret, kunne resultatet likevel ha falt?» Er svaret ja, mangler du en gren.<br><br>Et profitt-tre er MECE av konstruksjon, fordi det bygger på en identitet: resultat = inntekter − kostnader. Det er derfor identiteter er tryggere utgangspunkt enn temalister." },

      { "n": 2, "k": "Hypotese", "lvl": 2,
        "s": "Du har strukturert en lønnsomhetscase. Intervjueren sier «hvor vil du begynne?». Hva er et sterkt svar, og hva er et svakt?",
        "f": "<b>Svakt:</b> «Jeg vil gjerne se på inntektene først.» Det er en rekkefølge, ikke en hypotese.<br><br><b>Sterkt:</b> «Besøket er oppgitt som flatt, så volumleddet kan jeg utelukke. Da må fallet ligge i pris eller i kostnad per enhet. Jeg vil begynne med de største kostnadspostene, fordi et fall på 30 prosent er for stort til å komme fra en liten post. Hypotesen min er at en variabel kostnad har vokst raskere enn inntekten.»<br><br>Forskjellen: du sier <i>hva du tror</i>, <i>hvorfor</i>, og <i>hva som ville avkreftet det</i>. Det gjør resten av casen til en test av hypotesen i stedet for en rundtur." },

      { "n": 3, "k": "Casetyper", "lvl": 2,
        "s": "Nevn de fem vanligste casetypene, og den ene setningen som fanger hva hver av dem egentlig spør om.",
        "f": "<b>Lønnsomhet:</b> hvilken del av resultatregnskapet har flyttet seg, og hvorfor?<br><b>Markedsinngang:</b> er markedet attraktivt, kan vi vinne i det, og er det verdt det sammenlignet med alternativene?<br><b>M&amp;A:</b> hva er målselskapet verdt for oss — som er noe annet enn hva det er verdt i seg selv?<br><b>Prising:</b> hva er kundens alternativ, og hvor mye av verdien vi skaper kan vi ta?<br><b>Estimering:</b> kan du bygge et forsvarlig tall fra noe du faktisk vet?<br><br>Legg merke til at ingen av dem er et rammeverk. Det er spørsmål — og strukturen skal bygges for å svare på nettopp det spørsmålet." },

      /* ================= NIVÅ 1 · DEFINISJONER ================= */

      { "n": 4, "k": "MECE", "lvl": 1,
        "s": "Nevn de fem måtene å være MECE på, med én linje om hva du deler etter i hver. Hvilken er raskest, og hvilken er svakest alene?",
        "f": "<b>Algebra:</b> en ligning der leddene til sammen <i>er</i> svaret.<br><b>Prosess:</b> en sekvens med start, midt og slutt.<br><b>Konseptuelt:</b> idékategorier du lager for akkurat dette problemet.<br><b>Segmentering:</b> skiver av samme populasjon.<br><b>Motsatte ord:</b> et begrep og komplementet.<br><br><b>Motsatte ord er både den raskeste og den svakeste</b> — «internt mot eksternt» gjør sjelden noe arbeid alene, fordi den ikke navngir én eneste driver.<br><br><b>Middels svar:</b> ramser opp de fem. <b>Sterkt svar:</b> legger til at dette er verktøy og ikke maler, og at det er problemet som velger verktøyet. Aller sterkest er å nevne at kombinasjonen algebra + prosess + segmentering er den som i praksis produserer driverbaserte trær — en identitet gir toppen, prosessen gir leddene under, segmenteringen gir spredningen." },

      { "n": 5, "k": "MECE", "lvl": 1,
        "s": "Hva er den ordentlige testen på om grenene dine er kollektivt uttømmende? Hvorfor holder det ikke å se etter overlapp?",
        "f": "<b>Testen:</b> kan du sette likhetstegn mellom grenene og resultatet? Kan du det, er dekningen aritmetikk. Kan du det ikke, er det retorikk — og retorikk har alltid hull du ikke kan se.<br><br>Å se etter overlapp tester bare <i>ME</i>. «Marked, konkurranse, intern drift, regulering» har ingen synlig overlapp og består derfor den overfladiske testen — samtidig som den mangler miks, som er den vanligste årsaken til fallende margin i det hele tatt.<br><br><b>Middels svar:</b> «jeg sjekker at ingenting mangler.» Det er ønsketenkning, ikke en test. <b>Sterkt svar:</b> stiller kontrollspørsmålet — «hvis alle grenene mine var uendret, kunne resultatet likevel ha falt?» — og viser at et ja betyr at en gren mangler." },

      { "n": 6, "k": "MECE", "lvl": 1,
        "s": "Hva betyr regelen «én akse per nivå», og hvilken konkret feil oppstår når den brytes?",
        "f": "Regelen: på hvert nivå i treet skal du dele etter <b>én</b> egenskap. Blander du to, får du grener som ikke er gjensidig utelukkende.<br><br><b>Skoleeksempelet:</b> setter du «ferskvare» og «kampanjesalg» ved siden av hverandre, hører en laksefilet på tilbud hjemme i begge. Riktig grep er å dele først på kategori, og la kampanjeandel være en driver <i>inne i</i> hver kategori.<br><br>Dette er den vanligste kilden til overlapp i ekte trær, og den er lett å oppdage selv: prøv å plassere ett konkret objekt — én vare, én kunde, én time — og se om det havner to steder.<br><br><b>Middels svar:</b> gjengir regelen. <b>Sterkt svar:</b> viser at feilen ikke bare er estetisk. Overlappende grener betyr at du dobbelttelller når du regner, og at intervjueren ikke kan stole på tallet du lander på." },

      { "n": 7, "k": "Nedbrytning", "lvl": 1,
        "s": "Hvor dypt skal et casetre gå? Gi stopp-regelen, og et eksempel på en gren som er for grunn og en som er dyp nok.",
        "f": "<b>Stopp-regelen:</b> gå ned til grenen navngir noe et menneske kan endre, eller et tall som finnes i klientens egne systemer.<br><br><b>For grunn:</b> «kostnader». Den er verken handlingsbar eller målbar.<br><b>Dyp nok:</b> «lønnstimer per åpningstime på ferskvaredisken». Den er begge deler — noen kan sette den, og den ligger i timelisten allerede.<br><br>Tre eller fire hovedgrener holder. Fem eller flere leses som manglende prioritering.<br><br><b>Middels svar:</b> «så dypt som mulig». Feil — dybde uten prioritering er bare mengde. <b>Sterkt svar:</b> sier at treet skal være <b>asymmetrisk</b>: tre nivåer ned i grenen du mistenker, ett nivå i resten. Et perfekt symmetrisk tre forteller intervjueren én ting, nemlig at du ikke har en mistanke." },

      { "n": 8, "k": "Nedbrytning", "lvl": 1,
        "s": "Fire krav til hvordan strukturen sies høyt. Nevn dem, og si hvilket av dem som oftest glemmes.",
        "f": "<b>1. Top-down.</b> Alle overskriftene først, så dybden. Intervjueren skal vite hvor mange grener som kommer før du begynner på den første.<br><b>2. Si hva du legger bort, og hvorfor.</b> Den billigste måten å vise dømmekraft på, og den eneste måten å bevise at utelatelsen er et valg og ikke en forglemmelse.<br><b>3. Avslutt med hypotese, startgren og datauttrekk.</b> Uten dette er strukturen ferdig, men casen har ikke begynt.<br><b>4. Snakk i hele setninger.</b> Grener lest opp som stikkord høres ut som en huskeliste, uansett hvor god nedbrytningen er.<br><br><b>Det som oftest glemmes er nummer to.</b> Kandidater tar med alt fordi de er redde for å bli tatt for å mangle noe — og oppnår det motsatte, siden ingenting da er prioritert.<br><br>Hele framføringen har et hardt tak på rundt to minutter. Bruker du fire, stjeler du dem fra løsningsbyggingen." },

      { "n": 9, "k": "Hypotese", "lvl": 1,
        "s": "Hva er en hypotese i en case? Nevn de tre tingene som stadig sies i stedet, og hva hver av dem egentlig er.",
        "f": "<b>En hypotese er en påstand om hvilken gren som bærer problemet, formulert så den kan vise seg å være feil.</b><br><br>De tre bedragerne:<ul><li>«Jeg starter på inntektssiden og går deretter til kostnadssiden.» — en <b>rekkefølge</b>. Den sier hva du skal gjøre, ikke hva du tror om verden, og kan ikke motbevises av noe tall.</li><li>«Marginfallet kan skyldes pris, volum eller miks.» — en <b>mulighetsliste</b>, treet ditt lest baklengs. Den utelukker ingenting og er derfor sann uansett hva dataene viser.</li><li>«Jeg tror dette er et lønnsomhetsproblem.» — en <b>omformulering av prompten</b>. Intervjueren fortalte deg nettopp det.</li></ul><b>Middels svar:</b> definerer hypotesen riktig. <b>Sterkt svar:</b> kjenner igjen at alle tre bedragerne føles som hypoteser i rommet, fordi de har hypoteseform — de er setninger som begynner med «jeg tror». Formen er ikke testen; falsifiserbarheten er." },

      { "n": 10, "k": "Hypotese", "lvl": 1,
        "s": "Gjengi den to-delte testen på om det du nettopp sa faktisk var en hypotese.",
        "f": "<b>Del 1 — peker den på én gren og bort fra minst én annen?</b> «Det ligger i ferskvare og ikke i prisbildet» gjør begge deler. «Det kan være flere ting» gjør ingen av dem.<br><br><b>Del 2 — kan noen levere deg et tall i morgen som gjør den usann?</b> Kan du ikke navngi det tallet, har du skrevet en formulering, ikke en hypotese.<br><br><b>Middels svar:</b> husker del 1. Det er den lette halvdelen, og den er nesten alltid oppfylt hos folk som har lest et kurs. <b>Sterkt svar:</b> vekter del 2 tyngst og sier hvorfor: en hypotese uten et navngitt datauttrekk kan ikke tapes, og noe som ikke kan tapes gir intervjueren ingenting å vurdere. Poenget er ikke å ha rett — det er å ha risikert noe." },

      { "n": 11, "k": "Casetyper", "lvl": 1,
        "s": "To casetyper står ikke i femmerlisten: vekst og kostnad/operations. Hva spør hver av dem egentlig om, og hvor ryker de fleste?",
        "f": "<b>Vekst:</b> hvilke vekstveier er store nok til å bety noe? Todelingen er samme mot nytt marked × samme mot nytt produkt, med et kapabilitets- og risikolag under. <i>Der de fleste ryker:</i> de lister ideer uten å prioritere.<br><br><b>Kostnad / operations:</b> hvor er flaskehalsen, og er kuttet strukturelt? <i>Der de fleste ryker:</i> de optimaliserer et trinn som ikke er flaskehalsen.<br><br><b>Middels svar:</b> nevner begge og stopper. <b>Sterkt svar:</b> legger til at en vekstcase avgjøres i prioriteringen, ikke i idémyldringen — hver idé skal ha et grovt størrelsesanslag og en gjennomførbarhetsvurdering — og at to ting glemmes systematisk: at vekst koster kapital og folk, og at nytt produkt kan spise det gamle. På kostnadssiden er den tilsvarende markøren å skille strukturelt fra kosmetisk kutt, og å ikke regne med 100 prosent utnyttelse, som ingen anlegg har." },

      { "n": 12, "k": "Casetyper", "lvl": 1,
        "s": "Tre casetyper passer ikke i en boks: turnaround, PE-vurdering og offentlig sektor. Hvordan brytes hver av dem ned?",
        "f": "<b>Turnaround:</b> lønnsomhetstreet <i>pluss en tidsakse</i>. Stopp blødningen (likviditet), diagnostisér om problemet er strukturelt eller operasjonelt, og skill hva som må gjøres innen 90 dager fra det som tar tre år.<br><br><b>PE-vurdering:</b> vokser markedet, kan målet fortsette å vinne, holder enhetsøkonomien, hva kan velte dealen — pluss verdiskapingsplan, holdingperiode på tre til fem år og exit-rute.<br><br><b>Offentlig sektor / NGO:</b> målfunksjonen er ikke profitt. Si eksplisitt hva som maksimeres og under hvilken budsjettbeskrankning — typisk effekt per krone, rekkevidde, kvalitet, gjennomførbarhet.<br><br><b>Middels svar:</b> gjengir de tre nedbrytningene. <b>Sterkt svar:</b> ser hva de har til felles — alle tre legger en <i>ekstra dimensjon</i> oppå et vanlig tre. Turnaround legger på tid, PE legger på exit, offentlig sektor bytter ut målfunksjonen. Det er den ekstra dimensjonen som er hele casen; treet under er kjent stoff." },

      /* ================= NIVÅ 2 · ANVENDELSE ================= */

      { "n": 13, "k": "MECE", "lvl": 2,
        "s": "En byggevarekjede selger til proff og privat. Dekningsgraden er 18 prosent på proff og 30 prosent på privat, og ingen av dem har endret seg. Miksen har gått fra 60/40 proff/privat til 75/25. Regn ut hva som skjedde med den samlede dekningsgraden, og si hva det beviser.",
        "f": "<b>År 1:</b> 0,60 × 18 % + 0,40 × 30 % = 10,8 + 12,0 = <b>22,8 %</b><br><b>År 2:</b> 0,75 × 18 % + 0,25 × 30 % = 13,5 + 7,5 = <b>21,0 %</b><br><b>Fall: 1,8 prosentpoeng — uten at én eneste pris eller innkjøpsavtale er endret.</b><br><br>Det beviser at miks er en egen gren, ikke en underkategori av pris. Regner du på kjedens samlede dekningsgrad, ser du et fall og leter etter en prisendring som ikke finnes.<br><br><b>Middels svar:</b> regner riktig og sier «det er miks». <b>Sterkt svar:</b> sier hva det betyr for <i>neste trekk</i>: hvis begge segmentene er flate mens totalen faller, er hele fallet miks, og da er casen ikke lenger en marginsak — den er et spørsmål om hvorfor proffandelen vokser, og om det er ønsket. En kjede som vinner proffkunder kan ha en fallende dekningsgrad og en stigende <i>bunnlinje</i> samtidig, siden proffkunden kjøper langt mer per besøk." },

      { "n": 14, "k": "MECE", "lvl": 2,
        "s": "«Er det markedet eller er det oss?» er snittet motsatte ord. Når er det riktig valg, og når er det latskap?",
        "f": "<b>Riktig når spørsmålet faktisk er stilt.</b> I oppdrettscasen spør styret nøyaktig det, og lakseprisen er lik for alle — da er snittet ikke bare lovlig, det er det som avgjør casen. Noe som er felles for hele bransjen kan ikke forklare at bare vi faller.<br><br><b>Latskap når du bruker det som første gren uten at noe i prompten peker dit.</b> «Internt mot eksternt» navngir ingen driver, gir ingen tall å be om, og kan ikke prioriteres — begge halvdeler er like store og like tomme.<br><br><b>Middels svar:</b> «det kommer an på casen». <b>Sterkt svar:</b> gir testen — <i>finnes det et konkurrent- eller kategoritall som ville avgjort spørsmålet på ett minutt?</i> Finnes det, er snittet riktig og du ber om tallet. Finnes det ikke, har du delt problemet i to bokser du ikke kan fylle. Verktøyet velges av problemet, ikke av vanen." },

      { "n": 15, "k": "Nedbrytning", "lvl": 2,
        "s": "En kjede med 60 bilverksteder har fallende resultat per verksted. Du vurderer å dele treet per verksted. Hvorfor er det nesten alltid feil akse, og hva deler du etter i stedet?",
        "f": "<b>Feilen:</b> 60 grener som ser like ut er ikke 60 grener, det er én gren gjentatt 60 ganger. Regelen er å <b>velge aksen der du venter spredning</b> — en akse uten spredning er en akse uten informasjon.<br><br><b>Aksene med spredning på et verksted:</b><ul><li><b>Arbeidstype:</b> service og EU-kontroll (forutsigbar tid, presset pris) mot reparasjon (uforutsigbar tid, høyere margin) mot dekk og rekvisita.</li><li><b>Hvem som betaler:</b> forsikringsoppgjør og leasingavtale med fremforhandlet timepris, mot privatkunde som betaler listepris.</li><li><b>Mekanikertimen:</b> fakturerbare timer som andel av betalte timer — det er utnyttelsesgraden, og den er verkstedets egen.</li></ul><b>Middels svar:</b> «jeg deler per verksted og finner de dårligste». Det gir deg en rangering, ikke en årsak. <b>Sterkt svar:</b> bruker verkstedene som <i>spredningsmål</i> og ikke som grener: hvis det beste og det dårligste verkstedet har samme miks og samme timepris, men ulik fakturerbar andel, har du funnet driveren på ett minutt — og da er den variabelen grenen, ikke geografien." },

      { "n": 16, "k": "Nedbrytning", "lvl": 2,
        "s": "En studentsamskipnad går med underskudd på studentboligene og ber om hjelp. Hva skjer hvis du importerer profittreet, og hva er den riktige toppen på treet?",
        "f": "<b>Første regel er å starte med målfunksjonen:</b> hva maksimeres, under hvilken beskrankning? En samskipnad maksimerer <i>antall studenter med rimelig bolig av forsvarlig standard</i>, under to beskrankninger: budsjett og husleieregulering. Husleien er politisk bundet nedenfra og oppad.<br><br><b>Hva profittreet gjør:</b> det gir deg en inntektsside med bare ett virkemiddel — hev husleien — som er nøyaktig det oppdraget forbyr. Du bruker halve strukturen på en gren som er låst.<br><br><b>Riktig topp:</b> kostnad per utleid hybelmåned, delt i <i>kapitalkostnad per enhet</i> (byggekostnad, tomt, finansiering, levetid), <i>driftskostnad per enhet</i> (energi, vedlikehold, vaktmester, renhold) og <i>utnyttelse</i> (tomgang mellom semestre, som er systematisk og kjent på forhånd).<br><br><b>Middels svar:</b> sier «det er ikke profitt, det er samfunnsnytte» og blir stående der. <b>Sterkt svar:</b> viser at beskrankningen flytter treet konkret — når prisen er låst, er hele casen en kostnad- og utnyttelsescase, og den mest verdifulle grenen er ofte tomgangen om sommeren, fordi den er 100 prosent kjent og null prosent utnyttet." },

      { "n": 17, "k": "Hypotese", "lvl": 2,
        "s": "Et forsikringsselskap har fått dårligere combined ratio på bilforsikring. Din hypotese er at det er skadefrekvensen og ikke prisen. Skriv «testen er …» og «den faller hvis …».",
        "f": "<b>Testen er</b> skadefrekvens (antall skader per forsikret bilår) og gjennomsnittlig skadeutbetaling, hver for seg, per kundekohort og per tegningsår — holdt mot premie per bilår i samme kohort.<br><br><b>Den faller hvis</b> skadefrekvensen er flat på tvers av kohorter, og hele bevegelsen ligger i premien per bilår. Da er det ikke risiko som har endret seg, men prisen vi tar for den.<br><br><b>Hvorfor de to leddene må splittes:</b> combined ratio er et forhold, og et forhold kan bevege seg fra teller eller nevner. Ber du om «combined ratio over tid», får du tilbake nøyaktig tallet du allerede har.<br><br><b>Middels svar:</b> «jeg vil se på skadetallene». <b>Sterkt svar:</b> navngir <i>nivået</i> uttrekket skal på — per kohort og tegningsår, ikke i sum — fordi et selskap som vokser raskt kan ha uendret risiko i hver kohort og likevel stigende samlet frekvens, hvis de nye kundene er systematisk dårligere. Det er miks-effekten i forsikringsdrakt, og den er usynlig i totalen." },

      { "n": 18, "k": "Hypotese", "lvl": 2,
        "s": "Du har akkurat sagt hypotesen din. Intervjueren svarer: «Vi har sjekket det. Netto pris per kanal er flat.» Hva sier du, ordrett?",
        "f": "Setningen har <b>tre deler</b> og tar rundt elleve sekunder:<br><br><i>«Da faller hypotesen min. Det betyr at netto pris ikke er kilden, og at kostnad per solgte enhet er det eneste leddet igjen som er stort nok til å forklare fallet. Jeg vil derfor se på lønnstimer per solgte enhet, splittet på fast og innleid.»</i><br><br><b>Erkjenn — si hva det utelukker — oppgi neste trekk.</b><br><br><b>Middels svar:</b> «ok, da ser jeg på kostnadene i stedet.» Det er del tre alene, og det leses som å hoppe videre.<br><br><b>Sterkt svar:</b> tar med del to. Å si <i>hva som nå er utelukket</i> viser at du bruker informasjonen til å krympe søkerommet, ikke bare til å bytte tema. Og det aller viktigste: <b>ikke bli taus.</b> Et motargument midt i casen er nesten alltid informasjon, ikke en felle — BCG lister «ignorér tilbakemelding» blant tingene man ikke skal gjøre. En kandidat som forkaster hypotesen sin på et tall scorer høyere enn en som fikk rett uten å ha risikert noe." },

      { "n": 19, "k": "Casetyper", "lvl": 2,
        "s": "Et selskap skal prise en ny tjeneste. Variabel kostnad er 340 kroner per enhet. Kundens neste-beste alternativ koster 900 kroner, og vår løsning sparer kunden ytterligere 260 kroner i arbeidstid. Sett gulv og tak, og si hva som avgjør prisen mellom dem.",
        "f": "<b>Gulv = 340 kr</b> (variabel kostnad per enhet).<br><b>Tak = 900 + 260 = 1 160 kr</b> (kundens neste-beste alternativ pluss den kvantifiserte verdien av differansen).<br><b>Intervallet er 820 kroner bredt — og avstanden gulv–tak <i>er</i> prisingsmakten.</b><br><br>Hva som avgjør plasseringen: <b>målet</b>. Priser du for margin, legger du deg høyt og aksepterer lavere volum. Priser du for markedsandel, legger du deg lavt for å flytte kunder fra alternativet. Konkurrentprisene sier hvor i intervallet markedet forventer deg.<br><br><b>Middels svar:</b> regner ut gulv og tak og foreslår «midt imellom, si 750». Et tall uten et mål er en gjetning med tre sifre.<br><br><b>Sterkt svar:</b> avklarer målet <i>før</i> tallet, og legger til to ting: elastisitet og konkurrentrespons — en prisreduksjon som utløser priskrig gjør alle fattigere, inkludert klienten som «vant». Og en observasjon som er verdt en hel gren: er intervallet smalt, er dette egentlig ikke en prisingscase, men en kostnadscase." },

      { "n": 20, "k": "Casetyper", "lvl": 2,
        "s": "Markedsinngang har fire spørsmål i rekkefølge. Nevn dem, si hvorfor rekkefølgen er poenget, og hva som er den vanligste tabben.",
        "f": "<b>1. Er markedet attraktivt?</b> Størrelse, vekst, kundesegmenter, konsentrasjon, regulering, inngangsbarrierer.<br><b>2. Kan vi vinne der?</b> Forretningsmessig og teknisk kapabilitet, differensiering, konkurrentenes sannsynlige respons.<br><b>3. Lønner det seg?</b> Marked × oppnåelig andel × margin − inngangskostnad, med breakeven, tilbakebetalingstid og alternativkostnad.<br><b>4. Hvordan går vi inn?</b> Bygge selv, kjøpe eller joint venture, timing, pilot.<br><br><b>Rekkefølgen er poenget</b> fordi hvert spørsmål kan avslutte casen. Er markedet lite og krympende, er spørsmål to til fire bortkastet tid.<br><br><b>Den vanligste tabben:</b> markedsandelen plukket ut av lufta. «Vi tar 10 prosent» er ikke en forutsetning, det er en gjetning med to sifre — og den bærer hele lønnsomhetsregnestykket.<br><br><b>Middels svar:</b> husker alle fire lagene. <b>Sterkt svar:</b> sier at spørsmål to er det som skiller A fra C. De fleste regner på markedet og glemmer kapabiliteten — de svarer på om markedet er attraktivt, ikke på hvorfor <i>akkurat vi</i> skulle vinne i det. Og de avklarer hva suksess betyr for klienten: andel, profitt eller strategisk fotfeste gir tre ulike anbefalinger." },

      /* ================= NIVÅ 3 · SKREDDERSØM ================= */

      { "n": 21, "k": "MECE", "lvl": 3,
        "s": "Prompt: En apotekkjede med 180 apotek har hatt flat omsetning og fallende driftsresultat i tre år. Reseptvarer er prisregulert; handelsvarer er det ikke. Velg én av de fem MECE-måtene, begrunn valget, og bygg tre hovedgrener.",
        "f": "<b>Valget: segmentering — fordi prompten har gitt deg spredningen gratis.</b> Reseptvarer og handelsvarer har ikke bare ulik margin, de har ulik <i>mekanikk</i>: den ene har låst pris og fri kostnad, den andre har fri pris. Å behandle apoteket som én butikk er å gjennomsnitte to forretningsmodeller.<br><br><b>Tre grener:</b><ul><li><b>Reseptsiden.</b> Antall ekspederte resepter × regulert margin per pakke. Prisen er låst, så hele grenen er volum og kostnad per ekspedisjon — særlig farmasøyttimer per resept, siden ekspedisjonen krever autorisert personell.</li><li><b>Handelsvaresiden.</b> Bruttomargin per varegruppe (hudpleie, kosttilskudd, egne merkevarer) og hver gruppes andel av kurven. Dette er der prisingsmakten faktisk finnes.</li><li><b>Trafikk og konvertering.</b> Resepten drar kunden inn; spørsmålet er hvor mange som legger noe i kurven i tillegg, og hvor stor kurven er. Her binder de to grenene sammen.</li></ul><b>Middels svar:</b> velger algebra og bygger et generisk pris-ganger-volum-tre. Det er ikke galt, men det utnytter ikke det ene faktumet prompten ga fra seg.<br><br><b>Sterkt svar:</b> sier eksplisitt hvorfor reguleringen bestemmer snittet — <i>en akse er verdt noe når grenene oppfører seg systematisk forskjellig, og prisregulering garanterer det.</i> Aller sterkest: peker på at hvis reseptvolumet vokser mens resultatet faller, kan hele problemet være at den lønnsomme halvdelen krymper som andel, altså miks — og at farmasøytlønn er en kostnad som skalerer med den ulønnsomme halvdelen." },

      { "n": 22, "k": "MECE", "lvl": 3,
        "s": "Prompt: En flyplass har outsourcet bagasjehåndteringen. Andelen forsinket bagasje har doblet seg på ett år, og kontrakten har bøter. Bruk prosess-snittet og bygg leddene.",
        "f": "<b>Prosessen, fra fly til fly:</b><ul><li><b>Innsjekk og innlevering</b> — antall skranker og selvbetjeningspunkter i rushtimen.</li><li><b>Sortering</b> — sorteringsanleggets kapasitet i kolli per time, og andel som må håndteres manuelt fordi merkelappen ikke leses.</li><li><b>Transport til flysiden</b> — antall vogner og traktorer, og kjøreavstand til gaten.</li><li><b>Lasting</b> — bemanning per fly og tid per fly, mot planlagt bakketid.</li><li><b>Lossing og transfer</b> — den kritiske: minste tillatte overføringstid mellom to fly.</li><li><b>Utlevering på båndet</b> — antall bånd og tid fra on-block til første koffert.</li></ul><b>Hvorfor prosessen er riktig snitt:</b> hver eneste koffert må passere hvert eneste ledd, i denne rekkefølgen. Da må forsinkelsen nødvendigvis ligge i ett av dem, og kapasiteten i systemet er kapasiteten i det svakeste leddet.<br><br><b>Middels svar:</b> bygger leddene og stopper. <b>Sterkt svar:</b> legger til den ene tingen som gjør prosesstrær nyttige — <i>mål hvert ledd mot etterspørselen inn i det leddet, ikke mot hverandre</i>. Et ledd med lav kapasitet er ikke flaskehalsen hvis ingenting står i kø foran det. Og aller sterkest: sier at forsinkelsen sannsynligvis er konsentrert i tid, ikke i sted — be om andel forsinket bagasje per time gjennom døgnet før du velger ledd, siden en flyplass har to daglige topper og et anlegg som klarer snittet fint kan bryte sammen i tre timer." },

      { "n": 23, "k": "MECE", "lvl": 3,
        "s": "Prompt: En privat barnehagekjede med 90 barnehager får skjerpet bemanningsnorm og samtidig fallende barnekull i sine kommuner. Lag konseptuelle kategorier — kategorier ingen regnskapslinje deler etter — og si hvorfor de er riktige her.",
        "f": "<b>Kategoriene deles etter hva kjeden <i>kan gjøre noe med</i>, fordi begge sjokkene er utenfra:</b><ul><li><b>Det som er bundet av lov.</b> Bemanningsnorm, pedagognorm, arealkrav, makspris på foreldrebetaling. Null handlingsrom — men de definerer gulvet for kostnad per plass, og det gulvet skal regnes ut først.</li><li><b>Det som er bundet av bygningen.</b> Husleie, antall godkjente plasser, hvor barnehagen ligger i forhold til hvor barna faktisk bor om fem år. Handlingsrom finnes, men bare på års sikt og bare gjennom oppsigelse eller flytting.</li><li><b>Det som er fritt i morgen.</b> Vikarbruk mot fast bemanning, gruppestørrelse innenfor normen, åpningstid, matservering, innkjøpsavtaler på tvers av 90 enheter.</li></ul><b>Hvorfor konseptuelt slår algebra her:</b> et kostnadstre ville stilt husleie og vikarbruk side om side som to like store poster. Men den ene kan endres på mandag og den andre om tre år, og casen handler om et sjokk som allerede har truffet. <b>Handlingsrom er den aksen beslutningen har, selv om ingen regnskapslinje deler slik.</b><br><br><b>Middels svar:</b> lager tre kategorier og lar det stå. <b>Sterkt svar:</b> sier hva hver kategori skal brukes til — den bundne kategorien gir deg <i>hvor mye som må dekkes</i>, den frie gir deg <i>hvor mye du kan hente</i>, og differansen forteller om dette i det hele tatt er reddbart uten å legge ned enheter. Det er den differansen som er anbefalingen. Advarselen som hører til: konseptuelle kategorier er det mest allsidige verktøyet og det som lettest degenererer til malbruk, fordi 3C og 4P er nettopp konseptuelle kategorier laget av noen andre, til noe annet." },

      { "n": 24, "k": "Nedbrytning", "lvl": 3,
        "s": "Prompt: En matkasseleverandør med 70 000 abonnenter har vokst hvert år, men taper fortsatt penger. Investoren vil vite om dette noen gang blir lønnsomt. Bygg tre hovedgrener, og si hva du legger bort og hvorfor.",
        "f": "<b>Toppen er ikke resultat, den er <i>enhetsøkonomi</i>:</b> tjener vi penger på én kunde over kundens levetid? Et abonnementsselskap som vokser vil alltid vise underskudd hvis anskaffelseskostnaden bokføres i dag og inntekten kommer over to år — så det samlede resultatet svarer ikke på spørsmålet investoren stilte.<br><br><b>Gren 1 — dekningsbidrag per levert kasse.</b> Salgspris minus råvarekost, emballasje, plukk og pakking, og siste mil. Siste mil er den som ikke skalerer med volum, men med <i>tetthet</i>: antall leveringer per rutekilometer.<br><b>Gren 2 — levetid.</b> Churn per kohort og per måned i kundeforholdet, og antall kasser per kunde per måned. Her ligger casen: en kunde som bestiller tre uker av fire er en helt annen kunde enn en som bestiller én.<br><b>Gren 3 — anskaffelseskostnad per betalende kunde.</b> Markedsføring per registrering, delt på andelen som fortsatt betaler etter introtilbudet. Introtilbudet hører hjemme her, ikke i pris.<br><br><b>Legges bort:</b> lagerkostnad og administrasjon. De er faste, kjente og for små til å snu fortegnet på et selskap som taper penger per kunde — og hvis vi tjener penger per kunde, løser volumet dem av seg selv.<br><br><b>Middels svar:</b> bygger inntekt minus kostnad og finner at kostnadene er for høye. <b>Sterkt svar:</b> flytter toppen til enhetsøkonomi og sier hvorfor det endrer <i>svaret</i> og ikke bare oppsettet: hvis dekningsbidraget per kasse er positivt og levetidsverdien overstiger anskaffelseskostnaden, er underskuddet en investering og veksten er riktig. Er den ikke det, gjør vekst vondt verre — og da er anbefalingen å bremse, som er det stikk motsatte." },

      { "n": 25, "k": "Nedbrytning", "lvl": 3,
        "s": "Prompt: En kaffebarkjede med 55 utsalg har stabil omsetning per utsalg, men driftsmarginen har falt fra 11 til 6 prosent på to år. Bygg et bevisst asymmetrisk tre: tre nivåer ned i grenen du mistenker, ett nivå i resten.",
        "f": "<b>Grenen jeg mistenker — lønnskostnad per omsatt krone:</b><ul><li>Bemannede timer per åpningstime, per utsalg og per time på døgnet</li><li>… mot solgte enheter i samme time — altså om bemanningen følger trafikkurven eller vaktplanen<br><ul><li>… og hvor stor andel av timene som ligger i de tre timene som står for halve dagsomsetningen</li><li>… og andel innleide eller overtidsbetalte timer, som koster mer per time enn en planlagt time</li></ul></li></ul><b>Grenene med ett nivå, som sammenlikningsgrunnlag:</b><ul><li><b>Vareforbruk i prosent av omsetning</b> — kaffe, melk, bakevarer, svinn på ferske produkter mot slutten av dagen.</li><li><b>Miks og snittbong</b> — andel enkel kaffe mot spesialdrikker og mat, siden mat bærer flere marginpoeng enn en americano.</li><li><b>Faste kostnader per utsalg</b> — leie, som ofte er omsetningsbasert i kjøpesenter og fast i gateplan.</li></ul><b>Hvorfor asymmetrien er riktig her:</b> omsetningen per utsalg er oppgitt som stabil, og fem marginpoeng er for mye til å komme fra en liten post. Lønn og varer er de eneste to som er store nok, og av dem er lønn den som kan bevege seg uten at noen har bestemt det.<br><br><b>Middels svar:</b> utvikler alle fire grenene like dypt. Det er ryddig og forteller intervjueren at du ikke har en mistanke. <b>Sterkt svar:</b> sier asymmetrien høyt — «jeg går tre nivåer ned i lønn og ett i resten, fordi …» — og bruker de grunne grenene bevisst som kontroll: hvis vareforbruket i prosent også har steget, er det ikke bemanningen, det er prisen kjeden ikke har turt å ta ut. Asymmetrien <i>er</i> prioriteringen, gjort synlig." },

      { "n": 26, "k": "Nedbrytning", "lvl": 3,
        "s": "Prompt: Et kommunalt kulturhus har fått beskjed om å kutte tilskuddet med 20 prosent uten å redusere antall besøkende. Bygg treet. Hva er målfunksjonen, og hvor er beskrankningen som faktisk binder?",
        "f": "<b>Målfunksjonen:</b> maksimér besøk (og bredden i hvem som kommer) per tilskuddskrone, under to beskrankninger — budsjettet, og at huset er bygget for et bestemt antall seter i et bestemt antall kvelder.<br><br><b>Toppen som identitet:</b> Netto tilskuddsbehov = (Arrangementer × Seter × Belegg × Netto billettpris) + Andre inntekter − Faste huskostnader − Variable arrangementskostnader.<br><br><b>Grenene:</b><ul><li><b>Kalenderutnyttelse.</b> Hvor mange av årets kvelder er salen i bruk, og hva står den tom av? Dette er den bindende beskrankningen i de fleste kulturhus — et hus med 40 prosent utnyttelse har ikke et kostnadsproblem, det har et tomt-hus-problem.</li><li><b>Belegg per arrangementstype.</b> Egne produksjoner mot utleie mot gjestespill, med dekningsbidrag per kveld for hver.</li><li><b>Inntekt utenom billetten.</b> Utleie på dagtid til kurs og møter, servering, sponsor — den delen som ikke konkurrerer med kveldsprogrammet i det hele tatt.</li><li><b>Faste kostnader som ikke følger aktiviteten.</b> Bygg, energi, fast bemanning. Store, men nesten helt låst på ett års sikt.</li></ul><b>Middels svar:</b> lager et kostnadskutt-tre og foreslår å kutte i programmet. Det bryter beskrankningen oppdraget ga: besøkstallet skal holdes.<br><br><b>Sterkt svar:</b> ser at når inntekten skal opp og besøket ikke ned, er den eneste store frie variabelen <b>hvor mange kvelder huset faktisk er i bruk</b>, og at dagtidsutleie er ren gevinst fordi den bruker et bygg som allerede er betalt for. Og det aller sterkeste grepet: si eksplisitt at «besøkende» må defineres før du regner — 20 000 besøk fordelt på fem utsolgte konserter og 20 000 fordelt på 200 kvelder er to vidt forskjellige hus, og bare det ene av dem kan kutte." },

      { "n": 27, "k": "Hypotese", "lvl": 3,
        "s": "Prompt: En bilutleiekjede har hatt uendret antall utleiedøgn, uendret døgnpris og likevel 40 prosent lavere resultat i år. Skriv først C-svaret, så A-svaret. Marker hva som konkret skiller dem.",
        "f": "<b>C-svaret:</b> «Jeg vil se på fire ting. Marked: hvor stort er bilutleiemarkedet og hvordan vokser det. Konkurranse: hvem er de andre og hva er markedsandelene. Inntekt: pris og volum. Kostnad: faste og variable kostnader. Så setter jeg det sammen til en anbefaling.»<br><br>Dette er ikke tull — det er MECE nok og rolig framført. Men det er ordrett det samme treet som for et hotell og et stålverk, og det bruker <b>ingen</b> av de tre faktaene prompten ga fra seg.<br><br><b>A-svaret:</b> «Både utleiedøgn og døgnpris er oppgitt som uendret, så hele inntektssiden er matematisk utelukket. Da må fallet ligge på kostnadssiden eller i noe som ikke er utleie i det hele tatt. Jeg bryter det i tre.<br><br><i>Ett — kapitalkostnaden per bil.</i> En utleiebil koster innkjøpspris minus restverdi ved salg, fordelt på levetiden i flåten. Dette er den største enkeltposten og den som kan flytte seg 40 prosent uten at noen i selskapet har gjort noe: bruktbilprisene settes utenfor huset.<br><br><i>To — flåtestørrelse mot utleiedøgn.</i> Uendret antall utleiedøgn med en større flåte betyr fallende utnyttelse, og en bil som står er ren kostnad. Jeg vil se antall biler i flåten mot utleiedøgn, per måned.<br><br><i>Tre — driftskostnad per utleiedøgn.</i> Skade og reparasjon, klargjøring mellom leieforhold, og ensidig kjøring som gjør at biler må flyttes tomme mellom stasjoner.<br><br>Stasjonsleie og administrasjon lar jeg ligge; de er faste og forklarer ikke et fall på 40 prosent.<br><br><b>Hypotesen min</b> er at fallet er kapitalkostnad og ikke drift: restverdiene har falt, slik at avskrivning per bil har hoppet mens alt som er synlig i utleien står stille. <b>Testen er</b> realisert salgspris mot bokført restverdi for bilene som ble solgt ut av flåten i år, mot i fjor. Er avviket lite, tar jeg feil — og da går jeg rett til flåteutnyttelsen.»<br><br><b>Det som skiller, punkt for punkt:</b><ul><li><b>Utgangspunkt:</b> fire temaoverskrifter mot en identitet der to faktorer allerede er kjent.</li><li><b>Bruk av prompten:</b> null fakta brukt mot at alle tre brukes til å utelukke <i>før</i> første gren.</li><li><b>Grenene:</b> ville passet et stålverk mot at de bare gir mening for en bilflåte.</li><li><b>Utelatelser:</b> ingen mot to, med begrunnelse.</li><li><b>Første innsikt:</b> etter fjerde gren mot i setning én.</li></ul>C-svaret kan bare leses opp. A-svaret gir intervjueren en påstand å angripe — og det er det som gjør en case til en samtale." },

      { "n": 28, "k": "Hypotese", "lvl": 3,
        "s": "Prompt: En nordisk datasenteroperatør leier ut kapasitet på faste flerårige kontrakter. Marginen faller, men kontraktsprisene er låst. Skriv hypotesen, testen, og hva som ville avkreftet den — alle tre setningene.",
        "f": "<b>Hypotesen:</b> «Marginfallet ligger i strømkostnad per levert kilowatt, ikke i utnyttelsen av salen: kontraktene priser kapasitet i faste kroner, mens kraften kjøpes i et marked, slik at hele prisrisikoen ligger hos oss.»<br><br><b>Testen er</b> gjennomsnittlig kraftpris per levert kWh og PUE-tallet (forbrukt energi delt på energi som faktisk går til kundens utstyr), per anlegg og per måned, holdt mot solgt kapasitet i samme periode — og i tillegg hvor stor andel av forbruket som er sikret med prissikringsavtaler.<br><br><b>Den faller hvis</b> kraftprisen per kWh er flat og PUE er uendret. Da ligger fallet i at vi selger kapasitet vi ikke får betalt for — enten fordi salen ikke er full, eller fordi kontraktene har et tak på forbruk som kundene ikke når opp i.<br><br><b>Middels svar:</b> «hypotesen er at kostnadene har steget». Sant, men det utelukker ingenting, og ingen kan levere et tall som gjør det usant.<br><br><b>Sterkt svar:</b> gjør tre ting samtidig. Det navngir <i>hvilken</i> kostnad og bort fra hvilken annen. Det ber om et forholdstall (PUE) og ikke bare et kronetall, fordi et forholdstall skiller «kraften er dyrere» fra «vi bruker mer kraft per solgte enhet» — og de to har helt ulike medisiner. Og det spør om prissikringsandelen, som er det ene tallet som avgjør om dette er et markedsproblem eller et innkjøpsproblem. Aller sterkest: si at hypotesen er en <i>søkeretning, ikke et standpunkt du skal forsvare</i>. Poenget er ikke å ha rett i minutt sju, men å ha tatt feil raskt i minutt elleve." },

      { "n": 29, "k": "Casetyper", "lvl": 3,
        "s": "Prompt: Et industrikonsern vurderer å bygge et anlegg for gjenvinning av batterier fra elbiler i Norge. Dette er en hybrid. Si hvilke casetyper den er sammensatt av, og hva hver av dem legger til i treet.",
        "f": "<b>Tre typer i én prompt:</b><ul><li><b>Markedsinngang</b> gir rekkefølgen: er markedet attraktivt, kan vi vinne, lønner det seg, hvordan går vi inn. Her er «markedet» spesielt: tilgangen på <i>råstoff</i> er beskrankningen, ikke etterspørselen etter utvinnede metaller. Antall batterier som når endt levetid i Norden er kjent på forhånd fra bilsalget for 12–15 år siden — det er en av de best predikerbare markedsstørrelsene som finnes.</li><li><b>Kostnad / operations</b> gir anleggets innmat: kapasitet i tonn per år, utnyttelsesgrad, utbytte per metall, og hvilket prosesstrinn som er flaskehalsen. Et gjenvinningsanlegg tjener på gjennomstrømning, og et anlegg som går på 60 prosent har dobbelt så høy kapitalkostnad per tonn som ett som går på 90.</li><li><b>Prising</b> gir fortegnet på inntektssiden, og det er det viktigste enkeltgrepet: får vi <i>betalt</i> for å ta imot batteriene, eller må vi <i>kjøpe</i> dem? Konkurrerer flere anlegg om samme knappe råstoff, snur porthonoraret fra inntekt til kostnad — og hele forretningsmodellen med det.</li></ul><b>Middels svar:</b> kaller det en markedsinngangscase og bygger de fire lagene. Det er riktig, men det gjør anlegget til en boks med en margin i.<br><br><b>Sterkt svar:</b> sier hybriditeten høyt og sier hva den gjør: markedsinngangen gir <i>rekkefølgen</i> på spørsmålene, operations gir <i>kostnadssiden</i>, og prisingen avgjør om inntektssiden i det hele tatt har positivt fortegn. De fleste ekte caser er hybrider, og å navngi delene er ikke pedantisk — det er det som hindrer at du bygger tre lag som svarer på samme spørsmål. Fellen som hører til markedsinngang gjelder fortsatt: en oppnåelig andel må begrunnes med kapasitet og antall spillere, ikke gjettes." },

      { "n": 30, "k": "Casetyper", "lvl": 3,
        "s": "Prompt: En kjøper vurderer et mål med 80 millioner i EBITDA. Sammenlignbare selskaper omsettes til 8 ganger EBITDA. Kjøper anslår 25 millioner i årlige synergier, som koster 60 millioner å realisere. Selger krever 35 prosent premie. Regn, og si hvilket av de to M&amp;A-spørsmålene du er i.",
        "f": "<b>Regnestykket:</b><ul><li>Standalone verdi: 80 × 8 = <b>640 mill.</b></li><li>Premien: 640 × 0,35 = <b>224 mill.</b></li><li>Synergienes verdi: 25 × 8 = <b>200 mill.</b></li><li>Minus realiseringskostnad: 200 − 60 = <b>140 mill netto.</b></li><li><b>Resultat: 224 − 140 = 84 millioner i verdiødeleggelse.</b></li></ul>Legg merke til at kjøpet er tapsbringende <i>allerede før</i> realiseringskostnaden: 224 i premie mot 200 i brutto synergiverdi. Kjøper betaler 24 millioner mer enn alt han skaper, og deretter 60 til for å skape det.<br><br><b>Hvilket spørsmål:</b> er A og B <b>ulike</b> selskaper, er spørsmålet om akkurat dette målet passer — og det forutsetter at oppkjøp allerede er riktig grep. Er A og B <b>like</b> (kjøp av direkte konkurrent), er spørsmålet i realiteten hva som skjer med markedsklarerende pris når kapasitet konsolideres. Å navngi hvilket du svarer på gjør mer for karakteren enn en gren til.<br><br><b>Middels svar:</b> regner synergiene riktig og konkluderer «det er 200 millioner i synergier, så kjøpet er attraktivt». Teknisk korrekt synergianalyse, tapsbringende kjøp.<br><br><b>Sterkt svar:</b> stiller alltid spørsmålet <i>hva som betales</i>, ikke bare hva som skapes. Kjøper betaler en premie; er prisen høy nok, tilfaller hele synergien selger. Og legger til to nyanser: kostnadssynergier er langt mer troverdige enn inntektssynergier, og en synergi som er åpenbar for oss er sannsynligvis også åpenbar for de andre budgiverne — som er nettopp derfor premien er 35 prosent." },

      /* ================= NIVÅ 4 · UNDER PRESS ================= */

      { "n": 31, "k": "MECE", "lvl": 4,
        "s": "90 sekunder, høyt, med klokke. Prompt: En operatør av elsparkesykler har 6 000 kjøretøy i fire norske byer. Antall turer per dag har vokst 15 prosent, men selskapet taper mer penger enn i fjor. Si først hvilken av de fem MECE-måtene du bruker og hvorfor, deretter tre grener. Start klokken.",
        "f": "<b>Fasit, sagt på under 90 sekunder:</b><br><br>«Jeg bruker <b>algebra</b>, fordi problemet er at volumet vokser mens resultatet faller — og da må svaret ligge i en <i>per-enhet</i>-størrelse. Identiteten er: resultat = turer × (inntekt per tur − variabel kostnad per tur) − faste kostnader per kjøretøy × antall kjøretøy.<br><br><i>Ett — inntekt per tur.</i> Startgebyr pluss pris per minutt ganger turlengde i minutter. Turlengden er den jeg mistenker: flere turer kan bety kortere turer, og et startgebyr som ikke har fulgt med.<br><br><i>To — variabel kostnad per tur.</i> Lading, innhenting og utplassering, og reparasjon. Denne skalerer med turer, ikke med inntekt, så den er farlig i akkurat dette tilfellet.<br><br><i>Tre — faste kostnader per kjøretøy fordelt på turer.</i> Avskrivning på sykkelen delt på hvor mange turer den overlever, pluss bykonsesjon. Levetid i antall turer er den enkeltvariabelen som avgjør hele forretningsmodellen.<br><br>Markedsføring og hovedkontor lar jeg ligge; de er faste og forklarer ikke at flere turer gir mindre penger.»<br><br><b>Middels svar under press:</b> sier «jeg bruker algebra» og bygger deretter et generisk inntekt-minus-kostnad-tre uten å koble det til at volumet er oppgitt som voksende.<br><br><b>Sterkt svar:</b> bruker de tre sekundene på å si <i>hvorfor</i> algebra — voksende volum og fallende resultat peker matematisk på per-enhet — og lar det valget bestemme at alle tre grenene er per-tur-størrelser. Det er sammenhengen mellom verktøyvalget og grenene som scorer, ikke navnet på verktøyet. Sjekk til slutt at du faktisk sa noe du legger bort. Under tidspress er det alltid det punktet som ryker først." },

      { "n": 32, "k": "MECE", "lvl": 4,
        "s": "60 sekunder. Prompt: En veterinærkjede med 40 klinikker har fallende resultat. Gi to <i>ulike</i> MECE-snitt på samme prompt, og velg ett med begrunnelse. Du får ikke bygge ferdig noe tre — bare de to snittene og valget.",
        "f": "<b>Snitt A — algebra på klinikkens kapasitet:</b> resultat = behandlingsrom × åpne timer × utnyttelse × pris per behandlet time − variable kostnader − faste klinikkostnader. Rommet er den knappe ressursen, akkurat som stolen i en tannhelsekjede.<br><br><b>Snitt B — segmentering på inntektstype:</b> konsultasjon (veterinærens tid), kirurgi (rom, utstyr og tid), medisin og fôr over disk (ren varehandel), og forsikringsfinansierte forløp mot kunder som betaler selv.<br><br><b>Valget: B, av én grunn.</b> De fire inntektstypene har systematisk ulik margin og ulik prisingsmakt — varesalget konkurrerer med nettapotek, kirurgien konkurrerer ikke med noen — mens snitt A behandler alle timer i rommet som like verdt. <b>Én akse er verdt noe når grenene oppfører seg forskjellig, og A antar at de ikke gjør det.</b><br><br>Snitt A er likevel ikke bortkastet: den hører hjemme <i>inne i</i> gren B som driver, når du skal finne ut hvorfor kirurgikapasiteten ikke er full.<br><br><b>Middels svar:</b> gir to snitt og velger det ene med «jeg synes dette virker mest relevant». <b>Sterkt svar:</b> begrunner valget med spredning — velg aksen der du venter at grenene skiller lag — og plasserer det forkastede snittet som et nivå lenger ned i stedet for å kaste det. At du kunne se to snitt og velge mellom dem er i seg selv signalet: det viser at treet er et valg og ikke en refleks." },

      { "n": 33, "k": "Nedbrytning", "lvl": 4,
        "s": "90 sekunder, høyt. Prompt: Et norsk skipsverft bygger og reparerer fartøy. Nybyggsiden har full ordrebok, men de tre siste kontraktene gikk med tap, mens reparasjonssiden tjener penger. Ledelsen vil vite om de skal slutte å bygge nytt. Bygg treet og si det top-down.",
        "f": "<b>Fasit:</b><br><br>«Jeg vil bryte dette i tre, og jeg sier overskriftene først: <b>ett</b>, hvordan prosjektene prises og hvor avviket mot kalkyle oppstår. <b>To</b>, hva verftets kapasitet faktisk brukes til, altså fordelingen mellom nybygg og reparasjon. <b>Tre</b>, hvilke kostnader som blir liggende igjen hvis nybygg legges ned.<br><br><i>Ett — kalkyle mot faktisk.</i> Per kontrakt: timeavvik mot kalkylerte timer, materialavvik, og endringsordrer — hvem betaler for kundens endringer underveis. Jeg mistenker denne, og går tre nivåer ned: timeavvik per fase (prefab, seksjon, utrustning, sjøsetting), siden et tap som oppstår i utrustningsfasen er en helt annen sykdom enn et tap som var innebygget i tilbudet.<br><br><i>To — kapasitetsallokering.</i> Dokk- og kaidøgn brukt på nybygg mot reparasjon, og dekningsbidrag per dokkdøgn for hver. Reparasjon er kortsyklisk og fyller hullene; nybygg legger beslag på dokken i måneder.<br><br><i>Tre — hva som ikke forsvinner.</i> Dokk, kraner, fast fagarbeiderstab og lærlingløp. Hvis nybygg legges ned, blir disse igjen — så spørsmålet er ikke om nybygg er lønnsomt fullfordelt, men om det dekker sine egne særkostnader og bidrar til de felles.<br><br>Valutasikring og finanskostnader lar jeg ligge i første omgang, med mindre kontraktene er i utenlandsk valuta.<br><br><b>Hypotesen min</b> er at tapet er en kalkylefeil og ikke en driftsfeil: tilbudsprisen ble satt på gamle timesatser i et strammere arbeidsmarked. <b>Testen er</b> kalkylerte mot faktiske timer per fase for de tre kontraktene, mot de tre siste lønnsomme.»<br><br><b>Middels svar:</b> bygger et pris-og-kostnad-tre og anbefaler å slutte med nybygg fordi det taper penger. <b>Sterkt svar:</b> tar med gren tre. Det er den samme feilen som i flycasen — kutter du den ulønnsomme delen, blir dokken, kranene og staben igjen, og de faste kostnadene flytter bare over på reparasjonssiden og gjør den svakere. Spørsmålet er alltid dekningsbidrag mot særkostnader, aldri fullfordelt margin, når beslutningen er å legge ned." },

      { "n": 34, "k": "Nedbrytning", "lvl": 4,
        "s": "Skriv de 25 første sekundene ordrett — ikke stikkord, hele setninger. Prompt: Et alpinanlegg med 12 heiser har hatt like mange skidager solgt som før, men driftsresultatet er halvert på tre år.",
        "f": "<b>Fasit, ordrett:</b><br><br>«Jeg vil bryte dette i tre. <b>Ett:</b> inntekt per skidag, altså hva en gjest faktisk betaler etter sesongkort, familierabatter og pakkeavtaler med hotellene — og hvor stor andel av dagene som er solgt til full pris. <b>To:</b> inntekten utenom heiskortet, som er servering i bakken, skiutleie og skiskole, med dekningsbidrag på hver for seg. <b>Tre:</b> kostnadene som følger av å holde anlegget åpent uavhengig av hvor mange som kommer — snøproduksjon i kilowattimer, preparering i maskintimer, og bemanning i heisene. Snøproduksjonen er den jeg mistenker, fordi den både har blitt dyrere per kilowattime og trolig må gå flere timer enn før for å sikre åpning i desember.<br><br>Investeringer i nye heiser og markedsføring lar jeg ligge i første omgang; de er besluttet på forhånd og forklarer ikke at like mange gjester gir halv inntjening. Jeg starter i den tredje grenen, og skal jeg si hvorfor, er det fordi antall skidager er oppgitt som uendret — da er volumet matematisk utelukket, og en halvering er for stor til å komme fra rabattstrukturen alene.»<br><br><b>Middels svar:</b> leser opp tre grener som stikkord — «pris, andre inntekter, kostnader» — og går videre. Nedbrytningen kan være helt riktig, og det høres likevel ut som en huskeliste.<br><br><b>Sterkt svar:</b> gjør fire ting i samme åndedrag: sier antallet grener først, snakker i hele setninger, navngir det som legges bort <i>med begrunnelse</i>, og avslutter med startgren og hypotese. Legg spesielt merke til at faktumet fra prompten — uendret antall skidager — brukes to ganger: én gang til å utelukke volum, og én gang til å begrunne prioriteringen. Det er den doble bruken av et oppgitt tall som skiller de beste åpningene fra de gode." },

      { "n": 35, "k": "Hypotese", "lvl": 4,
        "s": "60 sekunder. Prompt: En pizzakjede driver 130 utsalg, 90 av dem som franchise og 40 i egen regi. De egeneide tjener systematisk mindre per utsalg enn franchisetakerne, på sammenlignbare lokasjoner. Si hypotesen din høyt — én setning som peker på én gren og bort fra minst én annen — og «testen er …» i én til.",
        "f": "<b>Fasit:</b><br><br>«<b>Hypotesen min</b> er at forskjellen ligger i lønnskostnad per omsatt krone og ikke i omsetning: franchisetakeren står selv i utsalget og bemanner etter trafikken time for time, mens et egeneid utsalg bemannes etter vaktplan og betaler full lønn og tillegg for de samme timene.<br><br><b>Testen er</b> lønnstimer per omsatt krone per time på døgnet, for de 40 egeneide mot de 90 franchiseutsalgene, i samme uke og på sammenlignbare lokasjoner — pluss eiers egen arbeidstid, som ikke står i franchisetakerens regnskap i det hele tatt.<br><br><b>Den faller hvis</b> lønnsandelen er lik, og forskjellen i stedet ligger i omsetning per utsalg eller i vareforbruk.»<br><br><b>Middels svar under press:</b> «jeg tror franchisetakerne er mer motiverte». Sant, sannsynligvis, og ubrukelig — det er ikke et tall noen kan trekke ut, og det peker ikke på en gren.<br><br><b>Sterkt svar:</b> oversetter motivasjonen til en <i>målbar mekanisme</i>. «Mer motivert» blir til «bemanner etter trafikk i stedet for etter vaktplan», og det er et uttrekk. Aller sterkest er det siste leddet: å be om eiers egen arbeidstid. Det er den skjulte kostnaden som gjør franchiseregnskapet kunstig godt, og en kandidat som ser den, har sett hele casen — for hvis forskjellen er ubetalt eierinnsats, er den ikke overførbar til egen drift, og anbefalingen snur helt." },

      { "n": 36, "k": "Hypotese", "lvl": 4,
        "s": "Fortsettelse, 45 sekunder. Du har akkurat sagt hypotesen om pizzakjeden. Intervjueren svarer: «Vi har tallene. Lønnsandelen er nesten identisk — 26 mot 27 prosent.» Snu, høyt, uten pause.",
        "f": "<b>Fasit, elleve sekunder:</b><br><br>«Da faller hypotesen min. Det betyr at bemanningen ikke er kilden, og at forskjellen må ligge i enten omsetningen per utsalg eller i vareforbruket — og siden lokasjonene er oppgitt som sammenlignbare, er vareforbruk det leddet jeg vil se på først. Jeg vil ha vareforbruk i prosent av omsetning, per utsalg, sammen med svinn og andel solgt på kampanje. Hypotesen min nå er at franchisetakeren styrer porsjonering og svinn strammere fordi han eier tapet selv.»<br><br><b>Tre deler:</b> erkjenn, si hva det utelukker, oppgi neste trekk.<br><br><b>Middels svar:</b> «hm, ok … da må jeg tenke litt.» Pausen er dyrere enn den føles. Kandidater som blir tause når hypotesen slår sprekker, gir vurdereren ingenting å vurdere.<br><br><b>Sterkt svar:</b> gjør snuen til en <i>innsnevring</i>. Legg merke til at 26 mot 27 prosent ikke bare avkrefter hypotesen — det utelukker den største kostnadsposten fra hele resten av casen, og det er verdifull informasjon. Det aller sterkeste er å gjenbruke resonnementet: den samme mekanismen (eieren bærer tapet selv) flyttes fra lønn til svinn, slik at den nye hypotesen er en videreutvikling og ikke et tilfeldig neste tema. Poenget er ikke å ha rett i minutt sju — det er å ha tatt feil raskt i minutt elleve, slik at de siste ti minuttene brukes riktig sted." },

      { "n": 37, "k": "Hypotese", "lvl": 4,
        "s": "90 sekunder for hele åpningen: struktur, hypotese og datauttrekk. Prompt: Et bemanningsbyrå innen helse leier ut sykepleiere til kommuner og sykehus. Omsetningen har vokst 20 prosent, men bruttomarginen per utleid time har falt fra 24 til 19 prosent.",
        "f": "<b>Fasit:</b><br><br>«Bruttomargin per utleid time er utleiepris minus lønn og sosiale kostnader, delt på utleieprisen. Da har fallet nødvendigvis én av to kilder: prisen vi tar, eller kostnaden per time vi betaler. Jeg bryter det i tre.<br><br><i>Ett — realisert utleiepris per time.</i> Splittet på hvordan timen er solgt: rammeavtale vunnet i anbud, mot akutt bestilling på kort varsel. De to prises helt ulikt, og en vekst på 20 prosent kommer sjelden jevnt fra begge.<br><br><i>To — lønnskostnad per utleid time.</i> Grunnlønn, men særlig tilleggene: kveld, natt, helg og overtid. Det er miksen av <i>når</i> timene ligger som driver denne, ikke lønnsnivået.<br><br><i>Tre — hvor mye vi betaler for timer vi ikke får solgt.</i> Fast ansatte konsulenter i beredskap, garantilønn, og ubenyttet tid mellom oppdrag.<br><br>Rekrutteringskostnad og administrasjon lar jeg ligge; de treffer under bruttomarginen og kan ikke forklare et fall på fem marginpoeng i selve timen.<br><br><b>Hypotesen min</b> er at fallet er miks og ikke pris: veksten har kommet i anbudsvunne rammeavtaler med lavere timepris, samtidig som en større andel av timene ligger på kveld, natt og helg der tilleggene er høyest. Prisen i hvert enkelt segment kan være helt uendret.<br><br><b>Testen er</b> realisert timepris og lønnskostnad per time, hver for seg, splittet på avtaletype og på skifttype, over 24 måneder — sammen med hvert segments andel av totale timer. <b>Den faller hvis</b> marginen har falt <i>innenfor</i> hvert segment. Da er det pris, ikke miks, og da går jeg til anbudsprisingen.»<br><br><b>Middels svar:</b> bygger pris minus kostnad og ber om marginen over tid. Det er tallet du allerede har fått.<br><br><b>Sterkt svar:</b> ser at 20 prosent vekst og fallende margin nesten alltid er en miks-historie, og ber derfor om <i>andelene</i> sammen med prisene. Uten andelene kan du ikke skille «hvert segment er blitt dårligere» fra «det dårlige segmentet er blitt større», og de to har motsatt anbefaling: den ene sier reforhandle, den andre sier selg annerledes." },

      { "n": 38, "k": "Casetyper", "lvl": 4,
        "s": "30 sekunder totalt, altså under åtte sekunder på hver. Si casetypen og den ene fellen for hver av disse fire: (a) En møbelkjede vurderer å kjøpe sin største leverandør. (b) Et bryggeri har vokst i volum, men resultatet står stille. (c) En kommune vil vite hvor mange ladepunkter den trenger i 2032. (d) En strømmetjeneste vurderer å heve abonnementsprisen med 20 kroner.",
        "f": "<b>(a) M&amp;A — vertikal integrasjon.</b> <i>Fellen:</i> å telle synergier uten kostnaden ved å realisere dem, og uten å spørre hva premien er. Er prisen høy nok, tilfaller hele synergien selger.<br><br><b>(b) Lønnsomhet, med miks som sannsynlig svar.</b> <i>Fellen:</i> å regne på totaler uten å segmentere. Volum opp og resultat flatt betyr at noe per enhet har falt — sannsynligvis at veksten har kommet i det billigste produktet eller den dyreste kanalen.<br><br><b>(c) Estimering, bottom-up.</b> <i>Fellen:</i> å begynne å regne før enheten er definert. Ladepunkter til hvem, hvor, og hvor mange biler per punkt — og på hvilket tidspunkt av døgnet toppen ligger.<br><br><b>(d) Prising.</b> <i>Fellen:</i> å hoppe til et tall før målet er avklart. Å prise for margin og å prise for markedsandel gir motsatt svar på samme case, og her kommer elastisiteten i tillegg: 20 kroner er ingenting hvis churn er null og alt hvis den ikke er det.<br><br><b>Middels svar:</b> treffer typen på alle fire. Det er gjenkjenning, og det er det lette.<br><br><b>Sterkt svar:</b> knytter fellen til <i>noe konkret i prompten</i> og ikke bare til typen generelt — i (b) er det at volum er nevnt og resultat er nevnt, som er miks-signaturen i to ord. Og det aller sterkeste: å si når en prompt er en hybrid. (a) er også en kostnadscase hvis leverandøren kjøpes for å sikre innkjøpspris, og (d) er også en lønnsomhetscase hvis prishevingen skal dekke et innholdsbudsjett som allerede har vokst. Kjenn igjen typen på en prompt du aldri har sett — også når den er en hybrid, som de fleste ekte caser er." },

      { "n": 39, "k": "Casetyper", "lvl": 4,
        "s": "90 sekunder, høyt, uten kalkulator. Estimer det årlige markedet i kroner for hjulskift på verksted i Norge. Si forutsetningene høyt før du regner, og sanity-sjekk til slutt.",
        "f": "<b>Enheten først:</b> kroner per år, betalt av privatpersoner for arbeidet med å skifte mellom sommer- og vinterhjul på verksted. Ikke dekksalg, ikke tunge kjøretøy.<br><br><b>Kjeden, bottom-up på bilen:</b><ul><li>Personbiler i Norge: <b>ca. 2,9 millioner</b></li><li>Andel som skifter på verksted i stedet for selv: <b>40 %</b> → 2,9 × 0,4 = <b>1,16 millioner biler</b></li><li>Skift per bil per år: <b>2</b> (vår og høst) → <b>2,32 millioner skift</b></li><li>Pris per skift: <b>800 kr</b></li><li><b>2,32 mill × 800 kr = 1 856 millioner ≈ 1,9 milliarder kroner</b></li></ul><b>Sanity-sjekk:</b> 1,9 mrd fordelt på grovt 2 000 bilverksteder gir under én million per verksted i året, eller rundt 1 200 skift per verksted. Med to sesonger på seks uker hver er det rundt 100 skift i uken, altså 20 om dagen — travelt, men fullt mulig for et verksted med flere løftebukker. Tallet henger sammen.<br><br><b>Middels svar:</b> lander på et tall i samme størrelsesorden, men sier forutsetningene som en liste av tall uten begrunnelse, og hopper over sanity-sjekken.<br><br><b>Sterkt svar:</b> gjør fire ting. Definerer enheten før første regnestykke. Begrunner den ene forutsetningen som faktisk bærer svaret — her verkstedandelen på 40 prosent, som kunne vært 25 eller 55 og som flytter svaret mer enn alt annet. Holder modellen grov: fem steg med to godt begrunnede antakelser slår tolv steg med ti gjettede. Og sanity-sjekker mot noe han vet fra før. Feilen ligger alltid i forutsetningene, aldri i desimalene — og det er forutsetningene du sier høyt som vurderes, ikke tallet du lander på. Bruk aldri 0 eller 100 prosent på noe ledd." },

      { "n": 40, "k": "Casetyper", "lvl": 4,
        "s": "90 sekunder. Et meieri har en pakkelinje med fire trinn, med kapasitet 1 200, 900, 1 400 og 950 enheter per time. Etterspørselen er 1 000 per time. Ledelsen vil investere i trinn 4 og løfte det til 1 100. Regn ut hva investeringen gir, og si hva de burde gjort i stedet.",
        "f": "<b>Dagens gjennomstrømning: 900 per time</b> — flaskehalsen er trinn 2, og et system leverer ikke mer enn sitt svakeste ledd.<br><br><b>Investeringen i trinn 4 (950 → 1 100) gir null.</b> Trinn 2 slipper fortsatt bare 900 gjennom, så trinn 4 får aldri mer enn 900 å jobbe med, uansett hva det kan klare.<br><br><b>Det de burde gjort:</b> løfte trinn 2. Til 1 050 gir det ny gjennomstrømning på <b>950</b>, fordi trinn 4 da blir den nye flaskehalsen. Økning: 50 / 900 = <b>5,6 prosent</b>.<br><br><b>Og deretter:</b> løft trinn 4 også, og taket blir 1 050 fra trinn 2 — men etterspørselen er 1 000, så <b>reell gjennomstrømning blir 1 000</b>, og videre investering er bortkastet.<br><br><b>Middels svar:</b> ser at trinn 2 er flaskehalsen og sier at investeringen er feil. Riktig, og halvferdig.<br><br><b>Sterkt svar:</b> tar med de to neste stegene. <b>Ett:</b> en flaskehals som fjernes flytter seg — den blir ikke borte. Det er nettopp derfor kapasitetsprosjekter systematisk underleverer mot forretningsplanen, og hvorfor du alltid skal regne ut hvem som blir <i>neste</i> flaskehals før du anbefaler investeringen. <b>To:</b> etterspørselen er også et tak. Over 1 000 per time er ekstra kapasitet verdiløs uansett hvor den ligger, og en kandidat som ikke sier det, anbefaler et anlegg som kommer til å stå halvtomt. Flaskehalsen finner du ved å sammenligne hvert trinns kapasitet mot etterspørselen inn i trinnet — ikke ved å lete etter trinnet som ser tregest ut." }
    ]
  },

  /* ==================================================================
     BANK 2 · GRUNNLAG (k0, k1, k2)
     ================================================================== */
  "grunnlag": {
    "cats": ["Vurderingen", "Formatet", "Husene"],
    "lvl": {
      "1": ["Nivå 1", "Definisjoner — si hva det er"],
      "2": ["Nivå 2", "Anvendelse — bruk det på et konkret tilfelle"],
      "3": ["Nivå 3", "Skreddersøm — bygg svaret fra bunnen"],
      "4": ["Nivå 4", "Under press — gjør det på tid, høyt"]
    },
    "items": [

      /* ================= NIVÅ 1 ================= */

      { "n": 1, "k": "Vurderingen", "lvl": 1,
        "s": "Hvilke fire ting vurderes i et caseintervju? Gi den skarpe versjonen av hver, ikke overskriften.",
        "f": "<b>Struktur.</b> Klarer du å ta et problem du aldri har sett og dele det i biter som ikke overlapper og som til sammen dekker alt? Og er bitene <i>dette</i> problemets biter, ikke en huskeliste du har med deg?<br><b>Kvantitativt håndverk.</b> Regner du riktig, raskt nok, og — like viktig — sier du framgangsmåten høyt så noen kan følge deg?<br><b>Dømmekraft.</b> Ser du hva tallet betyr? Skiller du et symptom fra en årsak? Vet du når du har nok til å konkludere?<br><b>Kommunikasjon.</b> Kommer svaret først? Tåler du å bli motsagt? Ville du sluppet inn i et rom hos klienten i morgen?<br><br><b>Middels svar:</b> nevner de fire ordene. <b>Sterkt svar:</b> sier hva prøven egentlig er — kandidater tror de blir målt på om de finner riktig svar, men de blir målt på om de er til å stole på med en klient i rommet. Det er en <i>arbeidsprøve</i>, ikke en kunnskapsprøve: intervjueren later som du allerede er ansatt. Og de fire måles ikke hver for seg — de måles samtidig, i samme tjue minutter, og en kandidat som er sterk på tre og taus på den fjerde blir husket for den fjerde." },

      { "n": 2, "k": "Vurderingen", "lvl": 1,
        "s": "Hvorfor er det å legge 3C, 4P eller Porters fem krefter over en case i dag et negativt signal? Hva har erstattet dem?",
        "f": "<b>Hvorfor:</b> prep-industrien har solgt rammeverk i tjue år, og husene har brukt de samme tjue årene på å lære seg å se dem. Å legge et navngitt rammeverk over en case viser at du behandler et konkret problem som en kategori.<br><br><b>Hva som har erstattet dem:</b> bygg strukturen fra en <b>identitet</b> eller en <b>verdikjede</b> som gjelder akkurat denne klienten, og si hvilken gren du tror svaret ligger i. Det er enklere og vanskeligere på samme tid — enklere fordi det ikke er noe å pugge, vanskeligere fordi det ikke er noe å pugge.<br><br><b>Middels svar:</b> «rammeverk er utdatert». Sagt slik er det et rykte. <b>Sterkt svar:</b> har belegget: BCGs og Bains egne rekrutteringssider beskriver en <i>arbeidsmåte</i> — strukturere tilnærmingen, stille gjennomtenkte spørsmål, analysere data, regne raskt, finne de viktigste faktorene — og BCG sier rett ut at det ikke alltid finnes ett riktig svar. <b>Ingen av de to sidene nevner ett eneste navngitt rammeverk.</b> Det er ikke en tolkning av hva husene mener; det er hva de skriver. Nyansen som gjør svaret helt: 3C og 4P er ikke dumme, de er <i>konseptuelle kategorier laget av noen andre, til noe annet</i>. Kategoriene skal du lage selv, til dette problemet." },

      { "n": 3, "k": "Formatet", "lvl": 1,
        "s": "Interviewer-led mot candidate-led: hvem styrer, hva er din jobb, og hva er den farligste feilen i hver av dem?",
        "f": "<table><tr><td><b>Interviewer-led</b></td><td><b>Candidate-led</b></td></tr><tr><td>Intervjueren fører deg fra spørsmål til spørsmål</td><td>Du sier hva du vil se på og hvorfor</td></tr><tr><td>Din jobb: svare skarpt på akkurat det som spørres om</td><td>Din jobb: drive casen fremover uten å bli bedt om det</td></tr><tr><td>Farligste feil: å vandre av gårde i egen retning</td><td>Farligste feil: å vente på neste spørsmål</td></tr><tr><td>Typisk: McKinsey</td><td>Typisk: Bain, BCG, Arkwright</td></tr></table><br><b>Middels svar:</b> gjengir tabellen. <b>Sterkt svar:</b> sier at dette er den viktigste enkeltforskjellen mellom husene, at å bomme på den er å bomme på hele intervjuet — og legger til det billigste grepet som finnes: <b>spør.</b> «Vil du at jeg skal drive casen fremover, eller foretrekker du å lede meg gjennom?» Det er helt legitimt og tar to sekunder. Aller sterkest: bemerke at ferdigheten ikke er å beherske den ene modusen, men å <i>bytte</i> mellom dem — Bains stil er dessuten i bevegelse mot interviewer-led, så begge modi må trenes." },

      { "n": 4, "k": "Formatet", "lvl": 1,
        "s": "Gjengi tidsbudsjettet for en case på 20 til 25 minutter, fase for fase, og si hva som avgjøres i hver.",
        "f": "<b>Bakgrunn, oppsett, gjentakelse — 2–3 min.</b> Aktiv lytting, oppsummere problemet med egne ord, avklare mål, to–tre spørsmål som <i>endrer</i> strukturen.<br><b>Struktur og forklaring — 4–5 min.</b> Under to minutter på selve framføringen; overskrifter først, så dybden; hypotese og prioritert gren til slutt.<br><b>Løsningsbygging — 8–10 min.</b> Grave etter tall, teste hypotesen, gruppere brainstorming.<br><b>Matte og eksponater — 3–5 min.</b> Si oppsettet høyt før du regner, sanity-sjekk, «so what» umiddelbart etter.<br><b>Syntese og anbefaling — 2–3 min.</b> Svar først, to–tre grunner med harde tall, risiko, neste steg.<br><br>Summen er 19 til 26 minutter, som er hele casen.<br><br><b>Middels svar:</b> husker fasene. <b>Sterkt svar:</b> sier hvor budsjettet kommer fra og hva det ikke er — det er Wharton Consulting Clubs casebok, altså en kalibrering, ikke en regel fra husene. Og trekker de to konsekvensene: <b>strukturen har et hardt tak på rundt to minutter</b>, og bruker du fire, stjeler du dem fra løsningsbyggingen, ikke fra pausen. <b>Hypotesen faller i minutt sju og skal leve i de neste ti</b> — den er ikke sluttproduktet, den er det som gjør de ti minuttene målrettede i stedet for utforskende." },

      { "n": 5, "k": "Husene", "lvl": 1,
        "s": "Hva er Solve, og hva er PEI? Nevn PEIs fire dimensjoner og formatet på økten.",
        "f": "<b>Solve</b> er McKinseys spillbaserte screening, med modulene Redrock, Sea Wolf og eventuelt Sustainable Futures Lab. En 65-minutters invitasjon betyr typisk to moduler; 85 minutter at den tredje er med. Den måler ikke forretningskunnskap, men strukturering, prioritering og beslutning under tidspress. Det overførbare er diagramlesing, prosentlogikk med riktig nevner og evidenssjekk.<br><br><b>PEI</b> — Personal Experience Interview — har fire dimensjoner, omdøpt sommeren 2025 uten at innholdet endret seg:<ul><li><b>Leadership</b> (før Inclusive Leadership): å løfte andre uten formell autoritet</li><li><b>Drive</b> (før Entrepreneurial Drive): initiativ og utholdenhet mot motstand</li><li><b>Growth</b> (før Courageous Change): læring i usikkerhet, hva du gjorde da det gikk galt</li><li><b>Connection</b> (før Personal Impact): overtalelse, konflikt, konsensus</li></ul><b>Formatet:</b> én historie per økt, etterfulgt av 10–25 oppfølgingsspørsmål.<br><br><b>Middels svar:</b> nevner de fire dimensjonene. <b>Sterkt svar:</b> ser hva formatet betyr for forberedelsen: oppfølgingsspørsmålene graver i <i>beslutningene dine</i>, ikke i utfallet. Det er en hard designbeskrankning på historieporteføljen — <b>få historier, svært dypt gjennomarbeidet, slår mange grunne.</b> Én historie som tåler 25 spørsmål er verdt mer enn seks som tåler tre." },

      /* ================= NIVÅ 2 ================= */

      { "n": 6, "k": "Vurderingen", "lvl": 2,
        "s": "«Si framgangsmåten høyt» er halve den kvantitative karakteren. Du skal regne ut hvor mye 3 400 kunder × 780 kroner utgjør. Vis forskjellen på en middels og en sterk framføring av samme regnestykke.",
        "f": "<b>Middels:</b> stillhet i tolv sekunder, deretter «2 652 000». Riktig svar, null poeng på håndverket — vurdereren har ingenting å følge, og hvis tallet er feil, finnes det ingen delvis kreditt.<br><br><b>Sterkt:</b> «Jeg tar 3 400 ganger 780. Jeg runder til 3 400 ganger 800 først, det er 2 720 000. Så trekker jeg fra 3 400 ganger 20, altså 68 000. Det gir 2 652 000, eller rundt 2,65 millioner kroner i året. Det tilsvarer i overkant av 200 000 i måneden — så dette er en post som betyr noe, men den er ikke stor nok til å forklare et avvik på ti millioner alene.»<br><br><b>Tre ting det sterke svaret gjør:</b><ul><li><b>Sier oppsettet før det regner</b>, så intervjueren kan stoppe deg hvis du har misforstått spørsmålet — som er langt verre enn regnefeil.</li><li><b>Velger en synlig metode</b> (rund opp, korriger ned) i stedet for å mumle. Metoden er det som vurderes; svaret er bare beviset.</li><li><b>Sier «so what» umiddelbart etter.</b> Et tall uten en tolkning er ferdig arbeid som ikke er levert.</li></ul>Kontroll: 3 400 × 800 = 2 720 000; 3 400 × 20 = 68 000; 2 720 000 − 68 000 = 2 652 000." },

      { "n": 7, "k": "Vurderingen", "lvl": 2,
        "s": "Dømmekraft er «å skille et symptom fra en årsak». En klient sier: «Kundetilfredsheten har falt, derfor faller salget.» Vis hva middels og sterk dømmekraft gjør med den setningen.",
        "f": "<b>Middels:</b> tar påstanden for gitt og strukturerer et tre for hvordan man hever kundetilfredsheten. Strukturen kan bli helt fin — og den svarer på klientens diagnose, ikke på klientens problem.<br><br><b>Sterkt:</b> «Jeg vil gjerne teste retningen på den sammenhengen før jeg bygger på den. Tre muligheter: tilfredsheten kan drive salget, salget kan drive tilfredsheten — misfornøyde kunder slutter å kjøpe og blir dermed overrepresentert blant dem som svarer — eller begge kan drives av noe tredje, for eksempel at leveringstiden har økt. Jeg vil se tilfredshet og salg per måned mot hverandre, og se hvilken som beveget seg først.»<br><br><b>Det som skiller:</b> ikke skepsis for skepsisens skyld, men at kandidaten <b>navngir hva som ville avgjort spørsmålet</b> — rekkefølgen i tid — og gjør det på ti sekunder uten å virke motvillig. Klienten har alltid en diagnose med seg inn i rommet, og den er ofte grunnen til at problemet ikke er løst ennå. Å overta klientens diagnose ukritisk er den vanligste måten en teknisk sterk kandidat mister dømmekraftspoeng på. Formuleringen betyr noe: «jeg vil gjerne teste» er samarbeid, «det tror jeg ikke på» er en krangel." },

      { "n": 8, "k": "Formatet", "lvl": 2,
        "s": "Du sitter i et McKinsey-intervju. Førti sekunder inn i tredje spørsmål merker du at du har begynt å foreslå hva dere skal se på videre. Hva er feilen, og hva sier du?",
        "f": "<b>Feilen:</b> du kjører candidate-led i en interviewer-led case. Casen er skrevet av et sentralt team og distribuert med manus — alle kandidater globalt får de samme spørsmålene i samme rekkefølge. <b>Du eier innholdet i hvert delsvar, ikke prosessen.</b> Å drive ditt eget løp er ikke initiativ her, det er å bomme på formatet, og det stjeler tid fra spørsmålet som faktisk vurderes.<br><br><b>Hva du sier:</b> avslutt setningen du er i, og lever svaret på det som ble spurt om. <i>«— men det er neste skritt. På spørsmålet ditt er svaret at de to største postene er X og Y, og av dem er X den som har flyttet seg.»</i> Ingen unnskyldning, ingen metakommentar om at du sporet av.<br><br><b>Middels reaksjon:</b> stopper opp og beklager. Det bruker fem sekunder på å gjøre intervjueren oppmerksom på noe han kanskje ikke hadde registrert.<br><br><b>Sterkt:</b> styrer tilbake i samme setning og gjør det til en overgang. Og aller sterkest: <b>det burde vært avklart i minutt null.</b> Ett spørsmål koster to sekunder — «vil du at jeg skal drive casen fremover, eller foretrekker du å lede meg gjennom?» — og gjør hele denne situasjonen umulig." },

      { "n": 9, "k": "Formatet", "lvl": 2,
        "s": "I en candidate-led case er den farligste feilen å vente. Hva er signalene på at du venter, og hvilken setning driver casen videre?",
        "f": "<b>Signalene, alle sammen ubevisste:</b><ul><li>Du avslutter et delsvar og ser opp med hevede øyenbryn.</li><li>Du sier «… og da er vel neste spørsmål hvordan det ser ut i praksis?» og stopper.</li><li>Du ber om data uten å si hva du skal bruke dem til, og venter på at intervjueren skal foreslå tolkningen.</li><li>Stillhet lengre enn tre sekunder etter et tall.</li></ul><b>Setningen som driver videre</b> har tre ledd: <i>tolkning — konsekvens — neste trekk.</i><br><br><i>«Det tallet betyr at kostnaden per enhet har steget 14 prosent mens prisen står stille, så hele marginfallet kan forklares her. Det gjør at jeg vil legge inntektssiden bort. Neste ting jeg vil se på er innkjøpspris mot volumrabatt de siste tre årene — kan jeg få det?»</i><br><br><b>Middels:</b> sier tolkningen og stopper. Da har du levert analysen og latt intervjueren gjøre prioriteringen — som er nøyaktig den delen som vurderes i candidate-led.<br><br><b>Sterkt:</b> tar alle tre leddene hver eneste gang, og gjør spesielt det midterste synlig. Å si hva du <i>legger bort</i> er det som beviser at du prioriterer. En kandidat som alltid ber om neste datasett uten å lukke noe, driver ikke casen — han utvider den." },

      { "n": 10, "k": "Husene", "lvl": 2,
        "s": "«Å trene på feil test» kalles den vanligste bortkastede uka i hele prosessen. Hva er det konkret som forveksles hos Bain og BCG, og hva gjør du i stedet?",
        "f": "<b>Bain:</b> screeningen er <i>enten</i> TestGorilla <i>eller</i> SOVA — to helt ulike tester. Invitasjonsmailen sier hvilken. Å trene på feil av de to er en tapt uke.<br><br><b>BCG Norden:</b> testen er <b>logisk resonnement, 80 spørsmål på 30 minutter, uten kalkulator</b> — dokumentert av BCG selv. Det er 22,5 sekunder per spørsmål, altså ren hastighetsdrill og ikke casetrening. Den er <b>ikke</b> Casey-chatboten; Casey og Pymetrics brukes i andre geografier.<br><br><b>Hva du gjør i stedet:</b> åpne invitasjonsmailen og les hva som faktisk står der, før du kjøper et kurs eller bruker en helg.<br><br><b>Middels svar:</b> husker at testene er forskjellige. <b>Sterkt svar:</b> ser at feilen ikke er uvitenhet, men <i>rekkefølge</i> — folk forbereder seg før de leser invitasjonen, fordi forberedelse føles produktivt og lesing ikke gjør det. Og legger til den beslektede for Kearney: 40 spørsmål på 60 minutter, altså 90 sekunder hver, over seks seksjoner uten kalkulator, med rapportert minuspoeng for feil svar og upubliserte scoringsregler — <b>der slår blankt gjetning</b>, som er stikk motsatt strategi av en test uten straff. Regelen for testene er den samme som for casen: sjekk hva som faktisk er dokumentert før du bruker tid." },

      /* ================= NIVÅ 3 ================= */

      { "n": 11, "k": "Vurderingen", "lvl": 3,
        "s": "Du har fått tilbakemeldingen «god struktur, men lite dømmekraft» etter et mock-intervju. Oversett den til tre konkrete vaner du skal endre, og si hvordan hver av dem høres ut i rommet.",
        "f": "Tilbakemeldingen betyr nesten alltid det samme: du produserer analyser og lar andre trekke konsekvensen.<br><br><b>Vane 1 — «so what» umiddelbart etter hvert tall.</b> Ikke etter tre tall, ikke i syntesen. <i>Høres ut som:</i> «Det er 14 prosent. Det er mer enn hele marginfallet, så denne ene posten kan forklare alt — de andre grenene kan jeg nedprioritere.»<br><br><b>Vane 2 — si hva du legger bort, og hvorfor, hver gang du velger.</b> Dømmekraft er ikke synlig i det du tar med; det er synlig i det du velger vekk med begrunnelse. <i>Høres ut som:</i> «Husleie lar jeg ligge — den er fast og har ikke endret seg på to år, så den kan ikke forklare et fall som kom i fjor.»<br><br><b>Vane 3 — skill symptom fra årsak høyt, minst én gang per case.</b> <i>Høres ut som:</i> «Churn er tallet som har flyttet seg, men churn er et symptom. Spørsmålet er hva kundene opplever før de sier opp — og der vil jeg se på leveringstid.»<br><br><b>Middels selvdiagnose:</b> «jeg må tenke mer på hva tallene betyr». Sant og uhandlingsbart — det gir ingen setning å øve på.<br><br><b>Sterk selvdiagnose:</b> oversetter en abstrakt karakter til <i>hørbare setninger</i>, fordi det er det eneste som kan trenes. Og ser den underliggende årsaken: god struktur og svak dømmekraft henger ofte sammen, siden en kandidat som er trygg på treet sitt gjerne <i>fullfører treet</i> i stedet for å forfølge det første funnet. Å forlate en gren tidlig føles som å svikte strukturen, og er i virkeligheten hele poenget." },

      { "n": 12, "k": "Vurderingen", "lvl": 3,
        "s": "Du har fire uker igjen til første intervju og omtrent ti timer i uka. Sett opp din egen prioritering, og begrunn rekkefølgen med hva som faktisk feller folk.",
        "f": "<b>Prioriteringen, i rekkefølge:</b><ol><li><b>Hoderegning hver dag, i korte økter.</b> Det er den eneste ferdigheten som blir målbart bedre av ren mengde, og den er hard å redde i selve rommet. 15–20 minutter daglig slår to timer på søndag.</li><li><b>Strukturering på så mange <i>forskjellige</i> prompter du rekker.</b> Kvantitet av ulike problemer slår dybde i ett — ferdigheten er å møte noe du aldri har sett, og den trenes bare av nye prompter.</li><li><b>Hele caser fra prompt til anbefaling, gjerne to i uka, gjort på tid.</b> Det er her de fire tingene måles samtidig, og det er den eneste øvelsen som avslører at strukturen tok fire minutter.</li><li><b>Fit-historiene skrevet ned.</b> De tar én kveld å lage og redder et helt intervju.</li></ol><b>Fordelt på ti timer i uka:</b> rundt to timer hoderegning (spredt på syv dager), fire timer struktureringsprompter, tre timer på to hele caser, og én time fit — og fit-timen tas <i>første</i> uke, ikke siste, fordi historiene må modnes.<br><br><b>Middels plan:</b> lister aktivitetene i den rekkefølgen kurset presenterer dem. <b>Sterk plan:</b> begrunner rekkefølgen med <i>redningsverdi</i> — hva som ikke kan improviseres i rommet kommer først. Regning kan ikke improviseres. En struktur kan bygges der og da hvis du har bygget nok av dem. En fit-historie kan ikke oppfinnes under press, men den kan skrives på en kveld. Og den vanskeligste innsikten: <b>har du få uker, gjør du ikke alt.</b> En plan som ikke velger bort noe, er ikke en plan — det er en ønskeliste, og den kollapser i uke to." },

      { "n": 13, "k": "Formatet", "lvl": 3,
        "s": "Skriv de to første minuttene av en case du ikke vet modus på. Prompt: En nordisk møbelkjede taper markedsandel til nettbaserte aktører og vil vite hva den skal gjøre. Ta med avklaringen, gjentakelsen og spørsmålene.",
        "f": "<b>Fasit, i rekkefølge:</b><br><br><b>1. Modus (5 sekunder).</b> «Før jeg starter — vil du at jeg skal drive casen fremover, eller foretrekker du å lede meg gjennom?»<br><br><b>2. Gjentakelsen med egne ord (20 sekunder).</b> «Slik jeg forstår det: klienten er en nordisk møbelkjede med fysiske varehus, den taper andel til rene nettaktører, og spørsmålet er hva den skal gjøre med det. Er det riktig oppfattet?» — <i>Egne ord, ikke prompten gjentatt ordrett. Å gjenta ordrett viser at du husker; å omformulere viser at du forstår.</i><br><br><b>3. Målet (10 sekunder).</b> «Hva er det klienten egentlig vil oppnå — å ta andelen tilbake, å beskytte lønnsomheten, eller å komme seg over på en modell som holder om fem år? De tre gir ulike anbefalinger.»<br><br><b>4. To–tre spørsmål som <i>endrer</i> strukturen (40 sekunder):</b><ul><li>«Taper vi andel fordi vi selger mindre, eller fordi markedet vokser der vi ikke er?» — avgjør om dette er et forsvars- eller et vekstproblem, og det er to helt ulike trær.</li><li>«Faller lønnsomheten sammen med andelen, eller holder marginen?» — avgjør om det haster.</li><li>«Har vi allerede en nettkanal, og hvor stor er den?» — avgjør om spørsmålet er å bygge eller å skalere.</li></ul><b>5. Så tenketid.</b> «Kan jeg få tretti sekunder til å strukturere?»<br><br><b>Middels åpning:</b> gjentar prompten, spør «hvor stort er markedet?» og går rett på strukturen. Markedsstørrelsen er nesten alltid et spørsmål som ikke endrer noen gren — det er et spørsmål som kjøper tid.<br><br><b>Sterk åpning:</b> stiller bare spørsmål som ville fått strukturen til å se annerledes ut avhengig av svaret, og sier gjerne hvorfor: «jeg spør fordi det avgjør om jeg bygger dette som et andels- eller et lønnsomhetsproblem». To–tre slike spørsmål er taket. Fem spørsmål er ikke grundighet, det er utsettelse — og de spises av løsningsbyggingen senere." },

      { "n": 14, "k": "Husene", "lvl": 3,
        "s": "Sett opp en tre ukers plan rettet spesifikt mot Arkwright. Bruk kildemerkene: hva er dokumentert, hva er kandidatrapport, og hva er ubekreftet — og la det styre hva du bruker tid på.",
        "f": "<b>Hva som er [D] — dokumentert av selskapet:</b> Oslo-kontor på Aker Brygge, rundt 60–65 konsulenter i Oslo og 120–150 i konsernet, med tyngdepunkt i strategi, profit improvement, M&amp;A og private equity. Det er selskapet som er dokumentert, ikke prosessen — men det er nok til å forme treningen, fordi det betyr korte, analytisk harde prosjekter.<br><br><b>Hva som er [K] — kandidatrapport, altså få kandidater og ikke et statistisk bilde:</b> to runder med én senior og én junior i hver, personlighets- og motivasjonsspørsmål som åpner hvert intervju, candidate-led case, og ett rapportert forløp med en enkel P&amp;L-case først og en M&amp;A-case etterpå med <b>20 minutter alene til å forberede en presentasjon</b>.<br><br><b>Hva som er ubekreftet og ikke skal trenes:</b> «den beryktede mattetesten». Det finnes <b>ingen dokumentasjon og ingen kandidatrapport</b> på at Arkwright bruker en numerisk screeningtest. Antall caser, om internship avviker fra fast stilling, og språket i rommet er heller ikke dokumentert.<br><br><b>Planen:</b><ul><li><b>Uke 1:</b> P&amp;L-mekanikk og enkel verdsettelsestenkning. Dette er [D]-drevet — det følger av hva firmaet faktisk gjør, ikke av rykter.</li><li><b>Uke 2:</b> candidate-led drilling, og fit-historier som tåler å åpne hvert intervju. Overlappen med BCG- og Bain-trening er stor, så denne uka er ikke bortkastet uansett hvor du havner.</li><li><b>Uke 3:</b> solo-presentasjonen. Gi deg selv 20 minutter alene med en M&amp;A-prompt, bygg en anbefaling, og fremfør den. <b>Dette er det eneste som ikke overlapper med noe annet hus</b>, og derfor det som har høyest avkastning per time.</li><li><b>Ikke i planen:</b> numerisk testtrening mot Arkwright. Send heller en e-post til recruiting@arkwright.no og spør. Det er raskere enn mer research.</li></ul><b>Middels plan:</b> trener mot ryktet, fordi ryktet er konkret og usikkerheten er ubehagelig. <b>Sterk plan:</b> lar kildekvaliteten bestemme timeforbruket — trene hardest mot det som følger av det dokumenterte, moderat mot det flere kandidater rapporterer, og <b>null</b> mot det ingen kan bekrefte. Å spørre er et lovlig trekk, og det tar ti minutter." },

      { "n": 15, "k": "Husene", "lvl": 3,
        "s": "Vurder disse tre påstandene og si hva du ville gjort med hver: (a) «McKinsey er interviewer-led.» (b) «BCG runde 1 er to case-intervjuer, finalen er én med partner.» (c) «Arkwright har en beryktet mattetest.» Bruk kildemerkene [D], [K], [P].",
        "f": "<b>(a) «McKinsey er interviewer-led» — [P], prep-bransjen.</b> Prep-bransjen har ofte hovedtrekkene riktig, men selger kurs og overdriver presisjonen. Her er hovedtrekket godt underbygget av mange uavhengige kilder, og konsekvensen er billig å ta høyde for. <i>Hva du gjør:</i> tren for det, men avklar med ett spørsmål i rommet uansett. Kostnaden ved å ta feil er hele intervjuet; kostnaden ved å spørre er to sekunder.<br><br><b>(b) «BCG runde 1 er to caser, finalen én med partner» — [D], dokumentert av BCG selv.</b> <i>Hva du gjør:</i> planlegg etter det uten forbehold. Samme kategori: BCG Nordens logikktest med 80 spørsmål på 30 minutter, som også er [D].<br><br><b>(c) «Arkwright har en beryktet mattetest» — verken [D], [K] eller egentlig [P].</b> Det finnes ingen dokumentasjon og ingen kandidatrapport. <i>Hva du gjør:</i> ingenting — bortsett fra å sende en e-post og spørre. Ikke tren mot en test som kanskje ikke finnes.<br><br><b>Middels vurdering:</b> rangerer de tre etter hvor sannsynlige de føles. <b>Sterk vurdering:</b> rangerer etter <i>kilde</i> og deretter etter <b>kostnaden ved å ta feil</b>, som er to uavhengige akser. (a) er svak kilde med lav feilkostnad, så tren og verifiser. (b) er sterk kilde, så bare planlegg. (c) er ingen kilde med høy tidskostnad, så la den ligge. Og den generelle regelen som følger: <b>datoer og prosessdetaljer er ferskvare.</b> Fristlisten er en kartlegging fra én dag, og hus flytter frister uten varsel — dobbeltsjekk mot portalen samme dag du søker." },

      /* ================= NIVÅ 4 ================= */

      { "n": 16, "k": "Vurderingen", "lvl": 4,
        "s": "45 sekunder, høyt. Du har funnet at 80 prosent av marginfallet ligger i én kundegruppe, at gruppen vokser, og at prisen der er 12 prosent lavere enn snittet. Lever anbefalingen. Svar først.",
        "f": "<b>Fasit:</b><br><br>«<b>Anbefalingen min er å reprise storkundesegmentet, ikke å kutte kostnader.</b> Tre grunner.<br><br><i>Én:</i> 80 prosent av marginfallet ligger i denne ene gruppen, så alt annet vi kunne gjort, adresserer maksimalt en femtedel av problemet.<br><br><i>To:</i> prisen der ligger 12 prosent under snittet, og gruppen vokser — så problemet blir større av seg selv hvis vi ikke gjør noe. Dette er ikke et engangsavvik, det er en trend som er innebygget i miksen.<br><br><i>Tre:</i> vi vet allerede at kundene kjøper til dagens pris, så spørsmålet er hvor mye av rabatten vi kan hente tilbake, ikke om segmentet er levedyktig.<br><br><b>Risikoen</b> er at de største kundene har forhandlingsmakt og kan flytte volum. Derfor vil jeg reprise ved fornyelse og ikke i løpende avtaler, og starte med de kundene som har lavest andel av vår kapasitet.<br><br><b>Neste steg:</b> hent prisliste mot realisert pris per kunde i segmentet, og ranger etter hvor mye en normalisering er verdt.»<br><br><b>Middels levering:</b> går gjennom analysen i den rekkefølgen den ble gjort, og lander på anbefalingen til slutt. Det er kronologi, ikke syntese — og på 45 sekunder rekker du aldri fram til poenget.<br><br><b>Sterk levering:</b> <b>svar først</b>, deretter to–tre grunner med harde tall, så risiko og neste steg. Legg merke til at hver grunn har et tall i seg, og at grunn to gjør det til en <i>hastesak</i> — det er den som flytter en anbefaling fra riktig til overbevisende. Og risikoavsnittet er ikke en innrømmelse: det er det som viser at du ville tørt å si dette til klienten selv." },

      { "n": 17, "k": "Formatet", "lvl": 4,
        "s": "20 sekunder. Intervjueren har akkurat lest prompten ferdig og sier ingenting mer. Han ser på deg. Hva sier du?",
        "f": "<b>Fasit, i denne rekkefølgen:</b><br><br>«Takk. La meg først sjekke at jeg har forstått: [gjenta problemet med egne ord på to setninger]. Er det riktig oppfattet?<br><br>Før jeg strukturerer — hva er det klienten egentlig vil oppnå her? Og vil du at jeg driver casen fremover, eller foretrekker du å lede meg gjennom?<br><br>Da vil jeg gjerne ta tretti sekunder til å samle tankene.»<br><br><b>Fire ting på tjue sekunder:</b> kvittere, gjenta med egne ord, avklare mål og modus, be om tenketid.<br><br><b>Middels reaksjon:</b> begynner å strukturere umiddelbart for å virke rask. Rask er ikke det som måles i denne fasen — <i>aktiv lytting</i> er, og de første to–tre minuttene er satt av til nettopp dette.<br><br><b>Nesten like dårlig:</b> stillhet i ti sekunder mens du skriver. Intervjueren vet ikke om du tenker eller har stoppet opp, og du har ikke sagt et ord han kan vurdere.<br><br><b>Sterkt:</b> be om tenketid <i>eksplisitt</i> og med en tidsangivelse. Det er helt legitimt, det gjør stillheten som følger til en avtalt stillhet i stedet for en pinlig en, og tretti sekunder med penn i hånd er verdt mer enn to minutter med improvisert struktur. Den vanligste tabben i hele denne sekvensen er å gjenta prompten <i>ordrett</i>: det beviser hukommelse, mens omformuleringen beviser forståelse — og det er bare den siste som gir poeng." },

      { "n": 18, "k": "Formatet", "lvl": 4,
        "s": "90 sekunder, candidate-led. Prompt: En bokhandelkjede med 70 butikker vurderer å legge ned halvparten og satse på nett. Kjør de to første minuttene som om du eier prosessen — og gjør deretter det samme åpningsgrepet i interviewer-led modus.",
        "f": "<b>Candidate-led:</b><br><br>«Jeg oppfatter spørsmålet som: er en halvering av butikknettet riktig grep, gitt at nettsalget skal ta over volumet? Jeg vil bygge dette rundt to spørsmål som må besvares i rekkefølge.<br><br><i>Først:</i> hvilke av de 70 butikkene taper penger på <b>særkostnadsbasis</b> — altså etter at vi har trukket fra bare de kostnadene som faktisk forsvinner hvis butikken stenges. Fullfordelt margin er feil mål her, fordi hovedkontor og lager blir igjen.<br><i>Så:</i> hvor mye av en stengt butikks omsetning som faktisk flytter seg til nett, og ikke til en konkurrent. Det er den ene forutsetningen hele beslutningen hviler på.<br><br>Jeg vil begynne med det andre, fordi det avgjør fortegnet på hele regnestykket. Kan jeg få vite om dere har stengt butikker før, og hva som skjedde med nettsalget i de postnumrene?»<br><br><b>Interviewer-led, samme prompt:</b> du sier den samme forståelsen, men avslutter et annet sted:<br><br>«… Jeg oppfatter spørsmålet som [samme to setninger]. Skal jeg begynne med å strukturere hvordan jeg ville vurdert dette, eller har du et konkret sted du vil at jeg skal starte?»<br><br><b>Forskjellen er de siste ti sekundene, og bare de.</b> Analysen, gjentakelsen og forståelsen er identiske. Candidate-led avsluttes med <i>ditt</i> valg av startpunkt og en dataforespørsel; interviewer-led avsluttes med å gi ballen tilbake.<br><br><b>Middels:</b> tror de to modiene krever ulike strukturer, og bytter tenkemåte. Det gjør de ikke.<br><br><b>Sterkt:</b> ser at det er <i>overleveringen</i> som skiller, ikke innholdet — og at ferdigheten derfor er billig å trene: kjør neste case candidate-led og den etter interviewer-led på samme prompt, og legg merke til at bare siste setning endres. Det er byttet mellom modi som er ferdigheten, ikke å beherske den ene." },

      { "n": 19, "k": "Husene", "lvl": 4,
        "s": "60 sekunder. Invitasjonen fra Bain ligger i innboksen. Si de tre tingene du sjekker først, og hva hver av dem endrer.",
        "f": "<b>Ett — hvilken test.</b> Bain sender <i>enten</i> TestGorilla <i>eller</i> SOVA, og mailen sier hvilken. <i>Endrer:</i> hva du forbereder den neste uka. Å trene på feil av de to er den vanligste bortkastede uka i hele prosessen.<br><br><b>To — hvilken runde og hvor mange intervjuer.</b> Bain kjører 2–3 runder over 4–6 uker. <i>Endrer:</i> hvor mye du kan spre treningen, og om skriftlig case er i bildet — den europeiske jokeren er rundt 55 minutter, sikt mot 3–5 slides, kalkulator ikke tillatt. Den trenes ikke ved å lese om den.<br><br><b>Tre — fristen for å svare og for å ta testen.</b> <i>Endrer:</i> alt annet. En test som må tas innen 72 timer gjør planen for uka til noe helt annet enn en med to ukers vindu.<br><br><b>Middels reaksjon:</b> begynner å øve umiddelbart, fordi det føles produktivt. Å lese invitasjonen føles ikke som forberedelse, og er den mest verdifulle halvtimen i hele prosessen.<br><br><b>Sterkt:</b> leser først, planlegger så — og tar med det som gjelder Bain spesielt: <b>case-stilen er i bevegelse mot interviewer-led og «answer first»</b>, så tren begge modi selv om Bain står oppført som candidate-led. Og Bain ber deg dele resonnement og utregninger <i>selv når du er usikker</i>, som er en eksplisitt invitasjon til å tenke høyt gjennom usikkerhet i stedet for å bli taus." },

      { "n": 20, "k": "Husene", "lvl": 4,
        "s": "90 sekunder. Det er 30. august. Ranger de norske søknadsfristene etter hva som haster, si hvilket hus som er det eneste som tåler å bli utsatt, og si hva du gjør i kveld.",
        "f": "<b>I dag, 30. august:</b> Arkwright (Internship 2027) og Implement (Junior Consultant + Graduate, Oslo). Disse er ikke «snart» — de er nå.<br><br><b>Innen to uker:</b> McKinsey 6. september (Associate Intern + Junior Associate), EY-Parthenon 8.–9. september, Bain 13. september (Associate Consultant), Arkwright Preview 13. september.<br><br><b>Sikkerhetsnettet:</b> Accenture 4. oktober — den seneste fristen blant de store.<br><br><b>Den eneste som tåler å bli utsatt: BCG.</b> Rullerende opptak, med portalfrist 31.12.2026. Alle de andre har en hard dato.<br><br><b>Hva som allerede er lukket:</b> PwC, Deloitte og KPMGs konsulentspor i denne syklusen. Deloittes neste vindu er januar. Kearney lyser ikke ut egen norsk graduate-frist på portalen.<br><br><b>Hva du gjør i kveld:</b> åpne NHH NU, dobbeltsjekk hver dato mot portalen samme dag — <b>listen er ferskvare og hus flytter frister uten varsel</b> — og send søknadene. Ikke tren case i kveld.<br><br><b>Middels prioritering:</b> begynner med den viktigste arbeidsgiveren. Det er å rangere etter preferanse, og preferanse er irrelevant når to frister går ut i dag.<br><br><b>Sterk prioritering:</b> rangerer etter <b>hva som er irreversibelt</b>. Du kan trene case etter fristen. Du kan ikke søke. Det er derfor kalenderen kommer før alt annet i forberedelsen — hele treningsplanen er verdiløs hvis søknaden ikke ble sendt, og en søknad tar to timer mens treningen tar seks uker. Aller sterkest: legg merke til at BCGs rullerende opptak er en fordel som kan bli en ulempe — uten en hard dato er det huset som lettest blir liggende." }
    ]
  }
};
