/* ============ CASETRENING · DYBDETRENING · BANK B (tall + framføring) ============
   Selvrettet trening. Du skriver svaret, avslører fasiten, og markerer selv
   om du kunne det. Rene data — visningen ligger i js/bundle-dybde.js.
   Kilder: kapittel 6–8 og tallarket i 15 for «tall», kapittel 9–12 og 14
   for «framforing». Alle tall er kontrollregnet mot ankertabellene i 7.5–7.6
   og 15.6.
   ============================================================================= */
window.EDU_DATA = window.EDU_DATA || {};
/* Object.assign, så lastrekkefølgen ikke kan slette banken i dybde.js. */
window.EDU_DATA.dybde = Object.assign(window.EDU_DATA.dybde || {}, {
  "tall": {
    "cats": ["Hoderegning", "Estimering", "Figurlesing"],
    "lvl": {
      "1": ["Nivå 1", "Teknikken — si hvordan grepet gjøres"],
      "2": ["Nivå 2", "Anvendelse — regn ett konkret tilfelle"],
      "3": ["Nivå 3", "Sammensatt — flere ledd, med sanity-sjekk"],
      "4": ["Nivå 4", "Under press — på tid, og sagt høyt"]
    },
    "items": [
      { id: 1, "k": "Hoderegning", n: 1,
        "s": "Hoderegningen din vurderes på tre ting samtidig. Hvilke tre er det, og hvilken av dem mangler oftest hos folk som faktisk regner godt?",
        "f": "<b>Oppsettet</b> — velger du riktig formel. <b>Utførelsen</b> — regner du riktig nok. <b>Formidlingen</b> — sier du hva du gjør mens du gjør det.<br><br>Den tredje er den som mangler. Kandidater som snakker gjennom utregningen får høyere uttelling på den kvantitative dimensjonen enn like nøyaktige kandidater som regner stille — fordi intervjueren kan stoppe deg før du har bygget fem ledd på et feil oppsett.<br><br><b>Sterkt mot middels:</b> middels regner riktig og leverer svaret. Sterkt sier formelen <i>før</i> tallene, ber om lov til å runde, sier størrelsesordenen først, og lever aldri mer enn 15–20 sekunder i stillhet. Presisjon er ikke kravet: et retningsriktig svar levert raskt, med framgangsmåten sagt høyt, slår et perfekt tall regnet i stillhet." },

      { id: 2, "k": "Hoderegning", n: 1,
        "s": "Forklar grepet «strip nullene, fest dem tilbake», og si hvilken enkeltfeil teknikken er motgift mot.",
        "f": "Del hvert tall i <b>sifre</b> og <b>tierpotens</b>, regn de to som atskilte regnestykker, og sett dem sammen først til slutt.<br><br><ul><li><b>32 × 25 000:</b> sifrene 32 × 25 = 800. Nullene: tre stykker. Svar <b>800 000</b>.</li><li><b>1,4 mrd × 350 kr:</b> mantissene 1,4 × 3,5 = 4,9. Potensene ni pluss to = elleve. Svar <b>490 mrd kr</b>.</li></ul>Motgift mot <b>å miste en tierpotens</b> — den vanligste feilen som finnes i caseregning. Symptomet er at svaret er tusen ganger for stort eller for lite, mens kandidaten regner videre uanfektet.<br><br><b>Sterkt mot middels:</b> middels vet at fellen finnes. Sterkt gjør den mekanisk umulig — skriv potensen som eget tall i margen, og <i>kontroller potensen før du kontrollerer sifrene</i>. Og skriv i enheter, ikke i siffer: «250M + 300M + 150M = 700M», med enheten på hver eneste linje." },

      { id: 3, "k": "Hoderegning", n: 1,
        "s": "Hvilke to ankere bygges all prosentregning av, og hvordan bygger du 5, 15, 18 og 35 prosent av dem?",
        "f": "<b>10 %</b> er å dele på 10. <b>1 %</b> er å dele på 100. Alt annet er addisjon og subtraksjon.<br><br><ul><li>5 % = halvparten av 10 % — 5 % av 2,9 mill. = <b>145 000</b></li><li>15 % = 10 % + 5 % — 15 % av 800 = <b>120</b></li><li>18 % = 20 % − 2 % — 18 % av 250 = <b>45</b></li><li>0,5 % = halvparten av 1 % — 0,5 % av 2,9 mill. = <b>14 500</b></li><li>35 % = 25 % + 10 % — 35 % av 40 mrd = <b>14 mrd</b></li></ul><b>Sterkt mot middels:</b> middels regner 0,18 × 250 direkte og bruker fem sekunder på å ikke bomme. Sterkt sier <i>«tjue prosent er femti, minus to prosent som er fem — førtifem»</i> mens hånden allerede skriver neste linje. Ankeret er ikke bare raskere; det gir intervjueren et regnestykke hun kan følge." },

      { id: 4, "k": "Hoderegning", n: 1,
        "s": "Hva er avrundingsregelen, og hvorfor gir 19 × 41 og 19 × 39 helt ulik uttelling for nøyaktig samme grep?",
        "f": "Regelen: <b>rund én faktor opp og den andre ned</b>, så feilene motvirker hverandre. Runder du begge samme vei, dobler du feilen i stedet for å nulle den ut. Ikke mer enn 10 prosent på ett enkelt ledd.<br><br><ul><li><b>19 × 41:</b> 20 × 40 = 800. Fasit 779 — <b>2,7 % bom</b>. Godt nok, fordi den ene gikk opp og den andre ned.</li><li><b>19 × 39:</b> samme grep gir også 800, men fasit er 741 — <b>8,0 % bom</b>, fordi begge ble rundet opp. Riktig her: 20 × 39 = 780, minus 39 = <b>741</b>, eksakt.</li></ul>Avrunding er metode, ikke slurv — men bare når retningen er kontrollert.<br><br><b>Sterkt mot middels:</b> middels runder og går videre. Sterkt flagger retningen høyt: «Jeg rundet opp, så det virkelige tallet ligger litt under — rundt 585.» Da vet intervjueren nøyaktig hvor mye presisjon svaret ditt bærer." },

      { id: 5, "k": "Hoderegning", n: 1,
        "s": "Si 72-regelen begge veier. Hvilke tall bruker du for tredobling og firedobling, og i hvilket ratespenn er regelen god?",
        "f": "<b>Doblingstid ≈ 72 / vekstrate</b> &nbsp;⇔&nbsp; <b>CAGR ≈ 72 / antall år til dobling</b>. Tredobling bruker <b>114</b>, firedobling <b>144</b>. Regelen er en tilnærming og er best mellom rundt 5 og 15 prosent.<br><br><ul><li>8 % vekst: 72 / 8 = 9 år — fasit 9,0 år</li><li>12 % vekst: 72 / 12 = 6 år — fasit 6,1 år</li><li>Doblet på 10 år: 72 / 10 = 7,2 % — fasit 7,2 %</li><li>100 mill. til 200 mill. på 5 år: 72 / 5 ≈ 14 % — fasit 14,9 %</li><li>10 % vekst, tredobling: 114 / 10 = 11,4 år — fasit 11,5 år</li></ul><b>Sterkt mot middels:</b> middels kan doblingstiden. Sterkt bruker <i>baklengsretningen</i>, for det er den som faktisk kommer i rommet: du får to tall og et antall år, og skal si en vekstrate uten å ta n-te rot av noe. Og på kort horisont med lav rate kan du gange lineært — men da sier du hvorfor: «4 prosent i 6 år er litt over 25 prosent, fordi renters rente.» Fasit 26,5 %." },

      { id: 6, "k": "Estimering", n: 1,
        "s": "Når velger du topp-ned og når bunn-opp? Si begrunnelsen slik du ville sagt den høyt, og nevn den typiske feilen i hver retning.",
        "f": "<b>Topp-ned</b> starter i en makrostørrelse — befolkning, husholdninger, BNP — og segmenterer nedover. Passer forbrukermarkeder. Typisk feil: for mange segmenteringssteg, så du mister sporet.<br><b>Bunn-opp</b> starter i én liten enhet — én butikk, én dag, én maskin — og skalerer oppover. Passer B2B, infrastruktur og kapasitetsbegrensede markeder. Typisk feil: enheten du bygger på er ikke representativ.<br><br><b>Begrunnelsen, høyt:</b> «Har markedet en naturlig makrostørrelse over seg, går jeg topp-ned. Er det <i>kapasitet</i> som setter grensen, går jeg bunn-opp, fordi et markedstall ikke gir meg noen ligning å regne i.»<br><br><b>Sterkt mot middels:</b> den vanligste svakheten er ikke å velge feil — det er å velge uten å si at man valgte. Intervjueren kan ikke skille en som traff fra en som gjettet, hvis begrunnelsen aldri ble uttalt. Sterkt krysspeiler i tillegg: «Jeg fikk 2,8 mrd topp-ned. Bunn-opp: 3 800 butikker × 1 900 kr per dag × 310 åpningsdager ≈ 2,2 mrd. Samme størrelsesorden — jeg lander på 2–3 milliarder.» Kravet er ikke at de møtes, men at de havner i samme tierpotens. Og tre filtre er nok; fire er ett for mye." },

      { id: 7, "k": "Estimering", n: 1,
        "s": "Hva er levetidstrikset, hvorfor skilles vekstleddet ut som eget ledd, og hvorfor er det den tryggeste forutsetningen du kan bygge på?",
        "f": "<b>Årlig marked = installert base / gjennomsnittlig levetid (+ vekst i basen)</b><br><br>Grepet snur oppgaven: i stedet for å gjette hvor mange som kjøper i år, teller du hvor mange som <i>eier</i>, og lar levetiden fortelle deg hvor mange av dem som må skiftes ut. Et modent marked selger nesten bare erstatninger.<br><br><b>Hvorfor vekstleddet skilles ut:</b> de to oppfører seg helt ulikt. Erstatningsvolumet er stabilt og forutsigbart; veksten svinger med konjunktur og befolkning. Blander du dem, kan du ikke si hvilken del av svaret som er robust.<br><br><b>Hvorfor det er trygt:</b> eierskap er noe du har egen erfaring med. Kjøpsfrekvens er det ikke. Du vet at du eier én oppvaskmaskin; du vet ikke hvor ofte folk kjøper dem.<br><br><b>Sterkt mot middels:</b> middels bruker formelen. Sterkt sier hvilken akse basen skal telles på — bil per person eller per husholdning? — og vet at husholdning mot individ er den aksen som koster mest å bomme på. TV, bil, vaskemaskin, hund og strømmeabonnement er per <b>husholdning</b>. Teller du dem per person, dobler du svaret." },

      { id: 8, "k": "Estimering", n: 1,
        "s": "Ram opp de norske ankertallene du skal kunne uten oppslag: befolkning, husholdninger, personer per husholdning, sysselsatte, personbiler, dagligvare, fastlands-BNP og gjennomsnittlig månedslønn.",
        "f": "<ul><li>Befolkning <b>5,6 mill.</b> — 1 % er 56 000. Bygg alle andre prosenter fra det.</li><li>Husholdninger <b>2,65 mill.</b>, med <b>2,1</b> personer per husholdning.</li><li>Sysselsatte <b>2,9 mill.</b> — grunnlaget for alt B2B som selges per ansatt. Arbeidsstyrken 3,1 mill.</li><li>Personbiler <b>2,9 mill.</b>, hvorav <b>0,95 mill.</b> elektriske (32 %). Nyregistrerte ~185 000.</li><li>Dagligvaremarkedet <b>~230 mrd kr</b> — referansen alle forbrukermarkeder måles mot.</li><li>Fastlands-BNP <b>~4 400 mrd kr</b>. Samlet BNP 5 500 mrd, ~1 mill. kr per innbygger.</li><li>Gjennomsnittlig månedslønn <b>62 000 kr</b>, altså rundt 745 000 i året. Medianlønn 56 000.</li><li>Boliger i småhus <b>~1,4 mill.</b>, ~12 000 nye ferdigstilt i året.</li><li>Oslo 0,73 mill. (~13 %), Bergen 0,3 mill., Trondheim 0,22 mill.</li></ul><b>Sterkt mot middels:</b> middels husker tallene. Sterkt sier <i>hvor de kommer fra</i> mens de brukes, og skiller faktum fra skjønn høyt: «Befolkningen er 5,6 millioner — det er et faktum jeg kan stå for. At 40 prosent går på kafé, er et skjønn jeg selv har satt.» Det skillet er noe av det som skiller en sterk estimeringsbesvarelse fra en middels. Og et drilltall du må lete etter, koster mer tid enn det sparer." },

      { id: 9, "k": "Figurlesing", n: 1,
        "s": "Du får et ark med en figur. Ram opp åpningsrutinen i riktig rekkefølge, og si hvilket steg som er der fellen ligger.",
        "f": "<ul><li><b>1. Be om et halvt minutt.</b> «Kan jeg få tretti sekunder til å lese dette?» Det er forventet, og det teller positivt.</li><li><b>2. Les tittelen høyt.</b> Bokstavelig.</li><li><b>3. Les aksene, enhetene og fotnoten høyt.</b> <i>Her ligger fellen, hver gang.</i> Si y-aksens startverdi som eget ord.</li><li><b>4. Parafraser og be om bekreftelse.</b> «Dette er omsetning per region, i millioner kroner, for 2023 og 2025, med regionene stablet. Stemmer det?»</li><li><b>5. Én observasjon, deretter én implikasjon.</b> Ikke les opp alle tallene.</li><li><b>6. Koble tilbake til spørsmålet du stilte før du fikk arket.</b></li><li><b>7. Si hva du vil vite videre.</b></li></ul><b>Sterkt mot middels:</b> middels leser figuren riktig og ramser opp hva den viser. Sterkt bruker pyramideprinsippet også her — konklusjonen først, tallene som støtte etterpå — og gjør rutinen i samme rekkefølge <i>også når figuren ser enkel ut</i>. Ferdigheten er ikke en innsikt, den er en vane." },

      { id: 10, "k": "Figurlesing", n: 1,
        "s": "Hva må leses først i hver av disse: 100 prosent stablet søyle, indeksert tidsserie, vannfall, Mekko og spredningsplott?",
        "f": "<ul><li><b>100 % stablet:</b> viser bare miks, ingen nivåer. Aldri les nivå ut av denne — spør etter totalen.</li><li><b>Indeksert tidsserie:</b> basisåret, og at 120 ikke er 120 enheter.</li><li><b>Vannfall / bro:</b> fortegn og rekkefølge. Kontroller at broen faktisk går opp.</li><li><b>Mekko:</b> areal er kroner. Bredde er markedsstørrelse, høyde er vår andel — den bredeste søylen er ikke størst.</li><li><b>Spredningsplott:</b> uteliggere og klynger, ikke trendlinjen.</li></ul>De øvrige: stablet søyle — totalen først, så miksendringen. Klynget søyle — hvilken dimensjon er gruppert og hvilken er farget. Linje — er y-aksen absolutt eller indeksert, og hvor starter den. Pris-, volum- og mikseffekt — hvilken effekt er størst i absoluttverdi, for <i>det</i> er svaret. Boblediagram — hva boblestørrelsen faktisk måler. Kakediagram — hva er totalen i kroner, og står den noe sted.<br><br><b>Sterkt mot middels:</b> middels leser diagrammet. Sterkt leser <i>diagramtypen</i> først og vet dermed hvilket spørsmål figuren ikke kan svare på — og sier det: «Dette er en 100 prosent stablet, så jeg kan ikke si noe om nivå. Har du totalen i kroner?»" },

      { id: 11, "k": "Hoderegning", n: 2,
        "s": "Regn 98 × 2,4 millioner i hodet. Si framgangsmåten høyt slik du ville gjort det i rommet.",
        "f": "<b>235,2 millioner.</b><br><br>Sagt høyt: «Jeg ekspanderer rundt et rundt tall. Hundre ganger 2,4 millioner er 240 millioner. Så trekker jeg fra to ganger 2,4 millioner, som er 4,8 millioner. Det gir <b>235,2 millioner</b> — millioner kroner, per år.»<br><br>Utregningen, linje for linje:<ul><li>(100 − 2) × 2,4 mill.</li><li>100 × 2,4 mill. = 240 mill.</li><li>2 × 2,4 mill. = 4,8 mill.</li><li>240 mill. − 4,8 mill. = <b>235,2 mill.</b></li></ul><b>Sterkt mot middels:</b> middels gjør 98 × 24 = 2 352 og fester på potensen — også riktig, men uten et grovsvar underveis. Sterkt leverer <i>størrelsesordenen etter tre sekunder</i>: «Dette lander rett under 240 millioner — la meg finne sifrene.» Da har intervjueren et brukbart tall før du er ferdig, og du kan bli avbrutt uten å tape noe." },

      { id: 12, "k": "Hoderegning", n: 2,
        "s": "Hva er 18 prosent av 3 500? Bruk etterkorreksjon fra 20 prosent, og si hvert ledd høyt.",
        "f": "<b>630.</b><br><br>Sagt høyt: «Tjue prosent av 3 500 er 700. Jeg rundet 18 opp til 20, altså to av tjue — ti prosent for mye. Så trekker jeg fra ti prosent av 700, som er 70. Svaret er <b>630</b>.»<br><br>Utregningen:<ul><li>20 % av 3 500 = 700</li><li>Overkorreksjon: 2 / 20 = 10 %</li><li>10 % av 700 = 70</li><li>700 − 70 = <b>630</b></li></ul>Kontroll: 0,18 × 3 500 = 630. Eksakt.<br><br><b>Sterkt mot middels:</b> middels bygger 18 % som 10 % + 5 % + 2 % + 1 % og bruker fire ledd. Sterkt går fra nærmeste runde anker og korrigerer <i>én gang</i>, med korreksjonen uttalt som prosent av prosenten — ikke som «litt mindre». Etterkorreksjonen er også det som gjør at du kan svare før intervjueren har lagt fra seg pennen." },

      { id: 13, "k": "Hoderegning", n: 2,
        "s": "En pris falt 15 prosent og er nå 2 550 kroner. Hva var den før? Si også hva feilsvaret er, og hvordan du avslører det på fem sekunder.",
        "f": "<b>3 000 kroner.</b><br><br>Sagt høyt: «Prosenten ble tatt av det <i>gamle</i> tallet, så jeg må dele meg tilbake, ikke gange meg fram. 2 550 delt på 0,85. Åtti prosent av 3 000 er 2 400, fem prosent til er 150 — det stemmer på 2 550. Svaret er <b>3 000 kroner</b>.»<br><br><b>Formelen:</b> opprinnelig verdi = ny verdi / (1 − fallet). Ikke ny verdi × (1 + fallet).<br><br><b>Feilsvaret:</b> 2 550 × 1,15 = 2 932,50. Det ligger som ferdig utregnet alternativ i enhver flervalgstest.<br><b>Avsløringen:</b> regn fallet fra feilsvaret. 2 932,50 − 2 550 = 382,50, og 382,50 / 2 932,50 = 13,0 % — ikke 15 %. Altså feil tall.<br><br><b>Sterkt mot middels:</b> middels husker formelen. Sterkt <i>kontrollerer den ved å gå veien tilbake</i>: 3 000 minus 15 prosent er 3 000 − 450 = 2 550. Ett ledd ekstra, to sekunder, og du kan aldri levere reverseringsfeilen." },

      { id: 14, "k": "Hoderegning", n: 2,
        "s": "Hvor mange prosent er 39 av 468? Og hva er 4 500 delt på 9? Gjør begge som oppslag, ikke som divisjon.",
        "f": "<b>8,3 prosent</b> og <b>500</b>.<br><br><b>39 av 468:</b> snu brøken. 468 / 39 = 12, altså 1/12, altså <b>8,3 %</b>. Sagt høyt: «Tolv ganger 39 er 468, så dette er en tolvdel — 8,3 prosent.»<br><br><b>4 500 / 9:</b> å dele på 9 er å dele på 10 og legge til rundt 11 prosent. 4 500 / 10 = 450, pluss 11 % = 499,5. Fasit <b>500</b>.<br><br>Brøktabellen skal sitte begge veier: 1/6 = 16,7 · 1/7 = 14,3 · 1/8 = 12,5 · 1/9 = 11,1 · 1/11 = 9,1 · 1/12 = 8,3 · 1/13 = 7,7 · 1/14 = 7,1 · 1/15 = 6,7 · 2/3 = 66,7 · 3/8 = 37,5 · 5/8 = 62,5.<br><br><b>Sterkt mot middels:</b> middels setter opp en lang divisjon og bruker tjue stille sekunder. Sterkt gjør aldri lang divisjon i et intervju — hun <i>gjenkjenner brøken</i>, og har derfor et tall å si høyt med én gang. Det er forskjellen mellom å bruke tjue sekunder og to minutter, og stillheten koster mer enn regnefeilen." },

      { id: 15, "k": "Hoderegning", n: 2,
        "s": "Driftsmarginen gikk fra 8 prosent til 10 prosent. Oppgi endringen på begge de to måtene den kan oppgis, og si hvilket ord som må sies høyt.",
        "f": "<b>+2 prosentpoeng</b>, og <b>+25 prosent relativt</b> (2 / 8 = 0,25).<br><br>Begge tall er riktige, og begge ligger som svaralternativ. Ordet som må sies høyt hver gang du sammenligner to prosenttall, er <b>«prosentpoeng»</b>.<br><br>Samme grep i tallarkets versjon: 45 % til 50 % er 5 prosentpoeng, men bare 11 prosent relativ økning (5 / 45).<br><br><b>Sterkt mot middels:</b> middels sier «marginen økte to prosent» og har dermed sagt noe som er feil på en måte ingen kan oppdage før senere. Sterkt sier <i>«to prosentpoeng, som er tjuefem prosent relativt»</i> — begge tallene, én gang, i samme setning. Blandes de sammen, blir svaret typisk en faktor ti feil, og fellen kommer nesten alltid sammen med et aksekutt i figuren." },

      { id: 16, "k": "Hoderegning", n: 2,
        "s": "Regn 240 × 450, 84 × 25 og 4 400 delt på 8 — med hvert sitt grep. Navngi grepet før du regner.",
        "f": "<b>108 000</b>, <b>2 100</b> og <b>550</b>.<br><br><ul><li><b>240 × 450 — halver og doble.</b> Halver den ene, doble den andre: 120 × 900 = <b>108 000</b>. Sagt høyt: «Jeg halverer 240 til 120 og dobler 450 til 900. Tolv ganger ni er 108, og så tre nuller.»</li><li><b>84 × 25 — faktoriser 25.</b> Å gange med 25 er å gange med 100 og dele på 4: 8 400 / 4 = <b>2 100</b>.</li><li><b>4 400 / 8 — halver tre ganger.</b> 4 400 → 2 200 → 1 100 → <b>550</b>.</li></ul>De tre andre grepene fra samme tabell: omorganiser (125 × 2,5 × 4 → (125 × 4) × 2,5 = 1 250), faktoriser 5 (860 × 5 → 8 600 / 2 = 4 300), del på 6 (del på 3, så halver: 1 800 → 600 → 300).<br><br><b>Sterkt mot middels:</b> middels kan grepene. Sterkt <i>navngir grepet høyt før tallene</i> — «jeg halverer og dobler her» — fordi det gjør regnestykket ditt reviderbart. Intervjueren følger metoden, ikke bare svaret, og kan si «stopp» før du er ferdig." },

      { id: 17, "k": "Estimering", n: 2,
        "s": "Hva er «én krone per nordmann per dag» verdt i året, og hva er «hundre kroner per husholdning per måned» verdt? Vis utregningen, og si hvorfor det første er det nyttigste ankeret som finnes.",
        "f": "<b>Én krone per nordmann per dag ≈ 2 milliarder kroner i året.</b><br>5,6 mill. × 365 = 2,044 mrd. Rund til <b>2 mrd</b>.<br><br><b>Hundre kroner per husholdning per måned ≈ 3,2 milliarder i året.</b><br>2,65 mill. × 100 kr × 12 = 3,18 mrd. Rund til <b>3,2 mrd</b>. Dette er versjonen for abonnementer og faste utgifter.<br><br><b>Hvorfor kroneankeret er det nyttigste:</b> nesten alle norske forbruksestimater kan sies i den enheten, og da får du plausibilitetssjekken gratis, uten å regne.<ul><li>2 kr per nordmann per dag ≈ 4 mrd</li><li>10 kr ≈ 20 mrd</li><li>100 kr ≈ 200 mrd — altså på nivå med hele dagligvaremarkedet, og umiddelbart absurd for ett enkelt produkt</li></ul><b>Sterkt mot middels:</b> middels regner estimatet ferdig og sier tallet. Sterkt <i>oversetter svaret til ankerenheten mens hun snakker</i>: «6,7 milliarder — det er drøyt tre kroner per nordmann per dag. Det er som en kaffe i måneden, og det er troverdig.» Ankeret er ferdig regnet; et anker du må regne ut i rommet er ikke et anker." },

      { id: 18, "k": "Estimering", n: 2,
        "s": "Anslå antall nye personbiler solgt i Norge per år med levetidstrikset. Regn hele veien, og si sanity-sjekken.",
        "f": "<b>Rundt 185 000 biler.</b><br><br>Sagt høyt, ledd for ledd:<ul><li>«Basen er 2,9 millioner personbiler — det er et ankertall.»</li><li>«En norsk bil lever rundt 17 år. Erstatning: 2,9 mill. / 17 ≈ <b>170 000</b>.»</li><li>«Bilparken vokser rundt 0,5 prosent i året. Én prosent av 2,9 millioner er 29 000, halvparten er <b>~15 000</b>.»</li><li>«Sum: <b>185 000 biler i året</b>.»</li></ul><b>Sanity, baklengs:</b> 185 000 av en base på 2,9 mill. er 6,4 prosent av bilparken skiftet ut hvert år — som svarer til en levetid på rundt 16 år. Det gjenskaper forutsetningen jeg selv satte, så ingen tierpotens har falt ut.<br><br>Faktisk førstegangsregistrert i 2025: 184 705.<br><br><b>Sterkt mot middels:</b> middels leverer 170 000 og stopper. Sterkt <i>skiller erstatning fra vekst som to ledd</i> og sier hvorfor: erstatningsvolumet er stabilt og forutsigbart, veksten svinger med konjunktur. Da vet intervjueren hvilken del av tallet ditt som er robust — og det er det som gjør estimatet brukbart i en anbefaling." },

      { id: 19, "k": "Figurlesing", n: 2,
        "s": "Y-aksen starter på 90. Søylene er 94 og 98, og den andre ser dobbelt så høy ut. Hva er den faktiske veksten, og hvorfor holder det ikke å vite at aksekutt finnes?",
        "f": "<b>4,3 prosent.</b> (98 − 94) / 94 = 4/94 = 4,26 %.<br><br>Den plottede høyden går fra fire til åtte enheter over grunnlinjen, altså en dobling i <i>synsinntrykk</i> — mens den faktiske veksten er 4,3 prosent.<br><br><b>Hvorfor kunnskap ikke hjelper:</b> effekten vedvarer etter at folk er opplært i den. Grafkompetanse beskytter ikke — de som leser figurer godt påvirkes også. Over fem studier ble 83,5 prosent av deltakerne påvirket. Du kan ikke forstå deg ut av denne fellen, fordi persepsjonen leverer svaret sitt før tenkningen får slippe til.<br><br><b>Det eneste som virker — vanen, ordrett:</b><br><i>«Y-aksen starter på 90, ikke på null, så jeg leser tallene og ikke høyden. Fra 94 til 98 er 4 av 94, altså 4,3 prosent.»</i><br><br>Én setning, hver gang, <b>også når aksen faktisk starter på null</b> — da er den gratis og tar to sekunder.<br><br><b>Sterkt mot middels:</b> middels oppdager aksekuttet når hun ser etter det. Sterkt har gjort avlesningen mekanisk: setningen utløses av synet av en y-akse, før inntrykket rekker å danne seg." },

      { id: 20, "k": "Figurlesing", n: 2,
        "s": "Vi har 20 prosent andel i et segment som utgjør 30 prosent av markedet. Hva er andelen vår av hele markedet, og hva heter fellen?",
        "f": "<b>6 prosent.</b> 0,20 × 0,30 = 0,06.<br><br>Fellen heter <b>prosent av prosent</b>, og den er nummer tre av de ni. Den nære tolkningen er «vi har 20 prosent», og den er gal med en faktor tre og et halvt.<br><br>Samme familie: en margin som «økte 2 prosent» er noe helt annet enn en som økte 2 prosentpoeng.<br><br><b>Vanen:</b> si nevneren høyt hver gang. «Tjue prosent <i>av segmentet</i>, og segmentet er tretti prosent <i>av markedet</i> — altså seks prosent av markedet.» Nevneren uttalt er hele forsvaret.<br><br><b>Sterkt mot middels:</b> middels regner riktig når hun blir spurt presist. Sterkt spør selv hvilken nevner spørsmålet ber om, <i>før</i> hun regner — fordi figuren nesten alltid er konstruert slik at den nærmeste tolkningen er den gale. Ikke for å lure deg, men fordi det er nettopp den forskjellen intervjueren vil se." },

      { id: 21, "k": "Hoderegning", n: 3,
        "s": "Omsetningen falt 15 prosent mens prisen økte 5 prosent. Hva skjedde med volumet? Regn det, og si hvorfor svaret ikke er minus 10 prosent.",
        "f": "<b>Volumet falt rundt 19 prosent.</b><br><br>Utregningen, sagt høyt: «Omsetning er pris ganger volum, så volumindeksen er omsetningsindeksen delt på prisindeksen. 0,85 delt på 1,05. Det er litt over 0,81 — altså et volumfall på rundt <b>19 prosent</b>.»<ul><li>0,85 / 1,05 = 0,8095</li><li>1 − 0,8095 = 0,1905 → <b>−19,0 %</b></li></ul><b>Hvorfor ikke −10 %:</b> prosenter kan ikke legges sammen — endringer <i>multipliseres</i>. Å trekke 5 fra 15 forutsetter at de to virker på samme grunnlag, og det gjør de ikke: prisøkningen virker på det nye volumet.<br><br><b>Sanity:</b> gå den andre veien. Volum ned 19 % og pris opp 5 % gir 0,81 × 1,05 = 0,85 — omsetningen ned 15 %. Det stemmer.<br><br><b>Sterkt mot middels:</b> middels svarer −10 % og har med det sagt at problemet er halvparten så stort som det er. Sterkt skriver <i>volumindeks = omsetningsindeks / prisindeks</i> som formel før hun regner, og bruker svaret til noe: «Volumet er ned nesten en femtedel. Da er dette ikke et prisproblem — kundene forsvant, og det er der jeg vil lete.»" },

      { id: 22, "k": "Hoderegning", n: 3,
        "s": "Et selskap gikk fra 140 til 280 millioner på seks år. Si CAGR uten å ta sjette rot av noe, og si hvor mye tilnærmingen bommer.",
        "f": "<b>Rundt 12 prosent.</b><br><br>Sagt høyt: «280 er nøyaktig det dobbelte av 140, så dette er en dobling på seks år. 72-regelen baklengs: 72 delt på 6 er <b>12 prosent i året</b>.»<br><br>Fasit: 2 opphøyd i en sjettedel, minus 1 = 12,25 %. Tilnærmingen bommer med 0,25 prosentpoeng, altså 2 prosent relativt — godt innenfor.<br><br><b>Merk hvorfor det gikk så fort:</b> du gjenkjente en dobling. Er tallene ikke en ren dobling, bruker du nærmeste faktor: tredobling tar 114, firedobling 144.<br><br><b>Kontrast — den feilen som ligger klar:</b> 140 til 280 er 100 prosent på seks år, altså «16,7 prosent i året» hvis du deler lineært. Det er 4,5 prosentpoeng for høyt, og det er feilsvaret som venter i alternativene.<br><br><b>Sterkt mot middels:</b> middels vet at 72-regelen finnes og bruker den framover. Sterkt bruker den <i>baklengs</i>, som er retningen som faktisk kommer — du får to tall og et antall år — og oppgir avviket selv: «Regelen er en tilnærming og er best mellom 5 og 15 prosent, så på 12 er den god. Fasit ligger rett over 12.»" },

      { id: 23, "k": "Hoderegning", n: 3,
        "s": "Klienten selger 24 000 enheter i måneden til 1 250 kroner, har 62 prosent dekningsgrad og 148 millioner i faste kostnader i året. Er de over nullpunktet, og med hvor mye margin? Regn hele veien.",
        "f": "<b>Ja — de tjener 75,2 millioner, og nullpunktet ligger på 239 millioner i omsetning, altså 66 prosent av dagens.</b><br><br>Sagt høyt, ledd for ledd:<ul><li>«Årlig volum: 24 000 × 12 = <b>288 000 enheter</b>.»</li><li>«Omsetning: 288 000 × 1 250 kr. Sifrene 288 × 125 = 36 000, og potensene gir <b>360 millioner kroner</b>.»</li><li>«Dekningsbidrag: 62 prosent av 360 mill. Seksti prosent er 216, to prosent til er 7,2 — <b>223,2 millioner</b>.»</li><li>«Minus faste 148 mill: <b>75,2 millioner i driftsresultat</b>.»</li><li>«Nullpunkt i omsetning = faste / dekningsgrad = 148 / 0,62 ≈ <b>239 millioner</b>.»</li><li>«Det er 66 prosent av dagens omsetning, så de tåler et omsetningsfall på en tredjedel før de går i null.»</li></ul><b>Sanity:</b> driftsmarginen er 75,2 / 360 = 21 prosent. Det plasserer dem over detaljhandel med merkevare og under programvare — plausibelt, og verdt å si: på det marginnivået er pris og markedsandel svaret, ikke kostnadskutt.<br><br><b>Sterkt mot middels:</b> middels regner nullpunktet ved å dele på prisen i stedet for på dekningsgraden — den vanligste metodefeilen i caseregning. Sterkt sier formelen i ord først, og legger til det ene leddet som gjør tallet til et råd: hvor mye omsetning tåler de å miste?" },

      { id: 24, "k": "Hoderegning", n: 3,
        "s": "Klienten vurderer å kutte prisen 3 prosent. Dekningsgraden er 30 prosent. Hvor mye må volumet opp for at de skal komme ut i null? Regn det, og kontroller svaret.",
        "f": "<b>Volumet må opp rundt 11 prosent.</b><br><br>Formelen: <b>nødvendig volumøkning = p / (m − p)</b>, der p er priskuttet og m dekningsgraden, begge i prosent.<br>3 / (30 − 3) = 3 / 27 = <b>11,1 %</b>.<br><br><b>Kontrollen, sagt høyt:</b> «La meg sjekke med tall. Sett prisen til 100 og variabel kostnad til 70, så dekningsbidraget er 30. Kutter jeg prisen til 97, blir dekningsbidraget 27. For å beholde samme totale dekningsbidrag må jeg selge 30 delt på 27 så mange enheter — altså <b>11 prosent flere</b>. Det stemmer.»<br><br><b>Og så tolkningen, som er halve svaret:</b> «Tre prosent i pris krever elleve prosent i volum. Det er nesten fire ganger så mye volum som pris, og det følger av at marginen er tynn. Spørsmålet er om markedet er elastisk nok — hvis ikke, er dette et tapsprosjekt.»<br><br><b>Sterkt mot middels:</b> middels husker formelen og leverer 11 prosent. Sterkt kjenner igjen <i>hvorfor forholdstallet er så brutalt</i>, og kobler det til bransjen: i dagligvare, fly og bilforhandel med under 3 prosent nettomargin kan et priskutt på to prosent utradere hele resultatet. Der er volum og kapasitetsutnyttelse løftestangen, ikke pris." },

      { id: 25, "k": "Estimering", n: 3,
        "s": "Anslå det norske markedet for oppvaskmaskiner i kroner per år. Velg akse, regn hele veien, og gjør minst to sanity-grep.",
        "f": "<b>Rundt 1,2 milliarder kroner.</b><br><br>Sagt høyt, ledd for ledd:<ul><li>«Riktig akse er <b>husholdning</b>, ikke individ — en oppvaskmaskin kjøpes én gang per hjem. Teller jeg per person, dobler jeg svaret.»</li><li>«Base: 2,65 mill. husholdninger × 75 prosent dekning ≈ <b>1,99 mill. maskiner</b> installert.»</li><li>«Levetid rundt 12 år: 1,99 mill. / 12 ≈ <b>165 000 enheter i året</b>.»</li><li>«Til rundt 7 000 kr stykket: 165 000 × 7 000 ≈ <b>1,16 mrd</b>. Jeg sier 1,2 milliarder.»</li></ul><b>Sanity 1 — per husholdning:</b> 1,16 mrd / 2,65 mill. = rundt 440 kr per husholdning per år. Det er en maskin til 7 000 kr hvert sekstende år, og det er i nærheten av levetiden jeg satte. Konsistent.<br><b>Sanity 2 — benchmark:</b> 1,2 mrd er en halv prosent av dagligvaremarkedet på 230 mrd. For én hvitevare er det troverdig; hadde jeg landet på 50 mrd, var en tierpotens på avveie.<br><br><b>Sterkt mot middels:</b> middels gjetter «hvor mange kjøper en oppvaskmaskin i året» og har da bygget på en forutsetning hun ikke har erfaring med. Sterkt teller <i>eierskap</i>, som hun har erfaring med, og lar levetiden gjøre resten. Og hun sier hvilke to tall som er fakta (2,65 mill. husholdninger) og hvilke to som er skjønn (75 prosent dekning, 12 års levetid) — så intervjueren vet nøyaktig hvor hun skal presse." },

      { id: 26, "k": "Estimering", n: 3,
        "s": "Anslå samlet lønnssum i Norge, og oppgi den som andel av fastlands-BNP. Bruk bare ankertall.",
        "f": "<b>Rundt 2 160 milliarder kroner, altså omtrent halvparten av fastlands-BNP.</b><br><br>Sagt høyt: «Jeg tar sysselsatte ganger månedslønn ganger tolv. 2,9 millioner sysselsatte, 62 000 kroner i måneden. 2,9 ganger 62 er rundt 180, så 180 milliarder i måneden — ganger tolv blir det <b>rundt 2 160 milliarder i året</b>.»<ul><li>2,9 mill. × 62 000 × 12 = 2 157,6 mrd</li><li>2 158 / 4 400 = 0,49 → <b>~49 prosent av fastlands-BNP</b></li></ul><b>Sanity — retningssjekk:</b> lønn skal være den største enkeltposten i en økonomi, men ikke hele den. En halvpart er nøyaktig der man skulle vente, så tallet står. Hadde jeg fått 20 prosent eller 90 prosent, hadde det vært en tierpotens eller en enhetsfeil.<br><br><b>Sanity — per hode:</b> 62 000 × 12 = 744 000 kroner i året per sysselsatt. Det kjenner jeg igjen, og et årsverk koster arbeidsgiveren betydelig mer enn det.<br><br><b>Sterkt mot middels:</b> middels regner tallet. Sterkt vet <i>hva det brukes til</i>: dette er ankeret for alt som selges som andel av lønnskostnad — HR-programvare, bemanning, rekruttering, forsikring. «Ett prosentpoeng av norsk lønnssum er 21,6 milliarder» er en setning som avgjør om et B2B-estimat er plausibelt, uten videre regning." },

      { id: 27, "k": "Estimering", n: 3,
        "s": "Anslå det norske markedet for varmepumper til enebolig, i kroner per år. Bruk levetidstrikset, skill erstatning fra nysalg, og sanity-sjekk mot to ankere.",
        "f": "<b>Rundt 2,4 milliarder kroner.</b><br><br>Sagt høyt, ledd for ledd:<ul><li>«Riktig nevner er <b>boliger i småhus</b>, ikke husholdninger — en luft-til-luft-pumpe monteres i en enebolig, ikke i en leilighet. Det er rundt <b>1,4 millioner</b> småhus.»</li><li>«Anta 60 prosent dekning: 1,4 mill. × 0,6 = <b>840 000</b> installerte pumper. Dette er et skjønn, ikke et faktum.»</li><li>«Erstatning, levetid rundt 12 år: 840 000 / 12 = <b>70 000 enheter i året</b>.»</li><li>«Nysalg: rundt 12 000 nye småhus ferdigstilles årlig, si 80 prosent med pumpe — <b>~9 600</b>. Sum rundt <b>80 000 enheter</b>.»</li><li>«Til 30 000 kr ferdig montert: 80 000 × 30 000 = <b>2,4 milliarder kroner</b>.»</li></ul><b>Sanity 1 — kroneankeret:</b> 2,4 mrd er rundt 1,2 kroner per nordmann per dag. For en varig installasjon i litt over halvparten av eneboligene er det plausibelt.<br><b>Sanity 2 — benchmark:</b> 2,4 mrd er én prosent av dagligvaremarkedet. Godt under taket, som det skal være.<br><br><b>Sterkt mot middels:</b> middels bruker 2,65 millioner husholdninger som nevner og lander 90 prosent for høyt, fordi leiligheter ikke har luft-til-luft. Sterkt velger nevneren <i>bevisst og høyt</i>, og skiller erstatning fra nysalg — så intervjueren ser at det stabile leddet er 70 000 og at bare 9 600 avhenger av byggekonjunkturen." },

      { id: 28, "k": "Estimering", n: 3,
        "s": "Regn de fire avledede dagligvareankerne: per husholdning per år, per uke, per innbygger per år, og hva ett prosentpoeng av markedet er verdt.",
        "f": "Fra <b>230 milliarder kroner</b>:<ul><li><b>Per husholdning:</b> 230 mrd / 2,65 mill. ≈ <b>87 000 kr i året</b></li><li><b>Per uke:</b> 87 000 / 52 ≈ <b>1 700 kr</b></li><li><b>Per innbygger:</b> 230 mrd / 5,6 mill. ≈ <b>41 000 kr i året</b></li><li><b>Ett prosentpoeng:</b> 1 % av 230 mrd = <b>2,3 mrd kr</b></li></ul>Sagt høyt for det første: «230 milliarder delt på 2,65 millioner husholdninger. 2,65 ganger 90 er rundt 238, så svaret ligger like under 90 000 — <b>rundt 87 000 kroner per husholdning per år</b>.»<br><br><b>Hvorfor disse er viktigere enn rådataene:</b> de er ferdig regnet. Et anker du må regne ut i rommet er ikke et anker. 1 700 kroner i uka er dessuten et tall du kan kjenne igjen fra ditt eget liv, og det er nettopp derfor det virker som sanity-sjekk.<br><br><b>Sterkt mot middels:</b> middels kjenner totalen på 230 milliarder. Sterkt bruker <b>prosentpoenget</b>: «En markedsandel på ett prosentpoeng i dagligvare er 2,3 milliarder kroner i omsetning. Da vet vi hva kampen om hyllemeter faktisk er verdt, og om synergien vi diskuterer er materiell.» Dagligvare er dessuten den beste norske målestokken: nesten alle forbrukermarkeder skal ligge under den, over 50 mrd er stort, og over 200 mrd er nesten sikkert feil." },

      { id: 29, "k": "Figurlesing", n: 3,
        "s": "En indeksert figur viser at segment A går fra 100 til 130 og segment B fra 100 til 110. A har 200 millioner i basisåret, B har 3 000 millioner. Hvem vokser mest, og hva er svaret verdt?",
        "f": "<b>B vokser mest i kroner — 300 millioner mot As 60 millioner.</b><ul><li>A: 200 mill. × 30 % = <b>60 mill.</b></li><li>B: 3 000 mill. × 10 % = <b>300 mill.</b></li></ul>B vokser altså fem ganger så mye i kroner, mens A har den bratteste kurven. Fellen heter <b>indeks forvekslet med absolutt</b>, og poenget er at den bratteste kurven ofte tilhører det <i>minste</i> segmentet.<br><br><b>Vanen:</b> les basisåret høyt, og si at 130 ikke er 130 enheter. Deretter: «Denne figuren viser relativ utvikling. Har du nivåtallene i basisåret? Uten dem kan jeg ikke si hvem som er størst eller hvem som bidrar mest.»<br><br><b>Sterkt mot middels:</b> middels leser figuren riktig og sier «A vokser raskest», som er sant og trivielt. Sterkt leverer observasjon <i>og</i> implikasjon: «A vokser raskest relativt, men B står for fem ganger så mye vekst i kroner. Skal vi allokere ressurser etter hvor pengene faktisk kommer fra, er det B — med mindre A er på vei til å bli stort nok til å ta igjen, og det krever at jeg får se flere år.» Merk at det siste leddet er en dataforespørsel, ikke en gjetning." },

      { id: 30, "k": "Figurlesing", n: 3,
        "s": "Et Mekko viser et byggsegment på 18 milliarder der vi har 8 prosent andel, og et industrisegment på 10 milliarder der vi har 22 prosent. Hvor tjener vi mest, og hva er det figuren gjør med øyet ditt?",
        "f": "<b>Industri: 2,20 milliarder mot byggs 1,44 milliarder.</b><ul><li>Bygg: 18 mrd × 8 % = <b>1,44 mrd</b></li><li>Industri: 10 mrd × 22 % = <b>2,20 mrd</b></li></ul>Fellen heter <b>areal-illusjon</b>. I et Mekko er bredde markedsstørrelse, høyde vår andel, og <i>arealet</i> er kroner. Den bredeste søylen — bygg, med 18 milliarder — er den nest minste i kroner. Øyet leser bredde som størrelse, fordi bredde er det som er lettest å sammenligne.<br><br><b>Vanen, ordrett:</b> «Dette er et Mekko, så arealet er kroner. Jeg regner bredde ganger høyde for hver søyle før jeg sier noe om hvilken som er størst.» Én setning, før inntrykket får sette seg.<br><br><b>Sterkt mot middels:</b> middels regner arealene når hun blir bedt om det. Sterkt regner dem uoppfordret og gjør et poeng av forskjellen: «Bygg er markedet med mest penger i, men industri er der <i>vi</i> har mest penger. Det er to ulike spørsmål, og hvilket vi skal svare på avhenger av om oppdraget er å beskytte dagens inntjening eller å finne vekst.» Å skille de to nevnerne er hele forskjellen." },

      { id: 31, "k": "Hoderegning", n: 4,
        "s": "Tjue sekunder, sagt høyt: fire prosent vekst i seks år — hvor mye er det totalt? Ikke ta noen potens.",
        "f": "<b>«Litt over 25 prosent, fordi renters rente.»</b> Fasit 26,5 %.<br><br>Slik sies det på tjue sekunder: «Fire ganger seks er 24, så lineært blir det 24 prosent. Men rentesrente legger på litt, så jeg sier <b>litt over 25 prosent</b> — og det ligger på 26 og en halv om vi regner det eksakt.»<br><br>Kontroll: 1,04 opphøyd i 6 = 1,2653 → <b>26,5 %</b>. Den lineære tilnærmingen bommer 2,5 prosentpoeng, altså 10 prosent relativt — akseptabelt <i>fordi du sa at den bommer og i hvilken retning</i>.<br><br>Tre vekstfaktorer verdt å ha som oppslag når det trengs mer presist: 1,1 i annen = 1,21, 1,1 i tredje = 1,331, og 1,1 i sjuende ≈ 2.<br><br><b>Sterkt mot middels:</b> middels sier «24 prosent» og har bommet ti prosent uten å vite det. Nesten like svakt: middels forsøker å regne 1,04 opphøyd i 6 i hodet og bruker halvannet minutt på tre desimaler ingen ba om. Sterkt gjør begge deler på én gang — leverer det lineære tallet, sier at det er for lavt, og navngir hvorfor. Metoden er svaret, ikke desimalen." },

      { id: 32, "k": "Hoderegning", n: 4,
        "s": "Tjue sekunder, sagt høyt: 3 800 butikker × 1 900 kroner per dag × 310 åpningsdager. Størrelsesorden først.",
        "f": "<b>Rundt 2,2 milliarder kroner i året.</b><br><br>Slik sies det:<br><i>«Dette lander i milliarder, ikke millioner — la meg finne sifrene. 3 800 ganger 1 900 er nesten 4 ganger 2, altså rundt 7,2 millioner kroner per dag. Ganger 310 dager: 7,2 ganger 3 er 21,6, så <b>rundt 2,2 milliarder kroner per år</b>.»</i><ul><li>3 800 × 1 900 = 7 220 000 kr per dag</li><li>7,22 mill. × 310 = <b>2 238 mill. ≈ 2,2 mrd kr</b></li></ul><b>Sanity, baklengs til én forutsetning:</b> 2,2 mrd fordelt på 3 800 butikker er 580 000 kroner per butikk per år — altfor lite for en dagligvarebutikk. Altså er dette <i>ikke</i> dagligvare, eller så er butikktallet feil. Når baklengsregningen gjenskaper en forutsetning du selv satte, vet du at ingen tierpotens har falt ut.<br><br><b>Sterkt mot middels:</b> middels regner riktig og leverer 2,238 milliarder — tre desimaler på et tall bygget av tre gjettede forutsetninger. Sterkt sier <b>størrelsesordenen etter tre sekunder</b>, leverer «2,2 milliarder», og bruker de siste fem sekundene på baklengssjekken i stedet for på et siffer ingen bruker." },

      { id: 33, "k": "Hoderegning", n: 4,
        "s": "Tjue sekunder, høyt og uten pause mellom dem: 35 prosent av 40 milliarder, 0,5 prosent av 2,9 millioner, og 15 prosent av 800.",
        "f": "<b>14 milliarder · 14 500 · 120.</b><br><br>Sagt høyt, uten pause:<ul><li>«35 prosent av 40 milliarder — det er 25 pluss 10. Ti milliarder pluss fire milliarder: <b>14 milliarder</b>.»</li><li>«0,5 prosent av 2,9 millioner — halvparten av én prosent. Én prosent er 29 000, halvparten er <b>14 500</b>.»</li><li>«15 prosent av 800 — ti pluss fem. 80 pluss 40: <b>120</b>.»</li></ul>Ingen av dem regnes direkte. Alle tre bygges av de to ankerne: 10 prosent er å dele på 10, 1 prosent er å dele på 100.<br><br><b>Sterkt mot middels:</b> middels kan hver enkelt, men trenger to sekunders stillhet før hvert svar til å sette opp regnestykket. Sterkt har <i>oppbyggingen</i> automatisert, ikke svarene — hun sier «tjuefem pluss ti» mens hun regner, så intervjueren hører metoden og ikke bare fasiten. Og enheten står på hvert eneste svar: «fjorten <i>milliarder kroner</i>». Å droppe enheten er den nest vanligste feilkilden, og den gir feil som ser helt plausible ut." },

      { id: 34, "k": "Estimering", n: 4,
        "s": "Nitti sekunder, sagt høyt: anslå antall barnehageplasser i Norge. Krysspeil to ankere før du lander.",
        "f": "<b>Rundt 260 000 plasser.</b><br><br>Sagt høyt, på tid:<ul><li>«Barnehage dekker aldersgruppen ett til fem år, altså fem årskull.»</li><li>«<b>Anker 1 — fødsler:</b> 55 000 fødsler i året × 5 årskull = <b>275 000 barn</b>.»</li><li>«<b>Anker 2 — aldersfordelingen:</b> 0,75 millioner barn 0–12 år er tretten årskull. Fem av tretten gir 0,75 mill. × 5/13 ≈ <b>288 000 barn</b>.»</li><li>«De to ligger innenfor fem prosent av hverandre, så jeg lander på rundt <b>280 000 barn</b> i barnehagealder.»</li><li>«Dekningsgraden er høy, si rundt 93 prosent: 280 000 × 0,93 ≈ <b>260 000 plasser</b>.»</li></ul><b>Sanity — per husholdning:</b> 260 000 plasser mot 2,65 millioner husholdninger er rundt én plass per tiende husholdning. Med rundt 2,1 personer per husholdning og fem barnekull i en befolkning på 5,6 millioner er det i riktig leie.<br><br><b>Sterkt mot middels:</b> middels velger ett anker og lander på 275 000 barn — og har da ingen måte å vite om hun bommet. Sterkt <b>krysspeiler to uavhengige ankere</b> og sier hva krysspeilingen viste: kravet er ikke at de møtes, men at de havner i samme tierpotens. Og hun skiller de to fakta (55 000 fødsler, 0,75 mill. barn) fra det ene skjønnet (93 prosent dekning) — så intervjueren vet at det bare er ett tall å presse på." },

      { id: 35, "k": "Estimering", n: 4,
        "s": "Seksti sekunder, sagt høyt: anslå det norske markedet for treningsabonnement i kroner per år, med sanity-sjekk.",
        "f": "<b>Rundt 6,7 milliarder kroner.</b><br><br>Sagt høyt, på tid:<ul><li>«Jeg går topp-ned, fordi dette er et forbrukermarked med en naturlig makrostørrelse over seg. Ligningen er befolkning × andel medlemmer × pris × 12.»</li><li>«Befolkning <b>5,6 millioner</b> — det er et ankertall.»</li><li>«Andel med abonnement: jeg setter <b>20 prosent</b>. Det er et skjønn. 20 prosent av 5,6 millioner er <b>1,12 millioner medlemmer</b>.»</li><li>«Pris: <b>500 kroner i måneden</b>, altså 6 000 i året.»</li><li>«1,12 millioner × 6 000 = <b>6,7 milliarder kroner</b>.»</li></ul><b>Sanity 1 — kroneankeret:</b> 6,7 mrd delt på 2 mrd er rundt <b>3,3 kroner per nordmann per dag</b>. Det er under en kaffe i uka, og det er troverdig for et abonnement en femtedel av befolkningen har.<br><b>Sanity 2 — benchmark:</b> 6,7 mrd er <b>2,9 prosent av dagligvaremarkedet</b> på 230 milliarder. Godt under, som et enkeltmarked skal være.<br><br><b>Sterkt mot middels:</b> middels leverer 6,7 milliarder og stopper — og har da ikke vist at hun kan oppdage om tallet er absurd. Sterkt bruker <b>minst to av de fem sanity-grepene og sier begge høyt</b>. Det er ikke regnefeilen som feller kandidaten; det er at hun ikke oppdager at svaret er urimelig og bygger en anbefaling på det." },

      { id: 36, "k": "Estimering", n: 4,
        "s": "Tretti sekunder: et estimat for det norske hundefôrmarkedet endte på 56 milliarder kroner. Si sanity-sjekken høyt, og si hva du gjør videre.",
        "f": "<b>Tallet er åpenbart for høyt — med minst en tierpotens.</b><br><br>Sagt høyt: «56 milliarder delt på 5,6 millioner nordmenn er <b>10 000 kroner per nordmann per år</b> på hundefôr. Det er åpenbart for høyt — jeg har gått galt på frekvensen.»<br><br>Tre grep som alle peker samme vei:<ul><li><b>Per capita:</b> 56 mrd / 5,6 mill. = 10 000 kr per nordmann per år.</li><li><b>Per husholdning:</b> 56 mrd / 2,65 mill. = 21 000 kr per husholdning per år — mer enn en firedel av hele dagligvareregningen på 87 000.</li><li><b>Kroneankeret:</b> 56 mrd er 27 kroner per nordmann per dag. Ti kroner er 20 milliarder; hundre kroner er 200 milliarder, altså hele dagligvaremarkedet. Hundefôr kan ikke ligge en fjerdedel av veien dit.</li></ul><b>Hva du gjør videre:</b> ikke start på nytt. Gå tilbake til den ene forutsetningen som mest sannsynlig er gal — her frekvens eller pris per kilo — og korriger den. Baklengs til én forutsetning er det sterkeste av de fem sanity-grepene, nettopp fordi det peker på <i>hvilken</i> forutsetning som ryker.<br><br><b>Sterkt mot middels:</b> middels regner riktig og leverer et absurd tall. Å regne riktig, men ikke fange et urimelig svar, leses som svak konsulentintuisjon — og det er en tyngre dom enn en regnefeil. Sterkt legger til ett siste ledd i <i>hver eneste</i> utregning: del svaret på noe du har erfaring med, og si høyt om det er troverdig." },

      { id: 37, "k": "Estimering", n: 4,
        "s": "Nitti sekunder, sagt høyt: anslå det norske frisørmarkedet i kroner, og avslutt med en kapasitetssjekk baklengs.",
        "f": "<b>Rundt 12 milliarder kroner — og anslaget ligger i øvre kant.</b><br><br>Sagt høyt, på tid:<ul><li>«Jeg bygger snittet av segmenter i stedet for å gjette på totalen. På tvers av barn, menn, kvinner og pensjonister lander jeg på rundt <b>4 klipp per innbygger per år</b>.»</li><li>«5,6 millioner × 4 = <b>22,4 millioner klipp</b>.»</li><li>«Til rundt <b>550 kroner</b> stykket: 22,4 millioner × 550. Tjue millioner ganger 550 er 11 milliarder, og de siste 2,4 millionene er 1,3 — <b>rundt 12 milliarder kroner</b>.»</li></ul><b>Kapasitetssjekken baklengs:</b> «22,4 millioner klipp delt på rundt 8 500 frisører er 2 635 klipp per frisør per år. Delt på 250 arbeidsdager blir det <b>10,5 klipp per frisør per dag</b>. Det er i overkant av en normal arbeidsdag, så anslaget ligger i øvre kant — og <i>det</i> sier jeg høyt.»<br><br><b>Benchmark:</b> 12 mrd er drøyt 5 prosent av dagligvaremarkedet. Et norsk forbrukermarked over 50 mrd er stort; dette er godt innenfor.<br><br><b>Sterkt mot middels:</b> middels leverer 12 milliarder med to desimaler og full selvtillit. Sterkt <b>krysspeiler etterspørselssiden mot tilbudssiden</b> — klipp mot frisørkapasitet — og bruker resultatet til å kalibrere retningen på egen usikkerhet. Å si «dette ligger i øvre kant, og her er hvorfor» er sterkere enn et presist tall uten spenn." },

      { id: 38, "k": "Figurlesing", n: 4,
        "s": "Tretti sekunder, sagt høyt: figuren viser 100 000 kunder begge år. Nye kunder gikk fra 25 til 50 prosent, lojale fra 30 til 20 prosent. Lever observasjon, implikasjon og neste steg.",
        "f": "<b>Slik sies det, på tretti sekunder:</b><br><i>«Totalen er uendret på 100 000 kunder, men lojale kunder er ned fra 30 000 til 20 000 — en tredjedel <b>[observasjon]</b>. Vi lekker kunder like fort som vi skaffer dem, så anskaffelseskostnaden er doblet uten at basen har vokst <b>[implikasjon]</b>. Jeg vil se churn per kohort før jeg konkluderer <b>[neste steg]</b>.»</i><br><br>Regningen bak: lojale 30 % av 100 000 = 30 000, deretter 20 % av 100 000 = 20 000. Fallet er 10 000 av 30 000 = <b>en tredjedel</b>. Nye kunder gikk fra 25 000 til 50 000, altså en dobling.<br><br>Fellen heter <b>miksendring skjult bak flat total</b>. Selskapet vokser ikke — det løper på tredemølle og betaler dobbelt for å stå stille.<br><br><b>Sterkt mot middels:</b> den vanligste svake besvarelsen er ikke feil — den er en <i>oppramsing</i>. «Nye kunder er doblet» er sant, og skårer nesten ingenting: det er halve observasjonen uten implikasjonen. Sterkt leverer alle tre leddene i én pust, og velger det ene tallet som bærer poenget i stedet for å lese opp figuren. Merk også at implikasjonen inneholder et <i>kostnadsutsagn</i> som ikke står i figuren — den er utledet, og det er nettopp det som er innsikt." },

      { id: 39, "k": "Figurlesing", n: 4,
        "s": "Tabellen har fotnoten «Alle tall i 1 000 kr». Summen av kolonnen er 2 807 400. Svaralternativene er oppgitt i millioner. Hva er svaret, og hvorfor er dette den dyreste fellen som finnes?",
        "f": "<b>2 807,4 millioner kroner</b> — altså rundt 2,8 milliarder.<br><br>Utregningen: 2 807 400 enheter × 1 000 kr = 2 807 400 000 kr = <b>2 807,4 mill. kr</b>.<br><br>De to feilsvarene som ligger klare: «2,8 millioner» (fotnoten ble ikke lest) og «2 807 400 millioner» (fotnoten ble lest to ganger). Begge ser plausible ut i en liste.<br><br>Dette er den oppgitte <b>hovedårsaken til feilsvar på aggregeringsoppgaver</b>. Grunnen er at fellen ikke ligger i figuren, men <i>utenfor</i> den — i overskriften eller fotnoten, som er stedet blikket hopper over.<br><br><b>Vanen:</b> steg tre i åpningsrutinen er å lese aksene, enhetene og fotnoten <b>høyt</b>. «Alle tall i tusen kroner» sagt med stemmen, før du ser på en eneste søyle.<br><br><b>Sterkt mot middels:</b> middels leser fotnoten, forstår den, og glemmer den fire regnesteg senere. Sterkt <i>skriver enheten øverst på regnearket</i> og gjentar den på hver linje — «tusen kroner», «millioner kroner» — så konverteringen ikke kan gå tapt underveis. Å droppe enheten gir feil som ser helt plausible ut: en månedsinntekt levert som årsinntekt, eller «30 klasserom per elev» i stedet for «30 elever per klasserom»." },

      { id: 40, "k": "Figurlesing", n: 4,
        "s": "Tretti sekunder, høyt: én region vokser 240 millioner fra en base på 800, mens samlet vekst er 520 millioner. En annen region vokser 55 prosent. Hvilken nevner ber spørsmålet om?",
        "f": "<b>Region A har 30 prosent vekstrate, men står for 46 prosent av veksten.</b><ul><li><b>Vekstrate:</b> 240 / 800 = <b>30 %</b></li><li><b>Vekstbidrag:</b> 240 / 520 = <b>46 %</b> av all vekst i selskapet</li><li>Den andre regionen vokser <b>55 prosent</b>, men bidrar bare 220 mill. — altså 220 / 520 = <b>42 %</b>, fra en base på bare 400 mill.</li></ul>Sagt høyt: «Før jeg svarer må jeg vite hvilken nevner du spør om: veksten <i>i</i> regionen, eller regionens andel <i>av</i> veksten. Den ene regionen har lavest vekstrate og høyest vekstbidrag samtidig.»<br><br>Dette er fellen som glir lettest gjennom, fordi <b>begge tall er riktige</b>. Ingenting i figuren avslører at du har svart på feil spørsmål.<br><br><b>Sterkt mot middels:</b> middels leser «55 prosent» og peker på den raskest voksende regionen — sant, og feil svar på spørsmålet som ble stilt. Sterkt spør etter nevneren <i>før</i> hun regner, og kobler til beslutningen: «Skal vi allokere flere selgere, følger jeg vekstbidraget, for det er der kronene kommer fra. Skal vi lære hva som virker, følger jeg vekstraten, for den lille regionen gjør åpenbart noe riktig.» Samme tall, to ulike anbefalinger — og det er derfor nevneren må uttales." }
    ]
  },
  "framforing": {
    "cats": ["Kommunikasjon", "Syntesen", "Fit"],
    "lvl": {
      "1": ["Nivå 1", "Grepet — si hva det er og hvorfor det virker"],
      "2": ["Nivå 2", "Formuleringen — si den ordrett, som en replikk"],
      "3": ["Nivå 3", "Sammensatt — hele sekvensen på et konkret tilfelle"],
      "4": ["Nivå 4", "Under press — på tid, høyt, uten notater"]
    },
    "items": [
      { id: 1, "k": "Kommunikasjon", n: 1,
        "s": "Hva er den ene regelen for alt du sier i et caseintervju, og hva er forskjellen på de to versjonene av «det er kaldt, og de fleste har gått»?",
        "f": "<b>Konklusjonen først, hver gang du åpner munnen.</b><br><br><b>Bunn-opp:</b> «Det er kaldt, og de fleste har gått, så jeg tror vi bør dra.»<br><b>Topp-ned:</b> «Jeg mener vi bør dra. For det første er det kaldt, for det andre har de fleste gått.»<br><br>Rekkefølgen er den <i>eneste</i> forskjellen — samme ord, samme innhold. En lytter som får konklusjonen først, kan sortere alt som kommer etterpå inn under den. En som får den sist, bruker tiden på å gjette hvor du skal, og halve tiden gjetter hun feil.<br><br><b>Men «tenk høyt» betyr ikke at hver halvtenkte idé skal ut.</b> Ta en pause, velg hva som er verdt å dele, og del det ferdig formet. Topp-ned er regelen som holder de to kravene sammen: du skal snakke, men du skal snakke i ferdige enheter.<br><br><b>Sterkt mot middels:</b> Bain skriver selv at de vil ha resonnementet ditt <i>også når du er usikker</i>, og BCG har «ikke bli taus» på sin egen liste. En kandidat som blir stille kan ikke vurderes — det finnes ingenting å sette en karakter på. Middels forstår dette og snakker mye. Sterkt snakker i konklusjoner, og lar strukturen være hørbar." },

      { id: 2, "k": "Kommunikasjon", n: 1,
        "s": "Beskriv notatsystemet: hvor mange ark, hvilken jobb har hvert av dem, og hvorfor ligger de i landskapsformat?",
        "f": "<b>Tre ark, i landskapsformat</b> — trær og tabeller får plass når arket ligger på tvers.<ul><li><b>Innsiktsarket.</b> Klientnavn, prompt og mål øverst til venstre; alt du får vite underveis, på høyre side. Dette arket forlater du aldri, og det er dette du synteserer fra.</li><li><b>Strukturarket.</b> Issue-treet. Dette er arket du eventuelt snur mot intervjueren.</li><li><b>Regnearket.</b> Nytt ark for hvert regnestykke — ikke et hjørne av et gammelt.</li></ul><b>Slik ser regnearket ut:</b> øverst, i ord, før du rører et tall: <i>Filmleie = billettinntekt × sats.</i> Under: billettinntekt 1 240, sats i fjor 43 prosent, i år 48. Så én linje per steg, hver merket. Nederst: svaret, innrammet.<br><br>Skriv forutsetningene ned, ikke bare si dem — du blir spurt om dem.<br><br><b>Sterkt mot middels:</b> middels har ryddige notater. Sterkt har notater med <i>faste roller</i>, og verdien viser seg til slutt: kandidater som mister tråden i anbefalingen, mistet den i notatene, ikke i hodet. Innsiktsarket er grunnen til at du kan si fire konkrete tall i syntesen uten å lete. Og målet øverst til venstre er også en filtreringsregel, ikke bare en overskrift." },

      { id: 3, "k": "Syntesen", n: 1,
        "s": "Nevn de fire forskjellene mellom en oppsummering og en syntese. Ingen av dem handler om hvor mye arbeid som ligger bak — hvorfor er det poenget?",
        "f": "<ul><li><b>Verbene.</b> Oppsummeringen forteller hva <i>du</i> gjorde. Syntesen sier hva <i>klienten</i> skal gjøre.</li><li><b>Rekkefølgen.</b> Oppsummeringen er kronologisk. Klienten var med hele veien — hun trenger ikke referatet.</li><li><b>Tallene.</b> «Steget en del» mot «fem prosentpoeng, 78 millioner i året». Det andre er etterprøvbart.</li><li><b>Standpunktet.</b> «Det ser ut som» er ikke et svar. «Jeg anbefaler» er.</li></ul><b>Hvorfor det er poenget:</b> to kandidater med nøyaktig samme 25 minutters analyse kan levere hver sin av disse. Syntesen krever ikke mer arbeid — den krever at du velger. Derfor er dette leddet rent håndverk, og derfor er det uforsvarlig å improvisere det.<br><br><b>Testen:</b> kan første setning stå alene i et styrereferat, uten resten? Da er det syntese. Må den ha med seg de fem foregående setningene for å bety noe, er det oppsummering.<br><br><b>Sterkt mot middels:</b> middels avslutter med «så det ser ut som filmleien er en viktig faktor her» — alt arbeidet er gjort, og ingenting av det leveres. Sterkt sier «resultatet faller fordi distributørene har tatt fem prosentpoeng mer av hver billettkrone», og har med det gjort de siste seksti sekundene til den delen av casen som huskes." },

      { id: 4, "k": "Syntesen", n: 1,
        "s": "Hva står RRRN for, og hvorfor kan ikke risikoen komme før grunnene?",
        "f": "<b>Recommendation, Reasoning, Risks, Next steps.</b> Minto-pyramiden anvendt på ett minutt. Hvert ledd står der det står av en grunn:<ul><li><b>Anbefalingen først</b>, fordi den bestemmer hvordan alt annet blir hørt.</li><li><b>Grunnene etter</b>, fordi et funn ikke betyr noe før man vet hva det skal bære.</li><li><b>Risikoen etter grunnene, ikke før.</b> Et forbehold sagt <i>før</i> standpunktet leses som at du ikke tør. Det samme forbeholdet sagt <i>etter</i> leses som dømmekraft. <b>Ordene er de samme.</b></li><li><b>Neste steg til slutt</b>, fordi det er det eneste leddet som krever noe av <i>henne</i> — og fordi det siste du sier, er det som blir sittende.</li></ul>Legg merke til at risikoleddet er det klareste eksempelet på at rekkefølge er innhold: nøyaktig samme setning skifter fra svakhet til styrke ved å flytte seg tretti sekunder.<br><br><b>Sterkt mot middels:</b> middels dekker alle fire leddene, men åpner med «det avhenger jo litt av …» og har dermed brukt risikoleddet som innledning. Sterkt legger forbeholdene der de hører hjemme, og lever anbefalingen <i>som en beslutning</i> — tonen bærer halve budskapet: samme setning sagt spørrende blir et forbehold, sagt rolig blir det et råd." },

      { id: 5, "k": "Syntesen", n: 1,
        "s": "Du har seksti sekunder til syntesen. Fordel dem på de fire leddene, og si kravet til hvert ledd.",
        "f": "<ul><li><b>Anbefaling — 10–15 sek.</b> Ett verb og ett objekt. «Kjøp Sørbakst.» Ingen «det avhenger av».</li><li><b>Grunner, 2–3 stk — 25–30 sek.</b> Ett tall fra casen per grunn. Nummerert høyt: «For det første …»</li><li><b>Risiko, 1–2 stk — 10 sek.</b> Risikoen <i>anbefalingen din skaper</i> — ikke en generisk risiko.</li><li><b>Neste steg, 1–2 stk — 10 sek.</b> Noe klienten kan gjøre denne uken.</li></ul>Anslaget på 60–90 sekunder kommer fra prep-bransjen og er ikke publisert av noe firma. Behandle det som en ramme du velger: ett minutt er kort nok til å tvinge fram prioritering, og <b>det er prioriteringen som vurderes</b>.<br><br><b>Grepet som gjør det trygt:</b> be om et halvminutt først. «Kan jeg få et halvminutt til å samle dette?» Skriv så to–tre <i>stikkord</i> — ikke setninger — for hvert av de fire leddene.<br><br><b>Sterkt mot middels:</b> middels improviserer syntesen fordi hun kan casen godt. Det er unødvendig risiko på det tidspunktet i intervjuet som teller mest. Sterkt bruker tretti sekunder på fire linjer stikkord og leverer derfor uten å lete — og stopper på tre grunner, fordi fire signaliserer at hun ikke har prioritert." },

      { id: 6, "k": "Fit", n: 1,
        "s": "Hva er PEI, hvilke fire dimensjoner har det etter navneendringen i 2025, hva het de før, og hvor mange historier graver intervjueren i?",
        "f": "<b>PEI = Personal Experience Interview</b>, McKinseys navn på fit-delen. Fire dimensjoner, alle omdøpt sommeren 2025 — substansen er uendret:<ul><li><b>Leadership</b> (før <i>Inclusive Leadership</i>) — du fikk folk til å trekke sammen, særlig noen som ikke måtte høre på deg.</li><li><b>Connection</b> (før <i>Personal Impact</i>) — du overbeviste noen som var uenig, og forsto hvorfor.</li><li><b>Drive</b> (før <i>Entrepreneurial Drive</i>) — du satte i gang noe selv og drev det gjennom motstand.</li><li><b>Growth</b> (før <i>Courageous Change</i>) — du tok en risiko eller feilet, og vet hva du lærte.</li></ul>Du får <b>én dimensjon per intervju</b>, og intervjueren graver i <b>én historie</b> i hele tidsvinduet. Tre intervjuer betyr tre ulike dimensjoner, så du trenger dekning på alle fire. BCG og Bain spør etter det samme uten navn på dimensjonene.<br><br><b>Sterkt mot middels:</b> middels kan taksonomien og lar det merkes. <b>Si aldri dimensjonsnavnet høyt</b> — verken «dette er min courageous change-historie» eller den nye etiketten. Firmaets interne taksonomi som overskrift på ditt eget svar avslører prep-materialet. Sterkt vet at én historie skal bære tjue minutter, og bygger derfor for dybde, ikke for bredde." },

      { id: 7, "k": "Fit", n: 1,
        "s": "Hvilke sju felter må en fit-historie ha? Nevn særlig de tre flertallet hopper over, og si hvorfor de avgjør.",
        "f": "De fire vanlige: <b>navn, situasjon, handling, resultat</b>.<br><br>De tre som avgjør om historien overlever oppfølging nummer tre:<ul><li><b>Hva sto på spill.</b> Ikke oppgaven, men konsekvensen: hva ville gått galt hvis ingen gjorde noe?</li><li><b>Hvem var uenig, og hvorfor mente de det.</b> Halve jobben ligger i siste ledd. Vet du bare <i>at</i> noen var uenig, har du ikke undersøkt historien.</li><li><b>«Så derfor».</b> Én setning om hva utfallet betydde utover deg selv. Ble rutinen beholdt året etter?</li></ul>Feltet «hva DU gjorde» skrives i <b>jeg-form</b>. McKinsey advarer mot «vi» på sin egen karriereside — dette er sjansen din til å skryte litt.<br><br>Og start «Situasjonen» med konteksten: «NHHS Consulting, våren 2026 …», ikke «Det var en gang jeg …» — ellers ser dekningsmatrisen fire historier fra samme sted.<br><br><b>Sterkt mot middels:</b> middels har situasjon, handling og resultat, og kollapser i fase to av sondene — der intervjueren spør hva den andre parten faktisk mente. Sterkt har undersøkt motparten <i>før</i> intervjuet, og kan derfor svare på «hvorfor sto hun så hardt på det?» uten å dikte. En pyntet historie kollapser nettopp der, fordi oppdiktede historier ikke har replikker." },

      { id: 8, "k": "Kommunikasjon", n: 2,
        "s": "Hva sier du, ordrett, når du vil ha tretti sekunder til å strukturere? Gi den på norsk og på engelsk.",
        "f": "<b>Norsk:</b> «Kan jeg få tretti sekunder? Da kommer jeg tilbake med tre grener og hvilken jeg vil starte i.»<br><b>English:</b> “Could I take thirty seconds? I'll come back with three branches and where I want to start.”<br><br>Setningen har <b>to deler, og begge må med</b>: <i>hvor lenge</i>, og <i>hva du kommer tilbake med</i>. Å ta tid er forventet. Å ta tid uten å varsle er å bli stille — og det er samme handling for intervjøren.<br><br>Trenger du mer: «Jeg trenger et halvminutt til — er det greit?» Det er bedre enn å levere en halv struktur.<br><br>Normene som sirkulerer — 60 til 120 sekunder til den første strukturen, 30 til 60 før et regnestykke — er rekonstruksjon fra ex-MBB-coacher, ikke publisert av noe firma. Behandle dem som størrelsesorden.<br><br><b>Sterkt mot middels:</b> middels sier «kan jeg få litt tid?» og gir intervjueren ingen forventning å måle mot. Sterkt <b>lover et leveranseinnhold</b>, og holder løftet på sekundet. Og i pausen skriver du — du fyller den aldri med lyd. Stillhet du har varslet, er greit. «Ehm» i tolv sekunder er det ikke." },

      { id: 9, "k": "Kommunikasjon", n: 2,
        "s": "Hva sier du, ordrett, når du er ferdig i én gren og vil over i en annen? Og hva sier du rett før et regnestykke? Begge språk.",
        "f": "<b>Lukke en gren</b><br>«Da har jeg det jeg trenger fra prisgrenen: prisen er ikke problemet. Nå går jeg over til kostnadene.»<br>“I have what I need from the pricing branch. I'd now like to move to costs.”<br><br><b>Før et regnestykke</b><br>«Jeg gjør dette i tre steg: volumet, så marginen, så sammenligning med i fjor.»<br>“I'll do this in three steps: volume, then margin, then a comparison with last year.”<br><br><b>Etter et tall</b><br>«Det gir 34 millioner. Det betyr at hele fallet ligger her.»<br>“That gives us 34 million. What that means is that the whole decline sits here.”<br><br>Hos MBB i Oslo kan intervjuet gå på engelsk uten forvarsel. Den engelske versjonen er ikke noe du rekker å oversette i rommet.<br><br><b>Sterkt mot middels:</b> middels går videre til neste gren, og intervjueren må selv gjette at den forrige er ferdig. Sterkt <b>lukker grenen med en konklusjon</b> — «prisen er ikke problemet» — så eliminasjonen blir hørbar. Og hun bruker navnet hver gang hun kommer tilbake: «kostnadsgrenen», ikke «det første vi snakket om». Tell dessuten før du lister: «Det er tre ting jeg vil se på.» Den ene vanen gjør at intervjueren opplever deg som MECE selv når innholdet strengt tatt ikke er det." },

      { id: 10, "k": "Kommunikasjon", n: 2,
        "s": "Prompten er: en kinokjede med 40 kinoer, resultatet ned fra 111 til 78 millioner på tre år, besøket flatt. Si rekapituleringen ordrett.",
        "f": "<b>Ordrett:</b><br><i>«La meg gjenta, så jeg er sikker på at jeg har forstått oppdraget: klienten driver 40 kinoer, resultatet har falt fra 111 til 78 millioner på tre år, mens besøket er flatt. Dere vil vite hvorfor, og hva de skal gjøre. Er det riktig oppfattet?»</i><br><br>Tre ting og bare tre skrives ned når prompten kommer: <b>målet, tallet og spørsmålet</b>. Pennen ligger stille de første sekundene — du ser på personen, ikke på papiret.<br><br>Rekapituleringen er den mest brukte måten å kjøpe tid på lovlig. Den gir deg <b>femten sekunder</b> og fanger misforståelser før de vokser.<br><br><b>Legg merke til de tre leddene:</b> du gjentar konteksten (40 kinoer), tallet (111 → 78 på tre år), og det du <i>ikke</i> ble fortalt at var viktig (besøket er flatt). Det siste er allerede halve strukturen: er volumet flatt, har du eliminert halve treet på ett sekund.<br><br><b>Sterkt mot middels:</b> middels gjentar prompten som referat. Sterkt gjentar den <i>som en avklaring</i>, avslutter med «er det riktig oppfattet?», og har allerede plukket ut hvilket tall som styrer strukturen. Er formatet uklart, følger hun opp med: «Vil du at jeg driver casen fremover, eller foretrekker du å lede meg gjennom?» Det tar to sekunder og avgjør hvordan du skal oppføre deg i tjue minutter." },

      { id: 11, "k": "Kommunikasjon", n: 2,
        "s": "Du oppdager selv at du har brukt fjorårets volum i et regnestykke for to minutter siden. Hva sier du, ordrett?",
        "f": "<b>Ordrett:</b><br><i>«Jeg har brukt fjorårets volum her. Riktig tall gir en margin på 6 prosent, ikke 8. Det endrer tallet fra 40 til 34 millioner, men ikke konklusjonen.»</i><br><br>Regelen er <b>én anerkjennelse, ikke tre unnskyldninger</b>.<br><br><b>Slik ikke:</b> «Åh, unnskyld, det var dumt, jeg beklager — jeg skulle sett det, beklager, jeg tar det på nytt …»<br><br><b>Det avgjørende siste leddet:</b> du <b>kalibrerer betydningen høyt</b> — «men ikke konklusjonen». Det viser at du vet hva som er materielt, og det er en annen ferdighet enn å regne riktig.<br><br>Rangeringen er klar: <b>å fange sin egen feil er bedre enn ikke å gjøre feil</b>, fordi det viser at du kvalitetssikrer eget arbeid. Å bli tatt er verre. Å skjule er verst — intervjueren vet nesten alltid, og det leses som manglende selvinnsikt, ikke som dårlig hoderegning.<br><br><b>Sterkt mot middels:</b> middels retter feilen og går videre i høyere tempo. Sterkt <b>senker tempoet i ett minutt etterpå</b> — andreordensfeilen er at kandidater som mister fotfestet forserer neste del og gjør feil nummer to. De rekonstruerte scoringsskjemaene har «modenhet og fremtoning» som egen akse, og den aksen blir først <i>synlig</i> når noe går galt." },

      { id: 12, "k": "Kommunikasjon", n: 2,
        "s": "Intervjueren sier at du tar feil. Si begge svarene ordrett: ett når hun ga deg ny informasjon, og ett når hun bare press-tester deg. Hva er det ene spørsmålet som avgjør hvilket du velger?",
        "f": "<b>Spørsmålet du stiller deg selv:</b> «Kom det et faktum jeg ikke hadde?» Det er hele skillet.<br><br><b>Ny informasjon — du snur, og sier hvorfor:</b><br><i>«Med den kostnadsstrukturen faller argumentet mitt. Jeg reviderer til at problemet ligger på volumsiden.»</i><br>“With that cost structure my argument doesn't hold. I'd revise to …”<br><br><b>Ingen ny informasjon — du blir stående:</b><br><i>«Jeg har tenkt på det, og jeg blir stående — av to grunner. For det første … For det andre …»</i><br>“I've considered that, and I'd still hold my position, for two reasons.”<br><br>Og først av alt: <b>ikke svar refleksivt.</b> Ta ett sekund. Refleksivt forsvar leses som defensivt, refleksiv kapitulasjon som ryggradsløst.<br><br><b>Sterkt mot middels:</b> skillet i én setning — å endre mening på grunnlag av <i>data</i> er styrke; å endre mening fordi intervjueren løftet et øyenbryn, er svakhet. Samme handling utenfra, motsatt vurdering. Middels har bare én modus, og den er som regel å gi seg. Sterkt har begge, og velger mellom dem synlig. Avbrytelser hos McKinsey er dessuten normalen, ikke et faresignal — formatet er intervjuerledet, så tren på å bli avbrutt i stedet for å øve på uforstyrrede monologer." },

      { id: 13, "k": "Kommunikasjon", n: 2,
        "s": "Du er fortsatt uenig etter at intervjueren har presset. Si ordrett hvordan du ber om plass og rammer inn uenigheten.",
        "f": "<b>Ordrett:</b><br><i>«Jeg ser dette annerledes — kan jeg dele mitt perspektiv? Den veien fungerer, men den gir de to største leverandørene all makten. Er det en risiko klienten kan bære?»</i><br>“I see this differently — may I share my perspective?”<br><br>Tre ting skjer i den replikken:<ul><li>Du <b>ber om plass før du tar den</b>. Uenigheten blir en invitasjon, ikke et avbrudd.</li><li>Du <b>gir motparten rett i det som er riktig</b> — «den veien fungerer» — så det som følger ikke leses som avvisning.</li><li>Du <b>rammer uenigheten som risikovurdering</b> og gir den tilbake som et spørsmål. Nå diskuterer dere klientens risiko, ikke hvem som har rett.</li></ul><b>Sterkt mot middels:</b> middels sier «jeg er uenig, fordi …» og har med det gjort samtalen til en konkurranse hun ikke kan vinne. Sterkt flytter uenigheten fra person til sak i første setning. Merk også at spørsmålet til slutt gjør det billig for intervjueren å gi seg — hun trenger ikke innrømme noe, bare svare på om risikoen er bærbar. Det er en konsulentferdighet, ikke en intervjuferdighet, og det er derfor den scorer." },

      { id: 14, "k": "Fit", n: 2,
        "s": "Kjør byttetesten. Hva er den, hvilke fire ord avslører raskest, og hvordan skriver du om et svar som ikke består den?",
        "f": "<b>Byttetesten:</b> skriv ned svaret ditt på «why this firm», bytt firmanavnet, og les det høyt. <b>Overlever det byttet, har du beskrevet konsulentbransjen — ikke firmaet.</b> Fungerer «why BCG»-svaret ditt ordrett på «why McKinsey», er det ikke et svar. Dette er den mest siterte enkeltdiagnosen i hele materialet.<br><br><b>De fire ordene som avslører raskest</b>, fordi alle bruker dem og ingen skiller: <i>bratt læringskurve, smarte kolleger, utfordrende problemer, globalt fotavtrykk</i>.<br><br><b>Slik består du den — en navngitt samtale:</b><br><i>«Jeg snakket med Marte på Oslo-kontoret på karrieredagen i februar. Hun hadde nettopp vært på et prosjekt for et oppdrettsselskap, og det hun sa som ble hengende var at halve jobben gikk med til å få to avdelinger som ikke stolte på hverandre til å bruke samme tall. Det var ikke slik jeg hadde tenkt på konsulentarbeid, og det gjorde meg mer interessert, ikke mindre.»</i><br><br>En samtale kan ikke googles og kan ikke kopieres til neste firma. Den består byttetesten av seg selv.<br><br><b>Sterkt mot middels:</b> middels leser karrieresidene og gjengir dem godt. Sterkt skaffer <b>én kaffe</b> — kontordag, bedriftspresentasjon, alumninettverket, eller en høflig melding til en analytiker som gikk ut to år før. Én kaffe er verdt mer enn ti timer på karrieresidene. Uten samtale er andrevalget noe etterprøvbart og lokalt: en praksisgruppe, en rapport du faktisk har lest, eller hvordan Oslo-kontoret jobber mot norsk energi, offentlig sektor eller sjømat. Og si at det er førstevalget ditt, uten forbehold." },

      { id: 15, "k": "Syntesen", n: 2,
        "s": "Gjør disse tre om fra sannheter om verden til funn fra casen, ordrett: «markedet vokser raskt», «kostnadene har økt betydelig», «det er synergier å hente».",
        "f": "<ul><li>«Markedet vokser raskt» → <b>«Markedet er 1,2 milliarder i dag og 1,9 om tre år.»</b></li><li>«Kostnadene har økt betydelig» → <b>«Filmleien er opp 132 millioner; ingen annen post har flyttet seg mer enn 10.»</b></li><li>«Det er synergier å hente» → <b>«44 av de 60 synergimillionene ligger i én post: 55 stillinger.»</b></li></ul>Hver grunn må være noe du <i>faktisk fant</i> i de siste 25 minuttene. Dette er «så derfor»-leddet, og det er der de fleste svarene tynnes ut — fordi generelle sannheter er lettere å si enn tall man må ha regnet ut.<br><br><b>Tre praktiske regler:</b> si tallet som tall, ikke som adjektiv. Stopp på tre grunner — fire signaliserer at du ikke har prioritert. Nummerer dem høyt, «for det første … for det andre …», så lytteren vet når du er ferdig med én.<br><br><b>Sterkt mot middels:</b> legg merke til hva som skjer i den andre omskrivingen: «opp 132 millioner» er et tall, men <b>«ingen annen post har flyttet seg mer enn 10»</b> er det som gjør tallet til et argument. Middels leverer tallet. Sterkt leverer tallet <i>og</i> kontrasten som gjør det avgjørende — for uten den vet ikke lytteren om 132 millioner er mye." },

      { id: 16, "k": "Kommunikasjon", n: 3,
        "s": "Du står helt fast midt i casen. Ram opp de fire trekkene i rekkefølge, og nevn de to trekkene som gjør situasjonen verre.",
        "f": "Gi deg selv en grense på <b>tretti sekunder</b>, og gå så gjennom fire trekk i rekkefølge:<ul><li><b>1. Si hvor du er.</b> Ikke <i>at</i> du er fast — <i>hvor</i>. Beskriv kanten av det du vet, og navngi hullet. Dette løser situasjonen oftere enn noe annet, fordi du viser intervjueren nøyaktig hvilket hull hun kan fylle.</li><li><b>2. Gå tilbake til målet.</b> Les det høyt fra øverste venstre hjørne av innsiktsarket. «Målet var å forklare et fall på 33 millioner. Da er spørsmålet: hvilke poster har flyttet seg med minst 33 millioner? Alt som er mindre, kan jeg legge bort.» Målet er en filtreringsregel, ikke bare en overskrift.</li><li><b>3. Gå tilbake til identiteten.</b> Resultat er inntekter minus kostnader. Hvilken gren har jeg ikke rørt? Et tre kan gås gjennom systematisk; en temaliste kan ikke.</li><li><b>4. Be om et tall.</b> «Har dere kostnadene fordelt på post for de tre siste årene?» er et sterkt spørsmål. «Er det noe annet jeg burde se på?» er det ikke — det ber intervjueren om å gjøre jobben din.</li></ul><b>De to trekkene som gjør det verre:</b> å <b>gjette et tall</b> for å fylle stillheten (nå må du forsvare noe du ikke tror på), og å <b>starte en ny struktur fra bunnen</b> — det dyreste du kan gjøre i rommet: du kaster fem minutters arbeid, mister alt intervjueren allerede har akseptert, og bruker opp tiden du hadde igjen.<br><br><b>Sterkt mot middels:</b> skill de to måtene å stå fast på. Står du fast i <b>regningen</b>, går du til formelen i ord øverst på regnearket — feilen ligger nesten alltid i oppsettet, ikke i multiplikasjonen. Står du fast i <b>retningen</b>, går du til målet. Å behandle et retningsproblem som et regneproblem er grunnen til at folk regner videre på noe som ikke betyr noe. Og husk hvordan dette faktisk vurderes: tjue sekunder fast, etterfulgt av en ryddig vei ut, er et <i>bedre</i> datapunkt enn aldri å komme i klemma." },

      { id: 17, "k": "Kommunikasjon", n: 3,
        "s": "Du står fast: du vet at marginen har falt og volumet er flatt, men du mangler kostnadene fordelt på post. Si trekk 1 ordrett, på norsk og engelsk.",
        "f": "<b>Norsk:</b><br><i>«Jeg står litt fast, så la meg si hvor jeg er. Jeg vet at marginen har falt og at volumet er flatt, så fallet må ligge i kostnadene. Det jeg mangler, er kostnadene fordelt på post. Uten den fordelingen kan jeg ikke velge gren.»</i><br><br><b>English:</b><br>“Let me say where I am. I know the margin has fallen and volume is flat, so the decline has to sit in costs. What I'm missing is the cost breakdown by line item.”<br><br><b>De fire leddene i replikken:</b> du navngir tilstanden, oppsummerer det du <i>vet</i>, trekker den slutningen kunnskapen tillater («fallet må ligge i kostnadene»), og navngir presis hvilket datapunkt som mangler.<br><br><b>Sterkt mot middels:</b> middels sier «jeg står litt fast» og stopper der — det gir intervjueren en tilstand, ikke et handlingsrom. Sterkt gjør stillstanden til en <b>dataforespørsel</b>. Og selv om hun ikke fyller hullet, har du vist at du vet forskjellen på <i>å mangle data</i> og <i>å mangle retning</i> — som er selve skillet mellom en kandidat som har mistet kontrollen og en som ikke har det. Det eneste trekket som ikke lar seg redde, er å bli stille: utgangen av en blindvei er per definisjon noe du sier høyt." },

      { id: 18, "k": "Kommunikasjon", n: 3,
        "s": "Intervjueren gir deg et hint om at hun vil et annet sted enn der du er. Hva sier du ordrett, hvor mange ganger kan du spørre, og hva er alternativet som straffes?",
        "f": "<b>Ordrett:</b><br><i>«Er dette en retning du synes er verdt å forfølge, eller vil du at jeg ser et annet sted?»</i><br><br>Det er et legitimt spørsmål — <b>én gang</b>. Bain sier selv at de ser etter kandidater som fanger opp signaler og justerer. <b>Å ignorere et hint er derimot på BCGs egen liste over feil.</b><br><br>Alternativet som straffes, er å registrere hintet og likevel fortsette i samme spor for ikke å virke usikker. Det leses ikke som selvtillit; det leses som at du ikke hører etter.<br><br><b>Og når hintet er fulgt, sier du hva du gjør:</b> «Da legger jeg prisgrenen til side og går rett på kostnadssiden» — så justeringen blir et valg og ikke en drift.<br><br><b>Sterkt mot middels:</b> merk kontrasten mot spørsmål nummer to i motsatt situasjon: å endre retning fordi det kom <i>informasjon</i> er styrke, mens å endre retning fordi noen løftet et øyenbryn er svakhet. Et hint er informasjon — det er intervjueren som forteller deg hvor tiden er verdt å bruke. Middels behandler alle signaler likt. Sterkt skiller signal fra press, og bruker spørsmålet sparsomt: to ganger blir det å be henne drive casen for deg." },

      { id: 19, "k": "Syntesen", n: 3,
        "s": "Hva er testen på om en risiko er ekte? Gi et eksempel på en som består, og forklar hvorfor «forutsatt at synergiene realiseres» er verdiløst.",
        "f": "<b>Testen:</b> hvis risikoen slår til, ville anbefalingen din endret seg? Er svaret nei, er det pynt.<br><br><b>En risiko som består:</b><br><i>«Den store risikoen er kundeoverlappet: kjedene liker ikke å gå fra to leverandører til én, og et volumfall på ti prosent spiser en tredjedel av synergien.»</i><br><br>To ting gjør den ekte: den er <b>kvantifisert</b>, og den er <b>skapt av anbefalingen</b> — den finnes ikke hvis klienten lar være å kjøpe.<br><br><b>Hvorfor «forutsatt at synergiene realiseres» er verdiløst:</b> alle synergier er forutsatt. En setning som er sann uansett hva svaret er, tilfører ingenting. Samme sak gjelder «det avhenger av gjennomføringen» og «kulturell fit blir viktig».<br><br>Det som er verdt å si, er hvilken <b>mekanisme</b> som gjør at de blir realisert — en earn-out knyttet til at stillingene faktisk er ute, for eksempel.<br><br><b>Neste steg må bestå samme prøve:</b> konkret nok til å settes i gang i morgen, og helst med data klienten allerede sitter på. «Det første jeg ville gjort, er å ringe tjue av de tapte kundene denne uken.»<br><br><b>Sterkt mot middels:</b> å ta med risiko og neste steg skiller deg fra flertallet — men bare hvis de er ekte. Middels legger til et forbehold for å virke balansert og svekker anbefalingen uten å tilføre noe. Sterkt navngir risikoen <i>hennes eget råd skaper</i>, setter et tall på den, og gjør den derfor til noe klienten kan handle på." },

      { id: 20, "k": "Syntesen", n: 3,
        "s": "Tallene peker begge veier. Nevn de tre måtene å lande nyansert uten å bli vag, og det ene grepet som gjør nyansert til skarpt.",
        "f": "«Det avhenger» er ikke et svar — det er en beskrivelse av at du ikke har tatt stilling. Men standpunktet trenger ikke være et rent ja:<ul><li><b>Betinget anbefaling med navngitt terskel.</b> «Ja, hvis frafallet holder seg under ti prosent. Det jeg har sett i dag, peker mot at det gjør det.»</li><li><b>Trinnvis anbefaling.</b> «Ja til 20 stasjoner nå, opsjon på de neste 40.» Du reduserer <i>innsatsen</i> i stedet for å utsette beslutningen.</li><li><b>Anbefal testen som avgjør.</b> «Ikke bevilg de 90 millionene ennå. Bruk seks uker på å måle oppetiden på fileteringslinja — er den over 90 prosent, blir dette et ja.»</li></ul><b>Grepet som gjør nyansert til skarpt:</b> navngi <b>tallet som ville snudd deg</b>.<br><i>«Jeg lander på ja, og det som ville endret det, er hvis kundeoverlappet er over 30 prosent.»</i><br><br><b>Sterkt mot middels:</b> en kandidat som kan si hva som ville gjort ham uenig med seg selv, har vist dømmekraft. En som sier «det avhenger av flere faktorer», har vist at han ikke vet hvilke. Middels tror nyanse betyr å holde begge muligheter åpne. Sterkt vet at nyanse betyr å <i>navngi grensen</i> mellom dem. Og lever det som en beslutning, også når det er en betinget en — tonen bærer halve budskapet." },

      { id: 21, "k": "Syntesen", n: 3,
        "s": "Kinocasen: resultatet falt fra 111 til 78 millioner på tre år, besøket flatt på 12 millioner billetter, inntektene vokste litt, mens filmleien steg fra 43 til 48 prosent av hver billettkrone. Skriv om oppsummeringen til en syntese — ordrett.",
        "f": "<b>Oppsummeringen (slik ikke):</b><br><i>«Vi begynte med å se på inntektene, som har vokst litt. Så gikk vi over til kostnadssiden, og der så vi på lønn, husleie og filmleie. Filmleien har steget en del. Vi så også på kiosk og reklame, som ser greie ut. Så det ser ut som filmleien er en viktig faktor her.»</i><br><br><b>Syntesen (slik):</b><br><i>«Resultatet faller fordi distributørene har tatt fem prosentpoeng mer av hver billettkrone. Det koster dere 78 millioner i året — mer enn hele resultatfallet. Jeg anbefaler at dere angriper filmleien direkte, og reforhandler med de to største distributørene først.»</i><br><br>De fire forskjellene, konkret her:<ul><li><b>Verbene:</b> «vi så på» → «dere skal reforhandle».</li><li><b>Rekkefølgen:</b> kronologisk gjennomgang → årsaken i første setning.</li><li><b>Tallene:</b> «steget en del» → «fem prosentpoeng, 78 millioner i året».</li><li><b>Standpunktet:</b> «det ser ut som» → «jeg anbefaler».</li></ul><b>Sterkt mot middels:</b> merk det ene leddet som gjør syntesen uangripelig: <b>«mer enn hele resultatfallet»</b>. Kostnadsposten sammenlignes med problemet den skal forklare, og da er saken avgjort — resten av kostnadssiden trenger ikke diskuteres. Middels rapporterer at filmleien har steget. Sterkt viser at den er <i>tilstrekkelig</i> til å forklare alt, og lukker dermed casen i én setning. Test den mot styrereferatet: kan første setning stå alene? Ja." },

      { id: 22, "k": "Fit", n: 3,
        "s": "«Jeg satt i en komité som arrangerte en karrieredag. Vi var uenige om budsjettet, og jeg klarte å overbevise de andre.» Skriv om til en åpning som tåler boring — ordrett.",
        "f": "<b>Ordrett, sterk versjon:</b><br><i>«Jeg hadde sponsoransvaret for en karrieredag med 600 påmeldte og et budsjett på 240 000. Seks uker før ville økonomiansvarlig kutte de to dyreste standene. Jeg skjønte ikke hvorfor hun sto så hardt på det, så jeg tok en kaffe med henne — hun hadde sittet alene med underskuddet året før og fryktet å stå med regningen igjen. Da byttet jeg argument: i stedet for å forsvare standene foreslo jeg å flytte risikoen, med 60 prosent forskuddsfaktura og en klausul som dekket oss hvis sponsorene trakk seg. Jeg sa at slik det lå nå, ga vi fra oss 80 000 sikre inntekter for å unngå en risiko på 30 000. Hun sa ja samme kveld. Vi endte 96 000 over budsjett, og forskuddsmodellen ble brukt av komiteen året etter.»</i><br><br><b>Seks grep gjorde forskjellen:</b><ul><li><b>Teller på alt:</b> 600 påmeldte, 240 000 i budsjett, seks ukers frist.</li><li><b>En motpart hvis grunn ble undersøkt:</b> hun fryktet å stå med regningen igjen.</li><li><b>En replikk du husker:</b> 80 000 sikre mot en risiko på 30 000.</li><li><b>En navngitt mekanisme:</b> du <i>flyttet risiko</i> — du argumenterte ikke hardere.</li><li><b>Tall på utfallet:</b> 96 000 over budsjett, altså 40 prosent over.</li><li><b>En «så derfor» som varte:</b> modellen ble brukt året etter.</li></ul><b>Sterkt mot middels:</b> den svake versjonen er ikke gal, den er <i>tom</i> — ingen tall, ingen motpart med en grunn, ingen replikk, ingen mekanisme, og en læring som kunne stått under hvilken som helst historie. Intervjueren har ingenting å grave i. Og <b>skalaen betyr mindre enn tettheten</b>: ikke unnskyld deg med «det var jo bare en studentforening, men …» — da har du bedt intervjueren om å score historien lavt, og hun gjør som du sier." },

      { id: 23, "k": "Fit", n: 3,
        "s": "Hva er diagnosen på hvorfor de fleste fit-svar blir for tynne, og hva er den ene feilen faktiske intervjuere nevner oftest?",
        "f": "<b>Diagnosen:</b> kandidaten svarer på <b>HVA</b>, intervjueren spør om <b>HVORFOR</b>. Kjernen er ikke handlingen, men beslutningsgrunnlaget — hvorfor du valgte som du gjorde, og hvilke alternativer du forkastet.<br><br><b>Feilen som nevnes oftest:</b> <b>analyse i stedet for empati.</b> Historier om mennesker fortalt som problemløsningsøvelser. Kandidaten forklarer hva hun analyserte seg fram til, men viser aldri at hun forsøkte å forstå <i>hvorfor</i> den andre var mot henne. Connection er en menneske-test, ikke en casetest.<br><br>De øvrige er kortere: for lang oppbygging, «vi» for «jeg», ingen ekte friksjon, ingen refleksjon på Growth.<br><br><b>Tidsbudsjettet som fikser den første:</b> Situasjon 15 sek (hvor, når, hvem — ikke hva studentforeningen <i>er</i>) · Oppgave 10 sek (ditt ansvar, og hva som sto på spill) · <b>Handling 60–75 sek</b> (det du gjorde, sa og valgte bort) · Resultat 15–25 sek (tall, og «så derfor»). Rundt to minutter totalt — så stopper du og lar dem grave.<br><br><b>Sterkt mot middels:</b> middels bruker begrunnelsene sine i åpningen og har ingenting igjen når oppfølgingene kommer. <b>Begrunnelsene er ammunisjon til oppfølgingene, ikke til åpningen.</b> Sterkt holder dem tilbake med vilje. Sondene kommer i tre faser — åpne, så spisse og mikroskopiske (hva sa du <i>nøyaktig</i>, hvordan reagerte de, hvilke alternativer hadde du), og til slutt kontrafaktiske. Fase to er autentisitetstesten: en pyntet historie kollapser der, fordi oppdiktede historier ikke har replikker." },

      { id: 24, "k": "Syntesen", n: 4,
        "s": "Ett minutt, høyt, uten notater. Ladestasjonscasen: markedet i Sverige er 1,2 mrd i dag og 1,9 mrd om tre år, full utbygging på 60 stasjoner krever 7,5 prosent markedsandel for å dekke faste kostnader, og det kravet faller til 4,7 prosent om tre år. Tre etablerte holder 80 prosent. Lever hele RRRN.",
        "f": "<b>Ordrett, på ett minutt:</b><br><br><b>«Ja til Sverige, men ikke til 60 stasjoner nå. Jeg anbefaler at dere bygger 20 stasjoner i sør først, og sikrer opsjon på tomtene til de resterende 40.»</b><br><br><i>Tre grunner. For det første er markedet reelt: 1,2 milliarder i dag, 1,9 milliarder om tre år. For det andre krever full utbygging 7,5 prosent markedsandel bare for å dekke de faste kostnadene — fra null, mot tre etablerte som holder 80 prosent. For det tredje faller det kravet til 4,7 prosent om tre år, så tiden jobber for dere.</i><br><br><i>Den store risikoen er at konkurrentene tar de beste plasseringene mens dere venter — det er tomtene, ikke laderne, som er den knappe ressursen. Det første jeg ville gjort, er å kartlegge hvor de tre etablerte har søkt om nettilknytning de siste tolv månedene.</i><br><br><b>Kontrollen som viser at grunnene henger sammen:</b> 7,5 prosent av 1,2 mrd er 90 millioner. 4,7 prosent av 1,9 mrd er 89 millioner. Det er <i>samme</i> faste kostnad — kravet faller ikke fordi kostnaden synker, men fordi markedet vokser. Sier du det høyt, har du vist at du forstår hvorfor tid er argumentet.<br><br><b>Sterkt mot middels:</b> se hvor mye arbeid hvert ledd gjør. Anbefalingen er <b>trinnvis</b> — den reduserer innsatsen i stedet for å utsette beslutningen. Risikoen er <b>skapt av rådet</b>: den finnes bare fordi du anbefalte å vente, og den peker på riktig knapp ressurs. Neste steg bruker <b>data som allerede finnes offentlig</b> og kan settes i gang på mandag. Middels sier «ja, men det avhenger av konkurransesituasjonen». Sterkt tar beslutningen, og forteller hva som ville snudd den." },

      { id: 25, "k": "Syntesen", n: 4,
        "s": "Ett minutt, på tid, uten notater: ta den siste casen du kjørte og lever hele syntesen høyt. Deretter: hvilke fire krav sjekker du den mot?",
        "f": "<b>De fire kravene, i rekkefølge:</b><ul><li><b>Anbefaling (10–15 sek):</b> ett verb og ett objekt. Kan første setning stå alene i et styrereferat? Ingen «det avhenger av».</li><li><b>Grunner, 2–3 (25–30 sek):</b> ett tall <i>fra casen</i> per grunn, nummerert høyt. Ikke en sannhet om verden — et funn fra de siste 25 minuttene.</li><li><b>Risiko, 1–2 (10 sek):</b> består den testen? Hvis den slår til, ville anbefalingen endret seg? Er den skapt av rådet ditt, og er den kvantifisert?</li><li><b>Neste steg, 1–2 (10 sek):</b> noe klienten kan gjøre <i>denne uken</i>, helst med data hun allerede sitter på.</li></ul><b>Fem feil å høre etter når du spiller opptaket:</b><ul><li>Du åpnet med kontekst i stedet for med anbefalingen.</li><li>Du sa et adjektiv der du hadde et tall.</li><li>Du hadde fire grunner — det signaliserer at du ikke prioriterte.</li><li>Risikoen din var sann uansett hva svaret var («forutsatt at gjennomføringen lykkes»).</li><li>Du sa hele minuttet spørrende. Tonen bærer halve budskapet.</li></ul><b>Sterkt mot middels:</b> middels øver på syntesen ved å lese notatene sine. Sterkt <b>skriver to–tre stikkord per ledd — ikke setninger — og sier det høyt uten å se ned</b>. Å improvisere syntesen er unødvendig risiko på det tidspunktet i intervjuet som teller mest, men å lese den opp er heller ikke levering. Fasiten på et syntesetrinn er skrevet som en <i>replikk</i> nettopp for at du skal kunne sammenligne setning for setning med din egen." },

      { id: 26, "k": "Kommunikasjon", n: 4,
        "s": "Nitti sekunder, høyt: kjør hele åpningen fra du kommer inn i rommet til du har rekapitulert prompten. Hvert ledd.",
        "f": "<b>Sekvensen, ferdig på forhånd:</b><ul><li><b>Hils, sett deg, legg arkene i landskapsformat, penn ned, se opp.</b></li><li><b>Én setning, og så stopper du:</b> <i>«Takk for at du tar deg tid — jeg har sett fram til dette.»</i></li><li><b>Når prompten kommer: pennen ligger stille de første sekundene.</b> Se på personen, ikke på papiret.</li><li><b>Skriv tre ting og bare tre:</b> målet, tallet og spørsmålet.</li><li><b>Rekapituler:</b> <i>«La meg gjenta, så jeg er sikker på at jeg har forstått oppdraget: klienten driver 40 kinoer, resultatet har falt fra 111 til 78 millioner på tre år, mens besøket er flatt. Dere vil vite hvorfor, og hva de skal gjøre. Er det riktig oppfattet?»</i></li><li><b>Avklar formatet hvis det er uklart:</b> <i>«Vil du at jeg driver casen fremover, eller foretrekker du å lede meg gjennom?»</i></li><li><b>Be om tid, med innhold:</b> <i>«Kan jeg få tretti sekunder? Da kommer jeg tilbake med tre grener og hvilken jeg vil starte i.»</i></li></ul><b>Sterkt mot middels:</b> åpningen er ikke oppvarming — den er <b>første datapunkt</b> på det de rekonstruerte scoringsskjemaene kaller fremtoning. Middels improviserer de første nitti sekundene fordi «det er bare small talk», og bruker dem på å bli rolig. Sterkt har dem ferdig, og bruker roen på å <i>lytte</i>. Formatspørsmålet tar to sekunder og avgjør hvordan du skal oppføre deg i tjue minutter. Ha også klokka på bordet der du ser den uten å snu hodet, og spør før du bruker kalkulator — anta at svaret er nei: «Er kalkulator greit, eller regner jeg for hånd?»" },

      { id: 27, "k": "Kommunikasjon", n: 4,
        "s": "Tretti sekunder, høyt og uten å nøle: du har regnet i tre minutter, tallet ga ingen mening, og du vet ikke hva neste steg er. Kom deg ut.",
        "f": "<b>Ordrett, på tretti sekunder:</b><br><i>«La meg stoppe og si hvor jeg er. Jeg har regnet på kostnad per enhet og fikk et tall som ikke gir mening — det er høyere enn prisen, så jeg har enten snudd en brøk eller mistet en tierpotens. La meg gå tilbake til oppsettet: kostnad per enhet er samlet variabel kostnad delt på volum. Er det riktig oppsett, eller er det noe jeg har misforstått i tallene dere ga meg?»</i><br><br><b>Hvorfor den virker, ledd for ledd:</b><ul><li>Du navngir <i>hvor</i> du er, ikke bare <i>at</i> du er fast.</li><li>Du sier hva som gjør tallet usannsynlig — sanity-sjekken er synlig.</li><li>Du diagnostiserer selv: snudd brøk eller tapt tierpotens, som er de to vanligste.</li><li>Du går til <b>formelen i ord</b>, ikke til multiplikasjonen. Står du fast i regningen, ligger feilen nesten alltid i oppsettet.</li><li>Du ender med en konkret forespørsel, ikke med «hva synes du?».</li></ul><b>Sterkt mot middels:</b> middels regner om igjen i stillhet i førti sekunder og håper det løser seg. Det er det ene trekket som ikke lar seg redde — BCG har «ikke bli taus» på sin egen liste, og Bain vil ha resonnementet ditt <i>også når du er usikker</i>. Sterkt bruker tretti sekunder som absolutt grense og sier veien ut høyt. Og hun starter <b>ikke</b> en ny struktur: det er det dyreste trekket i rommet — du kaster fem minutters arbeid og mister alt intervjueren allerede har akseptert. Tjue sekunder fast etterfulgt av en ryddig vei ut er et bedre datapunkt enn aldri å komme i klemma. Feilhåndtering og press er ikke forstyrrelser i evalueringen — de <i>er</i> evalueringen." },

      { id: 28, "k": "Fit", n: 4,
        "s": "To minutter, høyt og uten notater: fortell Connection-historien din på spørsmålet «fortell om en gang du overbeviste noen som var uenig med deg». Kjør deretter sondetesten på den.",
        "f": "<b>Tidsbudsjettet du leverer mot:</b> Situasjon 15 sek · Oppgave 10 sek · <b>Handling 60–75 sek</b> · Resultat 15–25 sek. Så stopper du og lar dem grave.<br><br><b>Sjekk historien mot de sju feltene:</b> navn · situasjon (med kontekst først: «NHHS Consulting, våren 2026 …») · <b>hva sto på spill</b> · hva DU gjorde, i jeg-form · <b>hvem var uenig, og hvorfor mente de det</b> · resultat med tall · <b>«så derfor»</b>.<br><br><b>Sondetesten:</b> tolv oppfølgingsspørsmål i tre faser — åpne, så spisse og mikroskopiske (<i>hva sa du nøyaktig? hvordan reagerte de? hvilke alternativer hadde du?</i>), til slutt kontrafaktiske. Svar hver enkelt <b>høyt</b>, og kryss av bare der du hadde et svar du ville sagt til en partner. <b>Terskelen er åtte av tolv.</b> Under den er historien en reserve, og grunnen er alltid én av tre: <i>for vag, for kollektiv, eller for langt fra atferden som testes</i>.<br><br><b>Kildestatus:</b> ingen av husene publiserer scoringsskjema, vekting eller terskler. Tolvpunktslista og terskelen på åtte er rekonstruert av ex-MBB-coacher — nyttige treningsmål, men ikke McKinseys egne. <b>Bygg historien for å tåle boring, ikke for å score på en liste.</b><br><br><b>Sterkt mot middels:</b> middels leverer en historie som holder i to minutter og faller fra hverandre i minutt fire. Sterkt har historien <i>undersøkt</i> — hun vet hva motparten mente og hvorfor, og hun har replikker fordi hendelsen faktisk skjedde. Og porteføljen skal dekke: minst to historier per dimensjon, høyst to dimensjoner per historie, minst fire ulike kontekster. Mål: åtte distinkte historier pluss to reserver. Fire historier fra samme verv leses som ett liv med én erfaring." },

      { id: 29, "k": "Fit", n: 4,
        "s": "Nitti sekunder, høyt og uten notater: si «why this firm» for det huset du faktisk søker. Kjør deretter byttetesten på det du nettopp sa.",
        "f": "<b>Kravet:</b> minst ett ledd som ikke kan flyttes til et annet firma. Sterkest er <b>en navngitt samtale</b> — hvem, hvilket prosjekt, og hva de sa som festet seg. En samtale kan ikke googles og kan ikke kopieres.<br><br><b>Byttetesten, kjørt etterpå:</b> bytt firmanavnet i det du nettopp sa, og les det høyt. Overlever det, har du beskrevet konsulentbransjen. De fire ordene som avslører raskest: <i>bratt læringskurve, smarte kolleger, utfordrende problemer, globalt fotavtrykk</i>.<br><br><b>Tre andre avslørere:</b><ul><li><b>Å lede med exit options, prestisje eller lønn.</b> Greit å verdsette privat; å lede med det leses som at du ikke blir. Intervjueren vurderer reelt om investeringen i deg lønner seg.</li><li><b>Uorganisert svar rett etter en strukturert case.</b> Er du skarp i casen og rotete her, skaper det tvil om at strukturen var ekte.</li><li><b>For polert.</b> Et svar som høres ut som en pitch og ikke som noe du ville sagt over en kaffe, feiler autentisitetstesten — verst hos BCG og Bain, der uformaliteten <i>er</i> testen.</li></ul><b>Kalibrer innsatsen mot huset:</b> hos <b>McKinsey</b> veier motivasjon lite og er nesten fraværende i PEI. Hos <b>BCG</b> veier den tungt — fit-delen er organisert rundt «de tre hvorfor», og spørsmålet kommer ofte i et <b>one-way videointervju</b> med ett til tre minutter per svar og ingen mulighet til å ta opp igjen. Det betyr at «why BCG» må sitte i en versjon du kan si til et kamera uten publikum: øv den høyt, på tid, med opptak. Hos <b>Bain</b> er den knyttet til <i>operating principles</i>, som de eksplisitt ber deg forberede — ha én kobling mellom egen erfaring og minst to av de fem.<br><br><b>Sterkt mot middels:</b> middels leverer et godt svar som kunne vært sagt av hvem som helst, om hvem som helst. Sterkt har ett ledd som bare hun kan si — og sier uten forbehold at dette er førstevalget." },

      { id: 30, "k": "Fit", n: 4,
        "s": "Seksti til nitti sekunder, høyt og uten notater: si «why consulting». Tre grunner, hver forankret i en konkret hendelse. La det høres ferdig ut.",
        "f": "<b>Kravet:</b> tre grunner, hver forankret i en <b>konkret hendelse fra ditt eget liv</b>. Ikke tre adjektiver.<br><br><b>Svak versjon — fire setninger, null informasjon om personen som sier dem:</b><br><i>«Jeg vil jobbe i konsulentbransjen fordi jeg liker variasjon og komplekse problemer. Læringskurven er bratt, man jobber med veldig flinke folk, og man får se mange bransjer. Jeg tror det er en god start på karrieren.»</i><br>Alt kunne vært skrevet før du hadde en eneste erfaring.<br><br><b>Sterk versjon:</b><br><i>«Tre grunner. Den første er at jeg liker å bli kastet inn i noe jeg ikke kan: i NHHS Consulting fikk jeg et logistikkprosjekt for en grossist, og det jeg husker best er de fire dagene før jeg forsto hvordan lageret deres faktisk fungerte. Den andre er at jeg vil jobbe der beslutningen tas — i deltidsjobben min laget jeg en bemanningsmodell som butikksjefen faktisk brukte, og forskjellen mellom å analysere og å bli brukt ble veldig tydelig. Den tredje er tempoet i tilbakemelding: jeg fikk mer konkret kritikk på åtte uker i det prosjektet enn på to år med gruppearbeid, og jeg vil ha mer av det.»</i><br><br><b>Forskjellen:</b> tre navngitte grunner i stedet for adjektiver, hver med én hendelse som bare du kan fortelle, og <b>en tydelig slutt</b> — det skal ikke høres ut som om du gikk tom.<br><br><b>Sterkt mot middels:</b> middels sier tre riktige ting om bransjen. Sterkt sier tre ting om <i>seg selv</i>, og lar hendelsen bære påstanden i stedet for omvendt. Legg merke til at ingen av de tre grunnene er positive om kandidaten på en åpenbar måte — den første handler om fire dager hun ikke forsto noe. Det er derfor den er troverdig. Skriv «why consulting» og «why firm» inn som to egne historier med sju felter, og kjør sondetesten på dem: klarer du ikke å svare på hvorfor du valgte som du gjorde og hvilke alternativer du forkastet, er motivasjonssvaret ditt like tynt som en historie under terskelen." }
    ]
  }
});
