/* Kapittel 10 — Progressivitet, flat skatt og rettferdighet */
window.EDU_DATA.chapterTasks[10] = {
  minutes: 20,
  tasks: [
    {
      id: "k10-1",
      topic: "Bunnfradrag og progresjon",
      points: 3,
      body: "<p>Et land har én skattesats på 35 % [eksempeltall], og de første kr 200 000 av inntekten er skattefrie. Anna tjener kr 500 000, Bjørn kr 1 000 000. Ingen av dem har andre fradrag.</p><p>Hva er gjennomsnittsskatten for Anna og for Bjørn?</p>",
      options: [
        "21,0 % for Anna og 28,0 % for Bjørn",
        "35,0 % for begge",
        "−5,0 % for Anna og 15,0 % for Bjørn",
        "14,0 % for Anna og 7,0 % for Bjørn",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — grunnlaget.</b> Bunnfradraget trekkes fra <i>inntekten</i>, ikke fra skatten. Anna: 500 000 − 200 000 = 300 000. Bjørn: 1 000 000 − 200 000 = 800 000.</p><p><b>Steg 2 — skatten.</b> Anna: 300 000 × 35 % = <b>105 000</b>. Bjørn: 800 000 × 35 % = <b>280 000</b>.</p><p><b>Steg 3 — gjennomsnittsskatten, alltid av brutto inntekt.</b> Anna: 105 000 / 500 000 = <b>21,0 %</b>. Bjørn: 280 000 / 1 000 000 = <b>28,0 %</b>.</p><p><b>Kontroll med formelen:</b> t̄(Y) = t × (1 − B/Y). For Anna 35 % × (1 − 0,4) = 21,0 % ✓, for Bjørn 35 % × (1 − 0,2) = 28,0 % ✓.</p><p>Marginalskatten er 35 % for begge, og likevel stiger gjennomsnittsskatten med 7,0 prosentpoeng. <b>En flat sats med bunnfradrag er progressiv.</b> Progresjonen kommer utelukkende fra bunnfradraget, som utgjør en fallende andel av inntekten når inntekten vokser. Spredningen leser du direkte ut av t × B × (1/Y<sub>lav</sub> − 1/Y<sub>høy</sub>) = 0,35 × 200 000 × (1/500 000 − 1/1 000 000) = 0,07 ✓. Dette er formen H2024 oppgave 4 har.</p>",
      traps: [
        null,
        "Bunnfradraget er glemt, altså «flat skatt» lest som «proporsjonal skatt». Bare en flat sats uten bunnfradrag har konstant gjennomsnittsskatt.",
        "Bunnfradraget trukket fra skatten i stedet for fra grunnlaget: 500 000 × 35 % − 200 000 = −25 000 og 1 000 000 × 35 % − 200 000 = 150 000.",
        "Bunnfradragets andel av inntekten brukt som gjennomsnittsskatt, altså t × B/Y i stedet for t × (1 − B/Y). Da faller satsen med inntekten, stikk motsatt av det bunnfradraget gjør.",
      ],
    },
    {
      id: "k10-2",
      topic: "Provenynøytral omlegging",
      points: 3,
      body: "<p>To skattytere utgjør hele økonomien: Kari tjener kr 300 000 og Per kr 900 000. <b>System 1</b> er en rent proporsjonal skatt på 25 % av all inntekt. <b>System 2</b> er en flat sats på 40 % over et bunnfradrag B [eksempeltall for begge].</p><p>Hvor stort må B være for at system 2 skal gi nøyaktig samme proveny som system 1, og hva skjer med fordelingen?</p>",
      options: [
        "B = 112 500, og Kari betaler like mye som før",
        "B = 225 000, og Kari betaler kr 45 000 mindre mens Per betaler kr 45 000 mer",
        "B = 225 000, og begge betaler det samme som før, siden provenyet er uendret",
        "B = 450 000, og Kari slipper skatt helt",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — provenyet i system 1.</b> Kari: 300 000 × 25 % = 75 000. Per: 900 000 × 25 % = 225 000. Til sammen <b>300 000</b>.</p><p><b>Steg 2 — provenyet i system 2, som funksjon av B.</b> Bunnfradraget gjelder <i>hver</i> skattyter, så grunnlaget er (300 000 − B) + (900 000 − B) = 1 200 000 − 2B. Kravet er 0,40 × (1 200 000 − 2B) = 300 000, altså 1 200 000 − 2B = 750 000 og <b>B = 225 000</b>.</p><p><b>Steg 3 — fordelingen.</b> Kari: 0,40 × (300 000 − 225 000) = <b>30 000</b>, altså 45 000 mindre enn de 75 000 hun betalte før. Per: 0,40 × (900 000 − 225 000) = <b>270 000</b>, altså 45 000 mer enn 225 000.</p><p><b>Kontroll:</b> 30 000 + 270 000 = 300 000 ✓, og de to endringene er like store med motsatt fortegn, som de må være når provenyet står stille.</p><p>Poenget er skillet mellom nivå og fordeling. <b>Samme proveny er ikke samme fordeling.</b> Gjennomsnittsskatten går fra 25,0 % til 10,0 % for Kari og fra 25,0 % til 30,0 % for Per: system 1 er proporsjonalt, system 2 er progressivt, og de henter inn krone for krone det samme.</p>",
      traps: [
        "Bunnfradraget satt slik at bare Kari betaler det samme som før. Da blir provenyet 75 000 + 315 000 = 390 000, altså ikke provenynøytralt.",
        null,
        "Provenynøytralitet forvekslet med fordelingsnøytralitet. B er riktig, men et uendret proveny sier ingenting om hvem som betaler det.",
        "Bunnfradraget trukket bare én gang fra samlet inntekt, som om det gjaldt økonomien og ikke hver skattyter. Da blir provenyet 180 000, godt under de 300 000 som skulle inn.",
      ],
    },
    {
      id: "k10-3",
      topic: "Skattekilen",
      points: 3,
      body: "<p>En reform hever marginalskatten på et inntektsintervall fra 40 % til 50 % [eksempeltall]. En arbeidstaker i intervallet har en lønnsinntekt før skatt på kr 800 000, og den kompenserte arbeidstilbudselastisiteten er 0,2.</p><p>Bruk tilnærmingen effektivitetstap ≈ ½ × ε<sub>kompensert</sub> × τ² × wL, der τ er marginalskattesatsen og wL lønnsinntekten før skatt. Hvor mye vokser effektivitetstapet?</p>",
      options: ["Kr 800", "Kr 3 200", "Kr 7 200", "Kr 14 400"],
      answer: 2,
      solution: "<p><b>Steg 1 — tapet før reformen.</b> ½ × 0,2 × 0,40² × 800 000 = 0,1 × 0,16 × 800 000 = <b>12 800</b>.</p><p><b>Steg 2 — tapet etter reformen.</b> ½ × 0,2 × 0,50² × 800 000 = 0,1 × 0,25 × 800 000 = <b>20 000</b>.</p><p><b>Steg 3 — økningen.</b> 20 000 − 12 800 = <b>7 200</b>.</p><p><b>Kontroll:</b> tapet vokser med kvadratet av kilen, så forholdet skal være (0,50/0,40)² = 1,5625. Og 20 000 / 12 800 = 1,5625 ✓. Ti prosentpoeng høyere sats øker altså tapet med 56 %, ikke med 25 %.</p><p>Det er substitusjonsvirkningen som skaper tapet, og derfor den <i>kompenserte</i> elastisiteten som står i formelen. Merk hva regnestykket ikke sier: det måler effektivitetskostnaden av progresjonstrinnet, ikke om arbeidstilbudet samlet går opp eller ned. Den virkningen er teoretisk ubestemt, fordi inntekts- og substitusjonsvirkningen trekker hver sin vei.</p>",
      traps: [
        "Kvadratet av satsendringen brukt i stedet for differansen mellom kvadratene: ½ × 0,2 × 0,10² × 800 000. Det er ikke tapet som er kvadratisk i endringen, men tapet som er kvadratisk i nivået.",
        "Tapet antatt å vokse lineært med satsen: 12 800 × 50/40 = 16 000, altså 3 200 mer. Da er hele poenget med kvadratet borte.",
        null,
        "½-faktoren glemt i begge leddene. Tapet er arealet av en trekant, ikke av et rektangel, så halvparten skal med.",
      ],
    },
    {
      id: "k10-4",
      topic: "De to likhetene",
      points: 3,
      body: "<p>Evneprinsippet er begrunnelsen kapitlet gir for at skatten fordeles etter evnen til å bære den, og faget deler kravet i horisontal og vertikal likhet.</p><p>Hvilket utsagn gjengir skillet riktig?</p>",
      options: [
        "Horisontal likhet er kravet om at skatten ikke skal vri valget mellom spareformer, vertikal likhet at den med større evne skal betale mer",
        "Horisontal likhet krever at alle betaler like mange kroner, vertikal likhet at alle betaler samme andel av inntekten",
        "Begge hviler på nytteprinsippet: horisontal likhet krever at to som mottar like mye fra staten betaler like mye, vertikal at den som mottar mer betaler mer",
        "Horisontal likhet krever at to med samme skatteevne betaler samme skatt, vertikal likhet at den med større evne betaler mer, men uten å si hvor mye mer",
      ],
      answer: 3,
      solution: "<p>Horisontal likhet: like tilfeller behandles likt, altså samme skatt ved samme skatteevne. Vertikal likhet: ulike tilfeller behandles passende ulikt, altså mer skatt ved større evne. Begge følger av <b>evneprinsippet</b>, som fordeler byrden etter evnen til å bære den og ikke etter hva den enkelte får igjen fra staten.</p><p>Det avgjørende, og det som gjør dette til et flervalgsspørsmål og ikke en politisk uenighet: <b>vertikal likhet sier ikke hvor mye mer.</b> En flat sats oppfyller kravet, siden den som tjener dobbelt betaler dobbelt så mange kroner. Skal du videre til en bestemt progresjonsgrad, trenger du en tilleggsforutsetning, typisk likt offer: skatten skal koste hver skattyter like mye i tapt nytte. Da avgjøres progresjonen av hvor raskt grensenytten av penger faller, og det kan ingen måle. Derfor spør eksamen hva argumentene er, aldri hvem som har rett.</p><p><b>Kontroll mot dagens system:</b> det duale systemet skattlegger lønn med opptil 47,4 % og kapitalinntekt med 22 % [dagens regel]. To personer med samme samlede inntekt møter altså ulik skatt avhengig av hvor inntekten kommer fra. Det er et brudd på horisontal likhet, og det er begrunnet med noe annet enn rettferdighet: kapitalen er mer bevegelig enn arbeidskraften.</p>",
      traps: [
        "Horisontal likhet forvekslet med nøytralitet. Nøytralitet gjelder at skatten ikke skal vri valget mellom aktiva, horisontal likhet at to med samme evne skal betale det samme. To ulike krav.",
        "Rundsumskatt lest som horisontal likhet og proporsjonal skatt som vertikal. Likhetene gjelder behandlingen av like og ulike skatteevner, ikke bestemte satsstrukturer.",
        "Evneprinsippet byttet ut med nytteprinsippet. Evneprinsippet fordeler skatten etter evnen til å bære den, ikke etter hva du får igjen fra staten.",
        null,
      ],
    },
    {
      id: "k10-5",
      topic: "Negativ inntektsskatt",
      points: 3,
      body: "<p>Et land innfører en negativ inntektsskatt: T(Y) = t × Y − G, med t = 30 % og en overføring G på kr 90 000 til alle [eksempeltall]. Ida har en inntekt på kr 200 000, Jonas på kr 600 000.</p><p>Hva er gjennomsnittsskatten for hver av dem?</p>",
      options: [
        "−15,0 % for Ida og 15,0 % for Jonas",
        "0,0 % for Ida og 15,0 % for Jonas",
        "16,5 % for Ida og 25,5 % for Jonas",
        "30,0 % for begge",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — Ida.</b> 0,30 × 200 000 − 90 000 = 60 000 − 90 000 = <b>−30 000</b>. Hun mottar 30 000. Gjennomsnittsskatten er −30 000 / 200 000 = <b>−15,0 %</b>.</p><p><b>Steg 2 — Jonas.</b> 0,30 × 600 000 − 90 000 = 180 000 − 90 000 = <b>90 000</b>, altså 90 000 / 600 000 = <b>15,0 %</b>.</p><p><b>Steg 3 — hvor skatten snur.</b> T = 0 når Y = G/t = 90 000 / 0,30 = <b>300 000</b>. Ida ligger under terskelen og mottar, Jonas over og betaler.</p><p><b>Kontroll med omskrivningen:</b> T = t × Y − G = t × (Y − G/t), så systemet er en flat sats med bunnfradrag B = 300 000, bortsett fra at det utbetaler under terskelen der en vanlig flat skatt stopper på null. For Jonas: 0,30 × (600 000 − 300 000) = 90 000 ✓, samme tall som i steg 2.</p><p>Gjennomsnittsskatten nærmer seg marginalsatsen på 30 % nedenfra og når den aldri. Et alternativ der gjennomsnittsskatten er lik eller høyere enn den eneste marginalsatsen, kan du forkaste uten å regne.</p>",
      traps: [
        null,
        "Variant 3 forvekslet med variant 2: den negative skatten kuttet på null, altså en flat sats med bunnfradrag 300 000. Jonas' tall stemmer, men det er nettopp utbetalingen under terskelen som skiller de to systemene, og bare variant 3 omfordeler nedover.",
        "Overføringen trukket fra inntekten i stedet for fra skatten: 0,30 × (200 000 − 90 000) = 33 000 og 0,30 × (600 000 − 90 000) = 153 000. G er et beløp i skatten, ikke et bunnfradrag i grunnlaget.",
        "Overføringen glemt helt, altså variant 1, den rent proporsjonale skatten. Da forsvinner hele progresjonen.",
      ],
    },
    {
      id: "k10-6",
      topic: "Optimal beskatning",
      points: 3,
      body: "<p>Kapitlet gjengir Sandmos oversikt og Mirrlees' resultater som argumenter, ikke som standpunkter. Eksamen tester at du kjenner konklusjonene, ikke at du deler dem.</p><p>Hvilket av utsagnene gjengir litteraturens konklusjoner riktig?</p>",
      options: [
        "Mirrlees' simuleringer gir en tilnærmet lineær løsning: gjennomsnittsskatten stiger, mens marginalskatten er konstant eller svakt fallende, og omfordelingen kommer fra bunnfradraget",
        "Optimal marginalskatt er høyere jo mer elastisk arbeidstilbudet er, fordi et bevegelig grunnlag gir mest proveny",
        "Teorien viser at en provenynøytral overgang til flat skatt øker arbeidstilbudet, siden marginalskatten faller",
        "Reell progresjon er sterkere enn formell progresjon, fordi fradrag og verdsettingsregler treffer de høyeste inntektene hardest",
      ],
      answer: 0,
      solution: "<p><b>Mirrlees' oppsett:</b> identiske preferanser, ulik produktivitet, myndigheter som ser inntekten men ikke evnen, og som har ulikhetsaversjon. Å løfte marginalskatten på et intervall gir mer proveny fra alle som ligger over det, men vrir bare dem som er i det. Simuleringene gir en tilnærmet lineær løsning, i praksis en negativ inntektsskatt: <b>stigende gjennomsnittsskatt, konstant eller svakt fallende marginalskatt</b>, og omfordelingen kommer fra bunnfradraget, ikke fra satsstrukturen.</p><p><b>De tre tingene som løfter optimal marginalskatt.</b> Den er høyere jo (i) <i>lavere</i> den kompenserte arbeidstilbudselastisiteten er, (ii) større spredningen i produktivitet er, og (iii) sterkere ulikhetsaversjonen er. (i) er effektivitetskostnaden: et grunnlag som ikke rømmer, er billig å skattlegge. (ii) er hvor mye det er å omfordele. (iii) er den eneste verdivurderingen av de tre.</p><p><b>Kontroll mot de to andre konklusjonene i kapitlet.</b> Arbeidstilbudet: teorien er ubestemt, fordi bare den midterste inntektsgruppen har begge virkningene trekkende samme vei, og empirien gir en beskjeden positiv virkning, mest for kvinner. Progresjonen: den reelle er <i>mindre</i> enn den formelle, av tre grunner, nemlig grunnlaget, insidensen og tilpasningen, og alle tre virker sterkest på toppen. Under flervalg frister alternativet som sier noe bestemt, fordi det ser ut som kunnskap. «Ubestemt» er et lovlig svar, og ofte det riktige.</p>",
      traps: [
        null,
        "Fortegnet på elastisitetsbetingelsen snudd. Dette er den vanligste feilversjonen: et elastisk grunnlag rømmer, og det er nettopp derfor det skal skattlegges lavere, ikke høyere.",
        "Overdrivelsen kapitlet advarer mot. En provenynøytral overgang hever marginalskatten for de laveste inntektene, og virkningen er ubestemt for både lave og høye. Teorien gir ingen slik hypotese.",
        "Kapitlets viktigste enkeltpåstand snudd. Reell progresjon er mindre enn formell, siden grunnlaget uthules, insidensen flytter byrden og tilpasningen er lettest der inntekten er mest bevegelig.",
      ],
    },
  ],
};
