/* Kapittel 11 — Hvem betaler skatten: insidens og elastisiteter */
window.EDU_DATA.chapterTasks[11] = {
  minutes: 25,
  tasks: [
    {
      id: "k11-1",
      topic: "Produsentprisen",
      points: 3,
      body: "<p>Et frikonkurransemarked er i likevekt. Myndighetene innfører en stykkskatt på t kroner per enhet, innkrevd av produsentene. Konsumentprisen er P, produsentprisen er p, og P = p + t. Likevekten er D(p + t) = S(p), der D′(P) &lt; 0 og S′(p) &gt; 0.</p><p>Hvilket uttrykk er ∂p/∂t?</p>",
      options: [
        "S′(p) / (S′(p) − D′(P))",
        "D′(P) / (S′(p) − D′(P))",
        "D′(P) / (D′(P) − S′(p))",
        "D′(P) / S′(p)",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — deriver likevekten med hensyn på t.</b> Venstresiden er sammensatt: argumentet p + t endrer seg med (∂p/∂t + 1), fordi p selv beveger seg når t øker.</p><p>D′ × (∂p/∂t + 1) = S′ × ∂p/∂t</p><p><b>Steg 2 — samle leddene med ∂p/∂t.</b> D′ × ∂p/∂t + D′ = S′ × ∂p/∂t, altså D′ = (S′ − D′) × ∂p/∂t. Nevneren ble S′ − D′ og ikke D′ − S′ nettopp fordi leddet D′ × ∂p/∂t byttet fortegn da det ble flyttet over.</p><p><b>Steg 3 — del.</b> ∂p/∂t = <b>D′(P) / (S′(p) − D′(P))</b>.</p><p><b>Kontroll med lovlige helninger.</b> Sett D′ = −2 og S′ = 3 [eksempeltall]. Nevneren er 3 − (−2) = 5, alltid strengt positiv fordi den er S′ + |D′|. Da er ∂p/∂t = −2/5 = −0,40 og ∂P/∂t = S′/(S′ − D′) = 3/5 = +0,60. Differansen er 0,60 − (−0,40) = 1,00. ✓ Den kontrollen er en identitet: P − p = t, så den deriverte av differansen må være nøyaktig 1.</p><p>Filteret du trenger på flervalg: ∂p/∂t skal ligge mellom −1 og 0. Negativ teller, positiv nevner, og |D′| mindre enn S′ + |D′|. Produsentprisen faller, men aldri med mer enn hele skatten.</p>",
      traps: [
        "Uttrykket for konsumentprisen. Det er positivt, og en skatt kan ikke løfte prisen selgeren sitter igjen med.",
        null,
        "Fortegnet i nevneren er snudd. D′ − S′ er alltid negativ, så brøken blir positiv (+0,40 med tallene over), og produsentprisen kan ikke stige.",
        "Nevneren er forkortet til S′ alene. Da blir paret −0,67 og S′/S′ = 1, med differanse 1,67 i stedet for 1.",
      ],
    },
    {
      id: "k11-2",
      topic: "Konsumentprisen",
      points: 3,
      body: "<p>Samme marked som over: stykkskatt t per enhet, P = p + t, likevekt D(P) = S(P − t), D′(P) &lt; 0 og S′(p) &gt; 0.</p><p>Hvilket uttrykk er ∂P/∂t?</p>",
      options: [
        "S′(p) / (S′(p) − D′(P))",
        "(S′(p) − D′(P)) / S′(p)",
        "S′(p) / (D′(P) − S′(p))",
        "D′(P) / (S′(p) − D′(P))",
      ],
      answer: 0,
      solution: "<p>Konsumentprisen krever ingen ny derivasjon. Kilen P = p + t gir ∂P/∂t = ∂p/∂t + 1, og ettallet skrives som (S′ − D′)/(S′ − D′):</p><p>∂P/∂t = D′/(S′ − D′) + (S′ − D′)/(S′ − D′) = (D′ + S′ − D′)/(S′ − D′) = <b>S′(p) / (S′(p) − D′(P))</b>.</p><p>De to uttrykkene er identiske bortsett fra telleren. D′ i telleren gir produsentprisen, S′ gir konsumentprisen. På eksamen står de som alternativer i hverandres spørsmål, så skriv ned hvilken pris det spørres om før du leter.</p><p><b>Kontroll med samme tall som i forrige oppgave.</b> D′ = −2, S′ = 3 [eksempeltall] gir ∂P/∂t = 3/5 = +0,60, som ligger mellom 0 og 1 slik det skal: positiv teller, positiv nevner, teller mindre enn nevner. Og 0,60 − (−0,40) = 1,00. ✓</p><p>Byrden deles altså 60/40 her, og delingen kommer utelukkende av at tilbudet reagerer sterkere på pris enn etterspørselen: S′ = 3 mot |D′| = 2. Den siden som reagerer minst, bærer mest.</p>",
      traps: [
        null,
        "Brøken er snudd. Med tallene over gir den 5/3 = 1,67, og konsumentprisen kan ikke stige med mer enn hele skatten.",
        "Fortegnet i nevneren er snudd. Da blir svaret −0,60, altså en skatt som senker prisen kjøperen betaler.",
        "Uttrykket for produsentprisen. Det er svaret på forrige spørsmål, ikke på dette.",
      ],
    },
    {
      id: "k11-3",
      topic: "Byrden fra helningene",
      points: 3,
      body: "<p>En vare omsettes i frikonkurranse til kr 20 per enhet. I området rundt likevekten har etterspørselen helning D′ = −6 og tilbudet helning S′ = 2, målt i enheter per krone [eksempeltall].</p><p>Myndighetene innfører en stykkskatt på kr 4 per enhet, og skatten legges på <i>kjøperne</i>: kjøperen betaler selgeren en pris og kr 4 til staten i tillegg.</p><p>Hva blir den nye konsumentprisen og den nye produsentprisen?</p>",
      options: [
        "Konsumentprisen kr 23 og produsentprisen kr 19",
        "Konsumentprisen kr 21 og produsentprisen kr 17",
        "Konsumentprisen kr 22 og produsentprisen kr 18",
        "Konsumentprisen kr 24 og produsentprisen kr 20",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hvem som krever inn skatten spiller ingen rolle.</b> Legges skatten på kjøperen, betaler han p til selgeren og t til staten, altså P = p + t, og likevekten blir bokstavelig talt den samme ligningen D(p + t) = S(p). Ingenting i utledningen refererer til hvem som fyller ut skjemaet. Regn derfor som om skatten lå på produsentene.</p><p><b>Steg 2 — nevneren.</b> S′ − D′ = 2 − (−6) = <b>8</b>. Legg merke til at minus foran et negativt tall ble pluss; det er her fortegnsfeilene oppstår.</p><p><b>Steg 3 — de to deriverte.</b> ∂P/∂t = 2/8 = <b>+0,25</b> og ∂p/∂t = −6/8 = <b>−0,75</b>.</p><p><b>Steg 4 — prisene.</b> Konsumentprisen: 20 + 0,25 × 4 = <b>kr 21</b>. Produsentprisen: 20 − 0,75 × 4 = <b>kr 17</b>.</p><p><b>Kontroll:</b> kjøperens byrde kr 1 pluss selgerens byrde kr 3 er kr 4 = t. ✓ Og kilen stemmer: 21 − 17 = 4. ✓</p><p>Merk at alle fire alternativene oppfyller kilen P − p = 4. Kilekontrollen alene skiller dem altså ikke, og du må lese fordelingen ut av helningene: |D′| = 6 mot S′ = 2, så etterspørselen er tre ganger så prisfølsom som tilbudet, og selgeren bærer tre firedeler av skatten.</p>",
      traps: [
        "D′ og S′ byttet om i tellerne, altså 75 % på kjøperen. Det snur regelen: den <i>minst</i> prisfølsomme siden bærer mest, og her er det tilbudet.",
        null,
        "Skatten antatt delt likt. En 50/50-deling er resultatet i monopolmodellen med lineær etterspørsel, ikke i frikonkurranse med ulike helninger.",
        "Formell insidens forvekslet med reell: skatten er lagt på kjøperne, altså antas kjøperne å bære den. Hvem som betaler inn, står ikke i noen av formlene.",
      ],
    },
    {
      id: "k11-4",
      topic: "Uelastisk etterspørsel",
      points: 3,
      body: "<p>Et legemiddel selges i dag for kr 240 per pakning, og det omsettes 50 000 pakninger i året. Pasientene må ha medisinen uansett pris, så etterspørselen er perfekt uelastisk i det aktuelle prisområdet: D′ = 0. Tilbudskurven er stigende, S′ &gt; 0.</p><p>Staten legger en stykkskatt på kr 60 per pakning på produsentene [eksempeltall].</p><p>Hva blir konsumentprisen, og hvor stort blir dødvektstapet?</p>",
      options: [
        "Konsumentprisen kr 240 og dødvektstap kr 0",
        "Konsumentprisen kr 270 og dødvektstap kr 0",
        "Konsumentprisen kr 300 og dødvektstap kr 3 000 000",
        "Konsumentprisen kr 300 og dødvektstap kr 0",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — sett D′ = 0 inn i de to formlene.</b> ∂P/∂t = S′/(S′ − 0) = S′/S′ = <b>1</b>, og ∂p/∂t = 0/(S′ − 0) = <b>0</b>. Kjøperen bærer hele skatten, selgeren ingenting, og det gjelder uansett hvor stor S′ er.</p><p><b>Steg 2 — prisene.</b> Konsumentprisen: 240 + 60 = <b>kr 300</b>. Produsentprisen: uendret <b>kr 240</b>. Selgeren tar imot 300, sender 60 til staten og beholder 240, akkurat som før.</p><p><b>Steg 3 — kvantumet.</b> Etterspørselen er perfekt uelastisk, så kvantumet er uendret på <b>50 000</b> pakninger.</p><p><b>Steg 4 — provenyet.</b> t × x = 60 × 50 000 = <b>kr 3 000 000</b>.</p><p><b>Steg 5 — dødvektstapet.</b> ½ × t × (x<sub>0</sub> − x<sub>t</sub>) = ½ × 60 × 0 = <b>kr 0</b>. Trekanten består av handler som ikke lenger skjer, og her skjer alle handlene som før. Skatten flytter penger fra kjøper til stat, men ødelegger ingen tilpasning.</p><p><b>Kontroll:</b> kjøperens byrde 60 pluss selgerens byrde 0 er 60 = t. ✓ Og kjøperne taper 60 × 50 000 = 3 000 000, som er nøyaktig det staten får inn. Ingenting forsvinner underveis.</p><p>Legg merke til at insidens og effektivitet trekker i hver sin retning her: den skatten som gir minst dødvektstap, er også den som treffer kjøperen hardest. Det er den samme innsikten som ligger under Ramsey-regelen.</p>",
      traps: [
        "Produsenten antatt å bære skatten fordi den er lagt på ham. Det er S′ = 0, altså uelastisk <i>tilbud</i>, som gir uendret konsumentpris; her er det etterspørselen som er uelastisk.",
        "Halve skatten veltet over. Delingen er 50/50 bare når helningene tilfeldigvis er like store, og med D′ = 0 er de så ulike de kan bli.",
        "Provenyet oppgitt som dødvektstap. Kr 3 000 000 er beløpet staten faktisk får inn, ikke verdien som forsvinner.",
        null,
      ],
    },
    {
      id: "k11-5",
      topic: "Elastisk tilbud",
      points: 3,
      body: "<p>En liten åpen økonomi importerer en vare til gitt verdensmarkedspris kr 80 per enhet. Tilbudet til det innenlandske markedet er derfor perfekt elastisk: leverandørene selger alt som etterspørres til kr 80, og ingenting under, altså S′ → ∞. Etterspørselen er fallende, D′ &lt; 0 og endelig.</p><p>Staten legger en stykkskatt på kr 12 per enhet på selgerne [eksempeltall].</p><p>Hva blir konsumentprisen, og hva sitter selgeren igjen med per enhet?</p>",
      options: [
        "Konsumentprisen kr 80 og produsentprisen kr 68",
        "Konsumentprisen kr 92 og produsentprisen kr 80",
        "Konsumentprisen kr 86 og produsentprisen kr 74",
        "Konsumentprisen kr 92 og produsentprisen kr 92",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — la S′ gå mot uendelig i de to formlene.</b> ∂P/∂t = S′/(S′ − D′) → 1 når S′ vokser, fordi den endelige størrelsen D′ blir uvesentlig ved siden av S′. Og ∂p/∂t = D′/(S′ − D′) → <b>0</b> av samme grunn: teller fast, nevner mot uendelig.</p><p><b>Steg 2 — prisene.</b> Konsumentprisen: 80 + 1 × 12 = <b>kr 92</b>. Produsentprisen: uendret <b>kr 80</b>.</p><p><b>Steg 3 — hvorfor.</b> Perfekt elastisk tilbud betyr at selgeren har et fullgodt alternativ: får han mindre enn 80 netto, selger han ingenting her. Da må hele skatten legges på kjøperen, ellers forsvinner tilbudet.</p><p><b>Kontroll:</b> 92 − 12 = 80. ✓ Kjøperens byrde er 92 − 80 = 12 og selgerens er 80 − 80 = 0, og 12 + 0 = 12 = t. ✓</p><p>Dette er samme utfall som med perfekt uelastisk etterspørsel, og det er ikke tilfeldig: det er alltid forholdet mellom helningene som teller, så en flat kurve og en loddrett motpart gir samme svar. Merk likevel én forskjell fra forrige oppgave: her er etterspørselen fallende, så kvantumet faller når prisen går fra 80 til 92, og det oppstår et dødvektstap.</p>",
      traps: [
        "Det motsatte grensetilfellet regnet: perfekt <i>elastisk etterspørsel</i> gir uendret konsumentpris og produsentpris ned med hele skatten. Her er det tilbudet som er elastisk.",
        null,
        "Skatten antatt delt likt. Delingen bestemmes av helningene, og med S′ → ∞ er den så skjev som den kan bli.",
        "Kilen er glemt. Selgeren tar imot 92, men sender 12 til staten, så produsentprisen er 80. P og p kan aldri være like når t &gt; 0.",
      ],
    },
    {
      id: "k11-6",
      topic: "Proveny og dødvektstap",
      points: 3,
      body: "<p>Et marked har etterspørselen x = 1 200 − 20P og tilbudet x = 400 + 20p, der P er konsumentprisen og p er produsentprisen [eksempeltall]. Uten skatt er likevekten P = p = kr 20 og x = 800 enheter.</p><p>Staten legger en stykkskatt på kr 6 per enhet på produsentene. Ny likevekt blir P = kr 23, p = kr 17 og x = 740 enheter.</p><p>Hvor stort blir provenyet og dødvektstapet?</p>",
      options: [
        "Proveny kr 4 800 og dødvektstap kr 180",
        "Proveny kr 4 440 og dødvektstap kr 360",
        "Proveny kr 4 440 og dødvektstap kr 2 220",
        "Proveny kr 4 440 og dødvektstap kr 180",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — kontroller den nye likevekten.</b> Sett D(p + t) = S(p): 1 200 − 20(p + 6) = 400 + 20p gir 1 080 − 20p = 400 + 20p, altså p = <b>17</b> og P = 17 + 6 = <b>23</b>. Kvantum: 400 + 20 × 17 = <b>740</b>, og etterspørselssiden gir 1 200 − 20 × 23 = 740. ✓</p><p><b>Steg 2 — delingen.</b> D′ = −20 og S′ = 20, så nevneren er 20 − (−20) = 40. ∂P/∂t = 20/40 = +0,50 og ∂p/∂t = −20/40 = −0,50. Kjøperen bærer kr 3 og selgeren kr 3, og 3 + 3 = 6 = t. ✓</p><p><b>Steg 3 — provenyet.</b> t × x<sub>t</sub> = 6 × <b>740</b> = <b>kr 4 440</b>. Det er det <i>nye</i> kvantumet som gjelder; de 60 enhetene som forsvant, gir ingen skatt.</p><p><b>Steg 4 — dødvektstapet.</b> ½ × t × (x<sub>0</sub> − x<sub>t</sub>) = ½ × 6 × 60 = <b>kr 180</b>. Formelen gir det samme: ½ × t<sup>2</sup> × |S′ × D′|/(S′ − D′) = ½ × 36 × 400/40 = ½ × 36 × 10 = 180. ✓</p><p><b>Kontroll — hele velferdsregnskapet.</b> Konsumentene taper 3 på hver av de 740 enhetene de fortsatt kjøper, pluss trekanten på de 60 som forsvant: 3 × 740 + ½ × 3 × 60 = 2 220 + 90 = 2 310. Produsentene taper like mye, 2 310, siden delingen er symmetrisk her. Samlet tap 4 620, hvorav staten får 4 440. Differansen 4 620 − 4 440 = <b>180</b>, som stemmer med steg 4. ✓</p>",
      traps: [
        "Provenyet regnet med kvantumet <i>før</i> skatten: 6 × 800. De 60 enhetene som forsvant, blir aldri solgt og gir ingen skatt.",
        "Halvparten glemt i trekantformelen: 6 × 60 i stedet for ½ × 6 × 60.",
        "Trekanten regnet på hele kvantumet i stedet for på kvantumsfallet: ½ × 6 × 740. Dødvektstapet gjelder bare handlene som <i>ikke</i> skjer.",
        null,
      ],
    },
    {
      id: "k11-7",
      topic: "Elastisitetsregelen",
      points: 3,
      body: "<p>En vare selges i frikonkurranse til kr 50 per enhet. I likevekten er etterspørselselastisiteten ε<sub>D</sub> = −0,4 og tilbudselastisiteten ε<sub>S</sub> = 1,6 [eksempeltall].</p><p>Staten innfører en stykkskatt på kr 5 per enhet.</p><p>Hvor stor del av skatten bærer kjøperen?</p>",
      options: ["Kr 1,00", "Kr 1,25", "Kr 4,00", "Kr 5,00"],
      answer: 2,
      solution: "<p><b>Steg 1 — regelen i elastisiteter.</b> Konsumentens andel av skatten er ε<sub>S</sub>/(ε<sub>S</sub> + |ε<sub>D</sub>|), produsentens er |ε<sub>D</sub>|/(ε<sub>S</sub> + |ε<sub>D</sub>|). Dette er de samme to brøkene som S′/(S′ − D′) og |D′|/(S′ − D′), fordi faktoren P/x er felles for begge elastisitetene når P = p før skatten og derfor forkortes bort.</p><p><b>Steg 2 — nevneren.</b> 1,6 + 0,4 = <b>2,0</b>.</p><p><b>Steg 3 — andelene.</b> Kjøperen: 1,6/2,0 = <b>80 %</b>. Selgeren: 0,4/2,0 = <b>20 %</b>.</p><p><b>Steg 4 — i kroner.</b> Kjøperen bærer 0,80 × 5 = <b>kr 4,00</b>, selgeren 0,20 × 5 = kr 1,00.</p><p><b>Kontroll:</b> andelene summerer til 1 (0,80 + 0,20), og kronene til t: 4,00 + 1,00 = 5,00. ✓ Prisene blir P = 50 + 4 = kr 54 og p = 50 − 1 = kr 49, og kilen stemmer: 54 − 49 = 5. ✓</p><p>Regelen i én setning: den minst elastiske siden bærer skatten, fordi den har færrest alternativer å rømme til. Her er etterspørselen fire ganger så lite elastisk som tilbudet, og kjøperen bærer derfor fire ganger så mye.</p>",
      traps: [
        "Andelene byttet om: |ε<sub>D</sub>| brukt i telleren for kjøperen. Da bærer den <i>mest</i> elastiske siden mest, som er regelen snudd på hodet.",
        "Forholdet mellom elastisitetene brukt som andel: (0,4/1,6) × 5. Nevneren skal være summen av de to, ikke den ene alene.",
        null,
        "Hele skatten lagt på kjøperen. Det krever ε<sub>D</sub> = 0 eller ε<sub>S</sub> → ∞, og her er begge endelige og ulik null.",
      ],
    },
  ],
};
