/* Kapittel 11 — Hvem betaler skatten: insidens og elastisiteter */
window.EDU_DATA.chapterTasks[11] = {
  minutes: 86,
  tasks: [
    {
      id: "k11-1",
      topic: "Produsentprisen",
      points: 3,
      body: "<p>Et frikonkurransemarked er i likevekt. Myndighetene innfører en stykkskatt på t kroner per enhet, innkrevd av produsentene. Konsumentprisen er P, produsentprisen er p, og P = p + t. Likevekten er D(p + t) = S(p), der D′(P) &lt; 0 og S′(p) &gt; 0.</p><p>Hvilket uttrykk er ∂p/∂t?</p>",
      options: [
        "S′(p) / (S′(p) − D′(P))",
        "D′(P) / (S′(p) − D′(P))",
        "D′(P) / (D′(P) − S′(p))",
        "D′(P) / S′(p)",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — deriver likevekten med hensyn på t.</b> Venstresiden er sammensatt: argumentet p + t endrer seg med (∂p/∂t + 1), fordi p selv beveger seg når t øker.</p><p>D′ × (∂p/∂t + 1) = S′ × ∂p/∂t</p><p><b>Steg 2 — samle leddene med ∂p/∂t.</b> D′ × ∂p/∂t + D′ = S′ × ∂p/∂t, altså D′ = (S′ − D′) × ∂p/∂t. Nevneren ble S′ − D′ og ikke D′ − S′ nettopp fordi leddet D′ × ∂p/∂t byttet fortegn da det ble flyttet over.</p><p><b>Steg 3 — del.</b> ∂p/∂t = <b>D′(P) / (S′(p) − D′(P))</b>.</p><p><b>Kontroll med lovlige helninger.</b> Sett D′ = −2 og S′ = 3 [eksempeltall]. Nevneren er 3 − (−2) = 5, alltid strengt positiv fordi den er S′ + |D′|. Da er ∂p/∂t = −2/5 = −0,40 og ∂P/∂t = S′/(S′ − D′) = 3/5 = +0,60. Differansen er 0,60 − (−0,40) = 1,00. ✓ Den kontrollen er en identitet: P − p = t, så den deriverte av differansen må være nøyaktig 1.</p><p>Filteret du trenger på flervalg: ∂p/∂t skal ligge mellom −1 og 0. Negativ teller, positiv nevner, og |D′| mindre enn S′ + |D′|. Produsentprisen faller, men aldri med mer enn hele skatten.</p>",
      traps: [
        "Uttrykket for konsumentprisen. Det er positivt, og en skatt kan ikke løfte prisen selgeren sitter igjen med.",
        null,
        "Fortegnet i nevneren er snudd. D′ − S′ er alltid negativ, så brøken blir positiv (+0,40 med tallene over), og produsentprisen kan ikke stige.",
        "Nevneren er forkortet til S′ alene. Da blir paret −0,67 og S′/S′ = 1, med differanse 1,67 i stedet for 1.",
      ],
    },
    {
      id: "k11-2",
      topic: "Konsumentprisen",
      points: 3,
      body: "<p>Et frikonkurransemarked får en stykkskatt t per enhet, P = p + t, likevekt D(P) = S(P − t), D′(P) &lt; 0 og S′(p) &gt; 0.</p><p>Hvilket uttrykk er ∂P/∂t?</p>",
      options: [
        "S′(p) / (S′(p) − D′(P))",
        "(S′(p) − D′(P)) / S′(p)",
        "S′(p) / (D′(P) − S′(p))",
        "D′(P) / (S′(p) − D′(P))",
      ],
      answer: 0,
      solution: "<p>Konsumentprisen krever ingen ny derivasjon. Kilen P = p + t gir ∂P/∂t = ∂p/∂t + 1, og ettallet skrives som (S′ − D′)/(S′ − D′):</p><p>∂P/∂t = D′/(S′ − D′) + (S′ − D′)/(S′ − D′) = (D′ + S′ − D′)/(S′ − D′) = <b>S′(p) / (S′(p) − D′(P))</b>.</p><p>De to uttrykkene er identiske bortsett fra telleren. D′ i telleren gir produsentprisen, S′ gir konsumentprisen. På eksamen står de som alternativer i hverandres spørsmål, så skriv ned hvilken pris det spørres om før du leter.</p><p><b>Kontroll med samme tall som i forrige oppgave.</b> D′ = −2, S′ = 3 [eksempeltall] gir ∂P/∂t = 3/5 = +0,60, som ligger mellom 0 og 1 slik det skal: positiv teller, positiv nevner, teller mindre enn nevner. Og 0,60 − (−0,40) = 1,00. ✓</p><p>Byrden deles altså 60/40 her, og delingen kommer utelukkende av at tilbudet reagerer sterkere på pris enn etterspørselen: S′ = 3 mot |D′| = 2. Den siden som reagerer minst, bærer mest.</p>",
      traps: [
        null,
        "Brøken er snudd. Med tallene over gir den 5/3 = 1,67, og konsumentprisen kan ikke stige med mer enn hele skatten.",
        "Fortegnet i nevneren er snudd. Da blir svaret −0,60, altså en skatt som senker prisen kjøperen betaler.",
        "Uttrykket for produsentprisen. Det er svaret på forrige spørsmål, ikke på dette.",
      ],
    },
    {
      id: "k11-3",
      topic: "Byrden fra helningene",
      points: 3,
      body: "<p>En vare omsettes i frikonkurranse til kr 20 per enhet. I området rundt likevekten har etterspørselen helning D′ = −6 og tilbudet helning S′ = 2, målt i enheter per krone [eksempeltall].</p><p>Myndighetene innfører en stykkskatt på kr 4 per enhet, og skatten legges på <i>kjøperne</i>: kjøperen betaler selgeren en pris og kr 4 til staten i tillegg.</p><p>Hva blir den nye konsumentprisen og den nye produsentprisen?</p>",
      options: [
        "Konsumentprisen kr 23 og produsentprisen kr 19",
        "Konsumentprisen kr 21 og produsentprisen kr 17",
        "Konsumentprisen kr 22 og produsentprisen kr 18",
        "Konsumentprisen kr 24 og produsentprisen kr 20",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hvem som krever inn skatten spiller ingen rolle.</b> Legges skatten på kjøperen, betaler han p til selgeren og t til staten, altså P = p + t, og likevekten blir bokstavelig talt den samme ligningen D(p + t) = S(p). Ingenting i utledningen refererer til hvem som fyller ut skjemaet. Regn derfor som om skatten lå på produsentene.</p><p><b>Steg 2 — nevneren.</b> S′ − D′ = 2 − (−6) = <b>8</b>. Legg merke til at minus foran et negativt tall ble pluss; det er her fortegnsfeilene oppstår.</p><p><b>Steg 3 — de to deriverte.</b> ∂P/∂t = 2/8 = <b>+0,25</b> og ∂p/∂t = −6/8 = <b>−0,75</b>.</p><p><b>Steg 4 — prisene.</b> Konsumentprisen: 20 + 0,25 × 4 = <b>kr 21</b>. Produsentprisen: 20 − 0,75 × 4 = <b>kr 17</b>.</p><p><b>Kontroll:</b> kjøperens byrde kr 1 pluss selgerens byrde kr 3 er kr 4 = t. ✓ Og kilen stemmer: 21 − 17 = 4. ✓</p><p>Merk at alle fire alternativene oppfyller kilen P − p = 4. Kilekontrollen alene skiller dem altså ikke, og du må lese fordelingen ut av helningene: |D′| = 6 mot S′ = 2, så etterspørselen er tre ganger så prisfølsom som tilbudet, og selgeren bærer tre firedeler av skatten.</p>",
      traps: [
        "D′ og S′ byttet om i tellerne, altså 75 % på kjøperen. Det snur regelen: den <i>minst</i> prisfølsomme siden bærer mest, og her er det tilbudet.",
        null,
        "Skatten antatt delt likt. En 50/50-deling er resultatet i monopolmodellen med lineær etterspørsel, ikke i frikonkurranse med ulike helninger.",
        "Formell insidens forvekslet med reell: skatten er lagt på kjøperne, altså antas kjøperne å bære den. Hvem som betaler inn, står ikke i noen av formlene.",
      ],
    },
    {
      id: "k11-4",
      topic: "Uelastisk etterspørsel",
      points: 3,
      body: "<p>Et legemiddel selges i dag for kr 240 per pakning, og det omsettes 50 000 pakninger i året. Pasientene må ha medisinen uansett pris, så etterspørselen er perfekt uelastisk i det aktuelle prisområdet: D′ = 0. Tilbudskurven er stigende, S′ &gt; 0.</p><p>Staten legger en stykkskatt på kr 60 per pakning på produsentene [eksempeltall].</p><p>Hva blir konsumentprisen, og hvor stort blir dødvektstapet?</p>",
      options: [
        "Konsumentprisen kr 240 og dødvektstap kr 0",
        "Konsumentprisen kr 270 og dødvektstap kr 0",
        "Konsumentprisen kr 300 og dødvektstap kr 3 000 000",
        "Konsumentprisen kr 300 og dødvektstap kr 0",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — sett D′ = 0 inn i de to formlene.</b> ∂P/∂t = S′/(S′ − 0) = S′/S′ = <b>1</b>, og ∂p/∂t = 0/(S′ − 0) = <b>0</b>. Kjøperen bærer hele skatten, selgeren ingenting, og det gjelder uansett hvor stor S′ er.</p><p><b>Steg 2 — prisene.</b> Konsumentprisen: 240 + 60 = <b>kr 300</b>. Produsentprisen: uendret <b>kr 240</b>. Selgeren tar imot 300, sender 60 til staten og beholder 240, akkurat som før.</p><p><b>Steg 3 — kvantumet.</b> Etterspørselen er perfekt uelastisk, så kvantumet er uendret på <b>50 000</b> pakninger.</p><p><b>Steg 4 — provenyet.</b> t × x = 60 × 50 000 = <b>kr 3 000 000</b>.</p><p><b>Steg 5 — dødvektstapet.</b> ½ × t × (x<sub>0</sub> − x<sub>t</sub>) = ½ × 60 × 0 = <b>kr 0</b>. Trekanten består av handler som ikke lenger skjer, og her skjer alle handlene som før. Skatten flytter penger fra kjøper til stat, men ødelegger ingen tilpasning.</p><p><b>Kontroll:</b> kjøperens byrde 60 pluss selgerens byrde 0 er 60 = t. ✓ Og kjøperne taper 60 × 50 000 = 3 000 000, som er nøyaktig det staten får inn. Ingenting forsvinner underveis.</p><p>Legg merke til at insidens og effektivitet trekker i hver sin retning her: den skatten som gir minst dødvektstap, er også den som treffer kjøperen hardest. Det er den samme innsikten som ligger under Ramsey-regelen.</p>",
      traps: [
        "Produsenten antatt å bære skatten fordi den er lagt på ham. Det er S′ = 0, altså uelastisk <i>tilbud</i>, som gir uendret konsumentpris; her er det etterspørselen som er uelastisk.",
        "Halve skatten veltet over. Delingen er 50/50 bare når helningene tilfeldigvis er like store, og med D′ = 0 er de så ulike de kan bli.",
        "Provenyet oppgitt som dødvektstap. Kr 3 000 000 er beløpet staten faktisk får inn, ikke verdien som forsvinner.",
        null,
      ],
    },
    {
      id: "k11-5",
      topic: "Elastisk tilbud",
      points: 3,
      body: "<p>En liten åpen økonomi importerer en vare til gitt verdensmarkedspris kr 80 per enhet. Tilbudet til det innenlandske markedet er derfor perfekt elastisk: leverandørene selger alt som etterspørres til kr 80, og ingenting under, altså S′ → ∞. Etterspørselen er fallende, D′ &lt; 0 og endelig.</p><p>Staten legger en stykkskatt på kr 12 per enhet på selgerne [eksempeltall].</p><p>Hva blir konsumentprisen, og hva sitter selgeren igjen med per enhet?</p>",
      options: [
        "Konsumentprisen kr 80 og produsentprisen kr 68",
        "Konsumentprisen kr 92 og produsentprisen kr 80",
        "Konsumentprisen kr 86 og produsentprisen kr 74",
        "Konsumentprisen kr 92 og produsentprisen kr 92",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — la S′ gå mot uendelig i de to formlene.</b> ∂P/∂t = S′/(S′ − D′) → 1 når S′ vokser, fordi den endelige størrelsen D′ blir uvesentlig ved siden av S′. Og ∂p/∂t = D′/(S′ − D′) → <b>0</b> av samme grunn: teller fast, nevner mot uendelig.</p><p><b>Steg 2 — prisene.</b> Konsumentprisen: 80 + 1 × 12 = <b>kr 92</b>. Produsentprisen: uendret <b>kr 80</b>.</p><p><b>Steg 3 — hvorfor.</b> Perfekt elastisk tilbud betyr at selgeren har et fullgodt alternativ: får han mindre enn 80 netto, selger han ingenting her. Da må hele skatten legges på kjøperen, ellers forsvinner tilbudet.</p><p><b>Kontroll:</b> 92 − 12 = 80. ✓ Kjøperens byrde er 92 − 80 = 12 og selgerens er 80 − 80 = 0, og 12 + 0 = 12 = t. ✓</p><p>Dette er samme utfall som med perfekt uelastisk etterspørsel, og det er ikke tilfeldig: det er alltid forholdet mellom helningene som teller, så en flat kurve og en loddrett motpart gir samme svar. Merk likevel én forskjell fra forrige oppgave: her er etterspørselen fallende, så kvantumet faller når prisen går fra 80 til 92, og det oppstår et dødvektstap.</p>",
      traps: [
        "Det motsatte grensetilfellet regnet: perfekt <i>elastisk etterspørsel</i> gir uendret konsumentpris og produsentpris ned med hele skatten. Her er det tilbudet som er elastisk.",
        null,
        "Skatten antatt delt likt. Delingen bestemmes av helningene, og med S′ → ∞ er den så skjev som den kan bli.",
        "Kilen er glemt. Selgeren tar imot 92, men sender 12 til staten, så produsentprisen er 80. P og p kan aldri være like når t &gt; 0.",
      ],
    },
    {
      id: "k11-6",
      topic: "Proveny og dødvektstap",
      points: 3,
      body: "<p>Et marked har etterspørselen x = 1 200 − 20P og tilbudet x = 400 + 20p, der P er konsumentprisen og p er produsentprisen [eksempeltall]. Uten skatt er likevekten P = p = kr 20 og x = 800 enheter.</p><p>Staten legger en stykkskatt på kr 6 per enhet på produsentene. Ny likevekt blir P = kr 23, p = kr 17 og x = 740 enheter.</p><p>Hvor stort blir provenyet og dødvektstapet?</p>",
      options: [
        "Proveny kr 4 800 og dødvektstap kr 180",
        "Proveny kr 4 440 og dødvektstap kr 360",
        "Proveny kr 4 440 og dødvektstap kr 2 220",
        "Proveny kr 4 440 og dødvektstap kr 180",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — kontroller den nye likevekten.</b> Sett D(p + t) = S(p): 1 200 − 20(p + 6) = 400 + 20p gir 1 080 − 20p = 400 + 20p, altså p = <b>17</b> og P = 17 + 6 = <b>23</b>. Kvantum: 400 + 20 × 17 = <b>740</b>, og etterspørselssiden gir 1 200 − 20 × 23 = 740. ✓</p><p><b>Steg 2 — delingen.</b> D′ = −20 og S′ = 20, så nevneren er 20 − (−20) = 40. ∂P/∂t = 20/40 = +0,50 og ∂p/∂t = −20/40 = −0,50. Kjøperen bærer kr 3 og selgeren kr 3, og 3 + 3 = 6 = t. ✓</p><p><b>Steg 3 — provenyet.</b> t × x<sub>t</sub> = 6 × <b>740</b> = <b>kr 4 440</b>. Det er det <i>nye</i> kvantumet som gjelder; de 60 enhetene som forsvant, gir ingen skatt.</p><p><b>Steg 4 — dødvektstapet.</b> ½ × t × (x<sub>0</sub> − x<sub>t</sub>) = ½ × 6 × 60 = <b>kr 180</b>. Formelen gir det samme: ½ × t<sup>2</sup> × |S′ × D′|/(S′ − D′) = ½ × 36 × 400/40 = ½ × 36 × 10 = 180. ✓</p><p><b>Kontroll — hele velferdsregnskapet.</b> Konsumentene taper 3 på hver av de 740 enhetene de fortsatt kjøper, pluss trekanten på de 60 som forsvant: 3 × 740 + ½ × 3 × 60 = 2 220 + 90 = 2 310. Produsentene taper like mye, 2 310, siden delingen er symmetrisk her. Samlet tap 4 620, hvorav staten får 4 440. Differansen 4 620 − 4 440 = <b>180</b>, som stemmer med steg 4. ✓</p>",
      traps: [
        "Provenyet regnet med kvantumet <i>før</i> skatten: 6 × 800. De 60 enhetene som forsvant, blir aldri solgt og gir ingen skatt.",
        "Halvparten glemt i trekantformelen: 6 × 60 i stedet for ½ × 6 × 60.",
        "Trekanten regnet på hele kvantumet i stedet for på kvantumsfallet: ½ × 6 × 740. Dødvektstapet gjelder bare handlene som <i>ikke</i> skjer.",
        null,
      ],
    },
    {
      id: "k11-7",
      topic: "Elastisitetsregelen",
      points: 3,
      body: "<p>En vare selges i frikonkurranse til kr 50 per enhet. I likevekten er etterspørselselastisiteten ε<sub>D</sub> = −0,4 og tilbudselastisiteten ε<sub>S</sub> = 1,6 [eksempeltall].</p><p>Staten innfører en stykkskatt på kr 5 per enhet.</p><p>Hvor stor del av skatten bærer kjøperen?</p>",
      options: ["Kr 1,00", "Kr 1,25", "Kr 4,00", "Kr 5,00"],
      answer: 2,
      solution: "<p><b>Steg 1 — regelen i elastisiteter.</b> Konsumentens andel av skatten er ε<sub>S</sub>/(ε<sub>S</sub> + |ε<sub>D</sub>|), produsentens er |ε<sub>D</sub>|/(ε<sub>S</sub> + |ε<sub>D</sub>|). Dette er de samme to brøkene som S′/(S′ − D′) og |D′|/(S′ − D′), fordi faktoren P/x er felles for begge elastisitetene når P = p før skatten og derfor forkortes bort.</p><p><b>Steg 2 — nevneren.</b> 1,6 + 0,4 = <b>2,0</b>.</p><p><b>Steg 3 — andelene.</b> Kjøperen: 1,6/2,0 = <b>80 %</b>. Selgeren: 0,4/2,0 = <b>20 %</b>.</p><p><b>Steg 4 — i kroner.</b> Kjøperen bærer 0,80 × 5 = <b>kr 4,00</b>, selgeren 0,20 × 5 = kr 1,00.</p><p><b>Kontroll:</b> andelene summerer til 1 (0,80 + 0,20), og kronene til t: 4,00 + 1,00 = 5,00. ✓ Prisene blir P = 50 + 4 = kr 54 og p = 50 − 1 = kr 49, og kilen stemmer: 54 − 49 = 5. ✓</p><p>Regelen i én setning: den minst elastiske siden bærer skatten, fordi den har færrest alternativer å rømme til. Her er etterspørselen fire ganger så lite elastisk som tilbudet, og kjøperen bærer derfor fire ganger så mye.</p>",
      traps: [
        "Andelene byttet om: |ε<sub>D</sub>| brukt i telleren for kjøperen. Da bærer den <i>mest</i> elastiske siden mest, som er regelen snudd på hodet.",
        "Forholdet mellom elastisitetene brukt som andel: (0,4/1,6) × 5. Nevneren skal være summen av de to, ikke den ene alene.",
        null,
        "Hele skatten lagt på kjøperen. Det krever ε<sub>D</sub> = 0 eller ε<sub>S</sub> → ∞, og her er begge endelige og ulik null.",
      ],
    },
    {
      id: "k11-8",
      topic: "Lineær likevekt",
      points: 3,
      body: "<p>Etterspørselen etter en vare er x = 900 − 30P og tilbudet er x = 20p − 100, der P er konsumentprisen og p produsentprisen i kroner, og x er antall enheter [eksempeltall]. Uten skatt er P = p.</p><p>Staten innfører en stykkskatt på kr 5 per enhet, innkrevd av produsentene.</p><p>Hva blir konsumentprisen, produsentprisen og omsatt kvantum i den nye likevekten?</p>",
      options: [
        "P = kr 25, p = kr 20 og x = 150",
        "P = kr 23, p = kr 18 og x = 210",
        "P = kr 22, p = kr 17 og x = 240",
        "P = kr 22, p = kr 17 og x = 300",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — likevekten uten skatt.</b> 900 − 30P = 20P − 100 gir 1 000 = 50P, altså P = p = <b>kr 20</b> og x = 20 × 20 − 100 = <b>300</b>.</p><p><b>Steg 2 — sett inn kilen.</b> Med skatten er P = p + 5, og likevekten skrives i produsentprisen: D(p + 5) = S(p). 900 − 30(p + 5) = 20p − 100 gir 750 − 30p = 20p − 100, altså 850 = 50p og <b>p = kr 17</b>. Da er <b>P = 17 + 5 = kr 22</b>.</p><p><b>Steg 3 — kvantumet fra begge kurvene.</b> Tilbudet: 20 × 17 − 100 = <b>240</b>. Etterspørselen: 900 − 30 × 22 = 900 − 660 = <b>240</b>. ✓ De to må gi samme tall, ellers er det ikke en likevekt.</p><p><b>Steg 4 — samme svar med insidensformlene.</b> S′ = 20 og D′ = −30, så nevneren er 20 − (−30) = 50. ∂P/∂t = 20/50 = 0,40 gir 0,40 × 5 = kr 2 opp, og ∂p/∂t = −30/50 = −0,60 gir 0,60 × 5 = kr 3 ned: 20 + 2 = 22 og 20 − 3 = 17. ✓ Kvantumsfallet er S′ × Δp = 20 × (−3) = −60, og 300 − 60 = 240. ✓</p><p>Kjøperen bærer 40 % og selgeren 60 %, fordi etterspørselen er den mest prisfølsomme siden (30 enheter per krone mot 20).</p><p><b>Kontroll:</b> 2 + 3 = 5 = t. ✓ Kilen P − p = 5 er en identitet, og den stemmer i alle fire alternativene. Det som skiller dem, er om kvantumet går opp på begge kurvene samtidig, og det gjør det bare i det riktige.</p>",
      traps: [
        "Hele skatten lagt på prisen, som om prisen fulgte tilbudsskiftet hele veien opp. Ved P = 25 etterspørres 900 − 750 = 150, men tilbudet ved p = 20 er 300, så markedet går ikke opp.",
        "Andelene byttet om: kjøperen tildelt |D′|/(S′ − D′) = 30/50 = 60 %, altså P = 23 og p = 18. Etterspørselen gir da 900 − 690 = 210, men tilbudet ved p = 18 gir 260.",
        null,
        "Prisene er riktige, men kvantumet er likevekten før skatten. Ved P = 22 kjøper konsumentene bare 900 − 660 = 240.",
      ],
    },
    {
      id: "k11-9",
      topic: "Konsumentenes tap",
      points: 3,
      body: "<p>Et marked har etterspørselen x = 1 000 − 40P og tilbudet x = 60p − 500, der P er konsumentprisen og p produsentprisen i kroner [eksempeltall]. Uten skatt er P = p = kr 15 og x = 400.</p><p>Staten innfører en stykkskatt på kr 2,50 per enhet, innkrevd av produsentene. Kurvene er lineære, så endringene i overskudd kan regnes eksakt.</p><p>Hvor mye taper konsumentene i konsumentoverskudd som følge av skatten?</p>",
      options: [
        "Kr 45",
        "Kr 370",
        "Kr 510",
        "Kr 555",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — ny likevekt.</b> D(p + 2,50) = S(p): 1 000 − 40(p + 2,50) = 60p − 500 gir 900 − 40p = 60p − 500, altså 1 400 = 100p og <b>p = kr 14</b>. Da er <b>P = kr 16,50</b>. Kvantum: 60 × 14 − 500 = <b>340</b>, og etterspørselen gir 1 000 − 40 × 16,50 = 1 000 − 660 = 340. ✓</p><p><b>Steg 2 — delingen.</b> Konsumentprisen steg med 16,50 − 15 = <b>kr 1,50</b>, og produsentprisen falt med 15 − 14 = <b>kr 1,00</b>. Formelen gir det samme: S′/(S′ − D′) = 60/100 = 60 % av 2,50 = 1,50. ✓</p><p><b>Steg 3 — konsumentenes tap, i to deler.</b> Rektangelet: de 340 enhetene de fortsatt kjøper, koster 1,50 mer, 1,50 × 340 = <b>kr 510</b>. Trekanten: de 400 − 340 = 60 enhetene som forsvant, ga et overskudd som nå er borte, ½ × 1,50 × 60 = <b>kr 45</b>. Samlet 510 + 45 = <b>kr 555</b>.</p><p><b>Kontroll — hele velferdsregnskapet.</b> Produsentene taper 1,00 × 340 + ½ × 1,00 × 60 = 340 + 30 = kr 370. De to sidene taper til sammen 555 + 370 = kr 925. Staten får 2,50 × 340 = kr 850, og dødvektstapet er ½ × 2,50 × 60 = kr 75. 850 + 75 = 925. ✓ Regnskapet går opp bare når begge trekantene er med.</p><p>Rektangelet på kr 510 er en overføring fra konsumentene til staten. For samfunnet samlet er det ikke et tap, men for konsumentene er det det, og spørsmålet gjelder konsumentene.</p>",
      traps: [
        "Bare trekanten: ½ × 1,50 × 60 = 45. Rektangelet 1,50 × 340 går til staten og er derfor ikke dødvektstap, men det er likevel penger konsumentene mister.",
        "Produsentenes tap, ikke konsumentenes: andelene byttet om slik at kjøperen får prisendringen på kr 1,00, altså 1,00 × 340 + ½ × 1,00 × 60 = 370.",
        "Trekanten glemt: 1,50 × 340 = 510 er bare tapet på enhetene som fortsatt kjøpes. Konsumentene mister også overskuddet på de 60 enhetene som ikke lenger omsettes.",
        null,
      ],
    },
    {
      id: "k11-10",
      topic: "Uelastisk tilbud",
      points: 3,
      body: "<p>En småbåthavn har 400 båtplasser, og antallet kan ikke endres: tilbudet er perfekt uelastisk. Leien er i dag kr 12 000 per plass per sesong, og alle plassene er leid ut. Etterspørselen etter båtplasser er fallende.</p><p>Kommunen innfører en avgift på kr 1 500 per plass per sesong. Avgiften skal betales av båteierne, altså leietakerne, direkte til kommunen [eksempeltall].</p><p>Hva betaler en båteier i alt per sesong (leie pluss avgift), og hva får havneeieren i leie?</p>",
      options: [
        "Båteieren betaler kr 12 000 i alt, og havneeieren får kr 10 500",
        "Båteieren betaler kr 12 750 i alt, og havneeieren får kr 11 250",
        "Båteieren betaler kr 13 500 i alt, og havneeieren får kr 12 000",
        "Båteieren betaler kr 15 000 i alt, og havneeieren får kr 13 500",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — hvem som betaler inn, spiller ingen rolle.</b> Båteieren betaler leien p til havneeieren og kr 1 500 til kommunen, så det han betaler i alt, er P = p + 1 500. Det er den samme kilen som når selgeren krever inn skatten, og likevekten er den samme ligningen.</p><p><b>Steg 2 — sett S′ = 0 inn i formlene.</b> ∂P/∂t = S′/(S′ − D′) = 0/(0 − D′) = <b>0</b>, og ∂p/∂t = D′/(0 − D′) = <b>−1</b>. Det kjøperen betaler i alt, endres ikke. Det selgeren sitter igjen med, faller med hele avgiften.</p><p><b>Steg 3 — hvorfor, uten formler.</b> Det er fortsatt 400 plasser, og de blir fortsatt leid ut. Etterspørselen bestemmer hva båteierne er villige til å betale i alt for den 400. plassen, og det er kr 12 000 som før. Havneeieren kan ikke kreve mer: da blir plasser stående tomme, og en tom plass gir ham ingenting.</p><p><b>Steg 4 — tallene.</b> Båteieren betaler i alt <b>kr 12 000</b>. Leien faller til 12 000 − 1 500 = <b>kr 10 500</b>.</p><p><b>Kontroll:</b> kjøperens byrde 12 000 − 12 000 = 0 pluss selgerens byrde 12 000 − 10 500 = 1 500 er 1 500 = t. ✓ Kommunen får 400 × 1 500 = kr 600 000, og havneeierens leieinntekt faller fra 400 × 12 000 = kr 4 800 000 til 400 × 10 500 = kr 4 200 000, altså med nøyaktig 600 000. Kvantumet er uendret, så dødvektstapet er null.</p><p>Grensetilfellet S′ = 0 ble spurt om i de åpne settene H2016 (oppgave 1c) og H2018 (oppgave 4b). Forelesningens eksempel er tilbyderen som selger et fast kvantum uansett pris.</p>",
      traps: [
        null,
        "Avgiften antatt delt likt. Deling på midten krever at helningene er like store; med S′ = 0 bærer selgeren alt.",
        "Formell insidens: båteierne betaler inn avgiften og antas derfor å bære den. Det er utfallet ved perfekt uelastisk etterspørsel (D′ = 0), ikke ved perfekt uelastisk tilbud.",
        "Avgiften lagt på to ganger: havneeieren antas å velte den over i leien (12 000 + 1 500 = 13 500), og så betaler båteieren kr 1 500 til kommunen i tillegg.",
      ],
    },
    {
      id: "k11-11",
      topic: "Subsidie",
      points: 3,
      body: "<p>Et marked har etterspørselen x = 1 200 − 50P og tilbudet x = 30p − 400, der P er prisen konsumentene betaler og p prisen produsentene får, i kroner [eksempeltall]. Uten inngrep er P = p = kr 20 og x = 200.</p><p>Staten innfører en subsidie på kr 4 per solgte enhet, utbetalt til produsentene, slik at p = P + 4.</p><p>Hva blir konsumentprisen, og hva koster subsidien staten?</p>",
      options: [
        "P = kr 16,00, og subsidien koster kr 1 600",
        "P = kr 17,50, og subsidien koster kr 1 300",
        "P = kr 18,50, og subsidien koster kr 800",
        "P = kr 18,50, og subsidien koster kr 1 100",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — en subsidie er en negativ skatt.</b> Med stykkskatt er P = p + t. Med subsidie s er P = p − s, altså samme modell med t = −4. Formlene gjelder uendret; kilen har bare snudd.</p><p><b>Steg 2 — ny likevekt.</b> D(p − 4) = S(p): 1 200 − 50(p − 4) = 30p − 400 gir 1 400 − 50p = 30p − 400, altså 1 800 = 80p og <b>p = kr 22,50</b>. Da er <b>P = 22,50 − 4 = kr 18,50</b>.</p><p><b>Steg 3 — kvantumet.</b> Tilbudet: 30 × 22,50 − 400 = 675 − 400 = <b>275</b>. Etterspørselen: 1 200 − 50 × 18,50 = 1 200 − 925 = 275. ✓</p><p><b>Steg 4 — hva det koster staten.</b> Subsidien betales på hver enhet som faktisk selges, altså på det nye kvantumet: 4 × 275 = <b>kr 1 100</b>.</p><p><b>Steg 5 — samme deling med formelen.</b> S′ = 30 og D′ = −50, så nevneren er 80. Konsumentenes andel av subsidien er S′/(S′ − D′) = 30/80 = 37,5 %, altså 0,375 × 4 = kr 1,50 lavere pris: 20 − 1,50 = 18,50. ✓ Produsentenes andel er 50/80 = 62,5 %, altså kr 2,50: 20 + 2,50 = 22,50. ✓ Regelen er den samme som for en skatt: den minst prisfølsomme siden får mest, her produsentene.</p><p><b>Kontroll — velferdsregnskapet.</b> Konsumentene vinner 1,50 × 200 + ½ × 1,50 × 75 = 300 + 56,25 = kr 356,25. Produsentene vinner 2,50 × 200 + ½ × 2,50 × 75 = 500 + 93,75 = kr 593,75. Til sammen kr 950, mens staten betaler kr 1 100. Differansen 1 100 − 950 = <b>kr 150</b> er dødvektstapet, og det stemmer med trekanten ½ × 4 × (275 − 200) = 150. ✓ Også en subsidie har dødvektstap: de 75 ekstra enhetene koster mer å produsere enn kjøperne verdsetter dem til.</p><p>Samme tankegang ga fasiten i H2022 oppgave 3: å fjerne en strømstøtte til produsentene virker som å innføre en stykkskatt.</p>",
      traps: [
        "Hele subsidien antatt å gå til konsumentene: P = 20 − 4 = 16, og kostnaden regnet på etterspørselen ved den prisen, 4 × 400. Prisen faller med hele beløpet bare når etterspørselen er perfekt uelastisk eller tilbudet perfekt elastisk.",
        "Andelene byttet om: konsumentene tildelt |D′|/(S′ − D′) = 50/80 = 62,5 %, altså kr 2,50 lavere pris. Etterspørselen ved P = 17,50 er 325, og 4 × 325 = 1 300.",
        "Prisen er riktig, men kostnaden er regnet på kvantumet før subsidien: 4 × 200. Subsidien øker omsetningen, og staten betaler for hver enhet som faktisk selges.",
        null,
      ],
    },
    {
      id: "k11-12",
      topic: "Elastisitet fra overveltingen",
      points: 3,
      body: "<p>Staten øker en avgift med kr 2 per enhet på en vare som omsettes i frikonkurranse [eksempeltall]. Konsumentprisen stiger med kr 1,50 som følge av økningen. Tilbudselastisiteten i likevekten er ε<sub>S</sub> = 1,2.</p><p>Bruk regelen for hvordan skattebyrden fordeles etter elastisitetene. Hvor stor er etterspørselselastisiteten i absoluttverdi, |ε<sub>D</sub>|?</p>",
      options: [
        "0,30",
        "0,40",
        "1,60",
        "3,60",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — konsumentens andel fra tallene.</b> Prisen steg med 1,50 av en avgift på 2, så konsumentens andel er 1,50/2 = <b>0,75</b>, og produsentens er 0,25.</p><p><b>Steg 2 — regelen i elastisiteter.</b> Konsumentens andel = ε<sub>S</sub>/(ε<sub>S</sub> + |ε<sub>D</sub>|). Sett inn: 1,2/(1,2 + |ε<sub>D</sub>|) = 0,75.</p><p><b>Steg 3 — løs.</b> 1,2 + |ε<sub>D</sub>| = 1,2/0,75 = 1,60, altså |ε<sub>D</sub>| = 1,60 − 1,2 = <b>0,40</b>.</p><p><b>Kontroll — samme svar via forholdet.</b> Andelene står i samme forhold som elastisitetene på motsatt side: konsumentens andel/produsentens andel = ε<sub>S</sub>/|ε<sub>D</sub>| = 0,75/0,25 = 3. Da er |ε<sub>D</sub>| = 1,2/3 = 0,40. ✓ Og tilbake i regelen: 1,2/(1,2 + 0,4) = 1,2/1,6 = 0,75. ✓</p><p>Etterspørselen er tre ganger så lite elastisk som tilbudet, og kjøperne bærer derfor tre ganger så mye av avgiften. Den minst elastiske siden bærer mest.</p>",
      traps: [
        "Produsentens andel brukt som forholdet mellom elastisitetene: |ε<sub>D</sub>|/ε<sub>S</sub> = 0,25, altså 0,25 × 1,2 = 0,30. Forholdet er andel delt på andel, 0,25/0,75 = 1/3, ikke andelen selv.",
        null,
        "Stoppet ett steg for tidlig: 1,2/0,75 = 1,60 er summen ε<sub>S</sub> + |ε<sub>D</sub>|, ikke |ε<sub>D</sub>|.",
        "Andelene byttet om: 0,75 satt lik |ε<sub>D</sub>|/(ε<sub>S</sub> + |ε<sub>D</sub>|), som gir |ε<sub>D</sub>| = 3 × 1,2 = 3,60. Da ville den mest elastiske siden båret mest.",
      ],
    },
    {
      id: "k11-13",
      topic: "Forholdet mellom prisendringene",
      points: 3,
      body: "<p>En stykkskatt t legges på produsentene, slik at P = p + t, der P er konsumentprisen og p produsentprisen. Likevekten er D(p + t) = S(p), med D′(P) &lt; 0 og S′(p) &gt; 0.</p><p>Hvilket uttrykk er forholdet mellom endringen i konsumentprisen og endringen i produsentprisen, (∂P/∂t)/(∂p/∂t)?</p>",
      options: [
        "S′(p) / D′(P)",
        "D′(P) / S′(p)",
        "S′(p) / (S′(p) − D′(P))",
        "−1",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — skriv opp de to deriverte.</b> Fra derivasjonen av likevekten er ∂p/∂t = D′/(S′ − D′) og ∂P/∂t = S′/(S′ − D′).</p><p><b>Steg 2 — del.</b> Nevneren S′ − D′ er felles og forkortes bort: [S′/(S′ − D′)] / [D′/(S′ − D′)] = <b>S′(p)/D′(P)</b>.</p><p><b>Steg 3 — les resultatet.</b> Forholdet er negativt, fordi de to prisene går hver sin vei. I absoluttverdi er det S′/|D′|: konsumentens byrde delt på produsentens byrde er lik tilbudets prisfølsomhet delt på etterspørselens. Den siden som har minst prisfølsomhet, bærer mest. Dette er forholdet H2016 oppgave 1b spurte etter.</p><p><b>Kontroll med tall.</b> D′ = −2 og S′ = 3 [eksempeltall] gir ∂P/∂t = 3/5 = 0,60 og ∂p/∂t = −2/5 = −0,40, og 0,60/(−0,40) = −1,50 = 3/(−2). ✓ Grensetilfellene går også opp: S′ = 0 gir forholdet 0, fordi konsumentprisen står stille, og når D′ går mot 0, vokser forholdet ubegrenset i absoluttverdi, fordi produsentprisen står stille.</p>",
      traps: [
        null,
        "Brøken snudd: dette er (∂p/∂t)/(∂P/∂t). Med D′ = −2 og S′ = 3 gir den −0,67 i stedet for −1,50.",
        "Dette er ∂P/∂t alene, ikke forholdet. Nevneren S′ − D′ står i begge de deriverte og forsvinner når du deler dem på hverandre.",
        "Differansen forvekslet med forholdet: det er ∂P/∂t − ∂p/∂t som alltid er 1. Forholdet er −1 bare når S′ = |D′|, altså når byrden deles likt.",
      ],
    },
    {
      id: "k11-14",
      topic: "Monopol",
      points: 3,
      body: "<p>En monopolist møter den inverse etterspørselen P = 120 − 2x og har konstant grensekostnad kr 40 per enhet [eksempeltall].</p><p>Staten innfører en stykkskatt på kr 20 per enhet, innkrevd av monopolisten.</p><p>Hva blir prisen konsumentene betaler, og hvor stort blir provenyet?</p>",
      options: [
        "P = kr 60 og proveny kr 600",
        "P = kr 70 og proveny kr 500",
        "P = kr 90 og proveny kr 300",
        "P = kr 100 og proveny kr 200",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — tilpasningen uten skatt.</b> Inntekten er P × x = 120x − 2x<sup>2</sup>, så grenseinntekten er MR = 120 − 4x, dobbelt så bratt som etterspørselen. MR = MC: 120 − 4x = 40 gir <b>x = 20</b> og P = 120 − 40 = <b>kr 80</b>.</p><p><b>Steg 2 — skatten løfter grensekostnaden.</b> Monopolisten betaler 20 til staten per enhet, så MC + t = 60. 120 − 4x = 60 gir <b>x = 15</b> og P = 120 − 30 = <b>kr 90</b>.</p><p><b>Steg 3 — provenyet.</b> t × x = 20 × 15 = <b>kr 300</b>.</p><p><b>Steg 4 — delingen.</b> Konsumentene betaler 90 − 80 = kr 10 mer. Monopolisten sitter igjen med 90 − 20 = kr 70 per enhet mot 80 før, altså kr 10 mindre. Skatten deles på midten, slik den alltid gjør med lineær etterspørsel og konstant grensekostnad: P* = (a + c + t)/2 = (120 + 40 + 20)/2 = 90. ✓</p><p><b>Kontroll:</b> 10 + 10 = 20 = t. ✓ Og full overvelting lønner seg ikke: ved P = 90 er profitten (90 − 60) × 15 = kr 450, ved P = 100 bare (100 − 60) × 10 = kr 400. Den samme mekanismen ga fasiten i H2021 oppgave 2, der prisen gikk fra 2 til 2,50 med en skatt på 1.</p>",
      traps: [
        "Grenseinntekten gitt samme helning som etterspørselen: 120 − 2x = 60 gir x = 30 og P = 60, som er pris lik grensekostnad pluss skatt, altså frikonkurranseløsningen. Provenyet blir 20 × 30 = 600.",
        "Fortegnsfeil: skatten trukket fra grensekostnaden, 120 − 4x = 40 − 20, som gir x = 25 og P = 70. En skatt kan ikke senke prisen fra 80, og provenyet 20 × 25 = 500 er like galt.",
        null,
        "Full overvelting: 80 + 20 = 100. Da faller salget til (120 − 100)/2 = 10 og provenyet til 200, og profitten blir 400 mot 450 ved P = 90. Monopolisten tjener på å ta halve skatten selv.",
      ],
    },
    {
      id: "k11-15",
      topic: "Dødvektstap og skattesats",
      points: 3,
      body: "<p>Et marked har etterspørselen x = 600 − 10P og tilbudet x = 15p − 150, der P er konsumentprisen og p produsentprisen i kroner [eksempeltall]. Uten skatt er P = p = kr 30 og x = 300.</p><p>I dag er det en stykkskatt på kr 4 per enhet, innkrevd av produsentene. Regjeringen foreslår å doble den til kr 8.</p><p>Med hvilken faktor multipliseres dødvektstapet og provenyet når skatten dobles? Sammenlign med situasjonen ved kr 4, og rund faktorene av til to desimaler.</p>",
      options: [
        "Dødvektstapet × 2,00 og provenyet × 2,00",
        "Dødvektstapet × 2,00 og provenyet × 1,83",
        "Dødvektstapet × 4,00 og provenyet × 2,00",
        "Dødvektstapet × 4,00 og provenyet × 1,83",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — hvor mye kvantumet faller per krone skatt.</b> S′ = 15 og D′ = −10, så ∂x/∂t = S′ × ∂p/∂t = S′D′/(S′ − D′) = 15 × (−10)/25 = <b>−6</b>. Med lineære kurver gjelder det for hver krone.</p><p><b>Steg 2 — skatt kr 4.</b> Kvantum 300 − 4 × 6 = <b>276</b>. Kontroll ved å løse: 600 − 10(p + 4) = 15p − 150 gir p = 28,40, P = 32,40 og x = 15 × 28,40 − 150 = 276. ✓ Proveny 4 × 276 = <b>kr 1 104</b>. Dødvektstap ½ × 4 × 24 = <b>kr 48</b>.</p><p><b>Steg 3 — skatt kr 8.</b> Kvantum 300 − 8 × 6 = <b>252</b>. Kontroll: p = 26,80, P = 34,80 og x = 15 × 26,80 − 150 = 252. ✓ Proveny 8 × 252 = <b>kr 2 016</b>. Dødvektstap ½ × 8 × 48 = <b>kr 192</b>.</p><p><b>Steg 4 — faktorene.</b> Dødvektstapet: 192/48 = <b>4,00</b>. Provenyet: 2 016/1 104 = 1,826, avrundet <b>1,83</b>.</p><p><b>Mekanismen.</b> Dødvektstapet er en trekant med høyde t og bredde lik kvantumsfallet, og kvantumsfallet er selv proporsjonalt med t. Derfor vokser tapet med kvadratet av satsen: ½ × t<sup>2</sup> × |S′D′|/(S′ − D′) = ½ × t<sup>2</sup> × 6 = 3t<sup>2</sup>. Provenyet vokser mindre enn satsen, fordi grunnlaget krymper.</p><p><b>Kontroll:</b> 3 × 4<sup>2</sup> = 48 og 3 × 8<sup>2</sup> = 192. ✓ Dødvektstapet per provenykrone går fra 48/1 104 = 4,3 % til 192/2 016 = 9,5 %. Doble satsen, og hver ekstra provenykrone blir dyrere.</p>",
      traps: [
        "Alt behandlet som proporsjonalt med satsen: kvantumet holdt fast på 276, slik at provenyet blir 8 × 276 = 2 208 (× 2,00) og trekanten ½ × 8 × 24 = 96 (× 2,00). Kvantumet faller videre når skatten øker.",
        "Provenyet er riktig, men trekanten har fått dobbel høyde og samme bredde: ½ × 8 × 24 = 96. Kvantumsfallet dobles også, fra 24 til 48.",
        "Dødvektstapet er riktig, men provenyet er regnet på kvantumet før skatt: 8 × 300 / (4 × 300) = 2,00. Skatten betales bare på enhetene som faktisk omsettes.",
        null,
      ],
    },
    {
      id: "k11-16",
      topic: "Lønnsavgift",
      points: 3,
      body: "<p>I et arbeidsmarked er etterspørselen etter arbeid L = 12 000 − 30W, der W er arbeidsgiverens samlede kostnad per time, og tilbudet av arbeid L = 20w + 2 000, der w er det arbeidstakeren sitter igjen med per time. L er timer, W og w er kroner [eksempeltall]. Uten avgift er W = w = kr 200 og L = 6 000.</p><p>Staten innfører en lønnsavgift på kr 25 per arbeidstime. Loven sier at arbeidsgiveren betaler kr 5 per time til staten, og at kr 20 per time trekkes fra arbeidstakerens lønn.</p><p>Hva blir arbeidsgiverens samlede kostnad per time (lønn pluss hans del av avgiften), og hva sitter arbeidstakeren igjen med per time etter sin del av avgiften?</p>",
      options: [
        "Kr 200 for arbeidsgiveren og kr 175 for arbeidstakeren",
        "Kr 205 for arbeidsgiveren og kr 180 for arbeidstakeren",
        "Kr 210 for arbeidsgiveren og kr 185 for arbeidstakeren",
        "Kr 215 for arbeidsgiveren og kr 190 for arbeidstakeren",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — oversett til insidensmodellen.</b> Arbeidsgiveren er kjøperen og arbeidstakeren selgeren. Kalles bruttolønnen på lønnsslippen w<sub>b</sub>, er W = w<sub>b</sub> + 5 og w = w<sub>b</sub> − 20, altså W = w + 25. Bare kilen på 25 kommer inn i likevekten; hvordan loven deler innbetalingen, gjør det ikke.</p><p><b>Steg 2 — ny likevekt.</b> Etterspørsel lik tilbud med W = w + 25: 12 000 − 30(w + 25) = 20w + 2 000 gir 11 250 − 30w = 20w + 2 000, altså 9 250 = 50w og <b>w = kr 185</b>. Da er <b>W = kr 210</b>.</p><p><b>Steg 3 — kvantumet fra begge sider.</b> 12 000 − 30 × 210 = 5 700 og 20 × 185 + 2 000 = 5 700. ✓</p><p><b>Steg 4 — delingen og lønnsslippen.</b> Arbeidsgiveren bærer 210 − 200 = kr 10 (40 %), arbeidstakeren 200 − 185 = kr 15 (60 %). Formelen gir det samme: kjøperens andel er S′/(S′ − D′) = 20/50 = 40 %. Bruttolønnen blir w<sub>b</sub> = 210 − 5 = kr 205: arbeidsgiveren betaler 205 + 5 = 210, og arbeidstakeren får 205 − 20 = 185.</p><p><b>Kontroll:</b> 10 + 15 = 25 = t. ✓ Hadde loven lagt hele avgiften på arbeidsgiveren, ville bruttolønnen blitt 210 − 25 = kr 185, og W og w ville vært nøyaktig de samme; bare tallet på lønnsslippen endres. Arbeidstakeren bærer mest her fordi arbeidstilbudet er minst prisfølsomt (20 timer per krone mot 30). Standardsynet i faget, at arbeidstakerne bærer lønnsavgiftene, bygger på at arbeidstilbudet er lite elastisk. Den samme overveltingen er leddet a i inntektsskiftningsligningen i kapittel 5.</p>",
      traps: [
        "Tommelfingerregelen «arbeidstakeren bærer arbeidsgiveravgiften» brukt uten å regne. Den gjelder når arbeidstilbudet er perfekt uelastisk; her stiger tilbudet med lønnen, så arbeidsgiveren bærer en del. Ved W = 200 etterspørres 6 000 timer, men ved w = 175 tilbys bare 5 500.",
        "Formell insidens: hver side antatt å bære sin lovbestemte del, 200 + 5 og 200 − 20. Da etterspørres 5 850 timer og tilbys 5 600, så markedet går ikke opp.",
        null,
        "Andelene byttet om: arbeidsgiveren tildelt |D′|/(S′ − D′) = 30/50 = 60 %, altså kr 15. Da etterspørres 5 550 timer og tilbys 5 800.",
      ],
    },
    {
      id: "k11-17",
      topic: "Elastisk etterspørsel",
      points: 3,
      body: "<p>Et lite land eksporterer hele produksjonen av en vare til verdensmarkedet, der prisen er kr 60 per enhet uansett hvor mye landet selger. Etterspørselen produsentene møter, er derfor perfekt elastisk. Tilbudet er x = 50p − 1 000, der p er prisen produsentene sitter igjen med [eksempeltall].</p><p>Staten innfører en avgift på kr 8 per eksportert enhet, innkrevd av produsentene.</p><p>Hva blir prisen produsentene sitter igjen med, og hvor stort blir provenyet?</p>",
      options: [
        "p = kr 44 og proveny kr 9 600",
        "p = kr 52 og proveny kr 12 800",
        "p = kr 56 og proveny kr 14 400",
        "p = kr 60 og proveny kr 16 000",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — grensetilfellet.</b> Perfekt elastisk etterspørsel betyr D′ → −∞. Da går ∂P/∂t = S′/(S′ − D′) mot <b>0</b> og ∂p/∂t = D′/(S′ − D′) mot <b>−1</b>. Kjøperne betaler verdensmarkedsprisen som før, og produsentene bærer hele avgiften.</p><p><b>Steg 2 — prisene.</b> P = kr 60 uendret, og p = 60 − 8 = <b>kr 52</b>.</p><p><b>Steg 3 — kvantumet.</b> Produsentene tilpasser seg prisen de sitter igjen med: x = 50 × 52 − 1 000 = <b>1 600</b>, ned fra 50 × 60 − 1 000 = 2 000.</p><p><b>Steg 4 — provenyet.</b> 8 × 1 600 = <b>kr 12 800</b>.</p><p><b>Kontroll:</b> kilen 60 − 52 = 8 = t. ✓ Kjøperens byrde 0 pluss produsentens 8 er 8. ✓ Dødvektstapet er ½ × 8 × (2 000 − 1 600) = kr 1 600: tilbudet er ikke uelastisk, så kvantumet faller.</p><p>Dette er H2025 oppgave 8b og 8c med kvantum lagt til. Der ga perfekt elastisk etterspørsel uendret konsumentpris kr 1,50 og produsentpris kr 1,00 etter en skatt på kr 0,50.</p>",
      traps: [
        "Avgiften trukket fra to ganger: 60 − 8 − 8 = 44, som gir x = 1 200 og proveny 9 600. Kilen mellom P og p er t, ikke 2t.",
        null,
        "Avgiften antatt delt likt: p = 60 − 4 = 56 og x = 1 800. Med perfekt elastisk etterspørsel kan kjøperne ikke bære noe; de kjøper bare til kr 60.",
        "Feil grensetilfelle: dette er utfallet ved perfekt elastisk tilbud, der kjøperne bærer alt. Her betaler kjøperne verdensmarkedsprisen og ikke én krone mer, så produsentprisen kan ikke bli stående på 60.",
      ],
    },
    {
      id: "k11-18",
      topic: "Andre markedsformer",
      points: 3,
      body: "<p>Formlene for ∂p/∂t og ∂P/∂t forutsetter frikonkurranse. Forelesningen om hvem som betaler skatten, går også gjennom monopol, oligopol, plattformer og selskapsskatten.</p><p>Hvilken påstand er riktig?</p>",
      options: [
        "En merverdiavgift på aviser kan føre til at avisprisen faller, fordi hver ekstra leser gjør annonseplassen mer verdt",
        "Under oligopol veltes halvparten av en stykkskatt over på konsumentene, akkurat som under monopol med lineær etterspørsel",
        "En monopolist velter hele stykkskatten over på kundene, fordi markedsmakten lar ham sette prisen",
        "Selskapsskatten bæres fullt ut av eierne av selskapene som betaler den, siden det er selskapene som betaler den inn",
      ],
      answer: 0,
      solution: "<p><b>Riktig: plattformen kan senke prisen.</b> En avis betjener to gjensidig avhengige kundegrupper, lesere og annonsører, og i et slikt tosidig marked gjelder ikke pris lik grensekostnad. Legges det merverdiavgift på avisen, kan det lønne seg å senke avisprisen for å holde på leserne, fordi leserne er det annonsørene betaler for. Forelesningens poeng er nettopp at en vare som skattlegges, kan falle i pris.</p><p><b>Oligopol:</b> ingen entydig regel. Overveltingen avhenger av om det er pris- eller kvantumskonkurranse, hvor mange bedrifter som konkurrerer, og formen på tilbuds- og etterspørselsfunksjonene.</p><p><b>Monopol:</b> full overvelting ville koste monopolisten for mange kunder. Med lineær etterspørsel og konstant grensekostnad stiger prisen med nøyaktig halve skatten, og med ikke-lineære funksjoner veltes mer over jo mindre prisfølsomt markedet er, men ikke alt.</p><p><b>Selskapsskatten:</b> hvem som betaler inn, avgjør ikke hvem som bærer. Harberger-analysen gir at kapitalen generelt bærer det meste, ikke bare kapitalen i selskapene som betaler, og det amerikanske Congressional Budget Office legger til grunn at 50 % veltes over på lønninger og produktpriser.</p><p><b>Kontroll:</b> de tre gale påstandene bruker en fast regel («halvparten», «hele», «fullt ut») der forelesningen sier at svaret avhenger av markedet. Det er et nyttig filter på denne typen spørsmål.</p>",
      traps: [
        null,
        "Halvparten er monopolresultatet med lineære funksjoner. For oligopol gir forelesningen ingen entydig regel: svaret avhenger av konkurranseformen, antall bedrifter og funksjonsformene.",
        "Markedsmakt betyr ikke full overvelting. Monopolisten mister for mange kunder ved å velte over alt, og med lineær etterspørsel stiger prisen bare med halve skatten.",
        "Formell insidens forkledd som reell: hvem som betaler inn, avgjør ikke hvem som bærer. CBO antar at 50 % veltes over på lønninger og produktpriser, og Harberger-analysen gir at skatten bæres av all kapital, ikke bare kapitalen i selskapene som betaler.",
      ],
    },
    {
      id: "k11-19",
      topic: "Kapitalisering",
      points: 3,
      body: "<p>I en fjellkommune står det 800 hytter, og det kan ikke bygges flere. Alle hyttene leies ut hele året, og en typisk hytte gir eieren en netto leieinntekt på kr 30 000 i året i all framtid. Kjøperne krever 5 % avkastning, så hytta omsettes for kr 600 000 [eksempeltall]. Leien bestemmes av etterspørselen etter hytteopphold.</p><p>Kommunen vedtar overraskende en eiendomsskatt på kr 4 000 per hytte per år, i all framtid, som eieren betaler. Se bort fra inntekts- og formuesskatt.</p><p>Hvor mye faller verdien av en hytte, og hvem bærer skatten?</p>",
      options: [
        "Verdien faller med kr 4 000, og den som eier hytta de kommende årene, bærer skatten år for år",
        "Verdien faller med kr 40 000, og skatten deles likt mellom eierne og leietakerne",
        "Verdien faller med kr 80 000, og den som eier hytta når skatten vedtas, bærer hele skatten",
        "Verdien faller med kr 80 000, og den som kjøper hytta etter vedtaket, bærer skatten fordi hun betaler den hvert år",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — hvem bærer den årlige skatten.</b> Antallet hytter er gitt, så tilbudet av hytteopphold er perfekt uelastisk: S′ = 0 og ∂P/∂t = 0. Leien kan ikke stige, og eieren bærer hele skatten på kr 4 000 hvert år. Netto leieinntekt faller til 30 000 − 4 000 = <b>kr 26 000</b>.</p><p><b>Steg 2 — verdien før og etter.</b> En evig kontantstrøm er verdt CF/r. Før: 30 000/0,05 = <b>kr 600 000</b>. Etter: 26 000/0,05 = <b>kr 520 000</b>.</p><p><b>Steg 3 — fallet.</b> 600 000 − 520 000 = <b>kr 80 000</b>, som er nøyaktig nåverdien av alle framtidige skattebetalinger: 4 000/0,05 = 80 000. Skatten er kapitalisert i prisen.</p><p><b>Steg 4 — hvem.</b> Den som eier hytta idet skatten vedtas, taper 80 000 på én gang, enten hun selger eller beholder hytta og betaler 4 000 i året. En kjøper etter vedtaket betaler 520 000, får 26 000 i året og tjener 26 000/520 000 = 5 %, som før. Hun betaler skatten inn hvert år, men bærer den ikke.</p><p><b>Kontroll:</b> 520 000 × 5 % = 26 000 = 30 000 − 4 000. ✓ Forelesningen bruker samme mekanisme i hytte-eksempelet: en ventet eiendomsskatt slår inn i prisen allerede før den innføres. Personlig økonomi-poenget er å unngå å sitte med aktivumet idet en ny skatt blir kjent.</p>",
      traps: [
        "Bare ett års skatt trukket fra verdien. Skatten betales i all framtid, og prisen er nåverdien av hele strømmen: 4 000/0,05 = 80 000.",
        "Skatten antatt delt likt: leien opp 2 000 og verdien ned 2 000/0,05 = 40 000. Med et fast antall hytter er tilbudet perfekt uelastisk, og leien kan ikke stige.",
        null,
        "Formell insidens: kjøperen betaler skatten inn hvert år, men hun har fått 80 000 i prisavslag, som er nøyaktig nåverdien av betalingene. Hun får 5 % avkastning som før.",
      ],
    },
    {
      id: "k11-20",
      topic: "Dødvektstapet som formel",
      points: 3,
      body: "<p>En stykkskatt t legges på et marked med likevekten D(p + t) = S(p), der D′ &lt; 0 og S′ &gt; 0 er helningene til etterspørselen og tilbudet, målt i enheter per krone. Kurvene er lineære, og ingen av dem er vannrett eller loddrett.</p><p>Hvilket uttrykk gir dødvektstapet av skatten?</p>",
      options: [
        "½ × t<sup>2</sup> × |S′D′| / (S′ − D′)",
        "½ × t × |S′D′| / (S′ − D′)",
        "t<sup>2</sup> × |S′D′| / (S′ − D′)",
        "½ × t<sup>2</sup> × S′",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — hvor mye kvantumet faller.</b> Kvantumet leses av tilbudet, x = S(p), så ∂x/∂t = S′ × ∂p/∂t = S′ × D′/(S′ − D′). Det er negativt, og kvantumsfallet ved skatten t er |Δx| = t × |S′D′|/(S′ − D′).</p><p><b>Steg 2 — trekanten.</b> Dødvektstapet er en trekant med høyde t, kilen mellom P og p, og bredde |Δx|: ½ × t × t × |S′D′|/(S′ − D′) = <b>½ × t<sup>2</sup> × |S′D′|/(S′ − D′)</b>.</p><p><b>Kontroll med tall.</b> Ta etterspørselen x = 400 − 20P og tilbudet x = 30p − 100 [eksempeltall], altså D′ = −20 og S′ = 30, med likevekt P = p = 10 og x = 200. En skatt t = 5 gir 400 − 20(p + 5) = 30p − 100, altså p = 8, P = 13 og x = 140. Trekanten er ½ × 5 × 60 = 150. Formelen: ½ × 25 × 600/50 = ½ × 25 × 12 = 150. ✓ De tre gale uttrykkene gir 30, 300 og 375.</p><p>Formelen viser to ting på én gang: tapet vokser med kvadratet av skatten, og det blir null hvis en av helningene er null, fordi |S′D′| da er null. Derfor gir en skatt på noe helt uelastisk ikke dødvektstap.</p>",
      traps: [
        null,
        "t ikke kvadrert: bare høyden i trekanten har fått t, men bredden, kvantumsfallet, er også proporsjonal med t. Med tallene i løsningen gir den 30.",
        "Halvparten glemt: t × |Δx| er rektangelet, ikke trekanten. Med tallene i løsningen gir den 300, det dobbelte av riktig.",
        "Kvantumsfallet regnet som om produsentprisen falt med hele skatten, |Δx| = S′ × t. Det gjelder bare når etterspørselen er perfekt elastisk (D′ → −∞); med tallene i løsningen gir den 375.",
      ],
    },
  ],
};
