/* Kapittel 12 — Skatt, risiko og implisitte skatter */
window.EDU_DATA.chapterTasks[12] = {
  minutes: 22,
  tasks: [
    {
      id: "k12-1",
      topic: "Fullt tapsfradrag",
      points: 3,
      body: "<p>Du har kr 200 000 å investere og må velge ett av to prosjekter. <b>Prosjekt A</b> gir en sikker gevinst på kr 30 000. <b>Prosjekt B</b> gir kr 150 000 i gevinst eller kr 60 000 i tap, med like stor sannsynlighet. Skatten på gevinst er 40 % [eksempeltall], og et tap kan i sin helhet føres mot annen skattepliktig inntekt, altså fullt tapsfradrag.</p><p>Hva er forventet resultat etter skatt for prosjekt B, og hvilket prosjekt velger du?</p>",
      options: [
        "Kr 15 000, og du velger A",
        "Kr 27 000, men du velger A",
        "Kr 45 000, og du velger B",
        "Kr 27 000, og du velger B",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — forventningen før skatt.</b> Forventet bruttogevinst G = ½ × 150 000 = <b>75 000</b>, forventet bruttotap L = ½ × 60 000 = <b>30 000</b>. Forventningen er E = G − L = 75 000 − 30 000 = <b>45 000</b>, altså mer enn de 30 000 A gir sikkert. Uten skatt velger du B.</p><p><b>Steg 2 — skatten med fullt tapsfradrag.</b> Staten tar 40 % av gevinsten og dekker 40 % av tapet, så hvert utfall krymper med den samme faktoren: 0,60 × 150 000 = +90 000 og 0,60 × (−60 000) = −36 000. Forventningen blir ½ × 90 000 − ½ × 36 000 = <b>27 000</b>, som er nøyaktig (1 − t) × E = 0,60 × 45 000 ✓</p><p><b>Steg 3 — A faller like mye.</b> 0,60 × 30 000 = <b>18 000</b>. Begge prosjektene er ganget med den samme faktoren 0,60, og derfor kan rangeringen ikke snu: 27 000 er fortsatt større enn 18 000, og du velger <b>B</b>, akkurat som du gjorde uten skatt. Det er hele Domar–Musgrave-poenget: med fullt tapsfradrag er skatten nøytral for prosjektvalget.</p><p><b>Kontroll — statens side.</b> Av B tar staten 0,40 × 45 000 = 18 000 og du beholder 27 000; 18 000 + 27 000 = 45 000 ✓ Av A tar staten 12 000 og du beholder 18 000; 12 000 + 18 000 = 30 000 ✓ Staten er stille partner med andelen t i begge, med i oppturen og nedturen med samme brøk.</p><p>Merk hva som ville skjedd uten tapsfradrag: E − t × G = 45 000 − 0,40 × 75 000 = 15 000, mindre enn As 18 000, og valget hadde snudd til A.</p>",
      traps: [
        "Regnet uten tapsfradrag: 45 000 − 40 % × 75 000 = 15 000. Oppgaven sier at tapet er fullt fradragsberettiget, og da bærer staten 40 % av tapet også.",
        "Riktig tall for B, men A er sammenlignet før skatt. Skatten krymper begge med 0,60, så A gir 18 000, ikke 30 000.",
        "Skatten er glemt helt. 45 000 er forventningen før skatt.",
        null,
      ],
    },
    {
      id: "k12-2",
      topic: "Replisering",
      points: 3,
      body: "<p>Marte har kr 2 000 000 i formue. Uten skatt plasserer hun kr 480 000 i et risikabelt aktivum som gir +24 % eller −16 % med like stor sannsynlighet [eksempeltall]; resten står på en konto med null avkastning. Så innføres en proporsjonal skatt på 25 % på avkastningen, med fullt tapsfradrag.</p><p>Hvor mye plasserer Marte i det risikable aktivumet etter at skatten er innført, hvis hun vil ha nøyaktig den samme fordelingen av sluttformuen som før?</p>",
      options: [
        "Kr 360 000",
        "Kr 640 000",
        "Kr 480 000, altså uendret, siden skatten er nøytral",
        "Kr 600 000",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hva skatten gjør med et uendret beløp.</b> Med 480 000 i aksjen er utfallene før skatt +115 200 og −76 800. Med 25 % skatt og fullt tapsfradrag krymper begge med 0,75: +86 400 og −57 600. Forventningen faller fra 19 200 til 14 400, og standardavviket fra 96 000 til 72 000. Her stopper de fleste og konkluderer at skatten dempet risikotakingen.</p><p><b>Steg 2 — repliseringen.</b> Sluttformuen er Y = A + (1 − t) × x<sub>1</sub> × r̃. Faktoren (1 − t) er ikke stokastisk, så det er produktet (1 − t)x<sub>1</sub> som bestemmer fordelingen. Skal produktet være det samme som før, må x<sub>1</sub>* = 480 000 / (1 − 0,25) = 480 000 / 0,75 = <b>kr 640 000</b>. Du deler på (1 − t), du ganger ikke.</p><p><b>Steg 3 — kontroll utfall for utfall.</b> 640 000 × 24 % = +153 600 og 640 000 × (−16 %) = −102 400. Etter skatt: 0,75 × 153 600 = <b>+115 200</b> og 0,75 × (−102 400) = <b>−76 800</b>. Identisk med utfallene uten skatt ✓ Ikke bare i forventning og standardavvik, men utfall for utfall, og derfor gir de identisk forventet nytte for enhver nyttefunksjon. Svaret avhenger ikke av hvor risikoavers Marte er.</p><p><b>Kontroll — statens regnskap.</b> Brutto forventning på 640 000 er 640 000 × 4 % = 25 600. Staten tar 0,25 × 25 600 = 6 400, Marte beholder 19 200, og 6 400 + 19 200 = 25 600 ✓ I det dårlige utfallet betaler staten henne 0,25 × 102 400 = 25 600, og det er nettopp derfor hun tør å skalere opp.</p>",
      traps: [
        "Ganget med (1 − t) i stedet for å dele: 480 000 × 0,75. Det er beløpet som gir halvert risiko, ikke uendret risiko.",
        null,
        "Nøytralitet forvekslet med uendret beløp. Skatten er nøytral for hvilken fordeling hun ender med, men bare fordi hun endrer beløpet.",
        "Ganget med (1 + t) i stedet for å dele på (1 − t): 480 000 × 1,25. Nær riktig svar, men oppskaleringen er 1/(1 − t) = 1,333, ikke 1,25.",
      ],
    },
    {
      id: "k12-3",
      topic: "Implisitt skattesats",
      points: 3,
      body: "<p>Staten utsteder to obligasjoner med nøyaktig samme risiko. Obligasjon A er fullt skattlagt og gir <b>12 %</b> før skatt. Obligasjon B er fritatt for skatt på renteinntekten og gir <b>9 %</b> [eksempeltall]. Markedet er velfungerende og prisene har satt seg.</p><p>Hva er den implisitte skattesatsen på obligasjon B?</p>",
      options: [
        "3,0 prosentpoeng",
        "25,0 %",
        "33,3 %",
        "75,0 %",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — likevektsbetingelsen.</b> To like risikable papirer må gi samme avkastning etter skatt, ellers finnes det en pengemaskin. B er skattefri og gir r; A gir R(1 − t*). Likevekten er r = R(1 − t*), altså 9 % = 12 % × (1 − t*).</p><p><b>Steg 2 — løs for satsen.</b> 1 − t* = r/R = 9/12 = 0,75, så t* = 1 − 0,75 = (R − r)/R = (12 − 9)/12 = <b>25,0 %</b>.</p><p><b>Steg 3 — hva tallet betyr.</b> Kjøperen av B gir avkall på 3 prosentpoeng, og det er 25 % av de 12 prosentene han kunne hatt. Ingen krever inn denne skatten, og staten får ingen inntekt av den. Den er kapitalisert i prisen: fritaket gjorde papiret attraktivt, prisen ble bydd opp, nevneren i avkastningsbrøken vokste, og avkastningen falt. I likevekt er t* lik marginalskatten til den marginale investoren, altså 25 %.</p><p><b>Kontroll:</b> 12 % × (1 − 0,25) = <b>9 %</b> ✓ Nevneren i satsen skal alltid være avkastningen før skatt på det fullt skattlagte papiret, R. Legg merke til at t* kan leses ut av to markedstall alene, uten at du kjenner noen lovbestemt sats.</p>",
      traps: [
        "Differansen i prosentpoeng presentert som en skattesats. En sats er dimensjonsløs og må måles mot et grunnlag.",
        null,
        "(R − r)/r: avkastningen etter skatt satt i nevneren. Samme feil som å regne en rabatt i prosent av prisen etter rabatt.",
        "r/R = 9/12, altså andelen som er igjen. Satsen er 1 − r/R, ikke r/R.",
      ],
    },
    {
      id: "k12-4",
      topic: "Valgregelen",
      points: 3,
      body: "<p>Samme to obligasjoner som over: A er fullt skattlagt og gir 12 %, B er skattefri og gir 9 %, og risikoen er den samme. Jonas har en marginalskatt på <b>40 %</b> på renteinntekter [eksempeltall].</p><p>Hvilken obligasjon bør Jonas eie, og hvor mye bedre er det valget målt i årlig avkastning etter skatt?</p>",
      options: [
        "A, den skattlagte, med 3,0 prosentpoeng",
        "A, den skattlagte, med 1,8 prosentpoeng",
        "B, den skattefrie, med 1,35 prosentpoeng",
        "B, den skattefrie, med 1,8 prosentpoeng",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — A etter Jonas sin egen sats.</b> 12 % × (1 − 0,40) = <b>7,2 %</b>.</p><p><b>Steg 2 — B er skattefri.</b> Den gir <b>9,0 %</b> etter skatt, det samme som før skatt. Den skal ikke skattlegges en gang til.</p><p><b>Steg 3 — differansen.</b> 9,0 − 7,2 = <b>1,8 prosentpoeng</b> i favør av den skattefrie. Jonas bør eie <b>B</b>.</p><p><b>Kontroll via satsene.</b> Den implisitte satsen er t* = (12 − 9)/12 = 25 %. Regelen sier: egen marginalskatt over t* gir det skattefavoriserte papiret. Jonas har 40 % mot markedets 25 %, så B. Gevinsten er (t − t*) × R = (40 % − 25 %) × 12 % = 0,15 × 12 = <b>1,8 prosentpoeng</b> ✓ Samme tall to veier.</p><p>Legg merke til at fortegnet i (t − t*) × R gjør hele jobben. Er din sats lavere enn markedets, er gevinsten negativ, og da skal du eie det skattlagte papiret. Jonas betaler samlet 25 % på B (alt implisitt) i stedet for sine egne 40 % på A, og det er nøyaktig de 15 prosentpoengene som blir til 1,8 når de ganges med de 12 prosentene.</p>",
      traps: [
        "Avkastningene sammenlignet før skatt: 12 mot 9. Da er hele poenget med implisitt skatt oversett, og fella «velg alltid den med høyest rente» er gått i.",
        "Egen marginalskatt brukt på begge papirene: 9 % × 0,60 = 5,4 % mot 7,2 %. B er skattefri, så 40 %-satsen treffer den ikke.",
        "Riktig valg, men (t − t*) er ganget med r i stedet for med R. Gevinsten måles mot avkastningen før skatt på det skattlagte papiret, 12 %.",
        null,
      ],
    },
    {
      id: "k12-5",
      topic: "Asymmetrisk tapsbehandling",
      points: 3,
      body: "<p>Et oppstartsselskap har ingen annen skattepliktig inntekt, og et tap gir derfor ingen skattereduksjon. Selskapet velger mellom to plasseringer av samme beløp. <b>Prosjektet</b> gir kr 500 000 i gevinst eller kr 300 000 i tap, med like stor sannsynlighet. <b>Den sikre plasseringen</b> gir kr 90 000. Gevinst skattlegges med 30 % [eksempeltall] i begge tilfeller.</p><p>Hva er prosjektets forventede resultat etter skatt, og hva velger selskapet?</p>",
      options: [
        "Kr 25 000, og selskapet velger den sikre plasseringen",
        "Kr 70 000, og selskapet velger prosjektet",
        "Kr 100 000, og selskapet velger prosjektet",
        "Kr −50 000, og selskapet velger den sikre plasseringen",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — før skatt.</b> Forventet bruttogevinst G = ½ × 500 000 = <b>250 000</b>, forventet bruttotap L = ½ × 300 000 = <b>150 000</b>, og forventningen E = 250 000 − 150 000 = <b>100 000</b>. Før skatt slår prosjektet den sikre plasseringens 90 000.</p><p><b>Steg 2 — skatten treffer bare oppsiden.</b> Uten tapsfradrag er formelen E<sub>etter</sub> = E − t × G = 100 000 − 0,30 × 250 000 = 100 000 − 75 000 = <b>25 000</b>. Kontroll utfall for utfall: ½ × 0,70 × 500 000 − ½ × 300 000 = 175 000 − 150 000 = 25 000 ✓ Tapet på 300 000 er like stort etter skatt som før, for det finnes ingen inntekt å føre det mot.</p><p><b>Steg 3 — den sikre plasseringen.</b> 90 000 × 0,70 = <b>63 000</b>. Den er sikker, så skatten treffer hele beløpet, men den har heller ingen nedside å miste fradrag på. 63 000 er større enn 25 000, og selskapet velger <b>den sikre plasseringen</b>.</p><p><b>Kontroll — hva fullt tapsfradrag ville gitt.</b> (1 − t) × E = 0,70 × 100 000 = 70 000, som er større enn 63 000, og da hadde selskapet valgt prosjektet ✓ Rangeringen snur på tapsbehandlingen alene, uten at ett eneste tall i prosjektet er endret. Det er slik Domar–Musgrave bryter sammen: staten er partner i oppturen med 30 % og i nedturen med null.</p><p>Merk konsekvensen. Et etablert selskap med overskudd fra andre prosjekter kan føre tapet mot dem umiddelbart og lander på 70 000. Oppstartsselskapet lander på 25 000 for det helt samme prosjektet. Skattesystemet favoriserer altså etablerte framfor nye i risikable prosjekter, det motsatte av hva man ofte tror.</p>",
      traps: [
        null,
        "(1 − t) × E brukt, altså regelen for fullt tapsfradrag. Oppgaven sier at tapet ikke gir fradrag, og da er formelen E − t × G.",
        "Skatten er glemt helt. 100 000 er forventningen før skatt, og der vinner prosjektet fordi den sikre plasseringen heller ikke er skattlagt.",
        "t ganget med bruttogevinsten i det gode utfallet (500 000) i stedet for med den forventede bruttogevinsten G = 250 000.",
      ],
    },
    {
      id: "k12-6",
      topic: "Skattefri investor",
      points: 3,
      body: "<p>En stiftelse betaler ingen skatt på renteinntekter. Den vurderer to obligasjoner med samme risiko: en fullt skattlagt som gir <b>8 %</b> før skatt, og en skattefri som gir <b>6,4 %</b> [eksempeltall]. Markedet er velfungerende og i likevekt.</p><p>Hvor mye taper stiftelsen i årlig avkastning ved å kjøpe den skattefrie obligasjonen i stedet for den skattlagte?</p>",
      options: [
        "Ingenting. Stiftelsen betaler ingen skatt, så de to papirene er likeverdige for den",
        "1,28 prosentpoeng",
        "1,6 prosentpoeng",
        "Ingenting, den tjener tvert imot 1,6 prosentpoeng, fordi den slipper skatten det andre papiret bærer",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — markedets implisitte sats.</b> t* = (8 − 6,4)/8 = 1,6/8 = <b>20 %</b>. Kontroll: 8 % × (1 − 0,20) = 6,4 % ✓ Den marginale investoren har 20 % marginalskatt og er indifferent.</p><p><b>Steg 2 — hva stiftelsen faktisk får.</b> Den skattlagte obligasjonen gir henne hele <b>8 %</b>, for hun betaler ingen skatt på renten. Den skattefrie gir <b>6,4 %</b>, og der er det ingenting å slippe unna: papiret gir bare 6,4 % til alle.</p><p><b>Steg 3 — tapet.</b> 8 − 6,4 = <b>1,6 prosentpoeng</b> i året.</p><p><b>Kontroll med valgregelen.</b> Gevinsten ved å velge det skattefavoriserte papiret er (egen sats − t*) × R = (0 % − 20 %) × 8 % = <b>−1,6 prosentpoeng</b> ✓ Negativ, fordi hennes egen sats ligger under markedets. Regelen sier at hun skal eie det fullt skattlagte papiret, og differansen er nøyaktig det hun taper om hun lar være.</p><p>Poenget er at skattefordelen ligger i prisen, ikke i loven. Den skattefrie obligasjonen bærer 20 % implisitt skatt, og stiftelsen betaler den fullt ut selv om hun ikke sender en krone til skattemyndighetene. Derfor havner skattefavoriserte aktiva hos investorene med høyest marginalsats, og alle med lavere sats taper på å eie dem. Scholes og Wolfson kaller det skatteklienteller.</p>",
      traps: [
        "Bare den eksplisitte skatten talt. Den implisitte skatten på 20 % betales gjennom lavere avkastning før skatt, og den treffer også den som er fritatt.",
        "t* ganget med r: 20 % × 6,4 %. Tapet måles mot avkastningen på det skattlagte papiret, 8 %, ikke mot det skattefrie.",
        null,
        "Fortegnet snudd. Stiftelsen slipper uansett skatten på det skattlagte papiret og får hele 8 %; det skattefrie gir henne mindre, ikke mer.",
      ],
    },
  ],
};
