/* Kapittel 13 — Internasjonal skatt og skatteparadiser */
window.EDU_DATA.chapterTasks[13] = {
  minutes: 22,
  tasks: [
    {
      id: "k13-1",
      topic: "Ordinær kredit",
      points: 3,
      body: "<p>Et norsk aksjeselskap driver et fast driftssted i Land A og tjener kr 4 000 000 der. Land A skattlegger driftsstedet med 12 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel]. Skatteavtalen mellom Norge og Land A bygger på <b>ordinær kredit</b>.</p><p>Hvor mye betaler selskapet i skatt til sammen på denne inntekten?</p>",
      options: ["Kr 400 000", "Kr 480 000", "Kr 880 000", "Kr 1 360 000"],
      answer: 2,
      solution: "<p><b>Steg 1 — de to skattene hver for seg.</b> Land A krever 4 000 000 × 12 % = <b>480 000</b>. Norge skattlegger den samme inntekten etter globalskatteplikten: 4 000 000 × 22 % = <b>880 000</b> før lettelse.</p><p><b>Steg 2 — kreditfradraget, og taket.</b> Fradraget er min(skatt betalt ute ; norsk skatt på inntekten) = min(480 000 ; 880 000) = <b>480 000</b>. Taket på 880 000 binder ikke her, fordi kildesatsen er lavere enn den norske.</p><p><b>Steg 3 — restskatten hit.</b> 880 000 − 480 000 = <b>400 000</b>.</p><p><b>Steg 4 — samlet.</b> 480 000 til Land A pluss 400 000 til Norge = <b>kr 880 000</b>.</p><p><b>Kontroll med satsen i stedet for kronene:</b> under ordinær kredit blir samlet belastning alltid maks(t<sub>hjem</sub> ; t<sub>kilde</sub>) = maks(22 % ; 12 %) = 22 %, og 4 000 000 × 22 % = 880 000. ✓ Er kildesatsen lavere enn den norske, ender du alltid på norsk nivå: kreditten er full, og restskatten dekker nøyaktig differansen.</p>",
      traps: [
        "Bare restskatten til Norge. Det er beløpet Norge krever i tillegg, ikke selskapets samlede skatt, og de 480 000 til Land A er faktisk betalt.",
        "Unntaksmetoden brukt der avtalen gir kredit. Under unntak overlever bare kildestatens sats, men her skattlegger Norge og gir fradrag i sin egen skatt.",
        null,
        "Avtalen oversett, så begge skattene er lagt sammen: 480 000 + 880 000. Det er utfallet uten skatteavtale, ikke under kredit.",
      ],
    },
    {
      id: "k13-2",
      topic: "Kredittaket",
      points: 3,
      body: "<p>Det samme selskapet driver også et fast driftssted i Land B og tjener kr 6 000 000 der. Land B skattlegger driftsstedet med 30 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel], og skatteavtalen med Land B bygger også på <b>ordinær kredit</b>.</p><p>Hvor mye betaler selskapet i skatt til sammen på denne inntekten?</p>",
      options: ["Kr 1 800 000", "Kr 1 320 000", "Kr 2 724 000", "Kr 3 120 000"],
      answer: 0,
      solution: "<p><b>Steg 1 — de to skattene.</b> Land B: 6 000 000 × 30 % = <b>1 800 000</b>. Norge før lettelse: 6 000 000 × 22 % = <b>1 320 000</b>.</p><p><b>Steg 2 — nå binder taket.</b> Kreditfradraget er min(1 800 000 ; 1 320 000) = <b>1 320 000</b>. Norge gir avkall på inntil den skatten Norge selv ville hatt på inntekten, og ikke en krone mer.</p><p><b>Steg 3 — restskatt og ukreditert skatt.</b> Restskatten til Norge er 1 320 000 − 1 320 000 = <b>0</b>, og den kan aldri bli negativ. Av den utenlandske skatten står 1 800 000 − 1 320 000 = <b>480 000</b> uten kredit, og den går som hovedregel tapt.</p><p><b>Steg 4 — samlet.</b> 1 800 000 + 0 = <b>kr 1 800 000</b>.</p><p><b>Kontroll:</b> maks(22 % ; 30 %) = 30 %, og 6 000 000 × 30 % = 1 800 000. ✓ Kontroller restposten også: satsforskjellen er 30 − 22 = 8 prosentpoeng, og 6 000 000 × 8 % = 480 000, nøyaktig den ukrediterte skatten. ✓</p><p>Merk at fullstendig unntak ville gitt nøyaktig det samme beløpet. For enhver kildesats over den norske faller de to metodene sammen, og valget mellom dem betyr bare noe når kildestaten skattlegger lavere enn Norge.</p>",
      traps: [
        null,
        "Kredit gitt uten begrensning, altså full kredit: 1 800 000 + (1 320 000 − 1 800 000). Da måtte Norge betalt ut 480 000 for å dekke en annen stats skatt, og restskatten kan aldri bli negativ.",
        "Den utenlandske skatten trukket fra det norske grunnlaget i stedet for fra den norske skatten: 1 800 000 + (6 000 000 − 1 800 000) × 22 %. Kredit er et fradrag i skatt, ikke i inntekt.",
        "Kreditten glemt helt, så begge skattene er lagt sammen: 1 800 000 + 1 320 000. Det er utfallet uten avtale.",
      ],
    },
    {
      id: "k13-3",
      topic: "Ingen skatteavtale",
      points: 3,
      body: "<p>Et norsk aksjeselskap har kr 5 000 000 i overskudd: kr 3 000 000 opptjent i Norge og kr 2 000 000 gjennom et fast driftssted i Land C. Land C skattlegger driftsstedet med 10 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel]. Norge har <b>ingen skatteavtale</b> med Land C.</p><p>Hvor mye betaler selskapet i skatt til sammen?</p>",
      options: ["Kr 860 000", "Kr 1 100 000", "Kr 1 600 000", "Kr 1 300 000"],
      answer: 3,
      solution: "<p><b>Steg 1 — den norske delen.</b> 3 000 000 × 22 % = <b>660 000</b>. Her er ingen kildestat inne i bildet.</p><p><b>Steg 2 — Land C krever sitt etter kildeprinsippet.</b> 2 000 000 × 10 % = <b>200 000</b>. Land C har hjemmelen i sin egen lov, og norsk lov binder ikke Land C.</p><p><b>Steg 3 — Norge krever sitt etter bostedsprinsippet.</b> Globalskatteplikten omfatter hele verdensinntekten, også den delen som er tjent i et land Norge ikke har avtale med: 2 000 000 × 22 % = <b>440 000</b>. Uten avtale finnes ingen lettelse å gi, verken unntak eller kredit, for det er skatteavtalen som er hjemmelen for lettelsen. Utfallet er mekanisk dobbeltbeskatning.</p><p><b>Steg 4 — samlet.</b> 660 000 + 200 000 + 440 000 = <b>kr 1 300 000</b>.</p><p><b>Kontroll:</b> uten avtale legges satsene sammen, så utlandsinntekten bærer 22 % + 10 % = 32 %, og 2 000 000 × 32 % = 640 000. Sammen med de 660 000 gir det 1 300 000. ✓ Kontroller fra en annen kant også: ren norsk beskatning ville vært 5 000 000 × 22 % = 1 100 000, og merbelastningen 1 300 000 − 1 100 000 = 200 000 er nøyaktig den skatten Land C krevde. ✓</p>",
      traps: [
        "Unntaksmetoden brukt på utlandsinntekten: 660 000 + 200 000. Unntak følger av en skatteavtale, og her finnes ingen.",
        "Bare den norske skatten talt: 5 000 000 × 22 %. Land C skattlegger etter sin egen rett uansett hva Norge gjør.",
        "Kildestatens sats brukt på hele verdensinntekten: 5 000 000 × 10 % + 5 000 000 × 22 %. Land C kan bare skattlegge de 2 000 000 som er opptjent gjennom driftsstedet der.",
        null,
      ],
    },
    {
      id: "k13-4",
      topic: "Kredit, flere land",
      points: 3,
      body: "<p>Kari er bosatt i Norge og har kr 1 800 000 i lønn. Norsk skatt på hele verdensinntekten er beregnet til kr 835 200. Marginalskatten hennes er 46,4 % [dagens regel, trinn 4], og det er denne satsen som skal brukes når norsk skatt på den enkelte utenlandsinntekten regnes ut. Deler av lønnen er tjent i utlandet [eksempeltall]:</p><ul><li>Land A: kr 300 000, skatt betalt der kr 45 000, skatteavtale med ordinær kredit</li><li>Land B: kr 250 000, skatt betalt der kr 125 000, skatteavtale med ordinær kredit</li><li>Land C: kr 150 000, skatt betalt der kr 12 000, ingen skatteavtale</li></ul><p>Hvor mye skal Kari betale i skatt til Norge?</p>",
      options: ["Kr 580 000", "Kr 662 200", "Kr 665 200", "Kr 674 200"],
      answer: 3,
      solution: "<p><b>Steg 1 — utgangspunktet.</b> Norge skattlegger hele verdensinntekten: <b>835 200</b>. Fra dette trekkes kreditfradragene, ett land om gangen.</p><p><b>Steg 2 — Land A, der taket ikke binder.</b> Skatt betalt der er 45 000. Norsk skatt på den samme inntekten er 300 000 × 46,4 % = 139 200. Fradraget er min(45 000 ; 139 200) = <b>45 000</b>, altså full kredit.</p><p><b>Steg 3 — Land B, der taket binder.</b> Skatt betalt der er 125 000. Norsk skatt på inntekten er 250 000 × 46,4 % = <b>116 000</b>, og det er det maksimale kreditfradraget. Fradraget er min(125 000 ; 116 000) = <b>116 000</b>. De resterende 125 000 − 116 000 = <b>9 000</b> får ingen kredit og går tapt.</p><p><b>Steg 4 — Land C, uten avtale.</b> Kreditten er en lettelse Norge har bundet seg til i en skatteavtale. Finnes ingen avtale, finnes ingen kredit: fradraget er <b>0</b>, og de 12 000 som er betalt i Land C blir stående som dobbeltbeskatning.</p><p><b>Steg 5 — betalbart til Norge.</b> 835 200 − 45 000 − 116 000 − 0 = <b>kr 674 200</b>.</p><p><b>Kontroll fra den andre kanten.</b> Samlet skatt i alle land: 674 200 + 45 000 + 125 000 + 12 000 = 856 200. Ren norsk beskatning ville vært 835 200, altså 21 000 mindre. Merbelastningen skal kunne spores til to poster og bare to: ukreditert skatt i Land B, 9 000, og hele skatten i Land C, 12 000. Og 9 000 + 12 000 = 21 000. ✓</p>",
      traps: [
        "Unntaksmetoden brukt på Land A, så inntekten er holdt utenfor norsk skatt: 835 200 − 139 200 − 116 000. Avtalen med Land A gir kredit, ikke unntak.",
        "Kredit gitt også for Land C: 674 200 − 12 000. Uten skatteavtale finnes ingen kredit å gi.",
        "Kreditten for Land B gitt uten begrensning: 835 200 − 45 000 − 125 000. Fradraget kan ikke overstige norsk skatt på den inntekten, altså 116 000.",
        null,
      ],
    },
    {
      id: "k13-5",
      topic: "Nøytralitet",
      points: 3,
      body: "<p>Et norsk selskap kan investere kr 1 000 000 hjemme, der overskuddet skattlegges med 22 % [dagens regel], eller gjennom et fast driftssted i Land D, der satsen er 12 % [eksempeltall]. Lokale selskaper i Land D betaler også 12 %. Norge har skatteavtale med Land D, og spørsmålet er hvilken metode avtalen skal bygge på.</p><p>Hvilken metode gir hvilken nøytralitet?</p>",
      options: [
        "Ordinær kredit gir kapitaleksportnøytralitet, fordi samlet skatt blir 22 % både hjemme og ute. Fullstendig unntak gir kapitalimportnøytralitet, fordi driftsstedet møter de samme 12 % som lokale konkurrenter i Land D.",
        "Ordinær kredit gir kapitalimportnøytralitet, fordi den likestiller selskapet med lokale konkurrenter. Fullstendig unntak gir kapitaleksportnøytralitet, fordi det lar eieren velge fritt mellom hjemme og ute.",
        "Begge metodene gir begge nøytralitetene, siden begge fjerner dobbeltbeskatningen.",
        "Ingen av metodene gir noen av nøytralitetene så lenge satsene er ulike. Nøytralitet krever at Land D setter satsen til 22 %.",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — regn de to metodene ut.</b> Under ordinær kredit blir samlet skatt maks(22 % ; 12 %) = 22 %, altså 220 000, det samme som om pengene ble investert hjemme. Under fullstendig unntak overlever bare kildesatsen: 1 000 000 × 12 % = 120 000.</p><p><b>Steg 2 — se hvem som blir likestilt.</b> Kredit gjør <i>eieren</i> indifferent: 780 000 igjen etter skatt uansett hvor kapitalen plasseres. Det er kapitaleksportnøytralitet, og den handler om landet kapitalen eksporteres fra. Unntak gjør <i>driftsstedet</i> likestilt med naboene: 12 % for det norskeide driftsstedet og 12 % for det lokale selskapet. Det er kapitalimportnøytralitet, og den handler om konkurransen i landet kapitalen importeres til.</p><p><b>Steg 3 — hvorfor de ikke kan oppfylles samtidig.</b> Skal eieren være indifferent, må samlet sats på utlandsinntekten være 22 %. Skal driftsstedet konkurrere på like vilkår i Land D, må den være 12 %. Det er to ulike krav til det samme tallet, og de er bare forenlige når t<sub>hjem</sub> = t<sub>kilde</sub>. Valget er derfor en avveining, ikke et regnestykke.</p><p><b>Kontroll:</b> sett kildesatsen til 22 %. Da gir kredit maks(22 ; 22) = 22 % og unntak 22 %, begge nøytralitetene er oppfylt samtidig, og de to metodene faller sammen. ✓ Merk til slutt at kredit er svaret hvis staten vil hindre overskuddsflytting til lavskatteland: belastningen blir maks(t<sub>hjem</sub> ; t<sub>kilde</sub>) uansett hvor overskuddet havner, så motivet forsvinner.</p>",
      traps: [
        null,
        "De to begrepene er byttet om. Eksport peker mot eieren i hjemstaten, import mot konkurransen i kildestaten.",
        "Nøytralitetene forvekslet med fravær av dobbeltbeskatning. Begge metodene fjerner dobbeltbeskatningen, men de utjevner ikke det samme, og bare én av dem kan oppfylles når satsene er ulike.",
        "Like satser gjort til vilkår for begge nøytralitetene. Kredit gir kapitaleksportnøytralitet nettopp fordi taket løfter belastningen ute opp til norsk nivå, uten at Land D endrer noe som helst.",
      ],
    },
    {
      id: "k13-6",
      topic: "Skatteparadis",
      points: 3,
      body: "<p>På De britiske jomfruøyene var det i 2021 om lag 900 000 offshore-selskaper på 31 000 innbyggere [eksempeltall fra pensum]. Jersey gikk i 2008 fra en selskapsskatt på 20 % til en standardsats på 0 %, men beholdt 10 % for finansforetak og 20 % for kraftselskaper og Jersey-eiendom. Mauritius har 15 % nominell sats for utenlandskeide GBC1-selskaper, men et automatisk utenlandsk skattefradrag senker den til 3 % uansett om det faktisk er betalt skatt ute.</p><p>Hva er det disse jurisdiksjonene selger, slik Schjelderup bruker begrepet <i>secrecy jurisdiction</i>?</p>",
      options: [
        "En skattesats på null. Det er satsen som definerer et skatteparadis, og de tre eksemplene viser hvor langt ned den er presset.",
        "Et inngjerdet regelverk forbeholdt utlendinger, et sikret skattemessig hjemsted for de selskapene regelverket gjelder, og hemmelighold om regnskaper og reelt eierskap.",
        "Fravær fra internasjonalt samarbeid. En jurisdiksjon som står utenfor OECDs Global Forum og ikke deltar i automatisk informasjonsutveksling, er et skatteparadis.",
        "Adgang til ulovlig skatteunndragelse. Det er dette som skiller et skatteparadis fra et land med lave skatter, og derfor rammes oppleggene av straff.",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — les satsene på nytt.</b> Jersey har 0 % som standard, men 20 % for kraftselskaper og Jersey-eiendom, altså nettopp de virksomhetene som drives lokalt. Mauritius har 15 % nominelt. Satsene er verken null eller like for alle, og de er ikke det jurisdiksjonene lever av.</p><p><b>Steg 2 — se mønsteret i stedet.</b> Ett regelsett gjelder dem som bor og driver lokalt, et annet og langt gunstigere gjelder utenlandske investorer, som til gjengjeld ikke får drive virksomhet i landet. Det er det inngjerdede regelverket. Til det kommer et eget regime som gir de skattefrie selskapene hjemsted i jurisdiksjonen, typisk gjennom krav om lokale styremedlemmer og styremøter, og en informasjonssituasjon uten offentlige regnskaper og uten oppdaterte aksjonærlister, med stråmenn i styrer og truster som eiere.</p><p><b>Steg 3 — argumentet fra avslørte preferanser.</b> Var den inngjerdede lovgivningen vekstfremmende, ville jurisdiksjonen brukt den på sin egen økonomi også. At den er forbeholdt utlendinger, avslører at den ikke er ment å skape verdier, men å hente inntekter fra andre land. Forretningsmodellen er antall registrerte selskaper ganger avgifter, og derfor tjener de minste statene mest per innbygger.</p><p><b>Kontroll med tallene:</b> 900 000 / 31 000 = 29 selskaper per innbygger, mot under 250 000 selskaper i hele Norge. Anslått avgiftsinntekt er om lag 30 000 dollar per innbygger mot et BNP per innbygger på 48 200 dollar, altså 30 000 / 48 200 = 62 % av BNP. ✓ Et regelverk som var laget for lokal verdiskaping, ville ikke gitt de tallene.</p>",
      traps: [
        "Tax haven forvekslet med secrecy jurisdiction. Satsen er et instrument, hemmeligholdet er varen, og de 15 prosentene på Mauritius viser at null ikke er noe vilkår.",
        null,
        "Formell etterlevelse forvekslet med reell åpenhet. Både Jersey og Caymanøyene er medlemmer av OECDs Global Forum, og legger man den målestokken til grunn, er det nesten ingen skatteparadiser igjen.",
        "Unndragelse og skatteplanlegging slått sammen. Tax evasion er ulovlig og tax avoidance er lovlig, paradisene brukes til begge deler, og de fleste oppleggene er ikke ulovlige.",
      ],
    },
  ],
};
