/* Kapittel 13 — Internasjonal skatt og skatteparadiser */
window.EDU_DATA.chapterTasks[13] = {
  minutes: 41,
  tasks: [
    {
      id: "k13-1",
      topic: "Ordinær kredit",
      points: 3,
      body: "<p>Et norsk aksjeselskap driver et fast driftssted i Land A og tjener kr 4 000 000 der. Land A skattlegger driftsstedet med 12 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel]. Skatteavtalen mellom Norge og Land A bygger på <b>ordinær kredit</b>.</p><p>Hvor mye betaler selskapet i skatt til sammen på denne inntekten?</p>",
      options: ["Kr 400 000", "Kr 480 000", "Kr 880 000", "Kr 1 360 000"],
      answer: 2,
      solution: "<p><b>Steg 1 — de to skattene hver for seg.</b> Land A krever 4 000 000 × 12 % = <b>480 000</b>. Norge skattlegger den samme inntekten etter globalskatteplikten: 4 000 000 × 22 % = <b>880 000</b> før lettelse.</p><p><b>Steg 2 — kreditfradraget, og taket.</b> Fradraget er min(skatt betalt ute ; norsk skatt på inntekten) = min(480 000 ; 880 000) = <b>480 000</b>. Taket på 880 000 binder ikke her, fordi kildesatsen er lavere enn den norske.</p><p><b>Steg 3 — restskatten hit.</b> 880 000 − 480 000 = <b>400 000</b>.</p><p><b>Steg 4 — samlet.</b> 480 000 til Land A pluss 400 000 til Norge = <b>kr 880 000</b>.</p><p><b>Kontroll med satsen i stedet for kronene:</b> under ordinær kredit blir samlet belastning alltid maks(t<sub>hjem</sub> ; t<sub>kilde</sub>) = maks(22 % ; 12 %) = 22 %, og 4 000 000 × 22 % = 880 000. ✓ Er kildesatsen lavere enn den norske, ender du alltid på norsk nivå: kreditten er full, og restskatten dekker nøyaktig differansen.</p>",
      traps: [
        "Bare restskatten til Norge. Det er beløpet Norge krever i tillegg, ikke selskapets samlede skatt, og de 480 000 til Land A er faktisk betalt.",
        "Unntaksmetoden brukt der avtalen gir kredit. Under unntak overlever bare kildestatens sats, men her skattlegger Norge og gir fradrag i sin egen skatt.",
        null,
        "Avtalen oversett, så begge skattene er lagt sammen: 480 000 + 880 000. Det er utfallet uten skatteavtale, ikke under kredit.",
      ],
    },
    {
      id: "k13-2",
      topic: "Kredittaket",
      points: 3,
      body: "<p>Et norsk aksjeselskap driver et fast driftssted i Land B og tjener kr 6 000 000 der. Land B skattlegger driftsstedet med 30 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel], og skatteavtalen med Land B bygger også på <b>ordinær kredit</b>.</p><p>Hvor mye betaler selskapet i skatt til sammen på denne inntekten?</p>",
      options: ["Kr 1 800 000", "Kr 1 320 000", "Kr 2 724 000", "Kr 3 120 000"],
      answer: 0,
      solution: "<p><b>Steg 1 — de to skattene.</b> Land B: 6 000 000 × 30 % = <b>1 800 000</b>. Norge før lettelse: 6 000 000 × 22 % = <b>1 320 000</b>.</p><p><b>Steg 2 — nå binder taket.</b> Kreditfradraget er min(1 800 000 ; 1 320 000) = <b>1 320 000</b>. Norge gir avkall på inntil den skatten Norge selv ville hatt på inntekten, og ikke en krone mer.</p><p><b>Steg 3 — restskatt og ukreditert skatt.</b> Restskatten til Norge er 1 320 000 − 1 320 000 = <b>0</b>, og den kan aldri bli negativ. Av den utenlandske skatten står 1 800 000 − 1 320 000 = <b>480 000</b> uten kredit, og den går som hovedregel tapt.</p><p><b>Steg 4 — samlet.</b> 1 800 000 + 0 = <b>kr 1 800 000</b>.</p><p><b>Kontroll:</b> maks(22 % ; 30 %) = 30 %, og 6 000 000 × 30 % = 1 800 000. ✓ Kontroller restposten også: satsforskjellen er 30 − 22 = 8 prosentpoeng, og 6 000 000 × 8 % = 480 000, nøyaktig den ukrediterte skatten. ✓</p><p>Merk at fullstendig unntak ville gitt nøyaktig det samme beløpet. For enhver kildesats over den norske faller de to metodene sammen, og valget mellom dem betyr bare noe når kildestaten skattlegger lavere enn Norge.</p>",
      traps: [
        null,
        "Kredit gitt uten begrensning, altså full kredit: 1 800 000 + (1 320 000 − 1 800 000). Da måtte Norge betalt ut 480 000 for å dekke en annen stats skatt, og restskatten kan aldri bli negativ.",
        "Den utenlandske skatten trukket fra det norske grunnlaget i stedet for fra den norske skatten: 1 800 000 + (6 000 000 − 1 800 000) × 22 %. Kredit er et fradrag i skatt, ikke i inntekt.",
        "Kreditten glemt helt, så begge skattene er lagt sammen: 1 800 000 + 1 320 000. Det er utfallet uten avtale.",
      ],
    },
    {
      id: "k13-3",
      topic: "Ingen skatteavtale",
      points: 3,
      body: "<p>Et norsk aksjeselskap har kr 5 000 000 i overskudd: kr 3 000 000 opptjent i Norge og kr 2 000 000 gjennom et fast driftssted i Land C. Land C skattlegger driftsstedet med 10 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel]. Norge har <b>ingen skatteavtale</b> med Land C. Forutsett, som i H2020 oppgave 2, at Norge ikke gir lempning for dobbeltbeskatning etter norsk intern rett når det ikke foreligger skatteavtale.</p><p>Hvor mye betaler selskapet i skatt til sammen?</p>",
      options: ["Kr 860 000", "Kr 1 100 000", "Kr 1 600 000", "Kr 1 300 000"],
      answer: 3,
      solution: "<p><b>Steg 1 — den norske delen.</b> 3 000 000 × 22 % = <b>660 000</b>. Her er ingen kildestat inne i bildet.</p><p><b>Steg 2 — Land C krever sitt etter kildeprinsippet.</b> 2 000 000 × 10 % = <b>200 000</b>. Land C har hjemmelen i sin egen lov, og norsk lov binder ikke Land C.</p><p><b>Steg 3 — Norge krever sitt etter bostedsprinsippet.</b> Globalskatteplikten omfatter hele verdensinntekten, også den delen som er tjent i et land Norge ikke har avtale med: 2 000 000 × 22 % = <b>440 000</b>. Oppgaven forutsetter at Norge bare lemper når en avtale krever det, så uten avtale gis verken unntak eller kredit, og utfallet er dobbeltbeskatning. Merk at dette er en eksamensforutsetning: etter skatteloven § 16-20 ville selskapet i virkeligheten fått 200 000 i kreditfradrag, og svaret blitt 1 100 000.</p><p><b>Steg 4 — samlet.</b> 660 000 + 200 000 + 440 000 = <b>kr 1 300 000</b>.</p><p><b>Kontroll:</b> uten avtale legges satsene sammen, så utlandsinntekten bærer 22 % + 10 % = 32 %, og 2 000 000 × 32 % = 640 000. Sammen med de 660 000 gir det 1 300 000. ✓ Samme tall regnet som merbelastning (en omskriving, så den fanger regnefeil, ikke feil premiss): ren norsk beskatning ville vært 5 000 000 × 22 % = 1 100 000, og merbelastningen 1 300 000 − 1 100 000 = 200 000 er nøyaktig den skatten Land C krevde. ✓</p>",
      traps: [
        "Unntaksmetoden brukt på utlandsinntekten: 660 000 + 200 000. Unntak følger av en skatteavtale, og her finnes ingen.",
        "Bare den norske skatten talt: 5 000 000 × 22 %. Land C skattlegger etter sin egen rett uansett hva Norge gjør.",
        "Kildestatens sats brukt på hele verdensinntekten: 5 000 000 × 10 % + 5 000 000 × 22 %. Land C kan bare skattlegge de 2 000 000 som er opptjent gjennom driftsstedet der.",
        null,
      ],
    },
    {
      id: "k13-4",
      topic: "Kredit, flere land",
      points: 3,
      body: "<p>Kari er bosatt i Norge og har kr 1 800 000 i lønn. Norsk skatt på hele verdensinntekten er beregnet til kr 835 200. Marginalskatten hennes er 46,4 % [eksempeltall, som i H2021 oppgave 4], og det er denne satsen som skal brukes når norsk skatt på den enkelte utenlandsinntekten regnes ut. Deler av lønnen er tjent i utlandet [eksempeltall]:</p><ul><li>Land A: kr 300 000, skatt betalt der kr 45 000, skatteavtale med ordinær kredit</li><li>Land B: kr 250 000, skatt betalt der kr 125 000, skatteavtale med ordinær kredit</li><li>Land C: kr 150 000, skatt betalt der kr 12 000, ingen skatteavtale</li></ul><p>Hvor mye skal Kari betale i skatt til Norge?</p>",
      options: ["Kr 580 000", "Kr 662 200", "Kr 665 200", "Kr 674 200"],
      answer: 3,
      solution: "<p><b>Steg 1 — utgangspunktet.</b> Norge skattlegger hele verdensinntekten: <b>835 200</b>. Fra dette trekkes kreditfradragene, ett land om gangen.</p><p><b>Steg 2 — Land A, der taket ikke binder.</b> Skatt betalt der er 45 000. Norsk skatt på den samme inntekten er 300 000 × 46,4 % = 139 200. Fradraget er min(45 000 ; 139 200) = <b>45 000</b>, altså full kredit.</p><p><b>Steg 3 — Land B, der taket binder.</b> Skatt betalt der er 125 000. Norsk skatt på inntekten er 250 000 × 46,4 % = <b>116 000</b>, og det er det maksimale kreditfradraget. Fradraget er min(125 000 ; 116 000) = <b>116 000</b>. De resterende 125 000 − 116 000 = <b>9 000</b> får ingen kredit og går tapt.</p><p><b>Steg 4 — Land C, uten avtale.</b> Oppgaven forutsetter at Norge bare gir lettelse når en skatteavtale forplikter det (se teksten). Da gir Land C ingen kredit: fradraget er <b>0</b>, og de 12 000 som er betalt i Land C blir stående som dobbeltbeskatning.</p><p><b>Steg 5 — betalbart til Norge.</b> 835 200 − 45 000 − 116 000 − 0 = <b>kr 674 200</b>.</p><p><b>Samme tall fra den andre kanten</b> (en omskriving, så den fanger regnefeil, ikke feil premiss). Samlet skatt i alle land: 674 200 + 45 000 + 125 000 + 12 000 = 856 200. Ren norsk beskatning ville vært 835 200, altså 21 000 mindre. Merbelastningen skal kunne spores til to poster og bare to: ukreditert skatt i Land B, 9 000, og hele skatten i Land C, 12 000. Og 9 000 + 12 000 = 21 000. ✓</p>",
      traps: [
        "Unntaksmetoden brukt på Land A, så inntekten er holdt utenfor norsk skatt: 835 200 − 139 200 − 116 000. Avtalen med Land A gir kredit, ikke unntak.",
        "Kredit gitt også for Land C: 674 200 − 12 000. Uten skatteavtale finnes ingen kredit å gi.",
        "Kreditten for Land B gitt uten begrensning: 835 200 − 45 000 − 125 000. Fradraget kan ikke overstige norsk skatt på den inntekten, altså 116 000.",
        null,
      ],
    },
    {
      id: "k13-5",
      topic: "Nøytralitet",
      points: 3,
      body: "<p>Et norsk selskap har et prosjekt med kr 1 000 000 i overskudd før skatt, enten hjemme, der overskuddet skattlegges med 22 % [dagens regel], eller gjennom et fast driftssted i Land D, der satsen er 12 % [eksempeltall]. Lokale selskaper i Land D betaler også 12 %. Norge har skatteavtale med Land D, og spørsmålet er hvilken metode avtalen skal bygge på.</p><p>Hvilken metode gir hvilken nøytralitet?</p>",
      options: [
        "Ordinær kredit gir kapitaleksportnøytralitet, fordi samlet skatt blir 22 % både hjemme og ute. Fullstendig unntak gir kapitalimportnøytralitet, fordi driftsstedet møter de samme 12 % som lokale konkurrenter i Land D.",
        "Ordinær kredit gir kapitalimportnøytralitet, fordi den likestiller selskapet med lokale konkurrenter. Fullstendig unntak gir kapitaleksportnøytralitet, fordi det lar eieren velge fritt mellom hjemme og ute.",
        "Begge metodene gir begge nøytralitetene, siden begge fjerner dobbeltbeskatningen.",
        "Ingen av metodene gir noen av nøytralitetene så lenge satsene er ulike. Nøytralitet krever at Land D setter satsen til 22 %.",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — regn de to metodene ut.</b> Under ordinær kredit blir samlet skatt maks(22 % ; 12 %) = 22 %, altså 220 000, det samme som om pengene ble investert hjemme. Under fullstendig unntak overlever bare kildesatsen: 1 000 000 × 12 % = 120 000.</p><p><b>Steg 2 — se hvem som blir likestilt.</b> Kredit gjør <i>eieren</i> indifferent: 780 000 igjen etter skatt uansett hvor kapitalen plasseres. Det er kapitaleksportnøytralitet, og den handler om landet kapitalen eksporteres fra. Unntak gjør <i>driftsstedet</i> likestilt med naboene: 12 % for det norskeide driftsstedet og 12 % for det lokale selskapet. Det er kapitalimportnøytralitet, og den handler om konkurransen i landet kapitalen importeres til.</p><p><b>Steg 3 — hvorfor de ikke kan oppfylles samtidig.</b> Skal eieren være indifferent, må samlet sats på utlandsinntekten være 22 %. Skal driftsstedet konkurrere på like vilkår i Land D, må den være 12 %. Det er to ulike krav til det samme tallet, og de er bare forenlige når t<sub>hjem</sub> = t<sub>kilde</sub>. Valget er derfor en avveining, ikke et regnestykke.</p><p><b>Kontroll:</b> sett kildesatsen til 22 %. Da gir kredit maks(22 ; 22) = 22 % og unntak 22 %, begge nøytralitetene er oppfylt samtidig, og de to metodene faller sammen. ✓ Merk til slutt at kredit er svaret hvis staten vil hindre overskuddsflytting til lavskatteland: belastningen blir maks(t<sub>hjem</sub> ; t<sub>kilde</sub>) uansett hvor overskuddet havner, så motivet forsvinner.</p>",
      traps: [
        null,
        "De to begrepene er byttet om. Eksport peker mot eieren i hjemstaten, import mot konkurransen i kildestaten.",
        "Nøytralitetene forvekslet med fravær av dobbeltbeskatning. Begge metodene fjerner dobbeltbeskatningen, men de utjevner ikke det samme, og bare én av dem kan oppfylles når satsene er ulike.",
        "Like satser gjort til vilkår for begge nøytralitetene. Kredit gir kapitaleksportnøytralitet nettopp fordi taket løfter belastningen ute opp til norsk nivå, uten at Land D endrer noe som helst.",
      ],
    },
    {
      id: "k13-6",
      topic: "Skatteparadis",
      points: 3,
      body: "<p>På De britiske jomfruøyene var det i 2021 om lag 900 000 offshore-selskaper på 31 000 innbyggere [eksempeltall fra pensum]. Jersey gikk i 2008 fra en selskapsskatt på 20 % til en standardsats på 0 %, men beholdt 10 % for finansforetak og 20 % for kraftselskaper og Jersey-eiendom. Mauritius har 15 % nominell sats for utenlandskeide GBC1-selskaper, men et automatisk utenlandsk skattefradrag senker den til 3 % uansett om det faktisk er betalt skatt ute.</p><p>Hva er det disse jurisdiksjonene selger, slik Schjelderup bruker begrepet <i>secrecy jurisdiction</i>?</p>",
      options: [
        "En skattesats på null. Det er satsen som definerer et skatteparadis, og de tre eksemplene viser hvor langt ned den er presset.",
        "Et inngjerdet regelverk forbeholdt utlendinger, et sikret skattemessig hjemsted for de selskapene regelverket gjelder, og hemmelighold om regnskaper og reelt eierskap.",
        "Fravær fra internasjonalt samarbeid. En jurisdiksjon som står utenfor OECDs Global Forum og ikke deltar i automatisk informasjonsutveksling, er et skatteparadis.",
        "Adgang til ulovlig skatteunndragelse. Det er dette som skiller et skatteparadis fra et land med lave skatter, og derfor rammes oppleggene av straff.",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — les satsene på nytt.</b> Jersey har 0 % som standard, men 20 % for kraftselskaper og Jersey-eiendom, altså nettopp de virksomhetene som drives lokalt. Mauritius har 15 % nominelt. Satsene er verken null eller like for alle, og de er ikke det jurisdiksjonene lever av.</p><p><b>Steg 2 — se mønsteret i stedet.</b> Ett regelsett gjelder dem som bor og driver lokalt, et annet og langt gunstigere gjelder utenlandske investorer, som til gjengjeld ikke får drive virksomhet i landet. Det er det inngjerdede regelverket. Til det kommer et eget regime som gir de skattefrie selskapene hjemsted i jurisdiksjonen, typisk gjennom krav om lokale styremedlemmer og styremøter, og en informasjonssituasjon uten offentlige regnskaper og uten oppdaterte aksjonærlister, med stråmenn i styrer og truster som eiere.</p><p><b>Steg 3 — argumentet fra avslørte preferanser.</b> Var den inngjerdede lovgivningen vekstfremmende, ville jurisdiksjonen brukt den på sin egen økonomi også. At den er forbeholdt utlendinger, avslører at den ikke er ment å skape verdier, men å hente inntekter fra andre land. Forretningsmodellen er antall registrerte selskaper ganger avgifter, og derfor tjener de minste statene mest per innbygger.</p><p><b>Kontroll med tallene:</b> 900 000 / 31 000 = 29 selskaper per innbygger, mot under 250 000 selskaper i hele Norge. Anslått avgiftsinntekt er om lag 30 000 dollar per innbygger mot et BNP per innbygger på 48 200 dollar, altså 30 000 / 48 200 = 62 % av BNP. ✓ Et regelverk som var laget for lokal verdiskaping, ville ikke gitt de tallene.</p>",
      traps: [
        "Tax haven forvekslet med secrecy jurisdiction. Satsen er et instrument, hemmeligholdet er varen, og de 15 prosentene på Mauritius viser at null ikke er noe vilkår.",
        null,
        "Formell etterlevelse forvekslet med reell åpenhet. Både Jersey og Caymanøyene er medlemmer av OECDs Global Forum, og legger man den målestokken til grunn, er det nesten ingen skatteparadiser igjen.",
        "Unndragelse og skatteplanlegging slått sammen. Tax evasion er ulovlig og tax avoidance er lovlig, paradisene brukes til begge deler, og de fleste oppleggene er ikke ulovlige.",
      ],
    },
    {
      id: "k13-7",
      topic: "Fra unntak til kredit",
      points: 3,
      body: "<p>Et norsk aksjeselskap har kr 100 000 000 i overskudd i 2026: kr 40 000 000 opptjent i Norge og resten gjennom faste driftssteder i tre land [eksempeltall]:</p><ul><li>Land A: kr 30 000 000, selskapsskatt 12 %</li><li>Land B: kr 20 000 000, selskapsskatt 30 %</li><li>Land C: kr 10 000 000, selskapsskatt 0 %</li></ul><p>Norsk selskapsskatt er 22 % [dagens regel]. Norge har skatteavtale med alle tre land, og alle tre bygger i dag på fullstendig unntak. Norge reforhandler avtalene slik at alle tre går over til ordinær kredit, beregnet land for land med tak lik norsk skatt på inntekten fra det enkelte landet. Se bort fra den globale minimumsskatten.</p><p>Hvor mye øker selskapets samlede skatt til alle land per år når avtalene går over til ordinær kredit?</p>",
      options: [
        "Kr 3 000 000",
        "Kr 3 600 000",
        "Kr 5 200 000",
        "Kr 13 200 000",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — det som ikke endrer seg.</b> Norge-inntekten gir 40 000 000 × 22 % = 8 800 000 i begge regimer. Kildeskattene er også de samme, for kildestaten skattlegger etter sin egen rett uansett hvilken metode Norge bruker: Land A 30 000 000 × 12 % = 3 600 000, Land B 20 000 000 × 30 % = 6 000 000, Land C 0. Det eneste som kan endre seg, er skatten til Norge på utlandsinntekten.</p><p><b>Steg 2 — i dag, fullstendig unntak.</b> Norge ser bort fra all utlandsinntekt, så restskatten hit er 0 for alle tre land. Land C-inntekten skattlegges da ingen steder: dobbelt ikke-beskatning, som bare unntaksmetoden kan gi (H2024 oppgave 10f).</p><p><b>Steg 3 — ordinær kredit, land for land.</b> Land A: norsk skatt 30 000 000 × 22 % = 6 600 000, kreditfradrag min(3 600 000 ; 6 600 000) = 3 600 000, restskatt <b>3 000 000</b>. Land B: norsk skatt 20 000 000 × 22 % = 4 400 000, kreditfradrag min(6 000 000 ; 4 400 000) = 4 400 000, restskatt <b>0</b>, og 6 000 000 − 4 400 000 = 1 600 000 av skatten i Land B står uten kredit, fordi kreditten er begrenset til norsk skatt på inntekten (H2024 oppgave 10g). Land C: norsk skatt 10 000 000 × 22 % = 2 200 000, ingen utenlandsk skatt å kreditere, restskatt <b>2 200 000</b>.</p><p><b>Steg 4 — økningen.</b> 3 000 000 + 0 + 2 200 000 = <b>kr 5 200 000</b>.</p><p><b>Kontroll med satsene.</b> Under unntak er belastningen på utlandsinntekten t<sub>kilde</sub>, under ordinær kredit maks(t<sub>hjem</sub> ; t<sub>kilde</sub>). Økningen per land er derfor (maks(22 ; t<sub>kilde</sub>) − t<sub>kilde</sub>) × Y: Land A (22 − 12) % × 30 000 000 = 3 000 000, Land B (30 − 30) % × 20 000 000 = 0, Land C (22 − 0) % × 10 000 000 = 2 200 000. Sum 5 200 000. ✓ Samlet går selskapet fra 8 800 000 + 9 600 000 = 18 400 000 (18,4 %) til 18 400 000 + 5 200 000 = 23 600 000 (23,6 %). Summert land for land under kredit: 8 800 000 + 6 600 000 + 6 000 000 + 2 200 000 = 23 600 000. ✓</p><p><b>Mekanismen.</b> Kreditten løfter lavt beskattet utlandsinntekt opp til norsk nivå og rører ikke inntekt som alt er beskattet høyere enn i Norge. For Land B gir de to metodene derfor samme skatt, og valget av metode betyr bare noe der kildesatsen er under 22 %.</p>",
      traps: [
        "Land C holdt utenfor, som om unntaksmetoden ikke gjaldt når kildestaten ikke skattlegger, slik at Norge allerede skulle ha skattlagt de 10 000 000. Fullstendig unntak er ubetinget; i dag skattlegges inntekten ingen steder, og overgangen til kredit henter inn 2 200 000.",
        "Kredit uten tak for Land B: 3 000 000 + 2 200 000 − 1 600 000, som om Norge betalte tilbake de 1 600 000 som Land B tar over norsk nivå. Restskatten kan aldri bli negativ (samme tall får du ved å slå sammen kredittaket for alle land, som oppgaven utelukker).",
        null,
        "Kreditten glemt: norsk skatt på hele utlandsinntekten, 60 000 000 × 22 %, lagt oppå kildeskattene. Det er overgangen til ingen avtale, ikke til ordinær kredit.",
      ],
    },
    {
      id: "k13-8",
      topic: "Internprising og minimumsskatt",
      points: 3,
      body: "<p>Et norsk konsern har et produksjonsselskap i Norge og et heleid salgsselskap i Land L. Produksjonsselskapet selger 200 000 enheter i året til salgsselskapet, som videreselger dem til uavhengige kunder for kr 900 per enhet. Anta at armlengdeprisen på salget fra Norge til Land L også er kr 900 per enhet [forenklet eksempel], men at konsernet setter internprisen til kr 650. Salgsselskapet har ingen andre inntekter eller kostnader. Selskapsskatten er 22 % i Norge [dagens regel] og 5 % i Land L [eksempeltall].</p><p>Konsernet omfattes av den globale minimumsskatten på 15 %, og toppskatten kreves inn i Norge. Se bort fra substansunntaket og fra alle andre regler: armlengdeprinsippet håndheves ikke, og det gjelder ingen særregler for lavskatteland.</p><p>Hvor mye sparer konsernet i skatt per år på internprisingen, sammenlignet med om internprisen var satt lik armlengdeprisen?</p>",
      options: [
        "Kr 3 500 000",
        "Kr 5 000 000",
        "Kr 8 500 000",
        "Kr 11 000 000",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — det flyttede overskuddet.</b> (armlengdepris − internpris) × volum = (900 − 650) × 200 000 = 250 × 200 000 = <b>50 000 000</b>. Det er overskuddet som bokføres i Land L i stedet for i Norge.</p><p><b>Steg 2 — skatten uten flytting.</b> Med internpris 900 blir de 50 000 000 stående i Norge: 50 000 000 × 22 % = <b>11 000 000</b>. Salgsselskapet går i null og betaler ingenting.</p><p><b>Steg 3 — skatten med flytting.</b> Land L: 50 000 000 × 5 % = 2 500 000. Den effektive satsen i Land L er 5 %, altså under gulvet, så toppskatten er maks(0 ; 15 % − 5 %) × 50 000 000 = 10 % × 50 000 000 = 5 000 000. Samlet: 2 500 000 + 5 000 000 = <b>7 500 000</b>.</p><p><b>Steg 4 — besparelsen.</b> 11 000 000 − 7 500 000 = <b>kr 3 500 000</b>.</p><p><b>Kontroll med formelen.</b> Besparelse = flyttet overskudd × (t<sub>høy</sub> − t<sub>lav</sub>), der t<sub>lav</sub> nå er løftet til gulvet: 50 000 000 × (22 % − 15 %) = 3 500 000. ✓ Uten gulvet ville besparelsen vært 50 000 000 × (22 % − 5 %) = 8 500 000, og toppskatten er nøyaktig forskjellen: 8 500 000 − 5 000 000 = 3 500 000. ✓ Begge kontrollene er samme regnestykke ordnet på en annen måte, så de fanger regnefeil og viser hvor toppskatten kommer inn, men de kan ikke avsløre en gal forutsetning.</p><p><b>Mekanismen.</b> Gevinsten ved overskuddsflytting er proporsjonal med satsforskjellen, og minimumsskatten krymper forskjellen fra 17 til 7 prosentpoeng. Den fjerner ikke motivet så lenge høyskattelandet ligger over 15 %, og den rører ikke hemmeligholdet, som er det Schjelderup mener paradisene egentlig selger.</p>",
      traps: [
        null,
        "Toppskatten, (15 % − 5 %) × 50 000 000, regnet ut og oppgitt som besparelsen. Den er en kostnad som trekker besparelsen ned, ikke selve besparelsen.",
        "Minimumsskatten oversett: 50 000 000 × (22 % − 5 %) er besparelsen før 15 %-gulvet ble innført.",
        "Bare skattereduksjonen i Norge talt, 50 000 000 × 22 %, som om overskuddet ble skattefritt i Land L. Både skatten der og toppskatten er glemt.",
      ],
    },
    {
      id: "k13-9",
      topic: "Dobbelt bosted",
      points: 3,
      body: "<p>Ingrid har bodd i Norge hele livet. I februar 2026 kjøper hun en leilighet i Land K og melder flytting til Skatteetaten. Mannen og de to barna blir boende i familiens hus i Stavanger, som hun fortsatt eier, og hun fortsetter i jobben hos sin norske arbeidsgiver. Alt arbeidet utføres i Norge; leiligheten i Land K bruker hun i helger og ferier.</p><p>Etter norsk intern rett er hun fortsatt bosatt i Norge, og etter Land Ks interne rett er hun bosatt i Land K. Skatteavtalen mellom Norge og Land K har en bostedsregel som i OECDs mønsteravtale artikkel 4.</p><p>Hvilket utsagn er riktig for inntektsåret 2026?</p>",
      options: [
        "Land K er bostedsstat etter avtalen, fordi hun har meldt flytting dit. Norge kan da bare skattlegge lønnen som kildestat.",
        "Norge er bostedsstat etter avtalen, fordi sentrum for livsinteressene hennes (familie, hus og arbeid) er i Norge. Norge skattlegger hele verdensinntekten hennes, og Land K kan ikke skattlegge lønnen, som er opptjent ved arbeid i Norge.",
        "Land K er bostedsstat etter avtalen, fordi det første kriteriet i bostedsregelen er fast bolig, og hun har kjøpt fast bolig i Land K.",
        "Begge land er bostedsstat, fordi hun er bosatt i begge etter intern rett. Begge kan skattlegge hele lønnen, og avtalen gir bare kredit for skatten i Land K.",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — se konflikten.</b> Ingrid er bosatt i to land etter to lands interne rett, og bosted gir globalskatteplikt. Uten avtale ville begge landene skattlagt hele inntekten hennes. Det var situasjonen i H2022 oppgave 4, der avtalen ikke kunne brukes og resultatet ble trippelbeskatning.</p><p><b>Steg 2 — avtalens bostedsregel utpeker én stat.</b> Regelen i OECDs mønsteravtale artikkel 4 går i fast rekkefølge: fast bolig, så sentrum for livsinteressene (de personlige og økonomiske båndene), så vanlig opphold, så statsborgerskap, og til slutt en gjensidig avtale mellom skattemyndighetene. Ingrid har fast bolig i begge land, huset i Stavanger og leiligheten i Land K, så det første kriteriet avgjør ingenting. Det andre gjør det: mann og barn, huset og arbeidsgiveren er i Norge. Norge er bostedsstat.</p><p><b>Steg 3 — konsekvensen for skatteplikten.</b> Norge beholder globalskatteplikten og skattlegger hele verdensinntekten hennes. Land K er etter avtalen bare kildestat og kan bare skattlegge inntekt som avtalen gir kildestaten rett til. Lønn kan skattlegges av den andre staten bare når arbeidet utføres der, og alt arbeidet utføres i Norge. Land K har derfor ingen rett til å skattlegge lønnen.</p><p><b>Kontroll: hva meldingen og leiligheten betyr.</b> Flyttemeldingen og leilighetskjøpet inngår i vurderingen, men bostedsregelen ser på de faktiske båndene, ikke på hva skattyteren har meldt. Snu faktum og se at regelen snur med det: hadde familien flyttet med og arbeidet blitt utført fra Land K, ville sentrum for livsinteressene og dermed bostedet vært i Land K. ✓</p>",
      traps: [
        "Flyttemeldingen gjort avgjørende. Bostedsregelen ser på de faktiske båndene, ikke på hva som er meldt til Skatteetaten; dette var et av de gale alternativene i H2022 oppgave 4.",
        null,
        "Det første kriteriet lest som avgjørende, men hun har fast bolig i begge land, huset i Stavanger og leiligheten i Land K, og da går regelen videre til sentrum for livsinteressene.",
        "Avtalens bostedsregel oversett. Den finnes nettopp for å løse dobbelt bosted ved å utpeke én stat; at begge skattlegger hele inntekten, er utfallet uten avtale, som i H2022 oppgave 4.",
      ],
    },
    {
      id: "k13-10",
      topic: "Tynn kapitalisering",
      points: 3,
      body: "<p>Et internasjonalt konsern eier et norsk datterselskap med et driftsresultat på kr 40 000 000 i året før renter. Datterselskapet trenger kr 200 000 000 i kapital og kan få dem på to måter: som egenkapital fra morselskapet, eller som lån fra konsernets finansieringsselskap i Land F til 5 % rente [eksempeltall]. Land F skattlegger renteinntekten med 3 % [eksempeltall]. Norsk selskapsskatt er 22 % [dagens regel], og rentene er fullt fradragsberettigede i Norge. Se bort fra rentebegrensningsreglene, kildeskatt på renter og utbytte, og minimumsskatten.</p><p>Hvor mye lavere blir konsernets samlede skatt per år om datterselskapet lånefinansieres i stedet for egenkapitalfinansieres?</p>",
      options: [
        "Kr 0",
        "Kr 1 900 000",
        "Kr 2 200 000",
        "Kr 2 500 000",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — egenkapitalfinansiering.</b> Ingen renter, og utbyttet til morselskapet gir ikke fradrag: skatten i Norge er 40 000 000 × 22 % = <b>8 800 000</b>, og Land F får ingenting.</p><p><b>Steg 2 — konsernintern gjeld.</b> Renten er 200 000 000 × 5 % = 10 000 000. I Norge: (40 000 000 − 10 000 000) × 22 % = 30 000 000 × 22 % = 6 600 000. I Land F: 10 000 000 × 3 % = 300 000. Samlet 6 600 000 + 300 000 = <b>6 900 000</b>.</p><p><b>Steg 3 — forskjellen.</b> 8 800 000 − 6 900 000 = <b>kr 1 900 000</b> per år.</p><p><b>Kontroll med formelen.</b> Flyttet grunnlag × satsforskjell = 10 000 000 × (22 % − 3 %) = 10 000 000 × 19 % = 1 900 000. ✓ Kontrollen er de samme tallene samlet i ett ledd, så den fanger regnefeil, ikke en gal forutsetning. Det er samme formel som ved internprising; bare kanalen er en annen.</p><p><b>Mekanismen.</b> Ingen krone forlater konsernet: renten er en overføring fra ett konsernselskap til et annet. Men den trekkes fra der satsen er 22 % og skattlegges der den er 3 %, så skattegrunnlaget flytter seg. Det er kapittel 9s F′<sub>G</sub> = r mot F′<sub>E</sub> = r/(1 − t) brukt over en landegrense, og det er grunnen til at motmiddelet er rentebegrensningsregler som kutter fradraget for konserninterne renter, altså en fradragsandel A under 1.</p>",
      traps: [
        "Konserninterne renter antatt å gå i null for konsernet. Pengestrømmen gjør det, men skattegrunnlaget gjør det ikke: fradraget gis til 22 % og inntekten skattlegges med 3 %.",
        null,
        "Bare fradraget i Norge talt, 10 000 000 × 22 %; skatten på renteinntekten i Land F, 300 000, er glemt.",
        "Skatten i Land F lagt til besparelsen i stedet for trukket fra: 2 200 000 + 300 000.",
      ],
    },
  ],
};
