/* Kapittel 14 — Sparing og porteføljevalg */
window.EDU_DATA.chapterTasks[14] = {
  minutes: 87,
  tasks: [
    {
      id: "k14-1",
      topic: "Mertons aksjeandel",
      points: 3,
      body: "<p>Marte er pensjonist, så humankapitalen er null og hele formuen hennes er finansiell. Hun skal fordele den mellom et globalt indeksfond og bankkonto. Fondet har forventet avkastning 7 % og standardavvik 25 %, risikofri rente er 2 %, og Martes risikoaversjon er γ = 2 [eksempeltall].</p><p>Hvor stor andel av formuen skal ligge i indeksfondet ifølge Mertons formel?</p>",
      options: ["80 %", "56 %", "40 %", "10 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — telleren er risikopremien.</b> μ − r<sub>f</sub> = 7 % − 2 % = 5 prosentpoeng, altså <b>0,05</b>. Det er meravkastningen over risikofri rente som hører hjemme her, ikke de 7 prosentene.</p><p><b>Steg 2 — variansen, ikke standardavviket.</b> σ = 25 % gir σ<sup>2</sup> = 0,25<sup>2</sup> = <b>0,0625</b>.</p><p><b>Steg 3 — nevneren.</b> γσ<sup>2</sup> = 2 × 0,0625 = <b>0,125</b>.</p><p><b>Steg 4 — andelen.</b> w* = 0,05 / 0,125 = 0,40, altså <b>40 %</b>.</p><p><b>Kontroll:</b> sett svaret tilbake inn. w* × γσ<sup>2</sup> = 0,40 × 2 × 0,0625 = 0,05, som er risikopremien. ✓ Har Marte kr 1 000 000, står kr 400 000 i fondet og kr 600 000 i banken.</p><p>Legg merke til hva som aldri kom inn i regnestykket: tidshorisonten. Mertons formel gir samme andel for ett år og for tjue.</p>",
      traps: [
        "Risikoaversjonen er utelatt fra nevneren: 0,05 / 0,0625. Da er γ satt til 1 uansett hva oppgaven sier.",
        "Forventet avkastning brukt i telleren i stedet for risikopremien: 0,07 / (2 × 0,0625). Risikofri rente må trekkes fra først.",
        null,
        "Standardavviket brukt i nevneren i stedet for variansen: 0,05 / (2 × 0,25). Dette er den dyreste enkeltfeilen i finansdelen.",
      ],
    },
    {
      id: "k14-2",
      topic: "Risikoaversjon",
      points: 3,
      body: "<p>Sondre får oppgitt at meravkastningen i aksjemarkedet over risikofri rente er 6 prosentpoeng, at markedets standardavvik er 20 %, og at risikofri rente er 3 % [eksempeltall]. Hans optimale aksjeandel etter Mertons formel er 50 % av formuen.</p><p>Hvor høy er Sondres risikoaversjon γ?</p>",
      options: ["0,33", "0,60", "1,50", "3,00"],
      answer: 3,
      solution: "<p><b>Steg 1 — snu formelen.</b> w* = (μ − r<sub>f</sub>) / (γσ<sup>2</sup>) gir γ = (μ − r<sub>f</sub>) / (w* × σ<sup>2</sup>).</p><p><b>Steg 2 — variansen.</b> σ = 20 % gir σ<sup>2</sup> = 0,20<sup>2</sup> = <b>0,04</b>.</p><p><b>Steg 3 — nevneren.</b> 0,50 × 0,04 = <b>0,02</b>.</p><p><b>Steg 4 — risikoaversjonen.</b> γ = 0,06 / 0,02 = <b>3,00</b>.</p><p><b>Kontroll:</b> sett γ = 3 inn i formelen igjen: 0,06 / (3 × 0,04) = 0,06 / 0,12 = 0,50, altså 50 %. ✓</p><p>Den risikofrie renten på 3 % er overflødig informasjon her. Meravkastningen er alt formelen trenger, og de tre prosentene står i teksten nettopp for å friste deg til å trekke dem fra en gang til. γ = 3 ligger midt i det empiriske anslaget på 2–5; γ = 1 svarer til logaritmisk nytte.</p>",
      traps: [
        "Brøken er snudd: w* × σ<sup>2</sup> / (μ − r<sub>f</sub>) = 0,02 / 0,06. Det gir 1/γ, ikke γ.",
        "Standardavviket brukt i stedet for variansen: 0,06 / (0,50 × 0,20).",
        "Risikofri rente trukket fra en gang til: (0,06 − 0,03) / 0,02. De 6 prosentpoengene er allerede meravkastningen.",
        null,
      ],
    },
    {
      id: "k14-3",
      topic: "Humankapital",
      points: 3,
      body: "<p>Sara er 28 år, fast ansatt i staten, og lønnen hennes svinger ikke med aksjemarkedet. Finansformuen er kr 600 000, og nåverdien av all framtidig arbeidsinntekt er anslått til kr 4 200 000. Meravkastningen i markedet er 4 prosentpoeng, markedets standardavvik er 20 % og Saras risikoaversjon er γ = 4 [eksempeltall].</p><p>Hun kan låne til risikofri rente. Hvor stor andel av finansformuen på kr 600 000 anbefaler Mertons formel at Sara har i aksjer?</p>",
      options: ["200 %", "100 %", "25 %", "0 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — Mertons andel av totalformuen.</b> σ<sup>2</sup> = 0,04, så w* = 0,04 / (4 × 0,04) = 0,04 / 0,16 = <b>25 %</b>.</p><p><b>Steg 2 — totalformuen.</b> F + H = 600 000 + 4 200 000 = <b>kr 4 800 000</b>. Humankapitalen er den desidert største posten på Saras balanse, og den står ikke i skattemeldingen.</p><p><b>Steg 3 — ønsket aksjebeløp.</b> 0,25 × 4 800 000 = <b>kr 1 200 000</b>.</p><p><b>Steg 4 — hvor beløpet må hentes.</b> Lønnen er trygg, altså β<sub>H</sub> = 0: humankapitalen er et implisitt bankinnskudd og leverer null aksjeeksponering. Hele beløpet må derfor tas i finansformuen: 1 200 000 − 0 = 1 200 000, og andelen av finansformuen er 1 200 000 / 600 000 = <b>200 %</b>.</p><p><b>Kontroll:</b> Sara låner kr 600 000 og plasserer kr 1 200 000 i aksjer. Balansen etterpå: aksjer 1 200 000, humankapital 4 200 000, gjeld 600 000, altså totalformue 4 800 000 og aksjeandel 1 200 000 / 4 800 000 = 25 %, nøyaktig w*. ✓</p><p>Dette er økonomenes eneste forsvar for «100 % aksjer når du er ung». Ikke at aksjer blir tryggere med tiden, men at en stor obligasjonslignende humankapital i ryggen tåler eksponeringen.</p>",
      traps: [
        null,
        "Andelen kappet ved 100 % fordi ønsket aksjebeløp overstiger finansformuen. Formelen anbefaler faktisk lånefinansiering her, og kappingen er et praktisk valg, ikke svaret på spørsmålet.",
        "w* brukt direkte på finansformuen. Merton gjelder totalformuen, og da faller humankapitalen ut av regnestykket.",
        "Humankapitalen behandlet som aksjer i stedet for som obligasjon: 1 200 000 − 4 200 000 er negativt, altså null i aksjer. Saras lønn er trygg, så β<sub>H</sub> er null.",
      ],
    },
    {
      id: "k14-4",
      topic: "Jobbrisiko",
      points: 3,
      body: "<p>Jonas jobber som megler, og bonusen gjør at lønnen svinger med aksjemarkedet: humankapitalens beta mot markedet er β<sub>H</sub> = 0,5. Finansformuen hans er kr 1 000 000 og humankapitalen kr 3 000 000. Meravkastningen er 5 prosentpoeng, markedets standardavvik er 25 % og γ = 2 [eksempeltall].</p><p>Hvor mange kroner av finansformuen skal stå i aksjer?</p>",
      options: ["kr 100 000", "kr 400 000", "kr 1 000 000", "kr 1 600 000"],
      answer: 0,
      solution: "<p><b>Steg 1 — Mertons andel.</b> σ<sup>2</sup> = 0,25<sup>2</sup> = 0,0625, så w* = 0,05 / (2 × 0,0625) = 0,05 / 0,125 = <b>40 %</b>.</p><p><b>Steg 2 — ønsket aksjeeksponering.</b> Totalformuen er 1 000 000 + 3 000 000 = 4 000 000, og 0,40 × 4 000 000 = <b>kr 1 600 000</b>.</p><p><b>Steg 3 — det humankapitalen allerede leverer.</b> β<sub>H</sub> × H = 0,5 × 3 000 000 = <b>kr 1 500 000</b>. Halve humankapitalen oppfører seg som aksjer, enten Jonas vil eller ikke.</p><p><b>Steg 4 — resten hentes i finansformuen.</b> 1 600 000 − 1 500 000 = <b>kr 100 000</b>, altså 10 % av finansformuen. De resterende kr 900 000 skal stå risikofritt.</p><p><b>Kontroll:</b> samlet aksjeeksponering blir 100 000 + 1 500 000 = 1 600 000, som er 40 % av 4 000 000. ✓</p><p>Sammenlign med Sara i forrige oppgave: samme formel, motsatt konklusjon, fordi jobbrisikoen har flyttet aksjeeksponeringen inn i humankapitalen. Det er også argumentet mot å eie aksjer i selskapet du jobber i.</p>",
      traps: [
        null,
        "w* brukt direkte på finansformuen: 0,40 × 1 000 000. Da er verken humankapitalen eller jobbrisikoen med i regnestykket.",
        "Humankapitalen vektet ned med β<sub>H</sub> før den legges til formuen: 0,40 × (1 000 000 + 0,5 × 3 000 000). Betaen hører hjemme i eksponeringen som trekkes fra, ikke i formuen som ganges opp.",
        "β<sub>H</sub> satt til null, altså humankapitalen behandlet som en ren obligasjon. Jonas' lønn svinger med markedet, og halve humankapitalen er derfor allerede aksjer.",
      ],
    },
    {
      id: "k14-5",
      topic: "Diversifisering",
      points: 3,
      body: "<p>Kari har halve porteføljen i aksje A og halve i aksje B [eksempeltall]. Aksje A har standardavvik σ<sub>A</sub> = 30 %, aksje B har σ<sub>B</sub> = 10 %, og korrelasjonen mellom dem er ρ = 0,4.</p><p>Hva er porteføljens standardavvik?</p>",
      options: ["17,61 %", "20,00 %", "35,21 %", "47,43 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — de to kvadrerte leddene.</b> 0,5<sup>2</sup> × 0,30<sup>2</sup> = 0,25 × 0,09 = <b>0,0225</b> og 0,5<sup>2</sup> × 0,10<sup>2</sup> = 0,25 × 0,01 = <b>0,0025</b>. Merk at både vektene og standardavvikene kvadreres.</p><p><b>Steg 2 — krysseleddet.</b> Det inneholder kovariansen ρσ<sub>A</sub>σ<sub>B</sub>, ikke ρ alene: 2 × 0,5 × 0,5 × 0,4 × 0,30 × 0,10 = 0,5 × 0,012 = <b>0,0060</b>.</p><p><b>Steg 3 — variansen.</b> 0,0225 + 0,0025 + 0,0060 = <b>0,0310</b>.</p><p><b>Steg 4 — standardavviket.</b> √0,0310 = 0,17607, altså <b>17,61 %</b>.</p><p><b>Kontroll:</b> så lenge ρ &lt; 1 må porteføljens standardavvik ligge under det vektede snittet av de to standardavvikene, 0,5 × 30 % + 0,5 × 10 % = 20 %. Og uten shortsalg kan det ikke komme under 10 %, siden minimum-varians-vekten i A er negativ med disse tallene. Bare ett alternativ ligger mellom 10 % og 20 %. ✓</p><p>De 2,39 prosentpoengene under det vektede snittet er diversifiseringsgevinsten. Forventningen ville derimot vært et rent vektet snitt; det er nettopp den forskjellen hele porteføljeteorien lever av.</p>",
      traps: [
        null,
        "Standardavvikene veid sammen direkte: 0,5 × 30 % + 0,5 × 10 %. Det er svaret bare når ρ = 1, altså når det ikke finnes noen diversifiseringsgevinst.",
        "Kvadratene på vektene glemt: 0,09 + 0,01 + 2 × 0,4 × 0,30 × 0,10. Da blir porteføljen mer risikabel enn aksje A alene, som er umulig.",
        "Krysseleddet regnet med ρ alene i stedet for ρσ<sub>A</sub>σ<sub>B</sub>: 0,0225 + 0,0025 + 2 × 0,25 × 0,4. Kovariansen krever begge standardavvikene.",
      ],
    },
    {
      id: "k14-6",
      topic: "Sparerate",
      points: 3,
      body: "<p>Ida og Jonas er begge 35 år og sparer ved utgangen av hvert år i 30 år [eksempeltall]. Ida setter av kr 50 000 i året og får 4 % årlig realavkastning. Jonas setter av kr 35 000 i året, men velger en portefølje med 6 % forventet realavkastning.</p><p>Hvem sitter igjen med mest etter 30 år, og hvor stor er forskjellen?</p>",
      options: [
        "Jonas, med kr 1 165 569 mer",
        "Jonas, med kr 38 852 mer",
        "Ida, med kr 450 000 mer",
        "Ida, med kr 37 210 mer",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — riktig verktøy.</b> En fast årlig innbetaling ved utgangen av året vokser til innbetalingen ganget med annuitetsfaktoren [(1 + r)<sup>n</sup> − 1] / r.</p><p><b>Steg 2 — Ida.</b> 1,04<sup>30</sup> = 3,2433975, faktoren blir (3,2433975 − 1) / 0,04 = 56,084938, og sluttformuen 50 000 × 56,084938 = <b>kr 2 804 247</b>.</p><p><b>Steg 3 — Jonas.</b> 1,06<sup>30</sup> = 5,7434912, faktoren blir (5,7434912 − 1) / 0,06 = 79,058186, og sluttformuen 35 000 × 79,058186 = <b>kr 2 767 037</b>.</p><p><b>Steg 4 — differansen.</b> 2 804 247 − 2 767 037 = <b>kr 37 210</b> i Idas favør.</p><p><b>Kontroll, delt opp i innskudd og renter:</b> Ida har betalt inn 1 500 000 og Jonas 1 050 000, altså kr 450 000 mer. Rentene er 1 304 247 for Ida og 1 717 037 for Jonas, altså kr 412 790 mer for Jonas. 450 000 − 412 790 = 37 210. ✓</p><p>Poenget er størrelsesordenen. Ida sparer 42,9 % mer i året, Jonas får 2 prosentpoeng høyere avkastning hvert eneste år i tretti år, og de to veier nesten nøyaktig like tungt. Forskjellen er at sparebeløpet er noe du styrer selv, mens avkastningen bare er et anslag.</p>",
      traps: [
        "Hele det innbetalte beløpet behandlet som ett innskudd i år 0: 1 500 000 × 1,04<sup>30</sup> mot 1 050 000 × 1,06<sup>30</sup>. Pengene kommer inn litt hvert år og forrentes derfor langt kortere.",
        "Bare ett års innskudd forrentet i tretti år: 50 000 × 1,04<sup>30</sup> mot 35 000 × 1,06<sup>30</sup>. Annuitetsfaktoren mangler, og med den de 29 andre innbetalingene.",
        "Renters rente utelatt helt. Differansen 450 000 er bare forskjellen i innbetalt beløp, 1 500 000 mot 1 050 000.",
        null,
      ],
    },
    {
      id: "k14-7",
      topic: "Mertons drivere",
      points: 3,
      body: "<p>Kari har regnet ut at hennes optimale aksjeandel etter Mertons formel er 50 % av totalformuen. Da anslo hun risikopremien μ − r<sub>f</sub> til 6 prosentpoeng og markedets standardavvik σ til 20 % [eksempeltall].</p><p>Etter en rolig periode justerer hun anslagene: premien er nå 4,5 prosentpoeng og standardavviket 15 %. Risikoaversjonen γ er den samme som før.</p><p>Hva blir Karis nye optimale aksjeandel w*? Rund av til én desimal.</p>",
      options: [
        "37,5 %",
        "50,0 %",
        "66,7 %",
        "88,9 %",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — finn γ fra det gamle valget.</b> Snu formelen: γ = (μ − r<sub>f</sub>) / (w* × σ<sup>2</sup>) = 0,06 / (0,50 × 0,20<sup>2</sup>) = 0,06 / 0,02 = <b>3</b>.</p><p><b>Steg 2 — den nye variansen.</b> σ = 15 % gir σ<sup>2</sup> = 0,15<sup>2</sup> = <b>0,0225</b>.</p><p><b>Steg 3 — den nye andelen.</b> w* = 0,045 / (3 × 0,0225) = 0,045 / 0,0675 = 0,6667, altså <b>66,7 %</b>.</p><p><b>Steg 4 — de to driverne hver for seg.</b> Premien står i telleren og faller til 4,5/6 = 0,75 av det gamle; alene ville det gitt 50 % × 0,75 = 37,5 %. Variansen står i nevneren og faller til 0,0225/0,04 = 0,5625 av det gamle, så andelen ganges med 1/0,5625 = 1,7778. Samlet: 50 % × 0,75 × 1,7778 = <b>66,7 %</b>.</p><p><b>Kontroll:</b> to veier gir samme tall, via γ = 3 i steg 3 og via forholdstallene i steg 4. Sett også svaret tilbake: 0,6667 × 3 × 0,0225 = 0,045, som er den nye premien. ✓</p><p>Poenget er asymmetrien. Premien falt med en firedel og trekker andelen ned med en firedel. Standardavviket falt også med en firedel, men det står i annen potens, og det løfter andelen med 78 %. Volatiliteten er den sterkeste driveren i formelen.</p>",
      traps: [
        "Bare premieendringen er tatt med: 50 % × 4,5/6 = 37,5 %. Variansen falt også, og siden den står i nevneren, trekker den andelen opp.",
        "Standardavvikene brukt i stedet for variansene: 50 % × 0,75 × 20/15 = 50,0 %. Da ser det ut som om endringene opphever hverandre, men σ står i annen potens i formelen.",
        null,
        "Bare volatilitetsendringen er tatt med: 50 % × (20/15)<sup>2</sup> = 88,9 %. Premien falt fra 6 til 4,5 prosentpoeng, og det trekker andelen ned med en firedel.",
      ],
    },
    {
      id: "k14-8",
      topic: "Livsløpet",
      points: 3,
      body: "<p>Ingrid er 35 år og har en trygg jobb i offentlig sektor, så humankapitalen hennes regnes som risikofri. Finansformuen er kr 2 000 000 og humankapitalen kr 4 000 000. Risikopremien er 3,6 prosentpoeng, markedets standardavvik 20 % og Ingrids risikoaversjon γ = 3 [eksempeltall]. Hun følger Mertons formel for andelen av totalformuen i aksjer.</p><p>Tjue år senere er finansformuen vokst til kr 4 000 000, mens humankapitalen er redusert til kr 1 000 000 og fortsatt er risikofri. Markedsanslagene og γ er uendret.</p><p>Hvor stor andel av <b>finansformuen</b> bør Ingrid ha i aksjer ved 55 år, og hvorfor?</p>",
      options: [
        "30 %, fordi Mertons andel ikke avhenger av alder",
        "37,5 %, lavere enn ved 35 år fordi humankapitalen er mindre verdt",
        "37,5 %, lavere enn ved 35 år fordi aksjer er mindre risikable jo lengre tidshorisonten er",
        "45 %, fordi hun beholder aksjebeløpet på kr 1 800 000 fra hun var 35",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — Mertons andel av totalformuen.</b> σ<sup>2</sup> = 0,20<sup>2</sup> = 0,04, så w* = 0,036 / (3 × 0,04) = 0,036 / 0,12 = <b>30 %</b>. Den gjelder ved begge aldre.</p><p><b>Steg 2 — ved 35 år.</b> Totalformue 2 000 000 + 4 000 000 = 6 000 000, aksjebeløp 0,30 × 6 000 000 = kr 1 800 000. Humankapitalen er et implisitt bankinnskudd og gir ingen aksjeeksponering, så hele beløpet står i finansformuen: 1 800 000 / 2 000 000 = <b>90 %</b>.</p><p><b>Steg 3 — ved 55 år.</b> Totalformue 4 000 000 + 1 000 000 = 5 000 000, aksjebeløp 0,30 × 5 000 000 = kr 1 500 000, og andelen av finansformuen 1 500 000 / 4 000 000 = <b>37,5 %</b>.</p><p><b>Steg 4 — hvorfor andelen falt.</b> w* er uendret: 30 % av alt hun eier. Det som har skjedd, er at den trygge posten utenfor finansformuen har krympet fra 4 til 1 million, mens finansformuen har vokst. Når mindre av det trygge ligger i humankapitalen, må mer av det ligge i finansformuen, og aksjeandelen av finansformuen faller fra 90 % til 37,5 %.</p><p><b>Kontroll:</b> balansen ved 55 år er aksjer 1 500 000, bank 2 500 000 og humankapital 1 000 000, til sammen 5 000 000. Aksjer delt på alt er 1 500 000 / 5 000 000 = 30 % = w*. ✓ Kontrollen er en identitet, men den fanger nevnerfeilen: bruker du w* på finansformuen, blir andelen av alt noe annet enn 30 %.</p><p>Dette er H2025 oppgave 11.4 med tall på. Der godtok sensor også «lik aksjeandel», fordi spørsmålet ikke sa hvilken nevner som mentes. Her står det finansformuen, og da er 37,5 % det eneste svaret. Tidshorisonten står ikke i formelen i det hele tatt.</p>",
      traps: [
        "w* brukt direkte på finansformuen, som om humankapitalen på kr 1 000 000 ikke fantes. Da blir totalporteføljen 1 200 000 / 5 000 000 = 24 % aksjer, under w*.",
        null,
        "Riktig tall, gal begrunnelse. Tidshorisonten står ikke i Mertons formel, og kurset avviser at aksjer blir tryggere av å eies lenge; hele nedgangen kommer av at humankapitalen har krympet.",
        "Aksjebeløpet fra 35 år holdt fast: 1 800 000 / 4 000 000 = 45 %. Beløpet skal være w* av dagens totalformue, 0,30 × 5 000 000 = 1 500 000. I H2022 oppgave 7 sto beløpet stille bare fordi totalformuen var den samme.",
      ],
    },
    {
      id: "k14-9",
      topic: "Aksjelignende lønn",
      points: 3,
      body: "<p>Mats er 58 år og aksjemegler. Lønnen hans følger aksjemarkedet én-til-én, så humankapitalens beta mot markedet er β<sub>H</sub> = 1. Finansformuen er kr 3 000 000, og humankapitalen, som er blitt liten fordi han snart går av, er kr 1 000 000. Risikopremien er 4,5 prosentpoeng, markedets standardavvik 15 % og Mats' risikoaversjon γ = 4 [eksempeltall].</p><p>Hvor stor andel av finansformuen bør Mats ha i aksjer ifølge Mertons formel? Rund av til én desimal.</p>",
      options: [
        "0 %",
        "25,0 %",
        "33,3 %",
        "50,0 %",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — Mertons andel.</b> σ<sup>2</sup> = 0,15<sup>2</sup> = 0,0225, så w* = 0,045 / (4 × 0,0225) = 0,045 / 0,09 = <b>50 %</b> av totalformuen.</p><p><b>Steg 2 — ønsket aksjeeksponering.</b> Totalformuen er 3 000 000 + 1 000 000 = 4 000 000, og 0,50 × 4 000 000 = <b>kr 2 000 000</b>.</p><p><b>Steg 3 — det humankapitalen allerede leverer.</b> β<sub>H</sub> × H = 1 × 1 000 000 = <b>kr 1 000 000</b>. Lønnen svinger som aksjer, så hele humankapitalen teller som aksjeeksponering.</p><p><b>Steg 4 — resten hentes i finansformuen.</b> 2 000 000 − 1 000 000 = kr 1 000 000 i aksjer, altså 1 000 000 / 3 000 000 = <b>33,3 %</b> av finansformuen. De andre kr 2 000 000 står risikofritt.</p><p><b>Kontroll:</b> samlet aksjeeksponering er 1 000 000 i finansformuen pluss 1 000 000 i humankapitalen, til sammen 2 000 000 = 50 % av 4 000 000 = w*. ✓ Kontrollen er en identitet, men den avslører nevnerfeilen: 50 % av finansformuen gir 62,5 % av alt.</p><p>Regelen «β<sub>H</sub> = 1 gir 0 % aksjer» fra H2025 oppgave 11.3 gjelder bare når humankapitalen alene dekker hele ønsket eksponering. Der var F = H og w* = 50 %, så humankapitalen på 1 million dekket nøyaktig ønsket beløp. Hos Mats er humankapitalen for liten til det, og differansen må ligge i finansformuen.</p>",
      traps: [
        "Regelen «β<sub>H</sub> = 1 gir 0 %» brukt uten å regne. Den gjelder bare når β<sub>H</sub> × H er minst like stor som w*(F + H); her dekker humankapitalen 1 000 000 av 2 000 000.",
        "Riktig kronebeløp, men delt på totalformuen: 1 000 000 / 4 000 000 = 25 %. Spørsmålet gjelder andelen av finansformuen på kr 3 000 000.",
        null,
        "w* brukt direkte på finansformuen: 0,50 × 3 000 000 = 1 500 000. Da kommer humankapitalens aksjeeksponering i tillegg, og totalporteføljen får (1 500 000 + 1 000 000) / 4 000 000 = 62,5 % aksjer.",
      ],
    },
    {
      id: "k14-10",
      topic: "ln-nytte",
      points: 3,
      body: "<p>Eirik skal plassere kr 400 000 i 15 år og må velge ett av to alternativer fullt ut [eksempeltall, se bort fra skatt].</p><p><b>Bank:</b> sikker rente 3 % per år.</p><p><b>Aksjefond:</b> med sannsynlighet 40 % blir det gode tider, og fondet er verdt kr 1 400 000 om 15 år. Med sannsynlighet 60 % blir det dårlige tider, og fondet er verdt kr 300 000.</p><p>Eirik har nyttefunksjonen U(W) = ln W, der W er sluttverdien. Hvilket alternativ velger han, og hvilke tall avgjør valget?</p>",
      options: [
        "Aksjer: forventet sluttverdi kr 740 000 er høyere enn bankens kr 623 187",
        "Bank: nytten 13,343 er høyere enn 13,228 for aksjer",
        "Aksjer: nytten 13,536 er høyere enn 13,343 for bank",
        "Aksjer: nytten 13,228 er høyere enn 12,899 for bank",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — bankens sluttverdi.</b> 400 000 × 1,03<sup>15</sup> = 400 000 × 1,557967 = <b>kr 623 187</b>.</p><p><b>Steg 2 — forventet sluttverdi i fondet.</b> 0,40 × 1 400 000 + 0,60 × 300 000 = 560 000 + 180 000 = <b>kr 740 000</b>. Det er mer enn banken, men det er kroner, ikke nytte.</p><p><b>Steg 3 — nytten av banken.</b> Sikkert utfall, så nytten er ln 623 187 = <b>13,3426</b>.</p><p><b>Steg 4 — forventet nytte av fondet.</b> Hvert utfall gjennom nyttefunksjonen først, så vekt: 0,40 × ln 1 400 000 + 0,60 × ln 300 000 = 0,40 × 14,1520 + 0,60 × 12,6115 = 5,6608 + 7,5669 = <b>13,2277</b>.</p><p><b>Steg 5 — valget.</b> 13,3426 &gt; 13,2277, så Eirik velger <b>banken</b>.</p><p><b>Kontroll i kroner:</b> sikkerhetsekvivalenten til fondet er tallet med logaritme 13,2277, altså e<sup>13,2277</sup> ≈ kr 555 551. Det er under bankens sikre 623 187, så banken vinner også målt i sikre kroner. ✓ Kontrollen kan ikke gi et annet valg enn nyttetallene, fordi e<sup>x</sup> er stigende, men den oversetter nytteforskjellen til kroner. Risikopremien er 740 000 − 555 551 = kr 184 449: så mye forventet sluttverdi er Eirik villig til å gi opp for å slippe risikoen.</p><p>Oppsettet er det samme som i H2022 oppgave 5, med andre tall: forventet sluttverdi peker mot aksjer, forventet nytte mot bank. 60 % sjanse for å ende under innskuddet veier tyngre i ln-nytte enn i kroner.</p>",
      traps: [
        "Forventet formue sammenlignet i stedet for forventet nytte. Det er valget til en risikonøytral investor; med ln-nytte må hvert utfall gjennom nyttefunksjonen før du vekter.",
        null,
        "Sannsynlighetene byttet om: 0,60 × ln 1 400 000 + 0,40 × ln 300 000 = 13,536. Det er de gode tidene som har 40 %.",
        "Innskuddet brukt som bankens sluttverdi: ln 400 000 = 12,899. Banken forrenter pengene i 15 år, til kr 623 187.",
      ],
    },
    {
      id: "k14-11",
      topic: "Subjektive sannsynligheter",
      points: 3,
      body: "<p>Eirik skal plassere kr 400 000 i 15 år og må velge ett av to alternativer fullt ut [eksempeltall, se bort fra skatt]. Banken gir sikker rente 3 % per år, altså kr 623 187 etter 15 år. Et aksjefond er verdt kr 1 400 000 om 15 år i gode tider og kr 300 000 i dårlige tider. Eirik har nyttefunksjonen U(W) = ln W, der W er sluttverdien.</p><p>Med den objektive sannsynligheten for gode tider, 40 %, velger Eirik banken. En venn mener sannsynligheten er høyere.</p><p>Hvor høy må Eiriks subjektive sannsynlighet for gode tider minst være for at han skal foretrekke aksjefondet? Rund av til én desimal.</p>",
      options: [
        "29,4 %",
        "47,5 %",
        "52,5 %",
        "Ingen sannsynlighet under 100 % er nok, for med ln-nytte velger han alltid banken",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — banken er ankeret.</b> ln 623 187 = <b>13,3426</b>. Den avhenger ikke av noen sannsynlighet.</p><p><b>Steg 2 — sluttverdiene står stille.</b> En annen sannsynlighet endrer vektene, ikke utfallene. Fondet er fortsatt verdt 1 400 000 eller 300 000, med nytte ln 1 400 000 = 14,1520 og ln 300 000 = 12,6115. Det var hele poenget i H2022 oppgave 5.4.</p><p><b>Steg 3 — indifferensbetingelsen.</b> Sett forventet nytte av fondet lik bankens: p × 14,1520 + (1 − p) × 12,6115 = 13,3426. Det gir p × (14,1520 − 12,6115) = 13,3426 − 12,6115, altså p × 1,5405 = 0,7311 og p = 0,4746, <b>47,5 %</b>.</p><p><b>Steg 4 — tolkning.</b> Tror Eirik på gode tider med mer enn 47,5 % sannsynlighet, velger han fondet; under det, banken.</p><p><b>Kontroll:</b> sett inn en sannsynlighet på hver side av terskelen. Ved 50 %: 0,5 × 14,1520 + 0,5 × 12,6115 = 13,3818 &gt; 13,3426, altså fondet. ✓ Ved 40 %: 0,40 × 14,1520 + 0,60 × 12,6115 = 13,2277 &lt; 13,3426, altså banken, som i oppgaveteksten. ✓</p><p>Sammenlign med terskelen for en risikonøytral investor, 29,4 %. Avstanden opp til 47,5 % er prisen på risikoen målt i sannsynlighet. Og legg merke til hvor lite som skal til: en venn som får Eirik til å tro på 50 % i stedet for 40 %, snur valget.</p>",
      traps: [
        "Terskelen for en risikonøytral investor: p × 1 400 000 + (1 − p) × 300 000 = 623 187 gir p = 323 187 / 1 100 000 = 29,4 %. Med ln-nytte kreves mer, fordi det dårlige utfallet veier tyngre i nytte enn i kroner.",
        null,
        "Ligningen løst for sannsynligheten for dårlige tider: 1 − 0,4746 = 52,5 %. Det er sannsynligheten for gode tider som må over terskelen.",
        "ln-nytte gir risikoaversjon, ikke risikoskrekk. Ved 50 % gir fondet 13,3818 mot bankens 13,3426, så Eirik velger aksjer når oddsen er god nok.",
      ],
    },
    {
      id: "k14-12",
      topic: "Tapsaversjon",
      points: 3,
      body: "<p>Hanne skal plassere kr 500 000 i 10 år, enten alt i bank til sikker rente 2 % per år, eller alt i et aksjefond. Fondet er verdt kr 1 150 000 om 10 år med sannsynlighet 50 % og kr 360 000 med sannsynlighet 50 % [eksempeltall, se bort fra skatt]. Nyttefunksjonen er U(W) = ln W, der W er sluttverdien.</p><p>Hanne er tapsavers. Referansepunktet er innskuddet på kr 500 000. Nytten av et utfall under referansepunktet ganges med 0,96, mens utfall over referansepunktet får vekt 1.</p><p>Hvilket alternativ velger Hanne, og hvilke nyttetall avgjør valget?</p>",
      options: [
        "Aksjer: nytten 13,375 er høyere enn 13,320 for bank",
        "Aksjer: nytten 13,641 er høyere enn 13,320 for bank",
        "Bank: nytten 13,320 er høyere enn 13,095 for aksjer",
        "Bank: nytten 13,320 er høyere enn 13,119 for aksjer",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — banken.</b> 500 000 × 1,02<sup>10</sup> = 500 000 × 1,218994 = kr 609 497. Det er over referansepunktet, så vekten er 1: ln 609 497 = <b>13,3204</b>.</p><p><b>Steg 2 — utfallene i fondet, og hvilket som er tap.</b> kr 1 150 000 er over 500 000, altså gevinst med vekt 1: ln 1 150 000 = <b>13,9553</b>. kr 360 000 er under 500 000, altså tap: ln 360 000 = 12,7939, vektet 0,96 × 12,7939 = <b>12,2821</b>.</p><p><b>Steg 3 — uten tapsaversjon, som referanse.</b> (13,9553 + 12,7939) / 2 = 13,3746 &gt; 13,3204. En vanlig ln-investor ville valgt fondet.</p><p><b>Steg 4 — med tapsaversjon.</b> (13,9553 + 12,2821) / 2 = <b>13,1187</b> &lt; 13,3204. Hanne velger <b>banken</b>.</p><p><b>Kontroll:</b> tapsaversjonen skal trekke forventet nytte ned med sannsynligheten for tap × (1 − vekten) × nytten i tapsutfallet: 0,5 × 0,04 × 12,7939 = 0,2559, og 13,3746 − 0,2559 = 13,1187. ✓ Samme tall, annen vei. Kontrollen er en identitet, så den fanger regnefeil, ikke at vekten er lagt på feil utfall; det må du sjekke i steg 2.</p><p>Metoden er den samme som i H2022 oppgave 5.6, der vekten var 1/1,03 og bare forsterket et valg av bank som allerede var tatt. Her snur den valget, og det er grunnen til at alle fire alternativene må regnes: to sier bank, to sier aksjer, og bare ett tallpar stemmer.</p>",
      traps: [
        "Tapsaversjonen ikke brukt: (13,9553 + 12,7939) / 2 = 13,375. Det er valget til en vanlig ln-investor, dratt videre uten den nye vekten.",
        "Vekten snudd: tapsnytten delt på 0,96 i stedet for ganget, (13,9553 + 12,7939 / 0,96) / 2 = 13,641. Da gjør tapet utfallet bedre, det motsatte av tapsaversjon.",
        "Vekten lagt på feil utfall: (0,96 × 13,9553 + 12,7939) / 2 = 13,095. Det er utfallet under referansepunktet, kr 360 000, som skal nedvektes.",
        null,
      ],
    },
    {
      id: "k14-13",
      topic: "Negativ korrelasjon",
      points: 3,
      body: "<p>Nora har 70 % av sparepengene i et aksjefond og 30 % i et obligasjonsfond [eksempeltall]. Aksjefondet har forventet avkastning 8 % og standardavvik 18 %. Obligasjonsfondet har forventet avkastning 3 % og standardavvik 6 %. Korrelasjonen mellom de to fondene er ρ = −0,2.</p><p>Hva er porteføljens standardavvik? Rund av til to desimaler.</p>",
      options: [
        "10,90 %",
        "12,37 %",
        "13,08 %",
        "14,40 %",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — de to kvadrerte leddene.</b> 0,7<sup>2</sup> × 0,18<sup>2</sup> = 0,49 × 0,0324 = <b>0,015876</b> og 0,3<sup>2</sup> × 0,06<sup>2</sup> = 0,09 × 0,0036 = <b>0,000324</b>.</p><p><b>Steg 2 — krysleddet, med fortegn.</b> 2 × 0,7 × 0,3 × (−0,2) × 0,18 × 0,06 = 0,42 × (−0,00216) = <b>−0,0009072</b>. Det er negativt fordi fondene har en svak tendens til å trekke i hver sin retning.</p><p><b>Steg 3 — variansen.</b> 0,015876 + 0,000324 − 0,0009072 = <b>0,0152928</b>.</p><p><b>Steg 4 — standardavviket.</b> √0,0152928 = 0,12366, altså <b>12,37 %</b>.</p><p><b>Kontroll:</b> uten korrelasjon (ρ = 0) er variansen 0,015876 + 0,000324 = 0,0162 og standardavviket 12,73 %. Negativ korrelasjon skal gi lavere risiko enn det, og 12,37 % &lt; 12,73 %. ✓ Og alt under ρ = 1 skal ligge under det vektede snittet 14,40 %. ✓</p><p>Forventet avkastning er et rent vektet snitt: 0,7 × 8 % + 0,3 × 3 % = 6,5 %. Mot alt i aksjefondet faller forventningen med 19 % (fra 8 til 6,5), mens standardavviket faller med 31 % (fra 18 til 12,37). Det er diversifiseringsgevinsten.</p>",
      traps: [
        "Vektene utelatt i krysleddet: 0,015876 + 0,000324 + 2 × (−0,2) × 0,18 × 0,06 = 0,01188, og √0,01188 = 10,90 %. Krysleddet skal ha med 2 × 0,7 × 0,3.",
        null,
        "Minustegnet på korrelasjonen mistet: 0,0162 + 0,0009072 = 0,0171072, og √0,0171072 = 13,08 %. Negativ korrelasjon senker risikoen, den øker den ikke.",
        "Standardavvikene veid sammen: 0,7 × 18 % + 0,3 × 6 % = 14,40 %. Det er svaret bare når ρ = 1.",
      ],
    },
    {
      id: "k14-14",
      topic: "Kapitalmarkedslinjen",
      points: 3,
      body: "<p>Risikofri rente er 2 %, og du kan både spare og låne til den renten. Markedsporteføljen, i praksis et globalt indeksfond, har forventet avkastning 7 % og standardavvik 15 % [eksempeltall].</p><p>Petter vil ha forventet avkastning 10 %. Han følger teorien og tar risikoen ved å låne til risikofri rente og plassere mer enn egenkapitalen i markedsporteføljen.</p><p>Hvilket standardavvik får Petters portefølje? Rund av til to desimaler.</p>",
      options: [
        "17,14 %",
        "18,97 %",
        "21,43 %",
        "24,00 %",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — Sharpe-forholdet.</b> Stigningstallet på kapitalmarkedslinjen er meravkastning per enhet risiko: (7 % − 2 %) / 15 % = <b>0,3333</b>.</p><p><b>Steg 2 — les av linjen.</b> E(r<sub>p</sub>) = r<sub>f</sub> + 0,3333 × σ<sub>p</sub>, så 10 % = 2 % + 0,3333 × σ<sub>p</sub>, og σ<sub>p</sub> = 8 % / 0,3333 = <b>24,00 %</b>.</p><p><b>Steg 3 — samme svar via vektene.</b> Andelen i markedsporteføljen er w = (10 − 2) / (7 − 2) = 8/5 = <b>1,6</b>: Petter plasserer 160 % av egenkapitalen i fondet og låner 60 %. Bankleddet har verken varians eller kovarians, så standardavviket skaleres lineært: 1,6 × 15 % = <b>24,00 %</b>.</p><p><b>Kontroll:</b> forventet avkastning med disse vektene er 1,6 × 7 % − 0,6 × 2 % = 11,2 % − 1,2 % = 10,0 %, som var målet. ✓ Og σ<sub>p</sub> / σ<sub>M</sub> − 1 = 24/15 − 1 = 0,6 er den lånte andelen, som i steg 3. ✓</p><p>Dette er regnestykket bak H2025 oppgave 15: mer risiko enn markedet skaffer du ved å låne og gire markedsporteføljen, ikke ved å kjøpe mer volatile enkeltaksjer.</p>",
      traps: [
        "Sharpe-forholdet regnet uten å trekke fra risikofri rente: 7/15 = 0,4667, og så 8 / 0,4667 = 17,14 %. Stigningstallet er meravkastning per enhet risiko.",
        "Variansen skalert lineært med vekten: σ<sub>p</sub><sup>2</sup> = 1,6 × 0,0225, altså σ<sub>p</sub> = 15 % × √1,6 = 18,97 %. Det er standardavviket som skaleres med vekten; variansen skaleres med vekten i annen.",
        "Lånekostnaden glemt: vekten regnet som 10/7 = 1,4286 og σ<sub>p</sub> = 1,4286 × 15 % = 21,43 %, som om lånet var gratis. Hver lånte krone koster 2 %, så vekten er (10 − 2) / (7 − 2) = 1,6.",
        null,
      ],
    },
    {
      id: "k14-15",
      topic: "Sharpe-forholdet",
      points: 3,
      body: "<p>Risikofri rente er 2 %, og du kan både spare og låne til den renten. Et globalt indeksfond har forventet avkastning 7,5 % og standardavvik 15 %. Et aktivt forvaltet fond har forventet avkastning 9,5 % og standardavvik 22 %. Begge tallene er etter kostnader [eksempeltall].</p><p>Du ønsker en portefølje med standardavvik 22 %. Hva gir høyest forventet avkastning ved det risikonivået?</p>",
      options: [
        "Det aktive fondet: 9,5 % mot 7,5 % i indeksfondet",
        "Det aktive fondet: et giret indeksfond med standardavvik 22 % gir bare 8,07 %",
        "Et giret indeksfond: 10,07 % mot 9,5 % i det aktive fondet",
        "Et giret indeksfond: 11,00 % mot 9,5 % i det aktive fondet",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — Sharpe-forholdene.</b> Indeksfondet: (7,5 − 2) / 15 = <b>0,3667</b>. Det aktive fondet: (9,5 − 2) / 22 = <b>0,3409</b>. Indeksfondet gir mer meravkastning per enhet risiko.</p><p><b>Steg 2 — gir indeksfondet opp til 22 %.</b> Vekten i fondet er 22 / 15 = 1,4667, altså 146,67 % av egenkapitalen i fondet og 46,67 % lånt.</p><p><b>Steg 3 — forventet avkastning.</b> E(r<sub>p</sub>) = 2 % + 1,4667 × 5,5 % = 2 % + 8,07 % = <b>10,07 %</b>. Samme tall fra linjen: 2 % + 0,3667 × 22 % = 10,07 %.</p><p><b>Steg 4 — sammenlign.</b> 10,07 % mot 9,5 % i det aktive fondet ved samme risiko. Det girede indeksfondet vinner.</p><p><b>Kontroll:</b> regn vektene ut hver for seg. 1,4667 × 7,5 % − 0,4667 × 2 % = 11,00 % − 0,93 % = 10,07 %. ✓ Det er en identitet, men oppstillingen viser lånekostnaden eksplisitt, og det er den alternativ D mangler.</p><p>Mekanismen er separasjonsteoremet: finn porteføljen med høyest Sharpe-forhold, og la risikoviljen bare bestemme hvor mye du låner eller sparer ved siden av. Det aktive fondet ligger under kapitalmarkedslinjen gjennom indeksfondet, selv om det har høyest forventet avkastning av de to.</p>",
      traps: [
        "Forventet avkastning sammenlignet uten å justere for risiko. Indeksfondets 7,5 % gjelder ved 15 % standardavvik; giret opp til 22 % gir det mer.",
        "Risikofri rente glemt som startpunkt: 1,4667 × 5,5 % = 8,07 %. Kapitalmarkedslinjen starter i r<sub>f</sub> = 2 %, og premien kommer oppå den.",
        null,
        "Lånekostnaden glemt: 7,5 % × 22/15 = 11,00 %, som om de lånte 46,67 % var gratis. Renten på lånet, 0,4667 × 2 % = 0,93 prosentpoeng, skal trekkes fra.",
      ],
    },
    {
      id: "k14-16",
      topic: "Gebyrer over tid",
      points: 3,
      body: "<p>Lise setter kr 200 000 i fond og lar pengene stå i 25 år uten flere innskudd [eksempeltall, se bort fra skatt]. Hun kan velge et indeksfond med årlig gebyr 0,2 % eller et aktivt fond med årlig gebyr 1,5 %. Begge fondene gir 7 % årlig avkastning før gebyr, og gebyret trekkes fra avkastningen hvert år.</p><p>Hvor mye mindre har Lise etter 25 år hvis hun velger det aktive fondet? Rund av til hele kroner.</p>",
      options: [
        "kr 65 000",
        "kr 159 801",
        "kr 273 206",
        "kr 322 808",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — nettoavkastningen.</b> Indeksfondet: 7 % − 0,2 % = 6,8 %. Det aktive fondet: 7 % − 1,5 % = 5,5 %.</p><p><b>Steg 2 — indeksfondet.</b> 200 000 × 1,068<sup>25</sup> = 200 000 × 5,179422 = <b>kr 1 035 884</b>.</p><p><b>Steg 3 — det aktive fondet.</b> 200 000 × 1,055<sup>25</sup> = 200 000 × 3,813392 = <b>kr 762 678</b>.</p><p><b>Steg 4 — differansen.</b> 1 035 884 − 762 678 = <b>kr 273 206</b>.</p><p><b>Kontroll:</b> forholdet mellom sluttverdiene er (1,055 / 1,068)<sup>25</sup> = 0,7363, og 1 − 0,7363 = 26,4 %. 26,4 % av 1 035 884 er 273 206. ✓</p><p>En gebyrforskjell på 1,3 prosentpoeng i året blir altså over en firedel av sluttverdien, fordi hver krone som går til gebyr, mangler i grunnlaget for all senere avkastning. Og det aktive fondet måtte slått markedet med 1,3 prosentpoeng i året før kostnader bare for å stå likt, noe Forbrukerrådet fant at norske aktive fond ikke gjorde for globale, europeiske eller nordiske aksjer (H2025 oppgave 16).</p>",
      traps: [
        "Gebyrforskjellen regnet av startbeløpet hvert år, uten vekst: 200 000 × 1,3 % × 25 = 65 000. Både saldoen og det tapte vokser med rentes rente.",
        "Gebyrforskjellen i kroner summert år for år, 1,3 % av saldoen i indeksfondet ved inngangen til hvert år: 2 600 × (1,068<sup>25</sup> − 1) / 0,068 = 159 801. Det mangler avkastningen de pengene ellers ville gitt resten av perioden.",
        null,
        "Indeksfondets eget gebyr glemt: 200 000 × (1,07<sup>25</sup> − 1,055<sup>25</sup>) = 322 808. Forskjellen i gebyr er 1,3 prosentpoeng, ikke 1,5.",
      ],
    },
    {
      id: "k14-17",
      topic: "Valutasikring",
      points: 3,
      body: "<p>Siri jobber i reiselivet. Når kronen er svak, får utenlandske turister mer for pengene, og da er både lønnen og jobbsikkerheten hennes best. Når kronen er sterk, går det dårligere. Hun eier et globalt indeksfond i utenlandsk valuta og vurderer å bytte til en valutasikret utgave av det samme fondet. Anta at valutasikringen er gratis og ikke endrer forventet avkastning.</p><p>Siri er risikoavers, og det som teller for henne, er samlet framtidig inntekt: arbeidsinntekt pluss verdien av fondet i kroner. Hva bør hun gjøre?</p>",
      options: [
        "Valutasikre, fordi det usikrede fondet er mest verdt i kroner nettopp når lønnen hennes er høy",
        "Ikke valutasikre, fordi et usikret utenlandsk fond alltid er en naturlig sikring for en norsk lønnstaker",
        "Det er likegyldig, fordi sikringen verken endrer forventet avkastning eller aksjerisikoen i fondet",
        "Valutasikre bare dersom hun er svært risikoavers, for en moderat risikoavers tåler valutasvingningene",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — fondet uten sikring.</b> Svak krone gjør utenlandske aksjer mer verdt i kroner; sterk krone gjør dem mindre verdt.</p><p><b>Steg 2 — lønnen.</b> Siris lønn er høy når kronen er svak og lav når den er sterk.</p><p><b>Steg 3 — samvariasjonen.</b> Usikret er fondet høyt og lønnen høy i de samme tilstandene, og begge lave i de samme. Valutaeksponeringen gir positiv samvariasjon med resten av inntekten, så samlet inntekt svinger mer. Sikringen fjerner valutadelen av fondets svingninger og dermed denne samvariasjonen.</p><p><b>Steg 4 — konklusjonen.</b> Samme forventning, lavere risiko i samlet inntekt: en risikoavers person bør <b>valutasikre</b>.</p><p><b>Kontroll mot H2024 oppgave 12c:</b> der var arbeidsinntekten høy når kronen er sterk. Det usikrede fondet betalte da mest når lønnen var lavest, og svaret var å <i>ikke</i> sikre. Regelen er den samme begge gangene: vurder et aktivum etter hvordan det samvarierer med resten av formuen din, humankapitalen inkludert. Snur fortegnet på samvariasjonen, snur svaret.</p>",
      traps: [
        null,
        "Svaret fra H2024 oppgave 12c pugget uten mekanismen. Der var lønnen høy når kronen er sterk; Siris lønn går motsatt vei, og da snur svaret.",
        "Forventet avkastning er uendret, men risikoen i samlet inntekt er det ikke. For en risikoavers er lavere varians med samme forventning en ren gevinst.",
        "Enhver risikoavers tar en gratis risikoreduksjon som ikke koster forventet avkastning. Graden av risikoaversjon avgjør hvor mye gevinsten er verdt, ikke hvilken vei beslutningen går.",
      ],
    },
    {
      id: "k14-18",
      topic: "Aktiv forvaltning",
      points: 3,
      body: "<p>Tenk deg et aksjemarked der indeksfondene eier 30 % av alle aksjene og de aktive fondene eier resten [eksempeltall]. I år stiger markedet 8 % før kostnader. Indeksfondene tar 0,2 % i årlig gebyr, de aktive fondene i snitt 1,4 %.</p><p>Hva kan du si om avkastningen til kundene i de aktive fondene, sett under ett?</p>",
      options: [
        "De får 8,0 % etter kostnader, fordi forvalterne velger aksjer som slår markedet og tjener inn gebyret",
        "De får 6,6 % etter kostnader, 1,2 prosentpoeng mindre enn indeksinvestorene",
        "De får 7,8 % etter kostnader, det samme som indeksinvestorene, fordi begge gruppene eier markedet",
        "Det kan ikke avgjøres uten å vite hvor dyktige forvalterne er",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — indeksinvestorene.</b> De eier markedet i markedsverdivekter og får per definisjon 8 % før kostnader, 8 % − 0,2 % = <b>7,8 %</b> etter.</p><p><b>Steg 2 — de aktive før kostnader.</b> Markedet er summen av alle investorer: 0,30 × 8 % + 0,70 × R<sub>aktiv</sub> = 8 %. Det gir R<sub>aktiv</sub> = (8 − 2,4) / 0,70 = <b>8 %</b>. Som gruppe eier de aktive også markedet.</p><p><b>Steg 3 — de aktive etter kostnader.</b> 8 % − 1,4 % = <b>6,6 %</b>.</p><p><b>Steg 4 — forskjellen.</b> 7,8 % − 6,6 % = <b>1,2 prosentpoeng</b>, nøyaktig gebyrforskjellen.</p><p><b>Kontroll:</b> vektet snitt etter kostnader er 0,30 × 7,8 % + 0,70 × 6,6 % = 2,34 % + 4,62 % = 6,96 %. Markedet minus vektet gebyr er 8 % − (0,30 × 0,2 % + 0,70 × 1,4 %) = 8 % − 1,04 % = 6,96 %. ✓ Kontrollen er en identitet: den bekrefter at tallene henger sammen, ikke selve resonnementet i steg 2.</p><p>Noen aktive forvaltere kan godt slå markedet i år, men bare ved at andre aktive taper like mye. Det er aritmetikken bak anbefalingen om indeksfond, og den krever ingen antakelse om at markedet er effisient eller at forvalterne er dårlige.</p>",
      traps: [
        "Hvis noen aktive slår markedet før kostnader, må andre aktive tape like mye, fordi indeksfondene får nøyaktig markedet. Gruppen får 8 % før gebyret og 6,6 % etter.",
        null,
        "Riktig før kostnader: begge gruppene får 8 %. Men de aktive betaler 1,4 % i gebyr, ikke 0,2 %.",
        "Dyktighet fordeler avkastningen mellom de aktive, men kan ikke løfte gruppen over markedet, for summen av alle investorer er markedet. Snittet følger av regnestykket alene.",
      ],
    },
    {
      id: "k14-19",
      topic: "Separasjonsteoremet",
      points: 3,
      body: "<p>Kari og Per har samme forventninger om markedet: risikopremien er 5 prosentpoeng og markedets standardavvik 20 % [eksempeltall]. Begge kan velge fritt mellom bankkonto til risikofri rente, et globalt indeksfond som representerer markedsporteføljen, og enkeltaksjer. Kari har risikoaversjon γ = 5, Per har γ = 2.</p><p>Hva sier teorien om optimale porteføljer, sammen med Mertons formel, om hvordan de bør plassere formuen?</p>",
      options: [
        "Kari: 25 % i en portefølje av lite volatile enkeltaksjer. Per: 62,5 % i indeksfondet. Resten i bank",
        "Begge velger indeksfondet og bank: Kari 5 % og Per 12,5 % i indeksfondet",
        "Begge velger indeksfondet og bank: Kari 62,5 % og Per 25 % i indeksfondet",
        "Begge velger indeksfondet og bank: Kari 25 % og Per 62,5 % i indeksfondet",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — hvilken risikabel portefølje.</b> Separasjonsteoremet: med et risikofritt aktivum ligger den beste kombinasjonen for alle på kapitalmarkedslinjen gjennom markedsporteføljen. Kari og Per eier derfor det <i>samme</i> indeksfondet. Risikoviljen avgjør ikke hvilke aksjer, bare hvor mye.</p><p><b>Steg 2 — hvor mye, med Merton.</b> σ<sup>2</sup> = 0,04. Kari: w* = 0,05 / (5 × 0,04) = 0,05 / 0,20 = <b>25 %</b>. Per: w* = 0,05 / (2 × 0,04) = 0,05 / 0,08 = <b>62,5 %</b>.</p><p><b>Steg 3 — resten i bank.</b> Kari 75 %, Per 37,5 %.</p><p><b>Kontroll:</b> begge porteføljene skal ligge på samme linje, altså ha samme Sharpe-forhold. Kari: meravkastning 0,25 × 5 = 1,25 prosentpoeng ved standardavvik 0,25 × 20 % = 5 %, forhold 0,25. Per: 0,625 × 5 = 3,125 prosentpoeng ved 0,625 × 20 % = 12,5 %, forhold 0,25. ✓ Samme linje, ulike punkter. Det følger av konstruksjonen, så kontrollen er en identitet; den bekrefter at begge eier markedsporteføljen og ikke noe annet.</p><p>Legg merke til at 5 % og 12,5 % i alternativ B er nøyaktig porteføljenes standardavvik. Standardavviksfeilen gir tall som ser kjente ut, og det er grunnen til at den er farlig.</p>",
      traps: [
        "Risikoviljen brukt til å velge hvilke aksjer. Separasjonsteoremet sier at alle eier den samme risikable porteføljen; lite volatile enkeltaksjer bærer usystematisk risiko som ikke betales, og Kari havner under kapitalmarkedslinjen.",
        "Standardavviket brukt i stedet for variansen: 0,05 / (5 × 0,20) = 5 % og 0,05 / (2 × 0,20) = 12,5 %.",
        "γ lest som risikovilje i stedet for risikoaversjon. γ står i nevneren, så Kari med γ = 5 skal ha den laveste andelen.",
        null,
      ],
    },
    {
      id: "k14-20",
      topic: "Perfekt negativ korrelasjon",
      points: 3,
      body: "<p>Aksje A har forventet avkastning 5 % og standardavvik 15 %. Aksje B har forventet avkastning 12 % og standardavvik 35 %. Korrelasjonen mellom dem er ρ = −1 [eksempeltall].</p><p>Hvor stor andel av porteføljen må stå i aksje A for at porteføljen skal være helt uten risiko? Rund av til én desimal.</p>",
      options: [
        "70,0 %",
        "84,5 %",
        "100,0 %",
        "175,0 %",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — hva ρ = −1 gjør med variansen.</b> Med andelen s i A blir σ<sub>p</sub><sup>2</sup> = s<sup>2</sup>σ<sub>A</sub><sup>2</sup> + (1 − s)<sup>2</sup>σ<sub>B</sub><sup>2</sup> − 2s(1 − s)σ<sub>A</sub>σ<sub>B</sub> = (sσ<sub>A</sub> − (1 − s)σ<sub>B</sub>)<sup>2</sup>. Et fullstendig kvadrat, så risikoen blir null når parentesen er null.</p><p><b>Steg 2 — sett parentesen lik null.</b> s × 0,15 = (1 − s) × 0,35 gir s × 0,50 = 0,35, altså s = <b>0,70</b>. Snarveien er s* = σ<sub>B</sub> / (σ<sub>A</sub> + σ<sub>B</sub>) = 0,35 / 0,50.</p><p><b>Steg 3 — samme svar fra den generelle formelen.</b> s* = (σ<sub>B</sub><sup>2</sup> − ρσ<sub>A</sub>σ<sub>B</sub>) / (σ<sub>A</sub><sup>2</sup> + σ<sub>B</sub><sup>2</sup> − 2ρσ<sub>A</sub>σ<sub>B</sub>) = (0,1225 + 0,0525) / (0,0225 + 0,1225 + 0,105) = 0,175 / 0,25 = <b>70,0 %</b>.</p><p><b>Kontroll:</b> sett s = 0,7 inn i variansformelen: 0,49 × 0,0225 + 0,09 × 0,1225 + 2 × 0,7 × 0,3 × (−1) × 0,15 × 0,35 = 0,011025 + 0,011025 − 0,02205 = 0. ✓ Porteføljen gir sikre 0,7 × 5 % + 0,3 × 12 % = 7,1 %.</p><p>Merk at svaret ikke er 50/50. Den mest risikable aksjen må ha minst vekt, slik at de to svingningene blir like store og nuller hverandre ut. 50/50 er svaret bare når standardavvikene er like, og det var feilen i forelesningsfoilene fra 2024.</p>",
      traps: [
        null,
        "Minimum-varians-formelen brukt med ρ = 0: σ<sub>B</sub><sup>2</sup> / (σ<sub>A</sub><sup>2</sup> + σ<sub>B</sub><sup>2</sup>) = 0,1225 / 0,145 = 84,5 %. Den gir lavest mulig risiko for ukorrelerte aksjer, men ikke null, og her er korrelasjonen −1.",
        "Hjørneregelen fra ρ = 1 (H2024 oppgave 12d): alt i aksjen med lavest standardavvik. Den gjelder bare ved perfekt positiv korrelasjon; 100 % i A har fortsatt 15 % risiko.",
        "Minustegnet på ρ mistet i formelen: (0,1225 − 0,0525) / (0,0225 + 0,1225 − 0,105) = 1,75. Det er nullrisikoporteføljen ved ρ = +1, som krever shortsalg av B.",
      ],
    },
  ],
};
