/* Kapittel 14 — Sparing og porteføljevalg */
window.EDU_DATA.chapterTasks[14] = {
  minutes: 22,
  tasks: [
    {
      id: "k14-1",
      topic: "Mertons aksjeandel",
      points: 3,
      body: "<p>Marte er pensjonist, så humankapitalen er null og hele formuen hennes er finansiell. Hun skal fordele den mellom et globalt indeksfond og bankkonto. Fondet har forventet avkastning 7 % og standardavvik 25 %, risikofri rente er 2 %, og Martes risikoaversjon er γ = 2 [eksempeltall].</p><p>Hvor stor andel av formuen skal ligge i indeksfondet ifølge Mertons formel?</p>",
      options: ["80 %", "56 %", "40 %", "10 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — telleren er risikopremien.</b> μ − r<sub>f</sub> = 7 % − 2 % = 5 prosentpoeng, altså <b>0,05</b>. Det er meravkastningen over risikofri rente som hører hjemme her, ikke de 7 prosentene.</p><p><b>Steg 2 — variansen, ikke standardavviket.</b> σ = 25 % gir σ<sup>2</sup> = 0,25<sup>2</sup> = <b>0,0625</b>.</p><p><b>Steg 3 — nevneren.</b> γσ<sup>2</sup> = 2 × 0,0625 = <b>0,125</b>.</p><p><b>Steg 4 — andelen.</b> w* = 0,05 / 0,125 = 0,40, altså <b>40 %</b>.</p><p><b>Kontroll:</b> sett svaret tilbake inn. w* × γσ<sup>2</sup> = 0,40 × 2 × 0,0625 = 0,05, som er risikopremien. ✓ Har Marte kr 1 000 000, står kr 400 000 i fondet og kr 600 000 i banken.</p><p>Legg merke til hva som aldri kom inn i regnestykket: tidshorisonten. Mertons formel gir samme andel for ett år og for tjue.</p>",
      traps: [
        "Risikoaversjonen er utelatt fra nevneren: 0,05 / 0,0625. Da er γ satt til 1 uansett hva oppgaven sier.",
        "Forventet avkastning brukt i telleren i stedet for risikopremien: 0,07 / (2 × 0,0625). Risikofri rente må trekkes fra først.",
        null,
        "Standardavviket brukt i nevneren i stedet for variansen: 0,05 / (2 × 0,25). Dette er den dyreste enkeltfeilen i finansdelen.",
      ],
    },
    {
      id: "k14-2",
      topic: "Risikoaversjon",
      points: 3,
      body: "<p>Sondre får oppgitt at meravkastningen i aksjemarkedet over risikofri rente er 6 prosentpoeng, at markedets standardavvik er 20 %, og at risikofri rente er 3 % [eksempeltall]. Hans optimale aksjeandel etter Mertons formel er 50 % av formuen.</p><p>Hvor høy er Sondres risikoaversjon γ?</p>",
      options: ["0,33", "0,60", "1,50", "3,00"],
      answer: 3,
      solution: "<p><b>Steg 1 — snu formelen.</b> w* = (μ − r<sub>f</sub>) / (γσ<sup>2</sup>) gir γ = (μ − r<sub>f</sub>) / (w* × σ<sup>2</sup>).</p><p><b>Steg 2 — variansen.</b> σ = 20 % gir σ<sup>2</sup> = 0,20<sup>2</sup> = <b>0,04</b>.</p><p><b>Steg 3 — nevneren.</b> 0,50 × 0,04 = <b>0,02</b>.</p><p><b>Steg 4 — risikoaversjonen.</b> γ = 0,06 / 0,02 = <b>3,00</b>.</p><p><b>Kontroll:</b> sett γ = 3 inn i formelen igjen: 0,06 / (3 × 0,04) = 0,06 / 0,12 = 0,50, altså 50 %. ✓</p><p>Den risikofrie renten på 3 % er overflødig informasjon her. Meravkastningen er alt formelen trenger, og de tre prosentene står i teksten nettopp for å friste deg til å trekke dem fra en gang til. γ = 3 ligger midt i det empiriske anslaget på 2–5; γ = 1 svarer til logaritmisk nytte.</p>",
      traps: [
        "Brøken er snudd: w* × σ<sup>2</sup> / (μ − r<sub>f</sub>) = 0,02 / 0,06. Det gir 1/γ, ikke γ.",
        "Standardavviket brukt i stedet for variansen: 0,06 / (0,50 × 0,20).",
        "Risikofri rente trukket fra en gang til: (0,06 − 0,03) / 0,02. De 6 prosentpoengene er allerede meravkastningen.",
        null,
      ],
    },
    {
      id: "k14-3",
      topic: "Humankapital",
      points: 3,
      body: "<p>Sara er 28 år, fast ansatt i staten, og lønnen hennes svinger ikke med aksjemarkedet. Finansformuen er kr 600 000, og nåverdien av all framtidig arbeidsinntekt er anslått til kr 4 200 000. Meravkastningen i markedet er 4 prosentpoeng, markedets standardavvik er 20 % og Saras risikoaversjon er γ = 4 [eksempeltall].</p><p>Hvor stor andel av finansformuen på kr 600 000 skal Sara ha i aksjer?</p>",
      options: ["200 %", "100 %", "25 %", "0 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — Mertons andel av totalformuen.</b> σ<sup>2</sup> = 0,04, så w* = 0,04 / (4 × 0,04) = 0,04 / 0,16 = <b>25 %</b>.</p><p><b>Steg 2 — totalformuen.</b> F + H = 600 000 + 4 200 000 = <b>kr 4 800 000</b>. Humankapitalen er den desidert største posten på Saras balanse, og den står ikke i skattemeldingen.</p><p><b>Steg 3 — ønsket aksjebeløp.</b> 0,25 × 4 800 000 = <b>kr 1 200 000</b>.</p><p><b>Steg 4 — hvor beløpet må hentes.</b> Lønnen er trygg, altså β<sub>H</sub> = 0: humankapitalen er et implisitt bankinnskudd og leverer null aksjeeksponering. Hele beløpet må derfor tas i finansformuen: 1 200 000 − 0 = 1 200 000, og andelen av finansformuen er 1 200 000 / 600 000 = <b>200 %</b>.</p><p><b>Kontroll:</b> Sara låner kr 600 000 og plasserer kr 1 200 000 i aksjer. Balansen etterpå: aksjer 1 200 000, humankapital 4 200 000, gjeld 600 000, altså totalformue 4 800 000 og aksjeandel 1 200 000 / 4 800 000 = 25 %, nøyaktig w*. ✓</p><p>Dette er økonomenes eneste forsvar for «100 % aksjer når du er ung». Ikke at aksjer blir tryggere med tiden, men at en stor obligasjonslignende humankapital i ryggen tåler eksponeringen.</p>",
      traps: [
        null,
        "Andelen kappet ved 100 % fordi ønsket aksjebeløp overstiger finansformuen. Formelen anbefaler faktisk lånefinansiering her, og kappingen er et praktisk valg, ikke svaret på spørsmålet.",
        "w* brukt direkte på finansformuen. Merton gjelder totalformuen, og da faller humankapitalen ut av regnestykket.",
        "Humankapitalen behandlet som aksjer i stedet for som obligasjon: 1 200 000 − 4 200 000 er negativt, altså null i aksjer. Saras lønn er trygg, så β<sub>H</sub> er null.",
      ],
    },
    {
      id: "k14-4",
      topic: "Jobbrisiko",
      points: 3,
      body: "<p>Jonas jobber som megler, og bonusen gjør at lønnen svinger med aksjemarkedet: humankapitalens beta mot markedet er β<sub>H</sub> = 0,5. Finansformuen hans er kr 1 000 000 og humankapitalen kr 3 000 000. Meravkastningen er 5 prosentpoeng, markedets standardavvik er 25 % og γ = 2 [eksempeltall].</p><p>Hvor mange kroner av finansformuen skal stå i aksjer?</p>",
      options: ["kr 100 000", "kr 400 000", "kr 1 000 000", "kr 1 600 000"],
      answer: 0,
      solution: "<p><b>Steg 1 — Mertons andel.</b> σ<sup>2</sup> = 0,25<sup>2</sup> = 0,0625, så w* = 0,05 / (2 × 0,0625) = 0,05 / 0,125 = <b>40 %</b>.</p><p><b>Steg 2 — ønsket aksjeeksponering.</b> Totalformuen er 1 000 000 + 3 000 000 = 4 000 000, og 0,40 × 4 000 000 = <b>kr 1 600 000</b>.</p><p><b>Steg 3 — det humankapitalen allerede leverer.</b> β<sub>H</sub> × H = 0,5 × 3 000 000 = <b>kr 1 500 000</b>. Halve humankapitalen oppfører seg som aksjer, enten Jonas vil eller ikke.</p><p><b>Steg 4 — resten hentes i finansformuen.</b> 1 600 000 − 1 500 000 = <b>kr 100 000</b>, altså 10 % av finansformuen. De resterende kr 900 000 skal stå risikofritt.</p><p><b>Kontroll:</b> samlet aksjeeksponering blir 100 000 + 1 500 000 = 1 600 000, som er 40 % av 4 000 000. ✓</p><p>Sammenlign med Sara i forrige oppgave: samme formel, motsatt konklusjon, fordi jobbrisikoen har flyttet aksjeeksponeringen inn i humankapitalen. Det er også argumentet mot å eie aksjer i selskapet du jobber i.</p>",
      traps: [
        null,
        "w* brukt direkte på finansformuen: 0,40 × 1 000 000. Da er verken humankapitalen eller jobbrisikoen med i regnestykket.",
        "Humankapitalen vektet ned med β<sub>H</sub> før den legges til formuen: 0,40 × (1 000 000 + 0,5 × 3 000 000). Betaen hører hjemme i eksponeringen som trekkes fra, ikke i formuen som ganges opp.",
        "β<sub>H</sub> satt til null, altså humankapitalen behandlet som en ren obligasjon. Jonas' lønn svinger med markedet, og halve humankapitalen er derfor allerede aksjer.",
      ],
    },
    {
      id: "k14-5",
      topic: "Diversifisering",
      points: 3,
      body: "<p>Kari har halve porteføljen i aksje A og halve i aksje B [eksempeltall]. Aksje A har standardavvik σ<sub>A</sub> = 30 %, aksje B har σ<sub>B</sub> = 10 %, og korrelasjonen mellom dem er ρ = 0,4.</p><p>Hva er porteføljens standardavvik?</p>",
      options: ["17,61 %", "20,00 %", "35,21 %", "47,43 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — de to kvadrerte leddene.</b> 0,5<sup>2</sup> × 0,30<sup>2</sup> = 0,25 × 0,09 = <b>0,0225</b> og 0,5<sup>2</sup> × 0,10<sup>2</sup> = 0,25 × 0,01 = <b>0,0025</b>. Merk at både vektene og standardavvikene kvadreres.</p><p><b>Steg 2 — krysseleddet.</b> Det inneholder kovariansen ρσ<sub>A</sub>σ<sub>B</sub>, ikke ρ alene: 2 × 0,5 × 0,5 × 0,4 × 0,30 × 0,10 = 0,5 × 0,012 = <b>0,0060</b>.</p><p><b>Steg 3 — variansen.</b> 0,0225 + 0,0025 + 0,0060 = <b>0,0310</b>.</p><p><b>Steg 4 — standardavviket.</b> √0,0310 = 0,17607, altså <b>17,61 %</b>.</p><p><b>Kontroll:</b> så lenge ρ &lt; 1 må porteføljens standardavvik ligge under det vektede snittet av de to standardavvikene, 0,5 × 30 % + 0,5 × 10 % = 20 %. Og uten shortsalg kan det ikke komme under 10 %, siden minimum-varians-vekten i A er negativ med disse tallene. Bare ett alternativ ligger mellom 10 % og 20 %. ✓</p><p>De 2,39 prosentpoengene under det vektede snittet er diversifiseringsgevinsten. Forventningen ville derimot vært et rent vektet snitt; det er nettopp den forskjellen hele porteføljeteorien lever av.</p>",
      traps: [
        null,
        "Standardavvikene veid sammen direkte: 0,5 × 30 % + 0,5 × 10 %. Det er svaret bare når ρ = 1, altså når det ikke finnes noen diversifiseringsgevinst.",
        "Kvadratene på vektene glemt: 0,09 + 0,01 + 2 × 0,4 × 0,30 × 0,10. Da blir porteføljen mer risikabel enn aksje A alene, som er umulig.",
        "Krysseleddet regnet med ρ alene i stedet for ρσ<sub>A</sub>σ<sub>B</sub>: 0,0225 + 0,0025 + 2 × 0,25 × 0,4. Kovariansen krever begge standardavvikene.",
      ],
    },
    {
      id: "k14-6",
      topic: "Sparerate",
      points: 3,
      body: "<p>Ida og Jonas er begge 35 år og sparer ved utgangen av hvert år i 30 år [eksempeltall]. Ida setter av kr 50 000 i året og får 4 % årlig realavkastning. Jonas setter av kr 35 000 i året, men velger en portefølje med 6 % forventet realavkastning.</p><p>Hvem sitter igjen med mest etter 30 år, og hvor stor er forskjellen?</p>",
      options: [
        "Jonas, med kr 1 165 569 mer",
        "Jonas, med kr 38 852 mer",
        "Ida, med kr 450 000 mer",
        "Ida, med kr 37 210 mer",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — riktig verktøy.</b> En fast årlig innbetaling ved utgangen av året vokser til innbetalingen ganget med annuitetsfaktoren [(1 + r)<sup>n</sup> − 1] / r.</p><p><b>Steg 2 — Ida.</b> 1,04<sup>30</sup> = 3,2433975, faktoren blir (3,2433975 − 1) / 0,04 = 56,084938, og sluttformuen 50 000 × 56,084938 = <b>kr 2 804 247</b>.</p><p><b>Steg 3 — Jonas.</b> 1,06<sup>30</sup> = 5,7434912, faktoren blir (5,7434912 − 1) / 0,06 = 79,058186, og sluttformuen 35 000 × 79,058186 = <b>kr 2 767 037</b>.</p><p><b>Steg 4 — differansen.</b> 2 804 247 − 2 767 037 = <b>kr 37 210</b> i Idas favør.</p><p><b>Kontroll, delt opp i innskudd og renter:</b> Ida har betalt inn 1 500 000 og Jonas 1 050 000, altså kr 450 000 mer. Rentene er 1 304 247 for Ida og 1 717 037 for Jonas, altså kr 412 790 mer for Jonas. 450 000 − 412 790 = 37 210. ✓</p><p>Poenget er størrelsesordenen. Ida sparer 42,9 % mer i året, Jonas får 2 prosentpoeng høyere avkastning hvert eneste år i tretti år, og de to veier nesten nøyaktig like tungt. Forskjellen er at sparebeløpet er noe du styrer selv, mens avkastningen bare er et anslag.</p>",
      traps: [
        "Hele det innbetalte beløpet behandlet som ett innskudd i år 0: 1 500 000 × 1,04<sup>30</sup> mot 1 050 000 × 1,06<sup>30</sup>. Pengene kommer inn litt hvert år og forrentes derfor langt kortere.",
        "Bare ett års innskudd forrentet i tretti år: 50 000 × 1,04<sup>30</sup> mot 35 000 × 1,06<sup>30</sup>. Annuitetsfaktoren mangler, og med den de 29 andre innbetalingene.",
        "Renters rente utelatt helt. Differansen 450 000 er bare forskjellen i innbetalt beløp, 1 500 000 mot 1 050 000.",
        null,
      ],
    },
  ],
};
