/* Kapittel 15 — Pensjon: folketrygd, tjenestepensjon og IPS */
window.EDU_DATA.chapterTasks[15] = {
  minutes: 64,
  tasks: [
    {
      id: "k15-1",
      topic: "Pensjonsbeholdning",
      points: 3,
      body: "<p>Sigrid er født i 1991 og er dermed i den nye opptjeningsmodellen. Ved inngangen til 2026 er pensjonsbeholdningen hennes kr 2 340 000 [eksempeltall], og i løpet av 2026 tjener hun kr 1 150 000 [eksempeltall]. Grunnbeløpet er kr 136 549 og opptjeningstaket 7,1 G er kr 969 498 [dagens regel]. Opptjeningssatsen er 18,1 % [dagens regel], og beholdningen reguleres årlig med lønnsveksten, som er 4,91 % [dagens regel, G-veksten til 2026].</p><p>Hvor stor er pensjonsbeholdningen ved utgangen av 2026?</p>",
      options: ["kr 2 515 479", "kr 2 630 373", "kr 2 638 989", "kr 2 663 044"],
      answer: 1,
      solution: "<p><b>Steg 1 — årets opptjening, med taket.</b> Opptjeningen regnes av min(pensjonsgivende inntekt; 7,1 G) = min(1 150 000; 969 498) = 969 498. De 180 502 kronene over taket gir null. Opptjening: 18,1 % × 969 498 = <b>175 479</b>.</p><p><b>Steg 2 — reguler først.</b> Rekkefølgen i formelen B<sub>t</sub> = B<sub>t−1</sub> × (1 + g) + opptjening<sub>t</sub> er bindende: 2 340 000 × 1,0491 = <b>2 454 894</b>.</p><p><b>Steg 3 — legg til opptjeningen etterpå.</b> 2 454 894 + 175 479 = <b>2 630 373</b>.</p><p><b>Kontroll:</b> beholdningen har vokst med 2 630 373 − 2 340 000 = 290 373. Av dette er 114 894 regulering av det som allerede lå der, og 175 479 er ny opptjening. 114 894 + 175 479 = 290 373. ✓ Merk også at 175 479 er nøyaktig maksimal årlig opptjening i 2026, altså 18,1 % × 7,1 G. Ingen kan få mer enn dette på ett år, uansett lønn.</p>",
      traps: [
        "Reguleringen er glemt. Beholdningen skal vokse med lønnsveksten hvert år, ikke bare få tilført årets opptjening.",
        null,
        "Rekkefølgen er snudd: årets opptjening er lagt til før reguleringen, og dermed regulert med et helt års lønnsvekst den ikke har hatt.",
        "18,1 % er regnet av hele lønnen på 1 150 000. Inntekt over 7,1 G gir null opptjening i folketrygden.",
      ],
    },
    {
      id: "k15-2",
      topic: "Delingstall og uttak",
      points: 3,
      body: "<p>Ola er født i 1970 og har en pensjonsbeholdning på kr 5 200 000 [eksempeltall]. Delingstallet for kullet hans er 21,15 ved uttak som 62-åring og 17,08 ved uttak som 67-åring [eksempeltall fra forelesningen]. Hold beholdningen fast på kr 5 200 000, altså se bort fra at den ville vokst videre i mellomtiden.</p><p>Hva skjer med den årlige alderspensjonen hvis han venter fra 62 til 67 år?</p>",
      options: [
        "Den blir 19,24 % lavere",
        "Den blir 8,06 % høyere",
        "Den blir 23,83 % høyere",
        "Den er uendret, fordi ordningen er nøytralt utformet",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — uttak ved 62.</b> Beholdningen deles på delingstallet: 5 200 000 / 21,15 = <b>245 863</b> kr i året.</p><p><b>Steg 2 — uttak ved 67.</b> 5 200 000 / 17,08 = <b>304 450</b> kr i året.</p><p><b>Steg 3 — endringen.</b> 304 450 / 245 863 − 1 = <b>23,83 %</b>. Beholdningen faller ut av brøken, så det samme tallet kommer rett ut av delingstallene: (21,15 − 17,08) / 17,08 = 23,83 %.</p><p><b>Kontroll:</b> årsbeløpet ganget med delingstallet må gi beholdningen tilbake. 245 863 × 21,15 = 5 200 002 og 304 450 × 17,08 = 5 200 006, begge lik 5 200 000 opp til avrundingen i årsbeløpene. ✓ Forventet samlet utbetaling er altså den samme, og det er nettopp det nøytralt utformet betyr: du kjøper en høyere årlig ytelse over færre år.</p>",
      traps: [
        "Delingstallet er brukt som multiplikator: 5 200 000 × 17,08 mot 5 200 000 × 21,15 gir 19,24 % lavere. Delingstallet er en divisor, fordi beholdningen skal fordeles på forventet gjenstående leveår.",
        "Utsettelsen regnet som 67 / 62 − 1. Årsbeløpet følger delingstallet, ikke alderen i seg selv.",
        null,
        "Nøytraliteten gjelder samlet forventet utbetaling over livet, ikke det årlige beløpet. Med fast teller og lavere nevner må årsbeløpet stige.",
      ],
    },
    {
      id: "k15-3",
      topic: "Kompensasjonsgrad",
      points: 3,
      body: "<p>Nils og Kari er i samme årskull og har begge 38 år med inntekt [eksempeltall]. Nils har tjent 5 G hvert år, Kari 8,5 G. Begge lønninger har fulgt lønnsveksten, begge tar ut pensjon ved 67 år, og delingstallet for kullet er 17,44 [eksempeltall]. Opptjeningen er 18,1 % av inntekt opp til 7,1 G [dagens regel].</p><p>Hva er kompensasjonsgraden, altså årlig alderspensjon fra folketrygden delt på sluttlønn, for hver av dem?</p>",
      options: [
        "39,44 % for begge",
        "32,94 % for begge",
        "39,44 % for Kari og 32,94 % for Nils",
        "39,44 % for Nils og 32,94 % for Kari",
      ],
      answer: 3,
      solution: "<p>Regn i G, så faller både G og kronebeløpene ut av brøken.</p><p><b>Steg 1 — Nils ligger under taket.</b> Hele lønnen gir opptjening: 18,1 % × 5 = 0,905 G per år, altså 0,905 × 38 = <b>34,39 G</b>.</p><p><b>Steg 2 — Nils' kompensasjonsgrad.</b> Årlig pensjon: 34,39 / 17,44 = 1,9719 G. Delt på sluttlønnen 5 G: <b>39,44 %</b>.</p><p><b>Steg 3 — Kari treffer taket.</b> Opptjeningen stopper på 7,1 G: 18,1 % × 7,1 = 1,2851 G per år, altså 1,2851 × 38 = <b>48,8338 G</b>. De 1,4 G hun tjener over taket gir ingenting.</p><p><b>Steg 4 — Karis kompensasjonsgrad.</b> Årlig pensjon: 48,8338 / 17,44 = 2,8001 G. Delt på sluttlønnen 8,5 G: <b>32,94 %</b>.</p><p><b>Kontroll i kroner, med G = 136 549 [dagens regel]:</b> Nils' beholdning er 34,39 × 136 549 = 4 695 920, årlig pensjon 4 695 920 / 17,44 = 269 261, sluttlønn 5 × 136 549 = 682 745, og 269 261 / 682 745 = 39,44 %. ✓ Karis beholdning er 48,8338 × 136 549 = 6 668 207, årlig pensjon 382 351, sluttlønn 8,5 × 136 549 = 1 160 666,50, og 382 351 / 1 160 666,50 = 32,94 %. ✓</p><p>Kari får 42 % mer i kroner enn Nils (382 351 / 269 261 = 1,42), men en klart lavere andel av sin egen lønn. Det er taket som gjør det, og det er derfor den som tjener mest er den som må spare mest selv.</p>",
      traps: [
        "Taket er glemt for Kari: 18,1 % × 8,5 × 38 / (17,44 × 8,5) gir 39,44 %, fordi lønnen da faller ut av brøken. Ser du samme kompensasjonsgrad for to ulike lønninger, mangler taket.",
        "Karis brøk 7,1/8,5 brukt også for Nils. Men Nils tjener 5 G og kommer aldri opp i taket på 7,1 G, så hele lønnen hans gir opptjening.",
        "De to er byttet om. Den som tjener mest får mest i kroner, men lavest kompensasjonsgrad, fordi bare inntekt opp til 7,1 G teller.",
        null,
      ],
    },
    {
      id: "k15-4",
      topic: "Maksimalt innskudd",
      points: 3,
      body: "<p>Jonas tjener kr 1 400 000 [eksempeltall] hos en arbeidsgiver som legger seg på maksimalsatsen i innskuddspensjonen. For 2026 er grunnbeløpet kr 136 549, folketrygdens opptjeningstak 7,1 G er kr 969 498 og 12 G er kr 1 638 588 [dagens regel]. Maksimalt innskudd er 7 % av lønn opp til 12 G, pluss 18,1 % av lønnen mellom 7,1 G og 12 G [dagens regel].</p><p>Hvor mye kan arbeidsgiveren maksimalt sette inn for Jonas i året?</p>",
      options: ["kr 98 000", "kr 145 786", "kr 175 921", "kr 351 400"],
      answer: 2,
      solution: "<p><b>Steg 1 — grunnsatsen treffer hele lønnen.</b> De 7 prosentene gjelder lønn fra første krone og opp til 12 G. Jonas ligger under 1 638 588, så hele lønnen teller: 7 % × 1 400 000 = <b>98 000</b>.</p><p><b>Steg 2 — tilleggssatsen treffer bare lønnen over 7,1 G.</b> 1 400 000 − 969 498 = 430 502, og 18,1 % × 430 502 = <b>77 921</b>. Satsen er ingen tilfeldighet: den er nøyaktig folketrygdens opptjeningssats, og finnes for at arbeidsgiver skal kunne kompensere for at folketrygden ikke gir opptjening over taket.</p><p><b>Steg 3 — sum.</b> 98 000 + 77 921 = <b>175 921</b>.</p><p><b>Kontroll, del lønnen i to i stedet:</b> de første 969 498 får bare 7 % = 67 865, og de siste 430 502 får 7 % + 18,1 % = 25,1 %, altså 108 056. 67 865 + 108 056 = 175 921. ✓</p><p>Til sammenligning er OTP-minimum 2 % × 1 400 000 = 28 000. Avstanden mellom en arbeidsgiver på minstesatsen og en på maksimum er nesten 148 000 kroner i året for den samme jobben.</p>",
      traps: [
        "Bare grunnsatsen. Tilleggssatsen over 7,1 G er glemt, og det er nettopp den som skiller en romslig ordning fra en gjennomsnittlig.",
        "7 % er regnet bare av lønnen opp til 7,1 G: 67 865 + 77 921. Grunnsatsen gjelder hele lønnen opp til 12 G, ikke bare den delen som ligger under folketrygdtaket.",
        null,
        "18,1 % er regnet av hele lønnen i stedet for av lønnen over 7,1 G: 98 000 + 253 400. Tilleggssatsen treffer bare det som ligger mellom 7,1 G og 12 G.",
      ],
    },
    {
      id: "k15-5",
      topic: "IPS etter skatt",
      points: 3,
      body: "<p>Du setter inn maksbeløpet på IPS, kr 25 000 [dagens regel, 2026], og lar det stå i 15 år til 6 % årlig avkastning [eksempeltall]. Skatten på alminnelig inntekt er 22 % og eierskatten er 37,84 % [dagens regel]. Vekstfaktoren over 15 år er 1,06<sup>15</sup> = 2,39656.</p><p>Hvor mye sitter du igjen med netto når pengene tas ut av IPS-kontoen?</p>",
      options: ["kr 36 452", "kr 37 243", "kr 46 733", "kr 59 914"],
      answer: 2,
      solution: "<p><b>Steg 1 — hele innskuddet står inne og vokser.</b> Fradraget gir 22 % × 25 000 = 5 500 kr tilbake med en gang, så ditt eget utlegg er 19 500, men det er 25 000 som ligger på kontoen og avkaster: 25 000 × 2,39656 = <b>59 914</b>. Ingen løpende skatt på avkastningen underveis, og ingen formuesskatt.</p><p><b>Steg 2 — uttaket skattlegges.</b> Uttak fra IPS er alminnelig inntekt, altså 22 %, ikke pensjonsinntekt: ingen trygdeavgift og ingen trinnskatt. 59 914 × 22 % = <b>13 181</b>.</p><p><b>Steg 3 — netto.</b> 59 914 − 13 181 = <b>46 733</b>.</p><p><b>Kontroll, flytt skattesatsen til begynnelsen:</b> fordi satsen inn og satsen ut er den samme, er 25 000 × 2,39656 × (1 − 0,22) det samme som [25 000 × (1 − 0,22)] × 2,39656 = 19 500 × 2,39656 = 46 733. ✓ Samme tall. IPS er derfor økonomisk identisk med at du skattet av lønnen først og lot resten vokse helt skattefritt.</p><p><b>Kontroll av statens andel:</b> de 5 500 kronene staten la inn gjennom fradraget har vokst med samme avkastning: 5 500 × 2,39656 = 13 181, nøyaktig skatten i steg 2. ✓ Staten er en passiv medeier på 22 % hele veien, verken mer eller mindre.</p>",
      traps: [
        "Skatten er tatt to ganger: innskuddet behandlet som om det var etter skatt (19 500), og uttaket likevel skattlagt med 22 %. Enten trekker du fradraget fra i begynnelsen eller skatten fra i slutten, aldri begge.",
        "Eierskatten 37,84 % brukt på uttaket. Det er satsen for aksjer og aksjesparekonto; IPS-uttak er alminnelig inntekt og skattlegges med 22 %.",
        null,
        "Uttaksskatten er glemt, altså IPS behandlet som en skattefri konto. Fradraget på 22 % er en utsettelse, og staten tar de samme 22 % igjen når pengene kommer ut.",
      ],
    },
    {
      id: "k15-6",
      topic: "Verdien av IPS",
      points: 3,
      body: "<p>Utgangspunktet er kr 25 000 inn på IPS [dagens regel, 2026], 15 år, 6 % avkastning [eksempeltall], vekstfaktor 2,39656, netto etter uttaksskatt kr 46 733. Alternativet er at du dropper IPS og i stedet plasserer ditt eget utlegg etter fradraget, kr 19 500, på en aksjesparekonto med samme avkastning. Gevinsten der skattlegges med eierskatten 37,84 % [dagens regel]. Se bort fra skjermingsfradrag og formuesskatt.</p><p>Hvor mye mer sitter du igjen med etter skatt med IPS enn med aksjesparekontoen?</p>",
      options: ["kr 5 500", "kr 10 305", "kr 13 181", "kr 23 486"],
      answer: 1,
      solution: "<p><b>Steg 1 — aksjesparekontoen vokser til det samme.</b> 19 500 × 2,39656 = <b>46 733</b>. Legg merke til at sluttverdien før skatt er nøyaktig den samme som IPS gir etter skatt. Det er ikke tilfeldig: det er den samme flyttingen av (1 − t) fra slutten til begynnelsen som i forrige oppgave.</p><p><b>Steg 2 — skatten på aksjesparekontoen.</b> Gevinsten er 46 733 − 19 500 = 27 233, og den skattlegges ved uttak: 27 233 × 37,84 % = <b>10 305</b>. Netto: 46 733 − 10 305 = <b>36 428</b>.</p><p><b>Steg 3 — forskjellen.</b> 46 733 − 36 428 = <b>10 305</b>.</p><p><b>Kontroll:</b> forskjellen er krone for krone den skatten aksjesparekontoen måtte betale. ✓ Det er hele innholdet i IPS-fordelen: avkastningen på din egen andel går fri for skatt, fordi skatten er utsatt til uttaket og treffer et beløp som har vokst med samme faktor som ditt eget.</p><p><b>Hvorfor fradraget i seg selv ikke er gevinsten:</b> de 5 500 kronene staten la inn, henter den ut igjen som 5 500 × 2,39656 = 13 181 ved uttak. Satsen inn og satsen ut er den samme 22 %, så det er ingen satsarbitrasje å hente, og IPS lønner seg ikke fordi du «skatter lavere som pensjonist». Fordelen er tidsverdien av utsettelsen, pluss fritaket for formuesskatt, som kommer på toppen av de 10 305 kronene. Prisen er bindingen til tidligst 62 år.</p>",
      traps: [
        "Fradraget på 22 % × 25 000 regnet som selve gevinsten. Fradraget er en utsettelse, ikke en rabatt: staten tar de samme 22 % igjen ved uttak.",
        null,
        "Den utsatte skatten i seg selv, altså statens andel ved uttak. Den er statens penger hele veien; din gevinst er skatten du slipper på din egen avkastning.",
        "Uttaksskatten på IPS er glemt: 59 914 − 36 428. Da er IPS behandlet som skattefri i stedet for utsatt, og fordelen blir mer enn dobbelt så stor som den er.",
      ],
    },
    {
      id: "k15-7",
      topic: "Karrierestigning",
      points: 3,
      body: "<p>Siri har jobbet i 40 år. De første 20 årene tjente hun 3 G i året, de siste 20 årene 9 G i året [eksempeltall]. Innenfor hver periode har lønnen fulgt lønnsveksten, altså G. Opptjeningen i folketrygden er 18,1 % av pensjonsgivende inntekt opp til 7,1 G [dagens regel]. Hun tar ut alderspensjon som 67-åring, og delingstallet for kullet hennes er 17,50 [eksempeltall].</p><p>Hva er kompensasjonsgraden hennes, altså årlig alderspensjon fra folketrygden delt på sluttlønnen? Oppgi svaret med to desimaler.</p>",
      options: [
        "23,21 %",
        "27,58 %",
        "32,64 %",
        "34,82 %",
      ],
      answer: 0,
      solution: "<p>Regn i G. Lønnen har fulgt G, og beholdningen reguleres med G, så hvert års opptjening beholder verdien sin målt i G fram til uttak.</p><p><b>Steg 1 — de første 20 årene, under taket.</b> 3 G gir full opptjening: 18,1 % × 3 = 0,543 G per år, altså 0,543 × 20 = <b>10,86 G</b>.</p><p><b>Steg 2 — de siste 20 årene, over taket.</b> Opptjeningen stopper på 7,1 G: 18,1 % × 7,1 = 1,2851 G per år, altså 1,2851 × 20 = <b>25,702 G</b>. De 1,9 G hun tjener over taket gir ingenting.</p><p><b>Steg 3 — beholdning og pensjon.</b> Alleårsregelen teller alle år: 10,86 + 25,702 = <b>36,562 G</b>. Årlig pensjon: 36,562 / 17,50 = <b>2,0893 G</b>.</p><p><b>Steg 4 — kompensasjonsgraden.</b> Sluttlønnen er 9 G: 2,0893 / 9 = <b>23,21 %</b>.</p><p><b>Kontroll i kroner, med G = 136 549 [dagens regel]:</b> beholdningen er 36,562 × 136 549 = 4 992 505, årlig pensjon 4 992 505 / 17,50 = 285 286, sluttlønnen 9 × 136 549 = 1 228 941, og 285 286 / 1 228 941 = 23,21 %. ✓</p><p><b>Mekanismen:</b> hadde Siri tjent 9 G i alle 40 år, ville hun fått 18,1 % × 7,1 × 40 / (17,50 × 9) = 32,64 %. Forskjellen er karrierestigningen. De tidlige årene gir opptjening av en lav lønn, men kompensasjonsgraden måles mot den høye sluttlønnen. Det er H2019 oppgave 6b: når din egen lønnsvekst er høyere enn samfunnets, blir kompensasjonsgraden alltid lavere.</p>",
      traps: [
        null,
        "Taket er glemt for de siste 20 årene: 18,1 % × (3 × 20 + 9 × 20) = 43,44 G, delt på 17,50 og på 9 G gir 27,58 %. Lønn over 7,1 G gir ingen opptjening.",
        "Regnet som om hele karrieren lå på sluttlønnsnivået, med taket: 18,1 % × 7,1 × 40 / (17,50 × 9) = 32,64 %. Det er logikken fra den gamle folketrygden, der de beste årene bestemte pensjonen. Alleårsregelen teller hvert år med den lønnen du faktisk hadde, og de 20 årene på 3 G trekker ned.",
        "Riktig pensjon, 2,0893 G, men delt på gjennomsnittslønnen på 6 G i stedet for sluttlønnen på 9 G. Kompensasjonsgraden måles mot sluttlønnen, og det er nettopp derfor karrierestigning senker den.",
      ],
    },
    {
      id: "k15-8",
      topic: "Når lønner det seg å vente",
      points: 3,
      body: "<p>Mona har en pensjonsbeholdning på kr 4 800 000 [eksempeltall] og vurderer å ta ut alderspensjonen fra folketrygden som 64-åring eller som 67-åring. Delingstallet for kullet hennes er 19,60 ved uttak som 64-åring og 17,20 ved uttak som 67-åring [eksempeltall]. Hold beholdningen fast på kr 4 800 000 uansett uttaksalder, og se bort fra regulering, skatt og diskontering.</p><p>Ved hvilken alder har uttak fra 67 år tatt igjen uttak fra 64 år, målt i samlet utbetalt pensjon? Rund av til én desimal.</p>",
      options: [
        "69,6 år",
        "83,6 år",
        "85,5 år",
        "88,5 år",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — årlig pensjon i hvert valg.</b> Beholdningen deles på delingstallet: 4 800 000 / 19,60 = <b>244 898</b> ved 64 og 4 800 000 / 17,20 = <b>279 070</b> ved 67.</p><p><b>Steg 2 — forspranget.</b> Tar hun ut ved 64, har hun fått tre år med pensjon før det andre valget gir noe: 3 × 244 898 = <b>734 694</b>.</p><p><b>Steg 3 — hvor fort forspranget spises opp.</b> Fra 67 får begge valgene utbetaling, så det er bare differansen som tar igjen: 279 070 − 244 898 = <b>34 172</b> i året.</p><p><b>Steg 4 — bruddpunktet.</b> 734 694 / 34 172 = <b>21,5 år</b> etter 67, altså ved <b>88,5 år</b>. Lever hun lenger enn det, lønte det seg å vente.</p><p><b>Kontroll:</b> beholdningen faller ut av regnestykket. Innhentingstiden er 3 × 244 898 / (279 070 − 244 898), og når begge beløpene er beholdningen delt på et delingstall, blir det 3 × 17,20 / (19,60 − 17,20) = 51,6 / 2,4 = 21,5 år. ✓ Og ved 88,5 år har valget ved 64 gitt 244 898 × 24,5 = 6 000 001, valget ved 67 har gitt 279 070 × 21,5 = 6 000 005, begge lik 6 000 000 opp til avrundingen i årsbeløpene. ✓</p><p>Dette er samme regning som manualens gjennomregnede eksempel i 15.3, med andre tall. Bruddpunktet ligger godt over 64 + 19,60 = 83,6 år. Det er ingen motsigelse til at ordningen er nøytral: delingstallet ved 67 er forventet gjenstående levetid for dem som faktisk lever til 67, og nøytraliteten gjelder forventet samlet utbetaling, ikke et bestemt bruddpunkt.</p>",
      traps: [
        "Forspranget er delt på hele årsbeløpet til den som venter: 734 694 / 279 070 = 2,6 år etter 67. Men den som startet ved 64 fortsetter å få 244 898 i året, så bare differansen på 34 172 tar igjen forspranget.",
        "Uttaksalder pluss delingstall, 64 + 19,60, altså omtrent forventet levealder. Nøytralitet betyr lik forventet samlet utbetaling; bruddpunktet er alderen der de to summene faktisk er like, og den må regnes ut.",
        "Riktig innhentingstid, 21,5 år, men lagt til 64 i stedet for 67. Innhentingen begynner først når den som venter får sin første utbetaling ved 67.",
        null,
      ],
    },
    {
      id: "k15-9",
      topic: "Levealdersjustering",
      points: 3,
      body: "<p>Anne er født i 1964, og datteren Ida er født i 1994. Begge tar ut alderspensjon fra folketrygden som 67-åringer, og når de gjør det, har de like stor pensjonsbeholdning målt i G. Anta at forventet levealder fortsetter å øke, slik den har gjort siden pensjonsreformen i 2011.</p><p>Hvilken påstand om levealdersjusteringen er riktig?</p>",
      options: [
        "Delingstallet avhenger bare av uttaksalderen, så Anne og Ida får samme delingstall og like høy årlig pensjon målt i G.",
        "Ida får et høyere delingstall enn moren og dermed lavere årlig pensjon. Med samme beholdning må hun ta ut senere for å få like mye i året.",
        "Ida får et høyere delingstall enn moren og dermed høyere årlig pensjon, fordi hun ventes å leve lenger.",
        "Ida får et lavere delingstall enn moren, fordi delingstallet synker jo senere pensjonen tas ut, og hun tar den ut nesten 30 år senere.",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hva delingstallet er.</b> Delingstallet er tilnærmet forventet antall gjenstående leveår ved uttak. Det fastsettes endelig det året kullet fyller 61, og er felles for kvinner og menn.</p><p><b>Steg 2 — levealdersjusteringen.</b> Pensjonsreformen i 2011 knyttet delingstallet til kullets levealder. Lever 1994-kullet lenger enn 1964-kullet, har det flere forventede leveår igjen ved 67, og delingstallet ved 67 blir høyere for Ida enn for Anne.</p><p><b>Steg 3 — hva det gjør med pensjonen.</b> Årlig pensjon = beholdning / delingstall. Samme teller og større nevner gir mindre årlig pensjon. Skal Ida få like mye i året som moren med samme beholdning, trenger hun et lavere delingstall, og det får hun bare ved å ta ut senere.</p><p><b>Kontroll med tall [eksempeltall]:</b> med 50 G i beholdning og delingstall 17,20 for Anne og 18,50 for Ida blir pensjonen 50 / 17,20 = 2,9070 G mot 50 / 18,50 = 2,7027 G, altså 7,03 % lavere for Ida. Selve retningen er ren brøkregning og kan ikke feile: med fast teller og større nevner blir brøken mindre. ✓</p><p>Delingstallet beveger seg i to retninger, og det er dem de gale alternativene blander. Innenfor ett kull synker det med uttaksalderen, som i H2025 oppgave 14. Fra kull til kull, ved samme uttaksalder, stiger det når levealderen øker. Denne oppgaven spør om den andre.</p>",
      traps: [
        "Overser levealdersjusteringen. Delingstallet avhenger både av årskullet og av uttaksalderen, og justeringen for årskull var selve poenget med reformen i 2011.",
        null,
        "Riktig retning på delingstallet, men det er en divisor. Beholdningen fordeles på flere forventede leveår, så hvert år får mindre, ikke mer.",
        "Blander de to retningene. Delingstallet synker med uttaksalderen innenfor ett kull, men ved samme uttaksalder stiger det fra kull til kull når levealderen øker. Kalenderåret uttaket skjer i er ikke det som teller.",
      ],
    },
    {
      id: "k15-10",
      topic: "Jobbe til 67",
      points: 3,
      body: "<p>Håkon fyller 62 og har en pensjonsbeholdning på 48 G, altså kr 6 554 352 med G = 136 549 [eksempeltall; G er dagens regel]. Han tjener 8 G, altså kr 1 092 392, og vurderer å jobbe fem år til og ta ut hele alderspensjonen først som 67-åring. Delingstallet for kullet hans er 21,60 ved uttak som 62-åring og 17,50 ved uttak som 67-åring [eksempeltall]. Opptjeningen er 18,1 % av inntekt opp til 7,1 G [dagens regel]. Både beholdningen og lønnen følger lønnsveksten, så du kan regne i G og gjøre om til kroner med G = 136 549 til slutt.</p><p>Hvor stor blir den årlige alderspensjonen hvis han jobber til 67 og tar ut da?</p>",
      options: [
        "kr 344 062",
        "kr 374 534",
        "kr 424 671",
        "kr 431 027",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — fem nye opptjeningsår, med taket.</b> 8 G er over taket, så hvert år gir 18,1 % × 7,1 = 1,2851 G. Over fem år: 1,2851 × 5 = <b>6,4255 G</b>. Reguleringen trenger du ikke regne ut: beholdningen reguleres med G, så målt i G holder den verdien sin.</p><p><b>Steg 2 — beholdningen ved 67.</b> 48 + 6,4255 = <b>54,4255 G</b>.</p><p><b>Steg 3 — pensjonen ved 67.</b> Nå gjelder delingstallet for 67 år: 54,4255 / 17,50 = 3,110029 G, og 3,110029 × 136 549 = <b>424 671</b> kr i året.</p><p><b>Kontroll i kroner:</b> den nye opptjeningen er 6,4255 × 136 549 = 877 396, beholdningen blir 6 554 352 + 877 396 = 7 431 748, og 7 431 748 / 17,50 = 424 671. ✓</p><p><b>Kontroll av de to effektene:</b> ved uttak som 62-åring ville han fått 48 / 21,60 × 136 549 = 303 442. Økningen er 424 671 / 303 442 = 1,3995. Den skal være produktet av at beholdningen vokser, 54,4255 / 48 = 1,133865, og at delingstallet faller, 21,60 / 17,50 = 1,234286: 1,133865 × 1,234286 = 1,3995. ✓ Å jobbe lenger virker gjennom to kanaler samtidig, og de ganges, de legges ikke sammen.</p>",
      traps: [
        "Den nye beholdningen er delt på delingstallet for 62 år: 54,4255 / 21,60 × 136 549. Da er bare den ekstra opptjeningen med, ikke at delingstallet faller når uttaket utsettes.",
        "Beholdningen er holdt fast på 48 G: 48 / 17,50 × 136 549. Det er bare delingstallseffekten; de fem årene i jobb gir også 6,4255 G ny opptjening.",
        null,
        "Taket er glemt: 18,1 % × 8 × 5 = 7,24 G i stedet for 6,4255 G, som gir 55,24 / 17,50 × 136 549. Lønn over 7,1 G gir ingen opptjening.",
      ],
    },
    {
      id: "k15-11",
      topic: "Skatt på IPS-uttak",
      points: 3,
      body: "<p>Tone fyller 64 og har kr 480 000 på IPS-kontoen [eksempeltall]. Hun vil tømme kontoen så raskt reglene tillater, med like store årlige utbetalinger fra i år. Reglene er at utbetalingen må gå over minst ti år og minst til fylte 80 år [dagens regel]. Se bort fra avkastningen i utbetalingsperioden.</p><p>Tone har alderspensjon som mer enn dekker personfradraget. Satsene for hennes inntektsnivå [dagens regel]: skatt på alminnelig inntekt 22 %, marginalskatt på pensjonsinntekt 31,1 % (22 % + trygdeavgift 5,1 % + trinnskatt 4,0 %), eierskatt 37,84 %.</p><p>Hvor mye skatt betaler hun hvert år på IPS-utbetalingen?</p>",
      options: [
        "kr 6 600",
        "kr 9 330",
        "kr 10 560",
        "kr 11 352",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — utbetalingstiden.</b> Begge kravene må oppfylles, så utbetalingen varer i det lengste av de to: minst ti år, og minst fra 64 til 80, som er 16 år. Det blir <b>16 år</b>. Tiårsregelen binder bare for den som starter etter fylte 70.</p><p><b>Steg 2 — årlig utbetaling.</b> 480 000 / 16 = <b>30 000</b>.</p><p><b>Steg 3 — skatten.</b> Uttak fra IPS skattlegges som alminnelig inntekt, altså 22 %: 30 000 × 22 % = <b>6 600</b>. Det er ikke pensjonsinntekt, så det kommer verken trygdeavgift eller trinnskatt på. Marginalskatten på pensjonsinntekt i oppgaveteksten gjelder alderspensjonen hennes, ikke IPS-uttaket.</p><p><b>Kontroll:</b> satsen ut skal være den samme som satsen inn. Innskuddene ga fradrag i alminnelig inntekt med 22 %, og over hele utbetalingsperioden betaler hun 16 × 6 600 = 105 600 = 22 % × 480 000. ✓ Staten tar tilbake nøyaktig sin andel på 22 % av det som står på kontoen, verken mer eller mindre.</p>",
      traps: [
        null,
        "Uttaket er behandlet som pensjonsinntekt: 30 000 × 31,1 %. IPS-uttak er alminnelig inntekt og får verken trygdeavgift eller trinnskatt. Satsen for pensjonsinntekt står i teksten som en felle.",
        "Bare tiårsregelen er brukt: 480 000 / 10 = 48 000, og 48 000 × 22 % = 10 560. Utbetalingen må også vare til fylte 80 år, og fra 64 er det 16 år.",
        "Eierskatten er brukt på uttaket: 30 000 × 37,84 %. Den gjelder aksjeutbytte, aksjegevinst og uttak fra aksjesparekonto, ikke IPS.",
      ],
    },
    {
      id: "k15-12",
      topic: "IPS og formuesskatt",
      points: 3,
      body: "<p>Per er enslig og har ingen gjeld. I formuesskatteberegningen for 2026 står han med kr 1 200 000 i bank, kr 1 000 000 i et rent aksjefond utenfor IPS, og kr 400 000 på IPS-kontoen, plassert i det samme aksjefondet [eksempeltall]. For 2026 gjelder [dagens regel]: aksjefond verdsettes til 80 % av markedsverdien, bunnfradraget er kr 1 900 000 og formuesskattesatsen er 1,0 %.</p><p>Hvor mye lavere blir formuesskatten hans for 2026 fordi de 400 000 kronene står på IPS-kontoen og ikke i fondet utenfor?</p>",
      options: [
        "kr 800",
        "kr 3 200",
        "kr 4 000",
        "kr 4 200",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — formuesverdien pengene ville hatt utenfor IPS.</b> Aksjefond verdsettes til 80 %: 400 000 × 80 % = <b>320 000</b>.</p><p><b>Steg 2 — sjekk bunnfradraget.</b> Uten IPS-beløpet er formuesverdien 1 200 000 + 1 000 000 × 80 % = 2 000 000, som er over bunnfradraget på 1 900 000. Hver krone formuesverdi utover det koster derfor 1,0 %.</p><p><b>Steg 3 — besparelsen.</b> 320 000 × 1,0 % = <b>3 200</b>.</p><p><b>Kontroll, regn skatten begge veier:</b> med pengene i fondet utenfor blir formuesskatten (2 000 000 + 320 000 − 1 900 000) × 1,0 % = 4 200. Med pengene på IPS blir den (2 000 000 − 1 900 000) × 1,0 % = 1 000. 4 200 − 1 000 = 3 200. ✓</p><p>Fritaket gjelder bare beløpet på IPS-kontoen. Resten av formuen skattlegges som før, og H2024 oppgave 13b hadde nettopp «du slipper formuesskatt på hele formuen din» som galt alternativ. Legg også merke til steg 2: hadde resten av formuen ligget under bunnfradraget, ville fritaket vært verdt mindre enn 1 % av formuesverdien.</p>",
      traps: [
        "Rabatten og verdsettingsandelen er byttet om: 400 000 × 20 % × 1,0 %. Aksjefond har 20 % rabatt, altså verdsettes de til 80 %, og det er 80 % du skal gange med.",
        null,
        "Rabatten er glemt: 400 000 × 1,0 %. Utenfor IPS ville fondet bare kommet med 80 % av markedsverdien i grunnlaget.",
        "Hele formuesskatten, som om IPS fritar hele formuen. Fritaket gjelder bare beløpet på kontoen; bankinnskuddet og fondet utenfor skattlegges som før, så han betaler fortsatt 1 000.",
      ],
    },
    {
      id: "k15-13",
      topic: "Verdien av utsettelsen",
      points: 3,
      body: "<p>Kari er 32 år og vurderer å sette kr 25 000 på IPS [dagens maks, 2026] i et rentefond med 4 % årlig avkastning [eksempeltall], og la pengene stå i 30 år til hun er 62. Innskuddet gir fradrag i alminnelig inntekt, og uttaket skattlegges som alminnelig inntekt. Satsen er 22 % begge veier [dagens regel].</p><p>Alternativet er å droppe IPS. Da blir de 25 000 kronene i lønn til kr 19 500 etter 22 % skatt, og dem setter hun på en vanlig sparekonto med samme rente, der renten skattlegges med 22 % hvert år. Se bort fra formuesskatt. Oppgitt: 1,04<sup>30</sup> = 3,243398.</p><p>Hvor mye mer sitter hun igjen med etter skatt om 30 år med IPS enn med sparekontoen?</p>",
      options: [
        "kr 0",
        "kr 5 500",
        "kr 12 339",
        "kr 14 232",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — IPS.</b> Hele innskuddet står og vokser uten løpende skatt: 25 000 × 3,243398 = <b>81 085</b>. Uttaket skattlegges med 22 %: 81 085 × 22 % = 17 839. Netto: 81 085 − 17 839 = <b>63 246</b>.</p><p><b>Steg 2 — sparekontoen.</b> Renten skattlegges hvert år, så pengene vokser med renten etter skatt: 4 % × (1 − 0,22) = 3,12 %. 1,0312<sup>30</sup> = 2,513548, og 19 500 × 2,513548 = <b>49 014</b>. Ingen skatt ved uttak, den er betalt underveis.</p><p><b>Steg 3 — forskjellen.</b> 63 246 − 49 014 = <b>14 232</b>.</p><p><b>Kontroll, flytt skattesatsen til begynnelsen:</b> fordi satsen inn og satsen ut er den samme, er IPS netto det samme som 19 500 × 3,243398 = 63 246. Det er en identitet og kan ikke feile, men den viser hva som skjer: dine egne 19 500 vokser med 4 % i IPS og med 3,12 % på sparekontoen. Forskjellen er derfor 19 500 × (3,243398 − 2,513548) = 19 500 × 0,729850 = 14 232. ✓</p><p>Det er hele verdien av skatteutsettelsen: avkastningen på dine egne penger slipper den årlige skatten. Staten er en passiv medeier på 22 % og tar sin andel med avkastning ved uttak, så fradraget på 5 500 er ingen gevinst i seg selv. Fritaket for formuesskatt kommer i tillegg.</p>",
      traps: [
        "Sparekontoen er regnet med 4 % uten løpende renteskatt: 19 500 × 3,243398 = 63 246, like mye som IPS. At satsen er 22 % inn og 22 % ut betyr at det ikke er noen satsgevinst, men renten på sparekontoen skattlegges hvert år, og det slipper IPS.",
        "Fradraget i innskuddsåret, 22 % × 25 000, er regnet som gevinsten. Det er en utsettelse som staten henter igjen med avkastning ved uttak, ikke en gave.",
        "«Rentefritt lån fra staten» tatt bokstavelig: avkastningen på statens 5 500 over 30 år, 5 500 × (3,243398 − 1) = 12 339. Men staten tar 22 % av sluttverdien og dermed også avkastningen på sin egen andel. Gevinsten din er at avkastningen på dine egne 19 500 slipper den årlige renteskatten.",
        null,
      ],
    },
    {
      id: "k15-14",
      topic: "Innskuddspensjon ved uttak",
      points: 3,
      body: "<p>Emil er 42 år og tjener kr 700 000 i året [eksempeltall]. Regn alt reelt, i dagens kroner: lønnen holder seg på kr 700 000, og innskuddspensjonen gir 4 % årlig realavkastning [eksempeltall]. Kontoen står i dag på kr 300 000. Arbeidsgiveren setter inn 5 % av lønnen ved utgangen av hvert år i 25 år, det siste innskuddet når han fyller 67. Deretter utbetales kontoen som ti like store årlige beløp, det første ett år etter det siste innskuddet, mens det som står igjen fortsatt forrentes med 4 %. Oppgitt: 1,04<sup>25</sup> = 2,665836 og 1,04<sup>−10</sup> = 0,675564.</p><p>Hvor stor andel av lønnen utgjør den årlige utbetalingen fra innskuddspensjonen? Oppgi svaret med to desimaler.</p>",
      options: [
        "29,50 %",
        "30,96 %",
        "32,25 %",
        "39,76 %",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — startbeløpet vokser i 25 år.</b> 300 000 × 2,665836 = <b>799 751</b>.</p><p><b>Steg 2 — de årlige innskuddene.</b> Innskuddet er 5 % × 700 000 = 35 000 i året. Sluttverdifaktoren for 25 innskudd er (2,665836 − 1) / 0,04 = 41,6459, så innskuddene blir 35 000 × 41,6459 = <b>1 457 607</b>.</p><p><b>Steg 3 — kontoen ved 67.</b> 799 751 + 1 457 607 = <b>2 257 358</b>.</p><p><b>Steg 4 — utbetalingen er en annuitet.</b> Annuitetsfaktoren for ti år er (1 − 0,675564) / 0,04 = 8,1109. Årlig utbetaling: 2 257 358 / 8,1109 = <b>278 312</b>.</p><p><b>Steg 5 — andel av lønnen.</b> 278 312 / 700 000 = <b>39,76 %</b>.</p><p><b>Kontroll:</b> nåverdien av de ti utbetalingene skal gi kontoen tilbake. 278 312 × 8,1109 = 2 257 361, lik 2 257 358 opp til avrundingen. ✓</p><p>Dette er rutinen fra H2020 oppgave 5b–c og H2021 oppgave 7b–c: sluttverdi av startbeløp pluss innskudd, deretter fordelt på utbetalingsårene og målt mot lønnen. Merk hvor lenge den varer. Innskuddspensjon i privat sektor utbetales som regel over ti år, så de 39,76 prosentene stopper etter den siste utbetalingen når Emil er 77, mens folketrygden er livsvarig.</p>",
      traps: [
        "Innskuddene er summert uten avkastning, 25 × 35 000 = 875 000, mens startbeløpet er forrentet. Hvert innskudd står og vokser fram til 67, og det er det sluttverdifaktoren 41,6459 fanger opp.",
        "Startbeløpet på 300 000 er tatt med uten avkastning. Det står i 25 år og vokser til 300 000 × 2,665836 = 799 751.",
        "Kontoen er delt på 10 uten avkastning i utbetalingsperioden: 2 257 358 / 10 = 225 736. Det som står igjen, forrentes mens det betales ut, så beløpet per år er en annuitet: 2 257 358 / 8,1109.",
        null,
      ],
    },
    {
      id: "k15-15",
      topic: "Hvem bærer risikoen",
      points: 3,
      body: "<p>Aina og Bjørn er 35 år og tjener like mye. Aina har innskuddspensjon: arbeidsgiveren setter inn 5 % av lønnen hvert år. Bjørn har ytelsespensjon: arbeidsgiveren har lovet ham 66 % av sluttlønnen inkludert folketrygden, livsvarig [eksempeltall]. De neste 30 årene blir avkastningen på pensjonsmidlene klart lavere enn både ordningene og de to hadde regnet med.</p><p>Hvilken påstand er riktig?</p>",
      options: [
        "Aina får lavere pensjon. Bjørns pensjon er uendret, fordi arbeidsgiveren hans må betale inn mer for å oppfylle løftet om ytelsen.",
        "Begge får lavere pensjon, fordi begge ordningene er fondert og pensjonen følger avkastningen på midlene.",
        "Bjørn får lavere pensjon, mens Aina er skjermet, fordi arbeidsgiveren hennes har forpliktet seg til et fast innskudd hvert år.",
        "Ingen av dem får lavere pensjon: Aina har fått innskuddene lovet og Bjørn ytelsen, og begge løftene holdes.",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — hva er avtalt?</b> I Ainas ordning er innskuddet avtalt, 5 % av lønnen. I Bjørns ordning er ytelsen avtalt, 66 % av sluttlønnen.</p><p><b>Steg 2 — hvem bærer risikoen?</b> Den parten som ikke har fått noe avtalt, bærer risikoen. Ainas pensjon er det innskuddene vokser til, så lavere avkastning gir henne lavere pensjon. Bjørns pensjon ligger fast, og det er arbeidsgiveren hans som må skyte inn mer når fondet vokser saktere enn forutsatt.</p><p><b>Kontroll med tall [eksempeltall]:</b> sett Ainas innskudd til 30 000 i året i 30 år. Med 5 % avkastning blir kontoen 30 000 × (1,05<sup>30</sup> − 1) / 0,05 = 30 000 × 66,4388 = 1 993 164. Med 3 % blir den 30 000 × (1,03<sup>30</sup> − 1) / 0,03 = 30 000 × 47,5754 = 1 427 262, altså 28,4 % mindre. Innskuddene er de samme i begge tilfellene; det er pensjonen som tar støyten. ✓</p><p>De andre forskjellene følger av det samme: Aina velger selv risikoprofil (H2025 oppgave 17), kontoen hennes blir et pensjonskapitalbevis ved jobbytte og arves ved dødsfall, og den utbetales som regel over ti år. Bjørn får en fripolise ved jobbytte, og ytelsen er livsvarig. H2024 oppgave 13a spør om nøyaktig dette skillet, og standarddistraktoren der er de to ordningene byttet om.</p>",
      traps: [
        null,
        "At begge er fonderte, betyr ikke at begge ansatte bærer avkastningsrisikoen. I ytelsesordningen er det arbeidsgiveren som må dekke gapet mellom fondet og den lovede ytelsen.",
        "Ordningene er byttet om. Et fast innskudd sier ingenting om hva pensjonen blir, og det er nettopp derfor Aina bærer risikoen; det er Bjørn som har fått utbetalingen lovet.",
        "Et lovet innskudd er ikke en lovet pensjon. Innskuddene holdes, men de vokser til mindre, så Ainas pensjon faller.",
      ],
    },
  ],
};
