/* Kapittel 18 — Finansiell psykologi */
window.EDU_DATA.chapterTasks[18] = {
  minutes: 20,
  tasks: [
    {
      id: "k18-1",
      topic: "Overkonfidens",
      points: 3,
      body: "<p>Jonas har en aksjeportefølje på kr 500 000. Han mener han kjenner de norske selskapene bedre enn markedet gjør, og gjør 240 handler i året [eksempeltall]. Gjennomsnittlig handelsbeløp er kr 25 000. Kurtasjen er kr 79 per handel, og spreaden koster ham i tillegg 0,20 % av handelsbeløpet på hver handel. Markedet gir 7,0 % forventet avkastning i året før kostnader, og Jonas velger i snitt like godt som gjennomsnittet av alle investorer.</p><p>Hvor mange prosentpoeng av den forventede avkastningen spiser handelskostnadene opp?</p>",
      options: ["2,40 prosentpoeng", "3,79 prosentpoeng", "6,19 prosentpoeng", "12,38 prosentpoeng"],
      answer: 2,
      solution: "<p><b>Steg 1 — kurtasjen.</b> 240 × 79 = <b>kr 18 960</b>.</p><p><b>Steg 2 — spreaden.</b> Den regnes av beløpet som omsettes, ikke av porteføljen: 240 × 25 000 × 0,20 % = 240 × 50 = <b>kr 12 000</b>.</p><p><b>Steg 3 — samlet kostnad.</b> 18 960 + 12 000 = <b>kr 30 960</b>.</p><p><b>Steg 4 — målt mot porteføljen.</b> 30 960 / 500 000 = <b>6,19 prosentpoeng</b>. Av de 7,0 prosentene står det igjen 0,81 % til Jonas.</p><p><b>Kontroll per handel:</b> hver handel koster 79 + 25 000 × 0,20 % = 79 + 50 = kr 129, og 240 × 129 = 30 960. ✓ Samme tall, annen vei.</p><p>Legg merke til hva som <i>ikke</i> står i regnestykket: ingenting om at Jonas var uheldig med aksjevalget. Markedet er gjennomsnittet av alle investorer før kostnader, så den som velger like godt som snittet, får snittet minus det han betaler for å velge. Kostnaden er proporsjonal med hvor ofte han handler, og det er overkonfidensen som bestemmer frekvensen. Forelesningens eget tall er av samme slag: 3 600 handler à kr 79 er kr 284 400 i ren kurtasje.</p>",
      traps: [
        "Bare spreaden er tatt med: 12 000 / 500 000. Kurtasjen på kr 79 per handel mangler.",
        "Bare kurtasjen er tatt med: 18 960 / 500 000. Spreaden er en like reell kostnad, og her er den nesten like stor.",
        null,
        "Hver av de 240 handlene er talt som en rundtur, altså både et kjøp og et salg. Oppgaven oppgir 240 handler, ikke 240 rundturer.",
      ],
    },
    {
      id: "k18-2",
      topic: "Disposisjonseffekten",
      points: 3,
      body: "<p>Ida trenger kr 200 000 i kontanter og skal selge én av to poster. Aksje A er kjøpt for kr 120 000 og er verdt kr 200 000 i dag. Aksje B er kjøpt for kr 275 000 og er verdt kr 200 000 i dag. Begge har delt ut utbytte som hvert år har oversteget skjermingsfradraget, så ingen av dem har ubenyttet skjerming til framføring. Eierskatten på aksjegevinst er 37,84 %, altså oppjusteringsfaktoren 1,72 ganger 22 % [dagens regel], og et realisert aksjetap gir fradrag med samme sats. Ida føler at det er lettest å selge A, «for den har gått bra».</p><p>Hvor mye mer sitter Ida igjen med i år hvis hun selger B i stedet for A?</p>",
      options: ["kr 34 100", "kr 58 652", "kr 100 881", "kr 155 000"],
      answer: 1,
      solution: "<p><b>Steg 1 — de to latente resultatene.</b> A: 200 000 − 120 000 = kr 80 000 i gevinst. B: 200 000 − 275 000 = kr 75 000 i tap.</p><p><b>Steg 2 — selger hun vinneren A.</b> Skatt: 80 000 × 37,84 % = kr 30 272. Igjen etter skatt: 200 000 − 30 272 = <b>kr 169 728</b>.</p><p><b>Steg 3 — selger hun taperen B.</b> Tapet gir fradrag med samme sats: 75 000 × 37,84 % = kr 28 380 i redusert skatt. Igjen etter skatt: 200 000 + 28 380 = <b>kr 228 380</b>.</p><p><b>Steg 4 — forskjellen.</b> 228 380 − 169 728 = <b>kr 58 652</b>.</p><p><b>Kontroll den andre veien:</b> forskjellen i realisert skattemessig resultat er 80 000 − (−75 000) = 155 000, og 155 000 × 37,84 % = 58 652. ✓ Samme tall.</p><p>Merk hva forskjellen egentlig er. Å realisere en gevinst er å betale skatt tidlig; å realisere et tap er å hente fradraget tidlig. Disposisjonseffekten velger begge deler feil vei. Selger Ida den andre posten senere, snur kontantstrømmen, men i mellomtiden har hun 58 652 kroner mer å forrente, altså et rentefritt lån fra staten. Og kjøpskursen sier uansett ingenting om framtiden: to som eier samme aksje til samme kurs i dag, skal ta samme beslutning.</p>",
      traps: [
        "Oppjusteringen er glemt: 155 000 × 22 %. Aksjeinntekt oppjusteres med 1,72 før 22-prosenten, både på gevinst og på tap.",
        null,
        "Oppjustert to ganger: 155 000 × 1,72 × 1,72 × 22 %. Faktoren brukes én gang, enten på grunnlaget eller innbakt i satsen 37,84 %.",
        "Forskjellen i skattemessig resultat, men uten å gange med skattesatsen. Det er grunnlaget, ikke skatten.",
      ],
    },
    {
      id: "k18-3",
      topic: "Mental regnskapsføring",
      points: 3,
      body: "<p>Mari har kr 120 000 på en sparekonto til 3,0 % rente [eksempeltall] og kr 120 000 i forbrukslån til 14,0 % rente [eksempeltall]. Hun kaller sparekontoen «bufferen» og lånet «bilen», og lar begge stå urørt. Renteinntekt er alminnelig inntekt og skattlegges med 22 %, og renteutgift gir fradrag i alminnelig inntekt med de samme 22 % [dagens regel].</p><p>Hvor mye høyere blir Maris formue om ett år hvis hun bruker hele innskuddet til å nedbetale lånet?</p>",
      options: [
        "Ingenting: hun flytter bare penger, og nettoformuen er den samme før og etter",
        "kr 8 205",
        "kr 9 504",
        "kr 10 296",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — innskuddsrenten etter skatt.</b> 3,0 % × (1 − 0,22) = <b>2,34 %</b>.</p><p><b>Steg 2 — lånerenten etter skatt.</b> Fradraget gjør lånet billigere med samme sats: 14,0 % × (1 − 0,22) = <b>10,92 %</b>.</p><p><b>Steg 3 — rentedifferansen.</b> 10,92 % − 2,34 % = <b>8,58 prosentpoeng</b>.</p><p><b>Steg 4 — i kroner.</b> 120 000 × 8,58 % = <b>kr 10 296</b> i året.</p><p><b>Kontroll den andre veien:</b> før skatt er differansen 120 000 × (14,0 % − 3,0 %) = kr 13 200, og siden begge sider treffes av de samme 22 prosentene, er beløpet etter skatt 13 200 × 0,78 = 10 296. ✓</p><p>Feilen er ikke regnefeil, men merkelapper. Mental regnskapsføring merker penger etter kilde og formål i stedet for å telle dem som én formue. Balansen ser uendret ut, og det er nettopp derfor avviket overlever: nettoformuen er kr 0 begge veier, men de to postene forrenter seg med svært ulik sats, og differansen er en ren, sikker og skattefri avkastning på kr 10 296. Ingen plassering i kapittel 14 gir noe i nærheten av 8,58 % risikofritt.</p>",
      traps: [
        "Bare balansen er sett på, ikke rentene. Nettoformuen er riktignok uendret, men de to postene forrenter seg med 2,34 % og 10,92 %, og det er differansen som er gevinsten.",
        "Eierskatten på 37,84 % er brukt på rentene. Renteinntekt og renteutgift er alminnelig inntekt og treffes av 22 %; oppjusteringen gjelder aksjeinntekt.",
        "Fradraget på lånet er regnet med, men skatten på renteinntekten er glemt: 10,92 % − 3,0 %. Innskuddsrenten skattlegges også.",
        null,
      ],
    },
    {
      id: "k18-4",
      topic: "Hjemmebias",
      points: 3,
      body: "<p>Petter jobber i oljeservice og har en aksjeportefølje på kr 1 500 000. I tråd med det Døskeland og Hvide finner for nordmenn flest, ligger 32 % av porteføljen i selskaper i hans egen bransje, og på den delen får han i snitt 3 prosentpoeng lavere årlig avkastning enn på resten. Norge utgjør 0,2 % av verdens aksjemarked.</p><p>Hva koster bransjekonsentrasjonen Petter per år, og hvor mye utgjør det målt mot hele porteføljen?</p>",
      options: [
        "kr 960 i året, altså 0,06 prosentpoeng",
        "kr 14 400 i året, altså 3,00 prosentpoeng",
        "kr 14 400 i året, altså 0,96 prosentpoeng",
        "kr 45 000 i året, altså 3,00 prosentpoeng",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — hvor stor er den konsentrerte delen.</b> 1 500 000 × 32 % = <b>kr 480 000</b>.</p><p><b>Steg 2 — mindreavkastningen treffer bare den delen.</b> 480 000 × 3 % = <b>kr 14 400</b> i året.</p><p><b>Steg 3 — målt mot hele porteføljen.</b> 14 400 / 1 500 000 = <b>0,96 prosentpoeng</b>. De 3 prosentpoengene gjelder 32 % av kapitalen, så virkningen på totalavkastningen er 0,32 × 3 = 0,96.</p><p><b>Kontroll:</b> 0,96 % × 1 500 000 = 14 400. ✓</p><p>Kroneprisen er likevel den minste delen av regningen. Poenget med hjemmebias er ikke at norske selskaper er dårlige, men at eksponeringen er dobbel: humankapitalen din er allerede en stor, udiversifisert posisjon i norsk økonomi og i din egen bransje. Går det dårlig med oljeservice, mister Petter jobben samtidig som 480 000 av porteføljen faller. Det ekstra kjennskapet er ikke bare gratis, det er negativt betalt: 3 prosentpoeng i året <i>og</i> høyere samvariasjon med resten av formuen.</p>",
      traps: [
        "Norges andel av verdensmarkedet, 0,2 %, er brukt som mindreavkastning. De to tallene måler helt ulike ting: 0,2 % er en vekt i verdensindeksen, 3 prosentpoeng er en avkastningsforskjell.",
        "Riktig kronebeløp, men prosentpoengene er regnet av de 480 000 i stedet for av hele porteføljen på 1 500 000.",
        null,
        "De 3 prosentpoengene er brukt på hele porteføljen. Bare 32 % av kapitalen ligger i egen bransje, og bare den delen har mindreavkastningen.",
      ],
    },
    {
      id: "k18-5",
      topic: "Forankring og flokkatferd",
      points: 3,
      body: "<p>Sindre eier 2 000 aksjer i et børsnotert flyselskap, kjøpt for kr 60 stykket. Kursen står fortsatt i kr 60 [eksempeltall]. Selskapet har nettopp varslet en emisjon til kr 6–10 per aksje, som vil vanne ut dagens eiere kraftig. Sindre resonnerer slik: «Kursen har ligget rundt 60 i månedsvis, så 60 er det aksjen faktisk er verdt.» Deretter sjekker han investorforumet, ser at nesten ingen andre selger, og tenker: «Da er det ingen grunn til at jeg skal være den som går ut.» Han beholder aksjene. Noen uker senere kollapser kursen.</p><p>Hvilke to avvik ligger bak Sindres to begrunnelser, i den rekkefølgen han bruker dem?</p>",
      options: [
        "Først forankring, deretter flokkatferd",
        "Først disposisjonseffekten, deretter overkonfidens",
        "Først overkonfidens, deretter forankring",
        "Først tapsaversjon, deretter mental regnskapsføring",
      ],
      answer: 0,
      solution: "<p><b>Den første begrunnelsen er forankring.</b> Det første tallet Sindre så, kursen på 60, styrer vurderingen hans, og den nye opplysningen som faktisk inneholder informasjon om verdien, emisjonskursen på 6–10, får ikke flytte den. Forankring er å la et tall som er tilgjengelig, men irrelevant, sette rammen for anslaget.</p><p><b>Den andre er flokkatferd.</b> Han erstatter egen analyse med observasjonen av hva de andre gjør. Merk at han ikke påstår at han vet mer enn markedet; han lener seg tvert imot på markedet og på forumet.</p><p>Dette er nøyaktig mekanismen i Norwegian-caset fra januar 2021: aksjen sto i kr 60 med en varslet emisjon til kr 6–10, prisen falt likevel ikke, over halvparten av eierne trodde på oppgang, og først da en ekspertvideo kom, solgte 21 % dagen etter. To ting skal du kunne herfra: feilprising kan vare lenge når aksjen er vanskelig å shorte, og store, likvide markeder er derfor langt mer effisiente enn små.</p>",
      traps: [
        null,
        "Disposisjonseffekten handler om å velge hvilken post man selger ut fra kjøpskursen, altså å selge vinnere og beholde tapere. Sindre er verken i gevinst eller tap, og den andre begrunnelsen er at andre gjør det samme, ikke at han vet bedre.",
        "Rekkefølgen er snudd, og overkonfidens passer ikke: den er å tro at du vet mer om selskapet enn markedet gjør. Sindre gjør det motsatte og lener seg på markedet og på forumet.",
        "Tapsaversjon forklarer hvorfor det gjør vondt å selge, men Sindre begrunner ikke med noe tap, og mental regnskapsføring krever at penger merkes etter kilde eller formål, noe ingenting i scenarioet gjør.",
      ],
    },
    {
      id: "k18-6",
      topic: "Mottiltak",
      points: 3,
      body: "<p>To forsøk fra forelesningen står side om side. I det første fikk halvparten av rundt 590 norske fondskunder Forbrukerrådets tall for aktive fond mot indeks; indeksandelen i gruppen steg fra 11 % til 15 %, og effekten holdt seg i to år. I det andre forsto deltakerne argumentet mot hjemmebias, og endret likevel ingenting i porteføljen. I tillegg finner Fernandes og medforfattere (2014) at generelle finansundervisningsprogrammer forklarer omtrent 0,1 % av variasjonen i atferd, mens automatisk pensjonssparing øker sannsynligheten for at folk sparer med rundt 50 %.</p><p>Hvilken konklusjon følger av disse resultatene?</p>",
      options: [
        "Økningen på 4 prosentpoeng er så liten at informasjon må avskrives som virkemiddel; bare innlåsing av pengene, som i IPS, endrer atferd",
        "Økningen er 4 prosentpoeng, altså drøyt en tredjedel relativt: et konkret og lett etterprøvbart råd kan rette en feilslutning, mens avvik som informasjon ikke biter på, må omgås med en regel som binder atferden på forhånd",
        "Forsøkene viser at finansundervisning virker, og at flere generelle kurs i personlig økonomi derfor er det billigste tiltaket mot alle de åtte avvikene",
        "Hjemmebias endret seg ikke fordi den er en legitim preferanse for selskaper man kjenner, og en preferanse kan ikke være feil, bare dyr",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hvor stor var effekten egentlig.</b> Fra 11 % til 15 % er 4 prosentpoeng, men målt relativt: (15 − 11) / 11 = <b>36,4 %</b>, altså drøyt en tredjedel flere som valgte indeks. Effekten holdt seg i to år, og andelen som trodde de kunne slå markedet, falt med 12 %. Det er ikke en neglisjerbar effekt.</p><p><b>Steg 2 — hvorfor virket det ene og ikke det andre.</b> Fondsrådet var konkret, gjaldt ett enkelt valg, og var lett å etterprøve. Hjemmebias-argumentet ble forstått, men handlingen uteble, og generell undervisning forklarer omtrent 0,1 % av variasjonen i atferd.</p><p><b>Steg 3 — hva som da gjenstår.</b> Regler som virker uten at du må ta beslutningen på nytt hver gang: globalt indeksfond mot overkonfidens og hjemmebias, automatisk månedlig sparing mot forankring og flokkatferd, IPS og obligatorisk tjenestepensjon mot manglende selvkontroll, og en skriftlig investeringsplan mot resten. Standardvalg er den sterkeste enkeltmekanismen: automatisk pensjonssparing øker sannsynligheten for å spare med rundt 50 %.</p><p><b>Kontroll:</b> 11 % × 1,364 = 15,0 %. ✓</p>",
      traps: [
        "Feilen er å lese 4 prosentpoeng som en liten effekt. Utgangspunktet var 11 %, så økningen er drøyt en tredjedel relativt, og den holdt seg i to år.",
        null,
        "Forsøket ga ett konkret råd om ett bestemt valg, ikke undervisning. Fernandes og medforfattere finner at generelle programmer forklarer omtrent 0,1 % av variasjonen i atferd.",
        "Hjemmebias er en feilslutning, ikke en preferanse: den øker samvariasjonen med humankapitalen din, og det er nøyaktig det diversifisering skal fjerne. At et råd ikke virker, gjør ikke avviket legitimt.",
      ],
    },
  ],
};
