/* Kapittel 18 — Finansiell psykologi */
window.EDU_DATA.chapterTasks[18] = {
  minutes: 30,
  tasks: [
    {
      id: "k18-1",
      topic: "Overkonfidens",
      points: 3,
      body: "<p>Jonas har en aksjeportefølje på kr 500 000. Han mener han kjenner de norske selskapene bedre enn markedet gjør, og gjør 240 handler i året [eksempeltall]. Gjennomsnittlig handelsbeløp er kr 25 000. Kurtasjen er kr 79 per handel, og spreaden koster ham i tillegg 0,20 % av handelsbeløpet på hver handel. Markedet gir 7,0 % forventet avkastning i året før kostnader, og Jonas velger i snitt like godt som gjennomsnittet av alle investorer.</p><p>Hvor mange prosentpoeng av den forventede avkastningen spiser handelskostnadene opp?</p>",
      options: ["2,40 prosentpoeng", "3,79 prosentpoeng", "6,19 prosentpoeng", "12,38 prosentpoeng"],
      answer: 2,
      solution: "<p><b>Steg 1 — kurtasjen.</b> 240 × 79 = <b>kr 18 960</b>.</p><p><b>Steg 2 — spreaden.</b> Den regnes av beløpet som omsettes, ikke av porteføljen: 240 × 25 000 × 0,20 % = 240 × 50 = <b>kr 12 000</b>.</p><p><b>Steg 3 — samlet kostnad.</b> 18 960 + 12 000 = <b>kr 30 960</b>.</p><p><b>Steg 4 — målt mot porteføljen.</b> 30 960 / 500 000 = <b>6,19 prosentpoeng</b>. Av de 7,0 prosentene står det igjen 0,81 % til Jonas.</p><p><b>Kontroll per handel:</b> hver handel koster 79 + 25 000 × 0,20 % = 79 + 50 = kr 129, og 240 × 129 = 30 960. ✓ Samme tall, annen vei.</p><p>Legg merke til hva som <i>ikke</i> står i regnestykket: ingenting om at Jonas var uheldig med aksjevalget. Markedet er gjennomsnittet av alle investorer før kostnader, så den som velger like godt som snittet, får snittet minus det han betaler for å velge. Kostnaden er proporsjonal med hvor ofte han handler, og det er overkonfidensen som bestemmer frekvensen. Forelesningens eget tall er av samme slag: 3 600 handler à kr 79 er kr 284 400 i ren kurtasje.</p>",
      traps: [
        "Bare spreaden er tatt med: 12 000 / 500 000. Kurtasjen på kr 79 per handel mangler.",
        "Bare kurtasjen er tatt med: 18 960 / 500 000. Spreaden er en like reell kostnad, og her er den nesten like stor.",
        null,
        "Hver av de 240 handlene er talt som en rundtur, altså både et kjøp og et salg. Oppgaven oppgir 240 handler, ikke 240 rundturer.",
      ],
    },
    {
      id: "k18-2",
      topic: "Disposisjonseffekten",
      points: 3,
      body: "<p>Ida trenger kr 200 000 i kontanter og skal selge én av to poster. Aksje A er kjøpt for kr 120 000 og er verdt kr 200 000 i dag. Aksje B er kjøpt for kr 275 000 og er verdt kr 200 000 i dag. Begge har delt ut utbytte som hvert år har oversteget skjermingsfradraget, så ingen av dem har ubenyttet skjerming til framføring. Eierskatten på aksjegevinst er 37,84 %, altså oppjusteringsfaktoren 1,72 ganger 22 % [dagens regel], og et realisert aksjetap gir fradrag med samme sats. Ida føler at det er lettest å selge A, «for den har gått bra».</p><p>Hvor mye mer sitter Ida igjen med i år hvis hun selger B i stedet for A?</p>",
      options: ["kr 34 100", "kr 58 652", "kr 100 881", "kr 155 000"],
      answer: 1,
      solution: "<p><b>Steg 1 — de to latente resultatene.</b> A: 200 000 − 120 000 = kr 80 000 i gevinst. B: 200 000 − 275 000 = −75 000, altså kr 75 000 i tap.</p><p><b>Steg 2 — selger hun vinneren A.</b> Skatt: 80 000 × 37,84 % = kr 30 272. Igjen etter skatt: 200 000 − 30 272 = <b>kr 169 728</b>.</p><p><b>Steg 3 — selger hun taperen B.</b> Tapet gir fradrag med samme sats: 75 000 × 37,84 % = kr 28 380 i redusert skatt. Igjen etter skatt: 200 000 + 28 380 = <b>kr 228 380</b>.</p><p><b>Steg 4 — forskjellen.</b> 228 380 − 169 728 = <b>kr 58 652</b>.</p><p><b>Kontroll den andre veien:</b> forskjellen i realisert skattemessig resultat er 80 000 − (−75 000) = 155 000, og 155 000 × 37,84 % = 58 652. ✓ Samme tall.</p><p>Merk hva forskjellen egentlig er. Å realisere en gevinst er å betale skatt tidlig; å realisere et tap er å hente fradraget tidlig. Disposisjonseffekten velger begge deler feil vei. Selger Ida den andre posten senere, snur kontantstrømmen, men i mellomtiden har hun 58 652 kroner mer å forrente, altså et rentefritt lån fra staten. Og kjøpskursen sier uansett ingenting om framtiden: to som eier samme aksje til samme kurs i dag, skal ta samme beslutning.</p>",
      traps: [
        "Oppjusteringen er glemt: 155 000 × 22 %. Aksjeinntekt oppjusteres med 1,72 før 22-prosenten, både på gevinst og på tap.",
        null,
        "Oppjustert to ganger: 155 000 × 1,72 × 1,72 × 22 %. Faktoren brukes én gang, enten på grunnlaget eller innbakt i satsen 37,84 %.",
        "Forskjellen i skattemessig resultat, men uten å gange med skattesatsen. Det er grunnlaget, ikke skatten.",
      ],
    },
    {
      id: "k18-3",
      topic: "Mental regnskapsføring",
      points: 3,
      body: "<p>Mari har kr 120 000 på en sparekonto til 3,0 % rente [eksempeltall] og kr 120 000 i forbrukslån til 14,0 % rente [eksempeltall]. Hun kaller sparekontoen «bufferen» og lånet «bilen», og lar begge stå urørt. Renteinntekt er alminnelig inntekt og skattlegges med 22 %, og renteutgift gir fradrag i alminnelig inntekt med de samme 22 % [dagens regel].</p><p>Hvor mye høyere blir Maris formue om ett år hvis hun bruker hele innskuddet til å nedbetale lånet?</p>",
      options: [
        "Ingenting: hun flytter bare penger, og nettoformuen er den samme før og etter",
        "kr 8 205",
        "kr 9 504",
        "kr 10 296",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — innskuddsrenten etter skatt.</b> 3,0 % × (1 − 0,22) = <b>2,34 %</b>.</p><p><b>Steg 2 — lånerenten etter skatt.</b> Fradraget gjør lånet billigere med samme sats: 14,0 % × (1 − 0,22) = <b>10,92 %</b>.</p><p><b>Steg 3 — rentedifferansen.</b> 10,92 % − 2,34 % = <b>8,58 prosentpoeng</b>.</p><p><b>Steg 4 — i kroner.</b> 120 000 × 8,58 % = <b>kr 10 296</b> i året.</p><p><b>Kontroll den andre veien:</b> før skatt er differansen 120 000 × (14,0 % − 3,0 %) = kr 13 200, og siden begge sider treffes av de samme 22 prosentene, er beløpet etter skatt 13 200 × 0,78 = 10 296. ✓</p><p>Feilen er ikke regnefeil, men merkelapper. Mental regnskapsføring merker penger etter kilde og formål i stedet for å telle dem som én formue. Balansen ser uendret ut, og det er nettopp derfor avviket overlever: nettoformuen er kr 0 begge veier, men de to postene forrenter seg med svært ulik sats, og differansen er en ren, sikker og skattefri avkastning på kr 10 296. Ingen plassering i kapittel 14 gir noe i nærheten av 8,58 % risikofritt.</p>",
      traps: [
        "Bare balansen er sett på, ikke rentene. Nettoformuen er riktignok uendret, men de to postene forrenter seg med 2,34 % og 10,92 %, og det er differansen som er gevinsten.",
        "Eierskatten på 37,84 % er brukt på rentene. Renteinntekt og renteutgift er alminnelig inntekt og treffes av 22 %; oppjusteringen gjelder aksjeinntekt.",
        "Fradraget på lånet er regnet med, men skatten på renteinntekten er glemt: 10,92 % − 3,0 %. Innskuddsrenten skattlegges også.",
        null,
      ],
    },
    {
      id: "k18-4",
      topic: "Hjemmebias",
      points: 3,
      body: "<p>Petter jobber i oljeservice og har en aksjeportefølje på kr 1 500 000. I tråd med det Døskeland og Hvide finner for nordmenn flest, ligger 32 % av porteføljen i selskaper i hans egen bransje, og på den delen får han i snitt 3 prosentpoeng lavere årlig avkastning enn på resten. Norge utgjør 0,2 % av verdens aksjemarked.</p><p>Hva koster bransjekonsentrasjonen Petter per år, og hvor mye utgjør det målt mot hele porteføljen?</p>",
      options: [
        "kr 960 i året, altså 0,06 prosentpoeng",
        "kr 14 400 i året, altså 3,00 prosentpoeng",
        "kr 14 400 i året, altså 0,96 prosentpoeng",
        "kr 45 000 i året, altså 3,00 prosentpoeng",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — hvor stor er den konsentrerte delen.</b> 1 500 000 × 32 % = <b>kr 480 000</b>.</p><p><b>Steg 2 — mindreavkastningen treffer bare den delen.</b> 480 000 × 3 % = <b>kr 14 400</b> i året.</p><p><b>Steg 3 — målt mot hele porteføljen.</b> 14 400 / 1 500 000 = <b>0,96 prosentpoeng</b>. De 3 prosentpoengene gjelder 32 % av kapitalen, så virkningen på totalavkastningen er 0,32 × 3 = 0,96.</p><p><b>Kontroll:</b> 0,96 % × 1 500 000 = 14 400. ✓</p><p>Kroneprisen er likevel den minste delen av regningen. Poenget med hjemmebias er ikke at norske selskaper er dårlige, men at eksponeringen er dobbel: humankapitalen din er allerede en stor, udiversifisert posisjon i norsk økonomi og i din egen bransje. Går det dårlig med oljeservice, mister Petter jobben samtidig som 480 000 av porteføljen faller. Det ekstra kjennskapet er ikke bare gratis, det er negativt betalt: 3 prosentpoeng i året <i>og</i> høyere samvariasjon med resten av formuen.</p>",
      traps: [
        "Norges andel av verdensmarkedet, 0,2 %, er brukt som mindreavkastning. De to tallene måler helt ulike ting: 0,2 % er en vekt i verdensindeksen, 3 prosentpoeng er en avkastningsforskjell.",
        "Riktig kronebeløp, men prosentpoengene er regnet av de 480 000 i stedet for av hele porteføljen på 1 500 000.",
        null,
        "De 3 prosentpoengene er brukt på hele porteføljen. Bare 32 % av kapitalen ligger i egen bransje, og bare den delen har mindreavkastningen.",
      ],
    },
    {
      id: "k18-5",
      topic: "Forankring og flokkatferd",
      points: 3,
      body: "<p>Sindre eier 2 000 aksjer i et børsnotert flyselskap, kjøpt for kr 60 stykket. Kursen står fortsatt i kr 60 [eksempeltall]. Selskapet har nettopp varslet en emisjon til kr 6–10 per aksje, som vil vanne ut dagens eiere kraftig. Sindre resonnerer slik: «Kursen har ligget rundt 60 i månedsvis, så 60 er det aksjen faktisk er verdt.» Deretter sjekker han investorforumet, ser at nesten ingen andre selger, og tenker: «Da er det ingen grunn til at jeg skal være den som går ut.» Han beholder aksjene. Noen uker senere kollapser kursen.</p><p>Hvilke to avvik ligger bak Sindres to begrunnelser, i den rekkefølgen han bruker dem?</p>",
      options: [
        "Først forankring, deretter flokkatferd",
        "Først disposisjonseffekten, deretter overkonfidens",
        "Først overkonfidens, deretter forankring",
        "Først tapsaversjon, deretter mental regnskapsføring",
      ],
      answer: 0,
      solution: "<p><b>Den første begrunnelsen er forankring.</b> Det første tallet Sindre så, kursen på 60, styrer vurderingen hans, og den nye opplysningen som faktisk inneholder informasjon om verdien, emisjonskursen på 6–10, får ikke flytte den. Forankring er å la et tall som er tilgjengelig, men irrelevant, sette rammen for anslaget.</p><p><b>Den andre er flokkatferd.</b> Han erstatter egen analyse med observasjonen av hva de andre gjør. Merk at han ikke påstår at han vet mer enn markedet; han lener seg tvert imot på markedet og på forumet.</p><p>Dette er nøyaktig mekanismen i Norwegian-caset fra januar 2021: aksjen sto i kr 60 med en varslet emisjon til kr 6–10, prisen falt likevel ikke, over halvparten av eierne trodde på oppgang, og først da en ekspertvideo kom, solgte 21 % dagen etter. To ting skal du kunne herfra: feilprising kan vare lenge når aksjen er vanskelig å shorte, og store, likvide markeder er derfor langt mer effisiente enn små.</p>",
      traps: [
        null,
        "Disposisjonseffekten handler om å velge hvilken post man selger ut fra kjøpskursen, altså å selge vinnere og beholde tapere. Sindre er verken i gevinst eller tap, og den andre begrunnelsen er at andre gjør det samme, ikke at han vet bedre.",
        "Rekkefølgen er snudd, og overkonfidens passer ikke: den er å tro at du vet mer om selskapet enn markedet gjør. Sindre gjør det motsatte og lener seg på markedet og på forumet.",
        "Tapsaversjon forklarer hvorfor det gjør vondt å selge, men Sindre begrunner ikke med noe tap, og mental regnskapsføring krever at penger merkes etter kilde eller formål, noe ingenting i scenarioet gjør.",
      ],
    },
    {
      id: "k18-6",
      topic: "Mottiltak",
      points: 3,
      body: "<p>To forsøk fra forelesningen står side om side. I det første fikk halvparten av rundt 590 norske fondskunder Forbrukerrådets tall for aktive fond mot indeks; indeksandelen i gruppen steg fra 11 % til 15 %, og effekten holdt seg i to år. I det andre forsto deltakerne argumentet mot hjemmebias, og endret likevel ingenting i porteføljen. I tillegg finner Fernandes og medforfattere (2014) at generelle finansundervisningsprogrammer forklarer omtrent 0,1 % av variasjonen i atferd, mens automatisk pensjonssparing øker sannsynligheten for at folk sparer med rundt 50 %.</p><p>Hvilken konklusjon følger av disse resultatene?</p>",
      options: [
        "Økningen på 4 prosentpoeng er så liten at informasjon må avskrives som virkemiddel; bare innlåsing av pengene, som i IPS, endrer atferd",
        "Økningen er 4 prosentpoeng, altså drøyt en tredjedel relativt: et konkret og lett etterprøvbart råd kan rette en feilslutning, mens avvik som informasjon ikke biter på, må omgås med en regel som binder atferden på forhånd",
        "Forsøkene viser at finansundervisning virker, og at flere generelle kurs i personlig økonomi derfor er det billigste tiltaket mot alle de åtte avvikene",
        "Hjemmebias endret seg ikke fordi den er en legitim preferanse for selskaper man kjenner, og en preferanse kan ikke være feil, bare dyr",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — hvor stor var effekten egentlig.</b> Fra 11 % til 15 % er 4 prosentpoeng, men målt relativt: (15 − 11) / 11 = <b>36,4 %</b>, altså drøyt en tredjedel flere som valgte indeks. Effekten holdt seg i to år, og andelen som trodde de kunne slå markedet, falt med 12 %. Det er ikke en neglisjerbar effekt.</p><p><b>Steg 2 — hvorfor virket det ene og ikke det andre.</b> Fondsrådet var konkret, gjaldt ett enkelt valg, og var lett å etterprøve. Hjemmebias-argumentet ble forstått, men handlingen uteble, og generell undervisning forklarer omtrent 0,1 % av variasjonen i atferd.</p><p><b>Steg 3 — hva som da gjenstår.</b> Regler som virker uten at du må ta beslutningen på nytt hver gang: globalt indeksfond mot overkonfidens og hjemmebias, automatisk månedlig sparing mot forankring og flokkatferd, IPS og obligatorisk tjenestepensjon mot manglende selvkontroll, og en skriftlig investeringsplan mot resten. Standardvalg er den sterkeste enkeltmekanismen: automatisk pensjonssparing øker sannsynligheten for å spare med rundt 50 %.</p><p><b>Kontroll:</b> 11 % × 1,364 = 15,0 %. ✓</p>",
      traps: [
        "Feilen er å lese 4 prosentpoeng som en liten effekt. Utgangspunktet var 11 %, så økningen er drøyt en tredjedel relativt, og den holdt seg i to år.",
        null,
        "Forsøket ga ett konkret råd om ett bestemt valg, ikke undervisning. Fernandes og medforfattere finner at generelle programmer forklarer omtrent 0,1 % av variasjonen i atferd.",
        "Forsøket skiller ikke mellom de to tolkningene forelesningen gir, feilslutning eller preferanse, og D slår fast den ene. Også som preferanse gjelder det at den øker samvariasjonen med humankapitalen din, og det er nøyaktig det diversifisering skal fjerne. At et råd ikke virker, gjør ikke avviket legitimt.",
      ],
    },
    {
      id: "k18-7",
      topic: "Verdifunksjonen",
      points: 3,
      body: "<p>Prospektteoriens verdifunksjon skiller seg fra en vanlig konkav nyttefunksjon av formuen på tre punkter. Nytten måles fra et <b>referansepunkt</b>, ikke fra formuens nivå. Kurven har en <b>knekk</b> i referansepunktet, fordi den er brattere for tap enn for gevinster; det er tapsaversjonen. Og den viser <b>avtakende følsomhet</b>: begge grenene flater ut jo lenger fra referansepunktet du kommer. Tre observasjoner [eksempeltall]:</p><p>(i) Per har kr 2 000 000 i formue. Han avslår et myntkast der han vinner kr 1 100 eller taper kr 1 000.</p><p>(ii) Kari kjenner forskjellen mellom å tape kr 0 og å tape kr 10 000 langt sterkere enn forskjellen mellom å tape kr 100 000 og å tape kr 110 000.</p><p>(iii) Ola og Siri har begge kr 900 000 i formue i dag. For ett år siden hadde Ola kr 1 000 000 og Siri kr 800 000. Ola er misfornøyd, Siri er fornøyd.</p><p>Hva forklarer hver av observasjonene?</p>",
      options: [
        "(i) knekken, (ii) avtakende følsomhet, (iii) referansepunktet",
        "(i) avtakende følsomhet, (ii) knekken, (iii) referansepunktet",
        "(i) vanlig risikoaversjon, altså en konkav nyttefunksjon av formuen, (ii) avtakende følsomhet, (iii) referansepunktet",
        "(i) knekken, (ii) avtakende følsomhet, (iii) vanlig risikoaversjon, altså en konkav nyttefunksjon av formuen",
      ],
      answer: 0,
      solution: "<p><b>(i) er knekken.</b> Myntkastet har positiv forventning: ½ × 1 100 − ½ × 1 000 = <b>kr 50</b>. Innsatsen er 0,05 % av Pers formue, og for så små beløp er enhver glatt nyttefunksjon tilnærmet lineær. Med U(W) = ln W er forventet nytte av å si ja ½ × ln 2 001 100 + ½ × ln 1 999 000, som er 0,0000249 <i>høyere</i> enn ln 2 000 000. Vanlig risikoaversjon sier altså ja. Et nei krever at tapet på 1 000 veier tyngre enn gevinsten på 1 100 allerede rett ved referansepunktet, og det er knekken.</p><p><b>(ii) er avtakende følsomhet.</b> Begge intervallene ligger på tapsgrenen, så det er ikke tap mot gevinst som sammenlignes, og knekken sier ingenting. Det Kari beskriver, er at tapsgrenen flater ut: de første 10 000 i tap merkes mer enn de 10 000 mellom 100 000 og 110 000. En konkav nyttefunksjon av formuen sier det motsatte: grensenytten er høyest der formuen er lavest, så de siste 10 000 i tap skulle gjort <i>mest</i> vondt.</p><p><b>(iii) er referansepunktet.</b> Ola og Siri har samme formue, så enhver nyttefunksjon av formuen gir dem samme nytte. Forskjellen kan bare komme fra at nytten måles fra der de startet: for Ola er 900 000 et tap på 100 000, for Siri en gevinst på 100 000.</p><p><b>Kontroll:</b> hver observasjon utelukker vanlig risikoaversjon av sin egen grunn, (i) fordi innsatsen er for liten, (ii) fordi fortegnet blir feil og (iii) fordi formuen er lik, og hver av de tre egenskapene brukes nøyaktig én gang. Det er de tre avvikene fra standard nyttefunksjon som H2019 oppgave 9h ba om, og som figur 18.1 tegner.</p>",
      traps: [
        null,
        "Knekken og avtakende følsomhet byttet om. Begge handler om hvor bratt kurven er, men knekken sammenligner tap med gevinst rett ved referansepunktet, mens (ii) sammenligner to tapsintervaller med hverandre. Der er det utflatingen som virker.",
        "Myntkastet forklart med vanlig risikoaversjon. For en innsats på 0,05 % av formuen er ln-nytten tilnærmet lineær og gir 0,0000249 høyere forventet nytte av å si ja; bare knekken ved referansepunktet får Per til å si nei.",
        "Olas misnøye forklart med vanlig risikoaversjon. Ola og Siri har samme formue, og en nyttefunksjon av formuen gir dem da samme nytte; bare et referansepunkt i fjorårets formue skiller dem.",
      ],
    },
    {
      id: "k18-9",
      topic: "Tapsaversjon og referansepunkt",
      points: 3,
      body: "<p>Sofie skal plassere kr 600 000 i 12 år og velger ett av to alternativer fullt ut [eksempeltall, se bort fra skatt].</p><p><b>Bankinnskudd:</b> sikker rente 2,5 % per år.</p><p><b>Aksjefond:</b> verdt kr 1 500 000 om 12 år med sannsynlighet 40 %, kr 700 000 med sannsynlighet 30 % og kr 380 000 med sannsynlighet 30 %.</p><p>Sofie har nyttefunksjonen U(W) = ln W, der W er sluttverdien, og hun er tapsavers. Referansepunktet er innskuddet på kr 600 000. Nytten av et utfall <i>under</i> referansepunktet ganges med tapsvekten 1/1,03 = 0,970874; nytten av et utfall på eller over referansepunktet får vekt 1.</p><p>Hvilket alternativ velger Sofie, og hvilke tall avgjør valget? Nyttetallene er rundet av til tre desimaler.</p>",
      options: [
        "Aksjefondet: forventet sluttverdi kr 924 000 er høyere enn kr 806 933 i banken",
        "Bank: nytten 13,601 er høyere enn 13,580 for aksjefondet",
        "Bank: nytten 13,601 er høyere enn 13,351 for aksjefondet",
        "Bank: nytten 13,601 er høyere enn 13,468 for aksjefondet",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — banken.</b> 600 000 × 1,025<sup>12</sup> = 600 000 × 1,344889 = <b>kr 806 933</b>. Det er over referansepunktet, så vekten er 1: ln 806 933 = <b>13,6010</b>.</p><p><b>Steg 2 — hvilke utfall er tap?</b> Sammenlign hvert utfall med <i>innskuddet</i>, ikke med banken. kr 1 500 000 og kr 700 000 ligger over 600 000 og får vekt 1. Bare kr 380 000 ligger under og får tapsvekten 0,970874.</p><p><b>Steg 3 — nytten av hvert utfall.</b> ln 1 500 000 = 14,22098. ln 700 000 = 13,45884. ln 380 000 = 12,84793, vektet 0,970874 × 12,84793 = <b>12,47372</b>.</p><p><b>Steg 4 — forventet nytte av fondet.</b> 0,40 × 14,22098 + 0,30 × 13,45884 + 0,30 × 12,47372 = 5,6884 + 4,0377 + 3,7421 = <b>13,4682</b>.</p><p><b>Steg 5 — valget.</b> 13,601 er høyere enn 13,468, og Sofie velger <b>banken</b>.</p><p><b>Steg 6 — hva tapsvekten gjorde.</b> Uten den gir fondet 0,40 × 14,22098 + 0,30 × 13,45884 + 0,30 × 12,84793 = 13,5804, som også er under bankens 13,6010. Banken vinner altså allerede for en vanlig ln-investor, og tapsvekten forsterker bare valget: marginen går fra 0,0206 til 0,1328. Slik var det i H2019 oppgave 9g og H2022 oppgave 5.6, med samme tapsvekt 1/1,03 og samme referansepunkt, innskuddet. At vekten også kan snu et valg, når banken bare så vidt vinner uten den, viser det gjennomregnede eksempelet i 18.2.</p><p><b>Kontroll:</b> tapsvekten skal trekke forventet nytte ned med sannsynligheten for tap × (1 − 0,970874) × nytten i tapsutfallet: 0,30 × 0,029126 × 12,84793 = 0,11226, og 13,58042 − 0,11226 = 13,46816 ≈ 13,4682. ✓ Kontrollen er en identitet, så den fanger regnefeil, men ikke et utfall som er vektet feil; det sjekker du i steg 2.</p><p>Forventet sluttverdi i fondet er 0,40 × 1 500 000 + 0,30 × 700 000 + 0,30 × 380 000 = kr 924 000, over bankens 806 933, og likevel velger Sofie banken, også uten tapsaversjon. Det gode utfallet måtte vært minst kr 1 579 184 for at fondet skulle slått banken uten tapsvekten, og kr 2 090 843 med den. Utfallet på kr 700 000 er fella: det er dårligere enn banken, men det er ikke et tap.</p>",
      traps: [
        "Forventet sluttverdi sammenlignet i stedet for forventet nytte: 0,40 × 1 500 000 + 0,30 × 700 000 + 0,30 × 380 000 = 924 000. Det er valget til en risikonøytral investor. Med ln-nytte teller det dårlige utfallet mer enn kronebeløpet tilsier, og banken vinner.",
        "Tapsaversjonen ikke brukt: 0,40 × 14,22098 + 0,30 × 13,45884 + 0,30 × 12,84793 = 13,580. Valget blir riktig, men tallet er nytten til en vanlig ln-investor, ikke Sofies.",
        "Bankens sluttverdi brukt som referansepunkt, slik at også kr 700 000 er vektet: 0,40 × 14,22098 + 0,30 × 0,970874 × 13,45884 + 0,30 × 12,47372 = 13,351. Konklusjonen blir riktig, men tallet er feil: 700 000 er under banken, men over innskuddet, og er derfor ikke et tap.",
        null,
      ],
    },
  ],
};
