/* Kapittel 19 — Flervalg med minuspoeng: rutinene og rekkefølgen */
window.EDU_DATA.chapterTasks[19] = {
  minutes: 18,
  tasks: [
    {
      id: "k19-1",
      topic: "Forventet poeng",
      points: 3,
      body: "<p>Eksamen gir [dagens regel] 3 poeng for et riktig svar, −1 for et feil svar og 0 for et ubesvart. Marte har seks spørsmål igjen der hun har klart å utelukke nøyaktig ett av de fire alternativene, men ikke kommer lenger. Hun vurderer å svare på alle seks.</p><p>Hva er forventet samlet poengsum fra de seks spørsmålene?</p>",
      options: ["+0,00 poeng", "+2,00 poeng", "+6,00 poeng", "+10,00 poeng"],
      answer: 1,
      solution: "<p><b>Steg 1 — hvor mange alternativer står igjen.</b> Fire minus ett utelukket gir n = 3. Sannsynligheten for å treffe er 1/3, og sannsynligheten for å bomme er 2/3.</p><p><b>Steg 2 — forventningen for ett spørsmål.</b> E = (1/3) × 3 − (2/3) × 1 = 1 − 0,6667 = <b>+0,3333 poeng</b>.</p><p><b>Steg 3 — seks uavhengige spørsmål.</b> Forventning er lineær, så summen er bare seks ganger så mye: 6 × 0,3333 = <b>+2,00 poeng</b>.</p><p><b>Kontroll — sjekk grensetilfellet.</b> Utelukker hun ingenting, er n = 4 og E = 0,25 × 3 − 0,75 × 1 = 0. Utelukker hun to, er n = 2 og E = 0,5 × 3 − 0,5 × 1 = +1. Svaret på +0,33 per spørsmål skal ligge mellom disse to, og det gjør det. ✓</p><p>Poenget er ikke tallet 2, men fortegnet: så snart ett eneste alternativ er strøket, er det dyrt å la spørsmålet stå blankt.</p>",
      traps: [
        "Regnet som blindgjetting blant fire alternativer, der forventningen faktisk er null. Det utelukkede alternativet er nettopp det som løfter forventningen over null.",
        null,
        "Minusleddet er glemt: 6 × (1/3 × 3) = 6. Det er verdien under den gamle regelen uten minuspoeng, ikke under dagens.",
        "Sannsynligheten for å bomme, 2/3, er brukt som sannsynligheten for å treffe: 6 × (2/3 × 3 − 1/3 × 1) = 10.",
      ],
    },
    {
      id: "k19-2",
      topic: "Terskelsannsynligheten",
      points: 3,
      body: "<p>Et spørsmål gir [dagens regel] 3 poeng for rett svar og −1 for feil, mens et ubesvart gir 0. Kall sannsynligheten for at du treffer riktig alternativ p.</p><p>Hvor stor må p minst være for at det lønner seg å svare i stedet for å la spørsmålet stå blankt?</p>",
      options: [
        "0 %, det lønner seg alltid å svare",
        "33,3 %",
        "25 %",
        "50 %",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — sett opp forventningen som funksjon av p.</b> Du treffer med sannsynlighet p og bommer med sannsynlighet 1 − p:</p><p>E(p) = 3p − 1 × (1 − p) = 3p − 1 + p = <b>4p − 1</b>.</p><p><b>Steg 2 — finn nullpunktet.</b> Å svare er bedre enn å stå blankt når E(p) &gt; 0, altså når 4p − 1 &gt; 0, altså p &gt; 1/4 = <b>25 %</b>.</p><p><b>Steg 3 — les det som en brøk.</b> Generelt er terskelen p* = F/(R + F), der R er poengene for rett og F er straffen for feil. Her: 1/(3 + 1) = 0,25. Straffen på −1 er valgt nettopp for å legge terskelen på 1 av 4.</p><p><b>Kontroll — sett inn tre verdier.</b> p = 0,25 (blindt blant fire) gir E = 4(0,25) − 1 = 0, altså akkurat på vippen. p = 1/3 (ett utelukket) gir E = 4/3 − 1 = +0,33. p = 0,5 (to utelukket) gir E = 2 − 1 = +1. Alle tre stemmer med tabellen i kapittel 0. ✓</p>",
      traps: [
        "«Svar alltid» var riktig under regelen i 2024 og 2025, da feil svar kostet null. Med −1 er svaret bare gratis når p overstiger terskelen.",
        "Brøken F/R = 1/3 brukt i stedet for F/(R + F) = 1/4. Nevneren skal være det samlede spennet mellom rett og feil, altså 3 + 1.",
        null,
        "Terskelen satt til 1/2, altså et krav om å være mer sannsynlig rett enn gal. Det er strengere enn regelen krever, og gjør at du lar poeng ligge igjen på hvert spørsmål der du har utelukket ett eller to alternativer.",
      ],
    },
    {
      id: "k19-3",
      topic: "Samlet forventning",
      points: 3,
      body: "<p>Et sett har 30 spørsmål [eksempeltall] à 3 poeng, altså 90 poeng maksimalt, med −1 for feil svar og 0 for ubesvart. Når tiden er ute, står Nora slik: hun er sikker på 18 spørsmål, har utelukket to alternativer på 6 spørsmål, har utelukket ett alternativ på 3 spørsmål, og er helt blank på 3 spørsmål. Hun svarer på alt unntatt de tre hun er helt blank på.</p><p>Hva er hennes forventede poengsum?</p>",
      options: ["61,00 poeng", "54,00 poeng", "63,25 poeng", "66,00 poeng"],
      answer: 0,
      solution: "<p><b>Steg 1 — de sikre.</b> 18 × 3 = <b>54,00</b>.</p><p><b>Steg 2 — de seks med to alternativer igjen.</b> Per spørsmål: 0,5 × 3 − 0,5 × 1 = +1,00. Til sammen 6 × 1,00 = <b>+6,00</b>.</p><p><b>Steg 3 — de tre med tre alternativer igjen.</b> Per spørsmål: (1/3) × 3 − (2/3) × 1 = +0,3333. Til sammen 3 × 0,3333 = <b>+1,00</b>.</p><p><b>Steg 4 — de tre blanke.</b> Ubesvart gir 0, altså <b>0,00</b>.</p><p><b>Steg 5 — summen.</b> 54,00 + 6,00 + 1,00 + 0,00 = <b>61,00 poeng</b> av 90.</p><p><b>Kontroll — hva utelukkingen var verdt.</b> Hadde hun latt alle de ni usikre stå blanke, ville hun fått 54,00. Differansen på 7,00 poeng er ren gevinst av å svare der hun kunne stryke noe, og den er nesten to og en halv oppgave verdt. ✓</p><p>Merk også hva de tre helt blanke bidrar med: null. Å gjette blindt på dem ville også gitt null i forventning, så valget der handler om varians, ikke om poeng.</p>",
      traps: [
        null,
        "Bare de sikre er talt, og alle gjetningene satt til null. «Gjetting gir null i forventning» gjelder bare blindt blant fire, ikke når alternativer er utelukket.",
        "De tre helt blanke er gjettet blindt og verdsatt til +0,75 hver, altså som om feil svar fortsatt kostet null. Under dagens regel er blindgjetting verdt nøyaktig 0.",
        "Minusleddet er glemt i begge gruppene: 54 + 6 × 1,5 + 3 × 1 = 66.",
      ],
    },
    {
      id: "k19-4",
      topic: "Dobbel vekting",
      points: 3,
      body: "<p>Enkelte spørsmål veier dobbelt: de gir 6 poeng for rett svar og −2 for feil, mens ubesvart fortsatt gir 0. Jonas står på et slikt spørsmål med ett alternativ utelukket, altså tre igjen, og ingen holdepunkter for å skille mellom dem.</p><p>Hva er forventet poengsum av å svare, og hva skjer med terskelen for når det lønner seg å svare?</p>",
      options: [
        "+0,67 poeng, og terskelen stiger til 50 %",
        "+2,00 poeng, og terskelen er uendret på 25 %",
        "+0,67 poeng, og terskelen er uendret på 25 %",
        "+3,33 poeng, og terskelen er uendret på 25 %",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — forventningen.</b> Med tre alternativer igjen treffer han med 1/3 og bommer med 2/3:</p><p>E = (1/3) × 6 − (2/3) × 2 = 2,00 − 1,3333 = <b>+0,6667 poeng</b>.</p><p><b>Steg 2 — terskelen.</b> p* = F/(R + F) = 2/(6 + 2) = 2/8 = <b>0,25</b>, altså nøyaktig den samme 25 % som under 3 og −1.</p><p><b>Kontroll — regn det en annen vei.</b> Både R og F er doblet, så hele forventningen må være doblet: 2 × [(1/3) × 3 − (2/3) × 1] = 2 × 0,3333 = 0,6667. ✓ Og en brøk endres ikke av at teller og nevner ganges med det samme tallet: 2/(6 + 2) = 1/(3 + 1). ✓</p><p>Konklusjonen er verdt å ta med seg: vektingen endrer hvor mye du vinner eller taper, men aldri <i>om</i> du skal svare. Strategien er den samme på alle spørsmål i settet.</p>",
      traps: [
        "Riktig forventning, men terskelen satt til 1/2. Terskelen avhenger av forholdet mellom R og F, og det er uendret når begge dobles.",
        "Minusleddet er glemt: (1/3) × 6 = 2. Straffen på −2 er nettopp det som er nytt ved dobbel vekting.",
        null,
        "Sannsynligheten for å bomme, 2/3, er brukt som sannsynligheten for å treffe: (2/3) × 6 − (1/3) × 2 = 3,33.",
      ],
    },
    {
      id: "k19-5",
      topic: "Varians ved gjetting",
      points: 3,
      body: "<p>Med 3 poeng for rett og −1 for feil [dagens regel] gir blindgjetting blant fire alternativer null i forventning. Sara har 12 spørsmål igjen der hun ikke klarer å utelukke noe som helst, og vurderer å gjette blindt på alle tolv. Utfallene er uavhengige.</p><p>Hva er standardavviket til den samlede poengsummen fra de tolv gjetningene?</p>",
      options: ["0,00 poeng", "6,00 poeng", "1,73 poeng", "20,78 poeng"],
      answer: 1,
      solution: "<p><b>Steg 1 — variansen for ett spørsmål.</b> Utfallet er +3 med sannsynlighet 0,25 og −1 med sannsynlighet 0,75. Forventningen er 0,25 × 3 − 0,75 × 1 = 0, så variansen er rett og slett E[X²]:</p><p>Var = 0,25 × 3² + 0,75 × (−1)² − 0² = 2,25 + 0,75 = <b>3,00</b>.</p><p><b>Steg 2 — summen av tolv uavhengige.</b> Varianser legges sammen, standardavvik gjør det ikke: Var(sum) = 12 × 3,00 = <b>36,00</b>.</p><p><b>Steg 3 — standardavviket.</b> √36 = <b>6,00 poeng</b>.</p><p><b>Kontroll — regn variansen med kortformen.</b> For et toutfallsspill er Var = p(1 − p)(R + F)², der R + F = 3 + 1 = 4 er avstanden mellom de to utfallene: 0,25 × 0,75 × 16 = 3,00. ✓ Samme tall som i steg 1.</p><p>Slik leses svaret: forventningen er 0, men resultatet ligger typisk et sted rundt ±6 poeng, altså to hele oppgaver i hver retning. Ligger du komfortabelt over en karaktergrense, er det risiko uten gevinst. Ligger du under, er spredningen den eneste sjansen du har. Det er det eneste argumentet for å gjette helt blindt, og det er situasjonsbestemt.</p>",
      traps: [
        "Forventningen forvekslet med spredningen. At forventningen er null betyr ikke at utfallet er null; det betyr at avvikene i begge retninger veier hverandre opp.",
        null,
        "Standardavviket for ett enkelt spørsmål, √3 = 1,73. Spørsmålet gjelder summen av tolv.",
        "Standardavvikene lagt sammen: 12 × 1,73. Det er varianser som er additive, ikke standardavvik, så faktoren er √12 og ikke 12.",
      ],
    },
    {
      id: "k19-6",
      topic: "Tidsbudsjettet",
      points: 3,
      body: "<p>Eksamen er fire timer, altså 240 minutter, og settet har 30 spørsmål [eksempeltall], altså 8 minutter i snitt per spørsmål. Reglene er [dagens regel] 3 poeng for rett, −1 for feil og 0 for ubesvart.</p><p>Med 20 minutter igjen står Kaja overfor et valg. <b>Alternativ A:</b> bruke hele kvarteret og de fem siste minuttene på ett tungt formelspørsmål hun anslår at hun løser riktig med 70 % sannsynlighet. <b>Alternativ B:</b> bruke fire minutter på hvert av fem spørsmål hun tidligere markerte, der hun allerede er nede i to alternativer, og svare på alle fem.</p><p>Hvor mye taper hun i forventning ved å velge A framfor B?</p>",
      options: ["2,00 poeng", "4,80 poeng", "5,40 poeng", "3,20 poeng"],
      answer: 3,
      solution: "<p><b>Steg 1 — verdien av alternativ A.</b> Ett spørsmål med treffsannsynlighet 0,70: E = 0,70 × 3 − 0,30 × 1 = 2,10 − 0,30 = <b>+1,80 poeng</b>.</p><p><b>Steg 2 — verdien av alternativ B.</b> Fem spørsmål med to alternativer igjen på hvert: E per spørsmål = 0,5 × 3 − 0,5 × 1 = +1,00, altså 5 × 1,00 = <b>+5,00 poeng</b>.</p><p><b>Steg 3 — differansen.</b> 5,00 − 1,80 = <b>3,20 poeng</b> tapt ved å velge A.</p><p><b>Kontroll — regn per minutt.</b> A gir 1,80/20 = 0,09 poeng per minutt. B gir 5,00/20 = 0,25 poeng per minutt, altså nesten tre ganger så mye. Rangeringen er den samme som differansen viser. ✓</p><p>Det er dette som er begrunnelsen for rekkefølgen. De sikre og de halvsikre spørsmålene har høy poengavkastning per minutt, og de tunge utledningene har lav. Bruker du de siste tjue minuttene på ett vanskelig spørsmål i stedet for på fem markerte, betaler du drøyt én hel oppgave for det. Til sammenligning hadde H2025-settet 29 spørsmål og H2024-settet 38, altså 8,3 og 6,3 minutter per spørsmål; tiden er romslig, men bare hvis den brukes der den gir poeng.</p>",
      traps: [
        "Formelspørsmålet regnet som sikkert, altså verdt 3 poeng: 5,00 − 3,00. Anslaget på 70 % er nettopp det som gjør A dårligere enn den ser ut.",
        "Sannsynligheten for å bomme, 0,30, brukt som sannsynligheten for å treffe i A: 0,30 × 3 − 0,70 × 1 = 0,20, som gir differansen 4,80.",
        "Minusleddet er glemt på begge sider: (5 × 1,5) − (0,7 × 3) = 7,50 − 2,10 = 5,40.",
        null,
      ],
    },
  ],
};
