/* Kapittel 2 — Avkastning før og etter skatt, og tidsverdien av et fradrag */
window.EDU_DATA.chapterTasks[2] = {
  minutes: 29,
  tasks: [
    {
      id: "k2-1",
      topic: "Totalavkastning",
      points: 3,
      body: "<p>Jonas kjøpte en utleieleilighet 1. januar for kr 2 400 000 og solgte den nøyaktig ett år senere for kr 2 640 000. I løpet av året fikk han kr 130 000 i leieinntekt og betalte kr 34 000 i vedlikehold og felleskostnader. Se bort fra skatt.</p><p>Hva var den nominelle totalavkastningen på leiligheten?</p>",
      options: ["4,00 %", "10,00 %", "12,73 %", "14,00 %"],
      answer: 3,
      solution: "<p><b>Steg 1 — direkteavkastningen.</b> For eiendom er kontantstrømmen leien <i>etter</i> vedlikehold og utgifter, ikke bruttoleien: 130 000 − 34 000 = <b>96 000</b>. Målt mot inngangsverdien: 96 000 / 2 400 000 = <b>4,0 %</b>.</p><p><b>Steg 2 — kapitalgevinsten.</b> 2 640 000 − 2 400 000 = 240 000, og 240 000 / 2 400 000 = <b>10,0 %</b>.</p><p><b>Steg 3 — totalavkastningen.</b> R = (P<sub>1</sub> − P<sub>0</sub> + Y<sub>1</sub>) / P<sub>0</sub> = (240 000 + 96 000) / 2 400 000 = 336 000 / 2 400 000 = <b>14,0 %</b>.</p><p><b>Kontroll:</b> komponentene skal summere til totalen. 10,0 % + 4,0 % = 14,0 %. ✓ Og i kroner: Jonas la ut 2 400 000 og satt igjen med 2 640 000 + 96 000 = 2 736 000, altså 336 000 mer. ✓</p><p>Merk at nevneren alltid er P<sub>0</sub>. Avkastning måler hva kapitalen du bandt opp har gitt deg, og den kapitalen er kjøpesummen. Bruker du bruttoleien i telleren i stedet for nettoleien, får du 370 000 / 2 400 000 = 15,42 %, et tall ingen av alternativene har.</p>",
      traps: [
        "Bare direkteavkastningen: 96 000 / 2 400 000. Kapitalgevinsten er glemt.",
        "Bare kapitalgevinsten: 240 000 / 2 400 000. Leien er glemt, og på et utleieobjekt er den nesten en tredel av avkastningen.",
        "Delt på salgskursen: 336 000 / 2 640 000. Nevneren skal være kapitalen du bandt opp, altså P₀, aldri P₁ og aldri gjennomsnittet.",
        null,
      ],
    },
    {
      id: "k2-2",
      topic: "Realavkastning etter skatt",
      points: 3,
      body: "<p>Silje har en aksjepost som gav 12 % nominell totalavkastning gjennom året. Inflasjonen var 4 % [eksempeltall]. Hele avkastningen skattlegges som eierinntekt med 37,84 % [dagens regel], og du kan se bort fra skjermingsfradraget.</p><p>Hva er Siljes realavkastning etter skatt?</p>",
      options: ["3,33 %", "3,46 %", "4,78 %", "7,69 %"],
      answer: 0,
      solution: "<p>Rekkefølgen er hele oppgaven: nominelt tall først, så skatt, så inflasjon. Skatten beregnes av det nominelle beløpet, for det er kroneverdien skattekontoret ser, og deflateringen kommer etterpå.</p><p><b>Steg 1 — nominell avkastning etter skatt.</b> 12 % × (1 − 0,3784) = 12 % × 0,6216 = <b>7,4592 %</b>.</p><p><b>Steg 2 — deflater.</b> r = (1 + 0,074592) / 1,04 − 1 = 1,074592 / 1,04 − 1 = 0,033262, altså <b>3,33 %</b>.</p><p><b>Kontroll i kroner:</b> sett 100 inn. Ved årets slutt har Silje 112. Skatten er 12 × 37,84 % = 4,5408, så hun sitter igjen med 107,4592. Målt i fjorårets kjøpekraft er det 107,4592 / 1,04 = 103,3262, altså 3,33 % realt. ✓</p><p><b>Kontroll med den effektive realskatten:</b> t<sub>real</sub> = t × i/(i − π) = 37,84 % × 12/8 = 56,76 %. Realavkastningen før skatt er 1,12/1,04 − 1 = 7,6923 %, og 7,6923 % × (1 − 0,5676) = 3,3262 %. ✓ Den nominelle satsen er 37,84 %, men reelt spiser skatten over halvparten, fordi Norge skattlegger den nominelle gevinsten uten fradrag for prisstigning.</p>",
      traps: [
        null,
        "Approksimasjonen brukt på siste steg: 7,4592 % − 4 %. Den ligger alltid r × π for høyt, her 0,13 prosentpoeng.",
        "Rekkefølgen snudd: først deflatert til 7,6923 %, så skattlagt med 37,84 %. Da later du som om staten gir fradrag for inflasjon, og svaret blir for høyt.",
        "Realavkastningen før skatt, 1,12/1,04 − 1. Skatten er glemt.",
      ],
    },
    {
      id: "k2-3",
      topic: "Effektiv realskatt",
      points: 3,
      body: "<p>En obligasjon gir 9 % nominell avkastning. Inflasjonen er 4 %, og avkastningen skattlegges med 30 % [eksempeltall].</p><p>Hvor stor andel av <i>realavkastningen</i> tar skatten?</p>",
      options: ["54,00 %", "30,00 %", "20,77 %", "16,67 %"],
      answer: 0,
      solution: "<p>Formelen er t<sub>real</sub> = t × i/(i − π). Den følger av å sette de to realavkastningene opp mot hverandre: telleren i den ene er i(1 − t) − π og i den andre i − π, og begge står over (1 + π), som forkortes bort.</p><p><b>Steg 1 — sett inn.</b> 30 % × 9/(9 − 4) = 30 % × 9/5 = 30 % × 1,8 = <b>54,0 %</b>.</p><p><b>Kontroll ved å regne begge realavkastningene:</b> før skatt er 1,09/1,04 − 1 = 4,8077 %. Nominelt etter skatt er 9 % × 0,70 = 6,3 %, og realt etter skatt 1,063/1,04 − 1 = 2,2115 %. Skatten tar 4,8077 − 2,2115 = 2,5962 prosentpoeng, og 2,5962/4,8077 = <b>54,0 %</b>. ✓</p><p>Legg merke til grenseverdiene: er π = 0, faller uttrykket tilbake til t = 30 %. Går π mot i, går brøken mot uendelig, og skatten spiser hele realavkastningen. Skattesatsen står stille på 30 %, men den reelle byrden bestemmes av inflasjonen.</p>",
      traps: [
        null,
        "Den nominelle satsen brukt direkte, som om skatten traff realavkastningen. Den treffer den nominelle avkastningen, og det er hele poenget.",
        "Inflasjonen lagt til i nevneren i stedet for trukket fra: 30 % × 9/13.",
        "Brøken snudd: 30 % × 5/9, altså real over nominell. Da får du et tall lavere enn satsen, og inflasjon kan aldri gjøre kapitalskatten mildere.",
      ],
    },
    {
      id: "k2-4",
      topic: "Nåverdi av fradrag",
      points: 3,
      body: "<p>Turid kjøper driftsmidler for kr 250 000. Hun kan enten utgiftsføre hele beløpet med en gang, eller avskrive kr 50 000 i året i fem år. Hun har rikelig med skattepliktig inntekt å føre fradraget mot i alle fem årene. Satsen på alminnelig inntekt er 22 % [dagens regel], og hun diskonterer med 8 % [eksempeltall]. Den umiddelbare besparelsen kommer i dag, avskrivningene ved slutten av hvert av årene 1 til 5.</p><p>Hvor mye er det verdt for Turid å ta hele fradraget med en gang?</p>",
      options: [
        "Kr 0. De to alternativene er like mye verdt.",
        "Kr 7 006",
        "Kr 11 080",
        "Kr 55 000",
      ],
      answer: 2,
      solution: "<p>Et fradrag er ikke penger, det er en skattebesparelse: fradraget ganget med satsen det virker mot. Og en skattebesparelse er en kontantstrøm som alle andre, så den skal diskonteres.</p><p><b>Steg 1 — alt med en gang.</b> 250 000 × 22 % = <b>55 000</b>, mottatt i dag, altså nåverdi 55 000.</p><p><b>Steg 2 — fordelt over fem år.</b> Årlig besparelse 50 000 × 22 % = <b>11 000</b>. Annuitetsfaktoren ved 8 % over fem år er [1 − 1,08<sup>−5</sup>]/0,08 = <b>3,9927</b>. Nåverdi: 11 000 × 3,9927 = <b>43 920</b>.</p><p><b>Steg 3 — differansen.</b> 55 000 − 43 920 = <b>kr 11 080</b> i favør av å ta alt med en gang.</p><p><b>Kontroll år for år:</b> 10 185,2 + 9 430,7 + 8 732,2 + 8 085,3 + 7 486,4 = 43 919,8 ≈ 43 920. ✓</p><p><b>Kontroll den andre veien:</b> udiskontert er alternativene identiske, 5 × 11 000 = 55 000 = 250 000 × 22 %. Det er utelukkende tidspunktene som skiller dem. Nåverdien av den fordelte strømmen er 3,9927/5 = 79,85 % av den umiddelbare, så tapet er 55 000 × (1 − 0,798542) = 11 080. ✓</p><p>Regelen er verdt å kunne som regel: så lenge diskonteringsrenten er positiv, vinner alltid å ta fradraget først, og speilbildet gjelder inntekt, som skal utsettes lengst mulig. To forbehold kan snu den. Du må ha inntekt å føre fradraget mot, og marginalsatsen kan være lavere i år 1 enn senere. Temaet har vært eksaminert som H2020 oppgave 1a og H2024 oppgave 3, begge ganger som begrepsspørsmål med et regnestykke bak.</p>",
      traps: [
        "Alternativene sammenlignet i udiskonterte kroner, 55 000 mot 5 × 11 000. Riktig bare hvis diskonteringsrenten er null, og dette alternativet er nesten alltid med.",
        "Også den umiddelbare besparelsen diskontert ett år, slik at begge strømmene starter i år 1: 55 000/1,08 − 43 920. To ulike tidskonvensjoner blandet i samme regnestykke.",
        null,
        "Hele skattebesparelsen ved å ta alt nå, som om avskrivningsalternativet var verdt null. Spørsmålet er differansen mellom to nåverdier.",
      ],
    },
    {
      id: "k2-5",
      topic: "Evig kontantstrøm",
      points: 3,
      body: "<p>En grunneier blir eksproprert og mister en leieinntekt på kr 480 000 i året for all framtid. Leien er nominelt fast: den vokser ikke med prisene. Erstatningen kapitaliseres med en <i>realrente</i> på 4 %, og inflasjonen ventes å bli 2,5 % [eksempeltall].</p><p>Hva er kontantstrømmen verdt når teller og nevner måles i samme enhet?</p>",
      options: ["Kr 7 095 344", "Kr 7 272 727", "Kr 7 384 615", "Kr 12 000 000"],
      answer: 1,
      solution: "<p>V = CF/r krever at kontantstrømmen og renten er i samme enhet. En nominelt fast leie må diskonteres med en <b>nominell</b> rente, ellers prises den som om den vokser med prisene.</p><p><b>Steg 1 — gjør realrenten om til nominell.</b> (1 + r)(1 + π) − 1 = 1,04 × 1,025 − 1 = 1,066 − 1 = <b>6,6 %</b>. Merk at den eksakte formelen brukes, ikke 4 % + 2,5 %.</p><p><b>Steg 2 — kapitaliser.</b> V = 480 000 / 0,066 = <b>kr 7 272 727</b>.</p><p><b>Kontroll ved å gjøre om kontantstrømmen i stedet for renten:</b> leien i år t er verdt 480 000/1,025<sup>t</sup> i dagens kjøpekraft, og den diskonteres med 4 % realt. Hvert ledd blir da 480 000/(1,025<sup>t</sup> × 1,04<sup>t</sup>) = 480 000/1,066<sup>t</sup>, altså nøyaktig samme rekke, og summen er den samme: 7 272 727. ✓</p><p><b>Kontroll baklengs:</b> 7 272 727 × 6,6 % = 480 000. ✓</p><p>Forskjellen mot 12 millioner er ikke en detalj. De 12 millionene forutsetter stilltiende at leien vokser med prisene hvert år, og det gjør den ikke her. Brøken er dessuten ekstremt følsom for renten: halverer du nevneren, dobles erstatningen.</p>",
      traps: [
        "Leien deflatert ett år og deretter kapitalisert med den nominelle renten: (480 000/1,025)/0,066. Inflasjonen er da trukket ut to ganger, én gang i telleren og én gang i nevneren.",
        null,
        "Nominell rente approksimert som 4 % + 2,5 % = 6,5 %. Krysseleddet r × π er utelatt, og erstatningen blir kr 111 888 for høy.",
        "Realrenten brukt på en nominell kontantstrøm: 480 000/0,04. Dette er den store enhetsfeilen, og den blåser erstatningen opp med nesten fem millioner.",
      ],
    },
    {
      id: "k2-6",
      topic: "To-periodemodellen",
      points: 3,
      body: "<p>Kari har inntekt kr 250 000 i periode 1 og kr 420 000 i periode 2. Hun kan spare eller låne til 6 % rente, og både renteinntekt og rentefradrag treffes av satsen på alminnelig inntekt, 22 % [dagens regel].</p><p>Hva er det høyeste konsumet Kari kan ha i periode 2?</p>",
      options: ["Kr 651 223", "Kr 658 823", "Kr 670 000", "Kr 681 700"],
      answer: 3,
      solution: "<p>Budsjettlinjen er C<sub>2</sub> = Y<sub>2</sub> + (Y<sub>1</sub> − C<sub>1</sub>)(1 + r(1 − t)). Det høyeste konsumet i periode 2 får Kari ved å sette C<sub>1</sub> = 0 og spare hele periode 1-inntekten.</p><p><b>Steg 1 — renten etter skatt.</b> r(1 − t) = 6 % × (1 − 0,22) = <b>4,68 %</b>. Skatten på renteinntekt og fradraget for renteutgifter har samme sats, så det samme tallet gjelder begge veier.</p><p><b>Steg 2 — forrent sparingen.</b> 250 000 × 1,0468 = <b>261 700</b>.</p><p><b>Steg 3 — legg til periode 2-inntekten.</b> 420 000 + 261 700 = <b>kr 681 700</b>.</p><p><b>Kontroll via det andre endepunktet:</b> det høyeste konsumet i periode 1 er 250 000 + 420 000/1,0468 = 651 223. De to endepunktene ligger på samme linje, så det ene ganget med 1 + r(1 − t) må gi det andre: 651 223 × 1,0468 = 681 700. ✓</p><p>Stigningstallet er −(1 + r(1 − t)) = <b>−1,0468</b>, mot −1,06 uten skatt. Skatten gjør linjen flatere, altså virker den som en lavere rente, og linjen vipper om utstyrspunktet E = (250 000, 420 000), som er tilgjengelig uansett rente og sats.</p>",
      traps: [
        "Det andre endepunktet på budsjettlinjen, høyeste konsum i periode 1: 250 000 + 420 000/1,0468.",
        "Periode 1-inntekten diskontert i stedet for forrentet: 420 000 + 250 000/1,0468. Sparing flytter kroner framover i tid, og da skal de ganges med 1 + r(1 − t).",
        "Rentene glemt: 250 000 + 420 000. Det er summen av inntektene, ikke endepunktet på budsjettlinjen.",
        null,
      ],
    },
    {
      id: "k2-7",
      topic: "Fradrag uten inntekt",
      points: 3,
      body: "<p>Maria eier et næringslokale gjennom Lokale AS. Selskapet har kr 180 000 i leieinntekt i hvert av de neste fem årene, og ingen andre kostnader og ingen annen inntekt. Nå må ventilasjonsanlegget skiftes for kr 250 000, og som i H2024 oppgave 3 kan selskapet velge mellom to måter å føre det på: utgiftsføre hele beløpet i år 1, eller avskrive kr 50 000 i året i fem år. Den delen av et fradrag som overstiger årets leieinntekt, går tapt: den kan verken føres mot annen inntekt eller framføres [forutsetning i oppgaven].</p><p>Satsen er selskapsskatten, 22 % [dagens regel], og selskapet diskonterer med 10 % [eksempeltall]. Skattebesparelsen kommer ved slutten av det året fradraget føres, altså om ett år for år 1. Annuitetsfaktoren for fem år ved 10 % er 3,7908.</p><p>Hvilket alternativ gir høyest nåverdi av skattebesparelsen, og med hvor mye?</p>",
      options: [
        "Avskrive over fem år, med kr 2 099",
        "Avskrive over fem år, med kr 5 699",
        "Utgiftsføre alt i år 1, med kr 8 301",
        "Avskrive over fem år, med kr 15 400",
      ],
      answer: 1,
      solution: "<p>Regelen «ta fradraget med en gang» har et forbehold, og sensorveiledningen til H2024 oppgave 3 sier det selv: den gjelder så lenge du har inntekt å føre fradraget mot. Det har ikke Lokale AS i år 1.</p><p><b>Steg 1 — hvor mye av fradraget som virker i år 1.</b> Leieinntekten er 180 000, så bare 180 000 av de 250 000 kan føres. Resten, 70 000, går tapt. Skattebesparelsen blir 180 000 × 22 % = <b>39 600</b>, mottatt om ett år: 39 600 / 1,10 = <b>36 000</b>.</p><p><b>Steg 2 — avskrivningen.</b> 50 000 i året er godt under leieinntekten, så hele fradraget virker hvert år. Årlig besparelse 50 000 × 22 % = 11 000, og nåverdien er 11 000 × 3,7908 = <b>41 699</b>.</p><p><b>Steg 3 — sammenlign.</b> 41 699 − 36 000 = <b>kr 5 699</b> i favør av å avskrive over fem år.</p><p><b>Kontroll via det tapte fradraget:</b> uten inntektsbegrensningen ville utgiftsføringen vært verdt 55 000 / 1,10 = 50 000, altså 50 000 − 41 699 = 8 301 <i>mer</i> enn avskrivningen. Begrensningen koster 70 000 × 22 % = 15 400 om ett år, som er 15 400 / 1,10 = 14 000 i nåverdi. 8 301 − 14 000 = −5 699, altså 5 699 i favør av avskrivningen. ✓ Samme tall, regnet via det som går tapt i stedet for det som blir igjen.</p><p>Tidsverdien virker fortsatt, den er bare mindre enn tapet. Et fradrag tatt tidlig er et rentefritt lån fra staten, men et fradrag som ikke kan brukes, er ikke et lån, det er et tap. Hadde leieinntekten vært minst 250 000, ville utgiftsføringen vunnet med 8 301, slik som i H2024-oppgaven. Og hadde de 70 000 kunnet framføres til år 2, ville utgiftsføringen vært verdt 36 000 + 15 400 / 1,21 = 36 000 + 12 727 = 48 727, og vunnet igjen. Les derfor alltid hva oppgaven sier om inntekten fradraget skal føres mot.</p>",
      traps: [
        "Besparelsen ved utgiftsføring behandlet som om den kom i dag: 41 699 − 39 600 = 2 099. Teksten sier at den kommer ved slutten av år 1, så 39 600 skal diskonteres ett år, akkurat som avskrivningene.",
        null,
        "Inntektsbegrensningen oversett, så hele 250 000 × 22 % = 55 000 regnes som brukbart i år 1: 55 000 / 1,10 − 41 699 = 8 301. Det er svaret når inntekten dekker fradraget, men her går 70 000 av det tapt.",
        "Udiskonterte kroner sammenlignet: 5 × 11 000 − 39 600 = 15 400. Retningen blir riktig, men beløpet er ingen nåverdi, og spørsmålet gjelder nåverdien.",
      ],
    },
    {
      id: "k2-8",
      topic: "Skatt og låntakeren",
      points: 3,
      body: "<p>Kari er låntaker i to-periodemodellen: hun konsumerer mer enn inntekten i periode 1 og betaler tilbake med renter i periode 2. Lånerenten er 5 %, og renteutgiftene gir fradrag med 22 % [dagens regel]. Anta at satsen som treffer renteinntekter og rentefradrag, økes til 28 % [eksempeltall]. Karis inntekter Y<sub>1</sub> og Y<sub>2</sub> etter skatt er uendret, og konsum i begge perioder er normale goder.</p><p>Hva skjer med Karis konsum i periode 1, C<sub>1</sub>?</p>",
      options: [
        "Renten etter skatt faller fra 3,90 % til 3,60 %. Substitusjonseffekten trekker C<sub>1</sub> opp og inntektseffekten trekker den ned, så virkningen er ubestemt.",
        "Ingenting: skatten treffer renteinntekter, ikke renteutgifter, så en låntakers budsjettlinje er uendret.",
        "Renten etter skatt faller fra 3,90 % til 3,60 %. Både substitusjons- og inntektseffekten trekker C<sub>1</sub> opp, så hun låner mer.",
        "Renten etter skatt stiger fordi skatten øker. Både substitusjons- og inntektseffekten trekker C<sub>1</sub> ned, så hun låner mindre.",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — renten etter skatt.</b> Før: 5 % × (1 − 0,22) = <b>3,90 %</b>. Etter: 5 % × (1 − 0,28) = <b>3,60 %</b>. For en låntaker er skatten et fradrag, så en høyere sats gjør hver rentekrone billigere. Skatt opp virker som rente ned.</p><p><b>Steg 2 — budsjettlinjen.</b> Stigningstallet −(1 + r(1 − t)) går fra −1,039 til −1,036. Linjen blir flatere og vipper om utstyrspunktet E = (Y<sub>1</sub>, Y<sub>2</sub>). Til høyre for E, der Kari er, ligger den nye linjen høyere, så mulighetene hennes utvides.</p><p><b>Steg 3 — substitusjonseffekten.</b> Konsum i dag er blitt billigere målt i konsum i morgen: én krone ekstra i periode 1 koster nå 1,036 i periode 2, mot 1,039 før. Hun flytter konsum mot periode 1, så C<sub>1</sub> <b>opp</b>.</p><p><b>Steg 4 — inntektseffekten.</b> Fortegnet følger Y<sub>1</sub> − C<sub>1</sub>. Kari har Y<sub>1</sub> − C<sub>1</sub> &lt; 0: hun betaler renter, og de er blitt billigere etter skatt. Hun er blitt rikere, og med normale goder bruker hun mer i begge perioder, så C<sub>1</sub> <b>opp</b>.</p><p><b>Steg 5 — samlet.</b> Begge effektene peker samme vei, så C<sub>1</sub> øker entydig. Siden Y<sub>1</sub> er uendret, øker også lånet C<sub>1</sub> − Y<sub>1</sub>.</p><p><b>Kontroll mot resultatet i kapitlet:</b> en renteøkning senker låntakerens C<sub>1</sub> entydig, fordi begge effektene trekker ned. Her faller renten etter skatt, og speilbildet må da gjelde: begge effektene trekker opp. ✓ Det høyeste mulige konsumet i periode 1, Y<sub>1</sub> + Y<sub>2</sub>/(1 + r(1 − t)), stiger også for enhver Y<sub>2</sub> &gt; 0 når nevneren går fra 1,039 til 1,036.</p><p>Samme skatteøkning ville gitt ubestemt virkning for en långiver: hun taper renteinntekt etter skatt og blir fattigere, så inntektseffekten trekker C<sub>1</sub> ned mens substitusjonseffekten trekker opp. Hvilken side av E du står på, avgjør svaret.</p>",
      traps: [
        "Långiverens tilfelle brukt på en låntaker. Inntektseffekten har fortegnet til Y₁ − C₁: den som sparer, blir fattigere når renten etter skatt faller, men Kari låner og betaler mindre i renter etter skatt, så hun blir rikere.",
        "Rentefradraget glemt. Renteinntekt og renteutgift treffes av samme sats, så r(1 − t) gjelder både for den som sparer og for den som låner.",
        null,
        "Skatten lest som en ekstra kostnad på lånet. For en låntaker virker satsen gjennom fradraget, så høyere sats senker renten etter skatt. Konklusjonen blir speilbildet av den riktige.",
      ],
    },
  ],
};
