/* Kapittel 3 — Avkastningen på ulike aktiva over tid, og hvem som eier hva */
window.EDU_DATA.chapterTasks[3] = {
  minutes: 20,
  tasks: [
    {
      id: "k3-1",
      topic: "Totalavkastning",
      points: 3,
      body: "<p>Du kjøper en utleiebolig for kr 4 000 000 [eksempeltall]. Ett år senere er den verdt kr 4 200 000. Brutto leieinntekt i året var kr 240 000. Følg Jordàs konvensjon: en tredel av brutto leie trekkes fra som vedlikehold, drift og avskrivning.</p><p>Hva er den nominelle totalavkastningen på boligen dette året?</p>",
      options: ["11,00 %", "9,00 %", "8,57 %", "5,00 %"],
      answer: 1,
      solution: "<p><b>Steg 1 — kapitalgevinsten.</b> (4 200 000 − 4 000 000) / 4 000 000 = <b>5,00 %</b>. Nevneren er inngangsverdien P<sub>0</sub>, aldri sluttprisen.</p><p><b>Steg 2 — netto leie.</b> En tredel av 240 000, altså 80 000, går til vedlikehold, drift og avskrivning. Igjen: 240 000 × 2/3 = <b>160 000</b>.</p><p><b>Steg 3 — direkteavkastningen.</b> 160 000 / 4 000 000 = <b>4,00 %</b>.</p><p><b>Steg 4 — summen.</b> R = kapitalgevinst + direkteavkastning = 5,00 % + 4,00 % = <b>9,00 %</b>.</p><p><b>Kontroll, i kroner først:</b> 200 000 + 160 000 = 360 000, og 360 000 / 4 000 000 = 9,00 %. ✓</p><p>Legg merke til fordelingen mellom de to leddene. Nesten halve avkastningen er leie, og det er nettopp poenget i Jordà: uten leieleddet er boligavkastning bare prisstigning, og da forsvinner mesteparten av tallet. Over 1870–2015 er bare rundt ett prosentpoeng av boligens 7,3 % realprisstigning.</p>",
      traps: [
        "Brutto leie brukt i telleren, altså 240 000 / 4 000 000 = 6,00 % i direkteavkastning. Tredelen til vedlikehold, drift og avskrivning er ikke trukket fra.",
        null,
        "Begge ledd delt på sluttprisen 4 200 000 i stedet for inngangsverdien 4 000 000: 360 000 / 4 200 000.",
        "Bare kapitalgevinsten. Leien er glemt, og det er nøyaktig leddet Jordàs bidrag består i å legge til.",
      ],
    },
    {
      id: "k3-2",
      topic: "Realavkastning",
      points: 3,
      body: "<p>Jordàs Norge-tall for 1870–2015: boligprisene steg 4,62 % nominelt per år, og netto leie utgjorde 6,72 % av boligverdien per år. Gjennomsnittlig inflasjon i perioden var 3,06 %.</p><p>Hva var den <b>eksakte</b> reelle totalavkastningen på norsk bolig?</p>",
      options: ["8,03 %", "8,28 %", "3,55 %", "1,51 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — nominell totalavkastning.</b> 4,62 % + 6,72 % = <b>11,34 %</b>. Deflater alltid totalen, ikke ett av leddene.</p><p><b>Steg 2 — den eksakte realformelen.</b> 1 + r = (1 + i) / (1 + π) = 1,1134 / 1,0306 = 1,080342, altså r = <b>8,03 %</b>.</p><p><b>Steg 3 — hvorfor ikke 8,28 %.</b> Approksimasjonen r ≈ i − π gir 11,34 − 3,06 = 8,28 %, altså 0,25 prosentpoeng for høyt. Den bommer alltid oppover, fordi den utelater leddet r × π. Med inflasjon på tre prosent over 145 år er avviket ikke støy.</p><p><b>Kontroll, gang tilbake:</b> 1,0803 × 1,0306 = 1,1134, som er den nominelle avkastningen vi startet med. ✓</p><p>Rekkefølgen er alltid nominelt, så etter skatt, så realt. Bytter du om, deflaterer du et beløp som ennå ikke er skattlagt.</p>",
      traps: [
        null,
        "Approksimasjonen r ≈ i − π brukt der oppgaven ber om det eksakte tallet. Den ligger alltid for høyt, her med 0,25 prosentpoeng.",
        "Bare leien deflatert: 1,0672 / 1,0306 − 1. Kapitalgevinsten mangler.",
        "Bare prisstigningen deflatert: 1,0462 / 1,0306 − 1. Dette er realprisstigningen på bolig, ikke avkastningen på den.",
      ],
    },
    {
      id: "k3-3",
      topic: "Sharpe-brøk",
      points: 3,
      body: "<p>Forelesningens tall fra Jordà, real avkastning per år 1870–2015 med standardavvik i parentes: bolig 7,3 % (10), aksjer 6,7 % (24), statsobligasjoner 2,5 % (11), statssertifikater 1,0 % (6).</p><p>Hva er Sharpe-brøken for bolig?</p>",
      options: ["0,24", "0,48", "0,63", "0,73"],
      answer: 2,
      solution: "<p><b>Steg 1 — hvilken rente er risikofri.</b> Statssertifikatene, altså 1,0 %. Statsobligasjoner er ikke risikofrie i denne sammenhengen: de har et standardavvik på 11, omtrent som bolig.</p><p><b>Steg 2 — meravkastningen.</b> 7,3 % − 1,0 % = <b>6,3 prosentpoeng</b>.</p><p><b>Steg 3 — del på standardavviket.</b> 6,3 / 10 = <b>0,63</b>.</p><p><b>Kontroll mot aksjer:</b> (6,7 − 1,0) / 24 = 0,2375, altså 0,24. Bolig er 0,63 / 0,2375 = 2,65 ganger så god per enhet risiko. ✓ Det stemmer med at bolig slår aksjer risikojustert i hvert eneste av de 16 landene, i snitt mer enn dobbelt så godt.</p><p>Men brøken forutsetter at du holder <i>hele</i> aktivaklassen. Standardavviket på 10 gjelder en portefølje av all bolig i 16 land over 145 år, ikke ett hus i én kommune. Den idiosynkratiske risikoen i ett objekt finnes ikke i tallet.</p>",
      traps: [
        "Aksjenes Sharpe-brøk, (6,7 − 1,0) / 24 = 0,2375. Riktig regnemåte, feil aktivum.",
        "Statsobligasjonsrenten 2,5 % brukt som risikofri rente: (7,3 − 2,5) / 10. Det er sertifikatrenten som er den risikofrie.",
        null,
        "Risikofri rente ikke trukket fra: 7,3 / 10. Da måler brøken avkastning per enhet risiko, ikke meravkastning per enhet risiko.",
      ],
    },
    {
      id: "k3-4",
      topic: "r mot g",
      points: 3,
      body: "<p>Jordàs uvektede snitt for 1870–2015: avkastningen på samlet formue er r = 6,28 % realt per år, mens BNP vokser med g = 2,87 % realt per år, et gap på 3,41 prosentpoeng. Anta at en formue forrentes med r, at økonomien vokser med g, at begge forrentes med renters rente, og at ingenting tas ut.</p><p>Hvor mange ganger så stor er formuen målt som andel av BNP etter 20 år?</p>",
      options: ["1,68 ganger", "1,92 ganger", "1,96 ganger", "3,38 ganger"],
      answer: 1,
      solution: "<p><b>Steg 1 — formuen.</b> 1,0628<sup>20</sup> = <b>3,3809</b>.</p><p><b>Steg 2 — BNP.</b> 1,0287<sup>20</sup> = <b>1,7611</b>.</p><p><b>Steg 3 — andelen.</b> 3,3809 / 1,7611 = <b>1,9198</b>, altså 1,92 ganger så stor andel som ved starten.</p><p><b>Kontroll den andre veien:</b> regn på forholdet direkte. Det vokser med 1,0628 / 1,0287 − 1 = 3,3149 % per år, ikke med gapet på 3,41 prosentpoeng. 1,033149<sup>20</sup> = 1,9198. ✓</p><p>Dette er Pikettys mekanisme i tall: lar du avkastningen bli stående, vokser posisjonen din med r mens lønnsinntektene i snitt vokser med g, og kapitaleiernes andel stiger av seg selv. Jordàs bidrag er at r &gt; g holder i hvert land og hver periode utenom årene i og rundt krig. Merk samtidig at r − g <i>ikke</i> varierer systematisk med veksten, så påstanden «lavere vekst gir automatisk større gap» er ikke bekreftet.</p>",
      traps: [
        "Gapet på 3,41 prosentpoeng ganget med 20 år uten renters rente: 1 + 0,0341 × 20.",
        null,
        "Gapet på 3,41 prosentpoeng brukt som årlig vekstrate: 1,0341<sup>20</sup>. Forholdet mellom to voksende størrelser vokser med 3,31 % per år, ikke med differansen i prosentpoeng.",
        "Bare formuen forrentet: 1,0628<sup>20</sup>. BNP-veksten er glemt, og da måles ikke andelen, bare formuen.",
      ],
    },
    {
      id: "k3-5",
      topic: "Effektiv formuesskatt",
      points: 3,
      body: "<p>Husholdning B er i topp 1 prosent og eier primærbolig med markedsverdi kr 6 000 000 og unoterte aksjer med markedsverdi kr 20 000 000. Ingen gjeld. Satser [dagens regel, 2026]: primærbolig verdsettes til 25 % av markedsverdien, aksjer får 20 % verdsettingsrabatt, bunnfradraget er kr 1 900 000 og satsen er 1,0 %. Selskapets bokførte egenkapital er 50 % av markedsverdien [eksempeltall, midt i intervallet 40–50 %].</p><p>Hva er husholdningens effektive formuesskattesats målt mot markedsverdien av formuen?</p>",
      options: ["1,00 %", "0,80 %", "0,23 %", "0,29 %"],
      answer: 3,
      solution: "<p><b>Steg 1 — boligens formuesverdi.</b> 6 000 000 × 25 % = <b>1 500 000</b>.</p><p><b>Steg 2 — aksjenes formuesverdi.</b> Unoterte aksjer verdsettes til selskapets bokførte egenkapital, ikke til markedsverdien: 20 000 000 × 50 % = 10 000 000. Så rabatten: 10 000 000 × 80 % = <b>8 000 000</b>. Rabatten trekkes én gang.</p><p><b>Steg 3 — skatten.</b> Grunnlag: 1 500 000 + 8 000 000 − 1 900 000 = 7 600 000. Skatt: 7 600 000 × 1,0 % = <b>76 000 kr</b>.</p><p><b>Steg 4 — den effektive satsen.</b> Nevneren er den faktiske formuen, altså markedsverdien: 6 000 000 + 20 000 000 = 26 000 000. 76 000 / 26 000 000 = <b>0,29 %</b>.</p><p><b>Kontroll, post for post:</b> 1 % av boligens formuesverdi er 15 000, 1 % av aksjenes formuesverdi er 80 000, og bunnfradraget er verdt 1 % × 1 900 000 = 19 000. 15 000 + 80 000 − 19 000 = 76 000. ✓</p><p>Den nominelle satsen er 1,0 %, den effektive er 0,29 %. Hele avstanden kommer fra verdsettingen: kr 26 000 000 i markedsformue teller som kr 9 500 000 på skattemeldingen. Det er derfor topp 1 prosent eier to tredeler av aksjene sine unotert, og derfor en skjerpelse av <i>eiendomsverdsettingen</i> treffer husholdninger uten aksjer hardest.</p>",
      traps: [
        "Skatten delt på grunnlaget etter bunnfradrag, kr 7 600 000. Da får du satsen tilbake og har ikke målt noe.",
        "Skatten delt på formuesverdien kr 9 500 000 i stedet for markedsverdien. Da forsvinner nettopp rabatten den effektive satsen skulle måle.",
        "Verdsettingsrabatten trukket fra to ganger på aksjene: 10 000 000 × 80 % × 80 % = 6 400 000, som gir 60 000 kr i skatt.",
        null,
      ],
    },
    {
      id: "k3-6",
      topic: "Justert ulikhet",
      points: 3,
      body: "<p>SSB erstatter mottatt utbytte med eierens andel av selskapets årsresultat, fordi skattemeldingen bare ser overskudd som faktisk er tatt ut. Gini-koeffisienten for inntekt etter skatt blir da: offisielt 0,23 i 2001 og 0,25 i 2018, justert 0,26 i 2001 og 0,35 i 2018.</p><p>Hvor mye vokste den <b>justerte</b> Gini-koeffisienten fra 2001 til 2018, målt i prosent?</p>",
      options: ["8,7 %", "25,7 %", "40,0 %", "34,6 %"],
      answer: 3,
      solution: "<p><b>Steg 1 — endringen.</b> 0,35 − 0,26 = <b>0,09</b>.</p><p><b>Steg 2 — del på startverdien.</b> 0,09 / 0,26 = <b>34,6 %</b>. Manualen runder dette til «+35 %».</p><p><b>Kontroll:</b> 0,26 × 1,346 = 0,3500, altså 2018-verdien. ✓</p><p><b>Sammenlign med den offisielle:</b> (0,25 − 0,23) / 0,23 = 8,7 %, avrundet +9 %. Det offisielle målet sier altså at ulikheten knapt har rørt seg, mens det justerte sier at den har vokst fire ganger så mye. Forskjellen er ikke uenighet om fordelingen, men om hva som telles som inntekt: da utbytteskatten kom i 2006, falt utbyttene til personlige aksjonærer fra 99 mrd. kr til 7,4 mrd. kr, og etter det måler den offisielle statistikken først og fremst når eierne velger å ta ut penger.</p>",
      traps: [
        "Den offisielle veksten, (0,25 − 0,23) / 0,23. Riktig regnemåte, feil mål: spørsmålet gjelder den justerte serien.",
        "Endringen delt på sluttverdien 0,35 i stedet for startverdien 0,26.",
        "Nivåforskjellen mellom justert og offisiell i 2018, 0,35 mot 0,25, i stedet for veksten over tid.",
        null,
      ],
    },
  ],
};
