/* Kapittel 6 — Fritaksmetoden, selskapsaksjonærer, aksjonærlån og exit-skatt */
window.EDU_DATA.chapterTasks[6] = {
  minutes: 30,
  tasks: [
    {
      id: "k6-1",
      topic: "Treprosentregelen",
      points: 3,
      body: "<p>Holding AS eier 60 % av aksjene i Drift AS, som er hjemmehørende i Norge. I løpet av året mottar Holding AS kr 4 000 000 i utbytte fra Drift AS, og selger i tillegg en aksjepost i et annet EØS-selskap med en gevinst på kr 2 500 000.</p><p>Bruk dagens regler: utbytte og gevinst på slike aksjer er fritatt etter fritaksmetoden, men 3 % av mottatt utbytte inntektsføres som alminnelig inntekt, og satsen på alminnelig inntekt er 22 % [dagens regel]. Konsernunntaket gjelder først ved mer enn 90 % eierskap og stemmer.</p><p>Hvor mye skatt utløser dette hos Holding AS?</p>",
      options: ["Kr 0", "Kr 26 400", "Kr 42 900", "Kr 120 000"],
      answer: 1,
      solution: "<p><b>Steg 1 — hva treprosentregelen treffer.</b> Regelen i § 2-38 sjette ledd gjelder <i>bare utbytte</i>. Gevinsten på kr 2 500 000 er fullt fritatt og holdes helt utenfor regnestykket.</p><p><b>Steg 2 — inntektsføringen.</b> 4 000 000 × 3 % = <b>120 000</b>. Dette er ikke skatt, det er et beløp som legges til alminnelig inntekt.</p><p><b>Steg 3 — skatten.</b> 120 000 × 22 % = <b>26 400</b>.</p><p><b>Kontroll med den effektive satsen:</b> 3 % × 22 % = 0,66 %, og 4 000 000 × 0,66 % = 26 400. ✓</p><p>Legg merke til størrelsesordenen. Den effektive skatten på konsernutbytte er 0,66 %, ikke 3 % og ikke 22 %. Hadde Holding AS eid mer enn 90 % av aksjene og hatt mer enn 90 % av stemmene, ville skatten vært kr 0.</p>",
      traps: [
        "Fritaksmetoden lest som et fullt fritak. Det stemmer for gevinsten, men ikke for utbyttet: treprosentregelen gjelder så lenge eierandelen er under 90 %.",
        null,
        "Treprosentregelen brukt på gevinsten også: (4 000 000 + 2 500 000) × 0,66 %. Regelen gjelder bare utbytte, fordi gevinster kommer sjeldnere og i større klumper.",
        "3 %-en behandlet som en skattesats i stedet for som en inntektsføring. Beløpet 120 000 er grunnlaget som legges til alminnelig inntekt, ikke skatten av det.",
      ],
    },
    {
      id: "k6-2",
      topic: "Samlet skatt i kjeden",
      points: 3,
      body: "<p>Drift AS har et overskudd på kr 1 000 000 før skatt og deler ut alt som er igjen etter selskapsskatt som utbytte. Holding AS eier 80 % av Drift AS, altså står kr 800 000 av overskuddet bak Holding AS' eierandel. Holding AS deler straks ut alt den har igjen etter egen skatt til sin personlige eier.</p><p>Satsene er [dagens regel]: selskapsskatt 22 %, eierskatt på utbytte 37,84 %, og 3 % av mottatt konsernutbytte inntektsføres når eierandelen er under 90 %. Skjermingsfradraget er brukt opp.</p><p>Hvor stor andel av de kr 800 000 forsvinner i skatt til sammen?</p>",
      options: ["51,52 %", "51,84 %", "52,97 %", "59,84 %"],
      answer: 1,
      solution: "<p><b>Steg 1 — selskapsskatten.</b> 1 000 000 × 22 % = 220 000, og 780 000 deles ut. Holding AS' andel er 780 000 × 80 % = <b>624 000</b>.</p><p><b>Steg 2 — treprosentregelen.</b> Inntektsført: 624 000 × 3 % = 18 720. Skatt: 18 720 × 22 % = <b>4 118,40</b>, som er det samme som 624 000 × 0,66 %.</p><p><b>Steg 3 — det Holding AS kan dele ut.</b> 624 000 − 4 118,40 = <b>619 881,60</b>.</p><p><b>Steg 4 — eierskatten.</b> 619 881,60 × 37,84 % = <b>234 563,20</b>. Eieren sitter igjen med 619 881,60 − 234 563,20 = <b>385 318,40</b>.</p><p><b>Steg 5 — samlet.</b> Bak eierandelen sto 800 000. Skatt: 800 000 − 385 318,40 = 414 681,60, altså 414 681,60 / 800 000 = <b>51,84 %</b>.</p><p><b>Kontroll med satsene alene:</b> 22 % + 78 % × (0,66 % + 99,34 % × 37,84 %) = 51,84 %. ✓ Eierandelen forsvinner ut av brøken, og bare 0,66 %-leddet kommer i tillegg én gang for hvert holdingselskap i kjeden som eier under 90 %. Det er nettopp det fritaksmetoden sørger for.</p><p>Uten treprosentregelen ville satsen vært 51,52 %. Regelen kostet altså 0,32 prosentpoeng, ikke 3.</p>",
      traps: [
        "Konsernunntaket antatt. Det gjelder først ved mer enn 90 % eierskap og stemmer; med 80 % slår treprosentregelen inn.",
        null,
        "3 %-en brukt som skattesats på utbyttet i stedet for som inntektsføring: 22 % + 78 % × (3 % + 97 % × 37,84 %).",
        "De to satsene lagt sammen direkte. Eierskatten treffer bare de 78 kronene som er igjen etter selskapsskatt, ikke hele 100.",
      ],
    },
    {
      id: "k6-3",
      topic: "Verdien av utsettelsen",
      points: 3,
      body: "<p>Jens eier Holding AS, som har kr 4 000 000 i opptjent kapital etter selskapsskatt. Han velger mellom to veier:</p><p><b>A.</b> Ta alt ut som utbytte nå, betale eierskatten, og plassere resten privat i aksjer.<br><b>B.</b> La pengene bli i Holding AS og plassere dem der i aksjer som omfattes av fritaksmetoden, slik at avkastningen i selskapet er skattefri, og først tømme selskapet til slutt.</p><p>Plasseringen dobler seg i begge tilfeller fram til han vil ha pengene ut [eksempeltall]. Eierskatten er 37,84 % [dagens regel], skjermingsfradraget ses bort fra, og uttaket fra Holding AS beskattes i sin helhet som utbytte.</p><p>Hvor mye mer sitter Jens igjen med etter all skatt i alternativ B enn i alternativ A?</p>",
      options: ["Kr 1 513 600", "Kr 3 027 200", "Kr 3 968 054", "Kr 940 854"],
      answer: 3,
      solution: "<p><b>Steg 1 — alternativ A, skatten i dag.</b> 4 000 000 × 37,84 % = 1 513 600. Igjen å investere: 4 000 000 − 1 513 600 = <b>2 486 400</b>.</p><p><b>Steg 2 — alternativ A, fram til slutten.</b> 2 486 400 × 2 = 4 972 800. Gevinsten er 4 972 800 − 2 486 400 = 2 486 400, og skatten 2 486 400 × 37,84 % = 940 853,76. Netto: 4 972 800 − 940 853,76 = <b>4 031 946,24</b>.</p><p><b>Steg 3 — alternativ B, fram til slutten.</b> Hele 4 000 000 blir stående og dobler seg skattefritt i selskapet: <b>8 000 000</b>.</p><p><b>Steg 4 — alternativ B, tømmingen.</b> Skatten kommer nå, på hele beløpet: 8 000 000 × 37,84 % = 3 027 200. Netto: 8 000 000 − 3 027 200 = <b>4 972 800</b>.</p><p><b>Steg 5 — fordelen.</b> 4 972 800 − 4 031 946,24 = <b>940 853,76</b>, altså kr 940 854.</p><p><b>Kontroll:</b> fordelen er avkastningen på skatten du ikke betalte i dag, etter at den avkastningen selv er beskattet. Den utsatte skatten på 1 513 600 dobler seg og gir 1 513 600 i avkastning, hvorav 62,16 % overlever: 1 513 600 × 62,16 % = 940 853,76. ✓</p><p>Merk hva regnestykket sier: eieren betaler <i>mer</i> skatt i alternativ B (3 027 200 mot 1 513 600 + 940 854 = 2 454 454), og kommer likevel bedre ut. Holdingselskapet er en utsettelse, ikke et fritak, og det er utsettelsen som er verdt penger.</p>",
      traps: [
        "Fordelen satt lik den utsatte skatten selv. Skatten kommer tilbake ved tømmingen; det du beholder er bare avkastningen på den, og bare etter eierskatt.",
        "Verdiene sammenlignet før den siste eierskatten i begge alternativene: 8 000 000 − 4 972 800. Det teller med selve skatten som faktisk blir betalt til slutt.",
        "Holdingselskapet oppfattet som et fritak, slik at hele 8 000 000 regnes som skattefritt. Fritaksmetoden fritar selskapets gevinst, ikke eierens uttak.",
        null,
      ],
    },
    {
      id: "k6-4",
      topic: "Aksjonærlån",
      points: 3,
      body: "<p>Kari eier 100 % av Kari AS. I mars låner hun kr 80 000 av selskapet og betaler alt tilbake 40 dager senere. I september låner hun kr 600 000 av selskapet, og dette lånet står ubetalt ved årets slutt. Begge lånene har markedsmessig rente og en skriftlig avtale.</p><p>Eierskatten på utbytte er 37,84 % [dagens regel], Kari har ingen ubenyttet skjerming, og lån under kr 100 000 som tilbakebetales innen 60 dager er unntatt fra regelen om at aksjonærlån skattlegges som utbytte.</p><p>Hvor mye skatt utløser lånene hos Kari?</p>",
      options: ["Kr 0", "Kr 132 000", "Kr 227 040", "Kr 257 312"],
      answer: 2,
      solution: "<p><b>Steg 1 — marslånet.</b> Kr 80 000 er under kr 100 000 og er tilbakebetalt innen 60 dager. Det faller inn under unntaket og utløser <b>ingen skatt</b>.</p><p><b>Steg 2 — septemberlånet.</b> Siden 2015 skattlegges lån fra selskap til personlig aksjonær som utbytte på utbetalingstidspunktet. Grunnlaget er hele lånebeløpet: <b>600 000</b>.</p><p><b>Steg 3 — skatten.</b> 600 000 × 37,84 % = <b>227 040</b>.</p><p><b>Kontroll med oppjustering på grunnlaget:</b> 600 000 × 1,72 = 1 032 000, og 1 032 000 × 22 % = 227 040. ✓</p><p>Legg merke til stillingen Kari nå står i: hun har kr 600 000 i kontanter, en skatteregning på kr 227 040 og en gjeld på kr 600 000 til selskapet. Det er strengt dårligere enn å ta beløpet som utbytte, der gjelden ikke oppstår. Verken markedsrente eller skriftlig avtale hjelper. Regelen er ingen ekstraskatt, den gjør bare låneveien like dyr som utbytteveien.</p>",
      traps: [
        "Et lån oppfattet som noe annet enn inntekt. Det var rettstilstanden fram til 2015, og det er nettopp hullet regelen tettet.",
        "22 % brukt uten oppjustering. Lånet skattlegges som utbytte, og eierskatten på utbytte er 22 % × 1,72 = 37,84 %.",
        null,
        "Marslånet tatt med: (80 000 + 600 000) × 37,84 %. Lån under kr 100 000 som tilbakebetales innen 60 dager, er unntatt.",
      ],
    },
    {
      id: "k6-5",
      topic: "Exit-skatt",
      points: 3,
      body: "<p>Peder flytter fra Norge til Portugal. Dagen før utflytting er aksjeposten hans verdt kr 18 000 000, og inngangsverdien er kr 4 500 000. Hele verdistigningen skjedde mens han var bosatt i Norge.</p><p>Bruk dagens regler: aksjene anses realisert dagen før utflytting, bunnfradraget er kr 3 000 000, satsen på alminnelig inntekt er 22 % og oppjusteringsfaktoren for utbytte og gevinst er 1,72 [dagens regel].</p><p>Hvor stor blir exit-skatten?</p>",
      options: ["Kr 2 310 000", "Kr 5 108 400", "Kr 6 811 200", "Kr 3 973 200"],
      answer: 3,
      solution: "<p><b>Steg 1 — den latente gevinsten.</b> 18 000 000 − 4 500 000 = <b>13 500 000</b>. Det er gevinsten som beskattes, ikke markedsverdien.</p><p><b>Steg 2 — bunnfradraget, som trekkes fra gevinsten.</b> 13 500 000 − 3 000 000 = <b>10 500 000</b>.</p><p><b>Steg 3 — eierskatten.</b> Oppjustering på satsen: 22 % × 1,72 = 37,84 %. Skatten er 10 500 000 × 37,84 % = <b>3 973 200</b>.</p><p><b>Kontroll med oppjustering på grunnlaget:</b> 10 500 000 × 1,72 = 18 060 000, og 18 060 000 × 22 % = 3 973 200. ✓ De to veiene må alltid gi samme tall.</p><p>Skatten er nå endelig fastsatt. Faller aksjene senere i verdi, settes den ikke ned. Peder velger deretter betalingsmåte: tolv rentefrie årlige rater, hele beløpet etter tolv år med renter, eller alt med en gang. De rentefrie ratene er best så lenge avkastningen hans er positiv. Flytter han tilbake innen tolv år med aksjene i behold, faller skatten bort.</p>",
      traps: [
        "Oppjusteringen glemt: 10 500 000 × 22 %. Grunnlaget er riktig, men satsen på aksjeinntekt er 37,84 %, ikke 22 %.",
        "Bunnfradraget glemt: 13 500 000 × 37,84 %.",
        "Skatten regnet av markedsverdien i stedet for av gevinsten: 18 000 000 × 37,84 %. Inngangsverdien og bunnfradraget er begge utelatt.",
        null,
      ],
    },
    {
      id: "k6-6",
      topic: "Kontinuitet ved gave",
      points: 3,
      body: "<p>Anders gir aksjene sine til datteren Sofie, som bor i Norge. På gavetidspunktet er aksjene verdt kr 6 000 000, og Anders' inngangsverdi er kr 1 200 000. Tre år senere selger Sofie hele posten for kr 8 000 000.</p><p>Arveavgiften er avskaffet, kontinuitetsprinsippet i skatteloven § 9-7 gjelder for aksjer, og eierskatten på gevinst er 37,84 % [dagens regel]. Se bort fra skjerming.</p><p>Hvor mye skatt utløser Sofies salg?</p>",
      options: ["Kr 756 800", "Kr 1 496 000", "Kr 2 573 120", "Kr 3 027 200"],
      answer: 2,
      solution: "<p><b>Steg 1 — Sofies inngangsverdi.</b> Kontinuitet betyr at hun overtar <i>giverens</i> inngangsverdi og øvrige skatteposisjoner. Inngangsverdien er dermed <b>1 200 000</b>, ikke verdien på gavetidspunktet.</p><p><b>Steg 2 — gevinsten.</b> 8 000 000 − 1 200 000 = <b>6 800 000</b>. Legg merke til at den inneholder hele Anders' latente gevinst på 6 000 000 − 1 200 000 = 4 800 000, pluss Sofies egen verdistigning på 2 000 000.</p><p><b>Steg 3 — skatten.</b> 6 800 000 × 37,84 % = <b>2 573 120</b>.</p><p><b>Kontroll ved å dele opp gevinsten:</b> 4 800 000 × 37,84 % = 1 816 320 og 2 000 000 × 37,84 % = 756 800, til sammen 2 573 120. ✓</p><p>Selve gaven utløste ingen skatt, men den fjernet den heller ikke. Den latente gevinsten fulgte med aksjene, og regningen kom da Sofie solgte. Unntaket er eiendom giveren selv kunne solgt skattefritt etter bo- og eiertidsreglene: der settes mottakerens inngangsverdi til antatt salgsverdi, og den latente gevinsten forsvinner. For aksjer finnes ingen slik skattefrihet. Hadde Sofie bodd i utlandet, ville gaven i tillegg utløst exit-skatt hos Anders, siden netto gevinst overstiger kr 100 000 i året.</p>",
      traps: [
        "Diskontinuitet lagt til grunn, altså inngangsverdien satt til verdien på gavetidspunktet: (8 000 000 − 6 000 000) × 37,84 %. Det gjelder bolig og fritidsbolig giveren kunne solgt skattefritt, ikke aksjer.",
        "22 % brukt uten oppjustering på riktig gevinst: 6 800 000 × 22 %.",
        null,
        "Skatten regnet av hele salgssummen: 8 000 000 × 37,84 %. Inngangsverdien er glemt helt.",
      ],
    },
    {
      id: "k6-7",
      topic: "Exit-skatt i rater",
      points: 3,
      body: "<p>Ingrid flyttet til Norge i 2014. Hun eide da en aksjepost som hun hadde kjøpt for kr 1 500 000, og som var verdt kr 4 000 000 den dagen hun ble bosatt her. Høsten 2026 flytter hun til Spania, og dagen før utflyttingen er posten verdt kr 19 000 000. Hun har verken kjøpt eller solgt aksjer i mellomtiden.</p><p>Reglene for exit-skatt [dagens regel]: aksjene anses realisert dagen før utflytting, bare verdistigningen mens hun var bosatt i Norge skattlegges, bunnfradraget er kr 3 000 000, og eierskatten er 37,84 %. Skatten kan betales med en gang, eller i tolv like, rentefrie årlige rater der den første forfaller ett år etter utflyttingen. Ingrid kan plassere pengene til 6 % [eksempeltall], og annuitetsfaktoren for tolv år ved 6 % er 8,3838.</p><p>Hvor mye er det verdt for Ingrid, målt i nåverdi, å betale i rentefrie rater i stedet for å betale alt med en gang?</p>",
      options: [
        "Kr 1 368 370",
        "Kr 1 653 447",
        "Kr 1 710 463",
        "Kr 3 172 430",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — gevinsten som er opptjent i Norge.</b> Exit-skatten treffer bare verdistigningen mens Ingrid var bosatt her, så utgangspunktet er verdien da hun flyttet inn, ikke kjøpesummen: 19 000 000 − 4 000 000 = <b>15 000 000</b>.</p><p><b>Steg 2 — bunnfradraget.</b> Det trekkes fra gevinsten: 15 000 000 − 3 000 000 = <b>12 000 000</b>.</p><p><b>Steg 3 — skatten.</b> 12 000 000 × 37,84 % = <b>4 540 800</b>. Kontroll med oppjustering på grunnlaget: 12 000 000 × 1,72 = 20 640 000, og 20 640 000 × 22 % = 4 540 800. ✓ Beløpet er nå låst: faller aksjene senere i verdi, settes skatten ikke ned.</p><p><b>Steg 4 — nåverdien av ratene.</b> Hver rate er 4 540 800 / 12 = 378 400, og nåverdien er 378 400 × 8,3838 = <b>3 172 430</b>.</p><p><b>Steg 5 — verdien av å betale i rater.</b> 4 540 800 − 3 172 430 = <b>kr 1 368 370</b>.</p><p><b>Kontroll:</b> tolv rater på 378 400 er 12 × 378 400 = 4 540 800, altså hele skatten, så forskjellen skyldes bare tidspunktene. ✓ Andelen spart er 1 − 8,3838 / 12 = 30,135 %, og 4 540 800 × 30,135 % = 1 368 370. Det er samme regnestykke skrevet om, så det fanger regnefeil, ikke metodefeil. En uavhengig grovkontroll: ratene betales i snitt etter 6,5 år, og 1 − 1 / 1,06<sup>6,5</sup> ≈ 31,5 %, nær 30,1 %. ✓</p><p>Ratene er et rentefritt lån fra staten, akkurat som et fradrag tatt tidlig i kapittel 2. Det tredje valget, hele beløpet etter tolv år, er forrentet: krever staten samme rente som Ingrid selv oppnår, er det like mye verdt som å betale straks. Utsettelsen forutsetter i utgangspunktet sikkerhet, men ved flytting til en EØS-stat som Spania kreves sikkerhet bare hvis det er reell risiko for at skatten ikke blir betalt (skatteloven § 10-70 sjuende ledd). Flytter hun tilbake innen tolv år med aksjene i behold, faller skatten bort.</p>",
      traps: [
        null,
        "Kjøpesummen brukt som inngangsverdi: (19 000 000 − 1 500 000 − 3 000 000) × 37,84 % = 5 486 800, og 5 486 800 × (1 − 8,3838 / 12) = 1 653 447. Verdistigningen fra 1,5 til 4 mill. skjedde før hun ble bosatt i Norge og skal holdes utenfor.",
        "Bunnfradraget glemt: 15 000 000 × 37,84 % = 5 676 000, og 5 676 000 × (1 − 8,3838 / 12) = 1 710 463.",
        "Nåverdien av ratene svart i stedet for besparelsen: 378 400 × 8,3838 = 3 172 430. Det er hva ratene koster i dag, ikke hva de sparer henne for.",
      ],
    },
    {
      id: "k6-8",
      topic: "Exit-skatt: reglene",
      points: 3,
      body: "<p>Nora er bosatt i Norge og eier alle aksjene i Nora Invest AS, et norsk aksjeselskap. Aksjene har inngangsverdi kr 2 000 000 og er verdt kr 9 000 000. Hun eier også en aksjepost i et børsnotert selskap med en latent gevinst på kr 3 500 000. Datteren hennes bor i Danmark.</p><p>Hvilken påstand er riktig etter reglene som gjelder i 2026?</p>",
      options: [
        "Gir Nora den børsnoterte aksjeposten til datteren, utløses exit-skatt hos Nora, selv om hun selv blir boende i Norge.",
        "Flytter Nora til Portugal og lar være å selge aksjene i Nora Invest AS i mer enn fem år, faller exit-skatten bort.",
        "Flytter Nora til Portugal og aksjene i Nora Invest AS deretter faller til halv verdi, settes exit-skatten ned tilsvarende.",
        "Flytter Nora Invest AS til Sveits, slik at selskapet blir skattemessig hjemmehørende der, kan det ikke utløse norsk skatt så lenge Nora selv blir boende i Norge.",
      ],
      answer: 0,
      solution: "<p>Fire påstander, fire regler. Ta dem én for én.</p><p><b>Steg 1 — gaven (A).</b> Exit-skatten er ikke bare en skatt på å flytte selv. Gir du aksjer til en nærstående som bor i utlandet, utløses exit-skatt hos deg når netto gevinst overstiger kr 100 000 i året. Den latente gevinsten er her 3 500 000, godt over grensen. Du trenger ikke flytte, det holder at aksjene gjør det. Påstanden er <b>riktig</b>, og det var nettopp dette H2024 oppgave 10 spurte om.</p><p><b>Steg 2 — femårsregelen (B).</b> Fram til 29. november 2022 falt exit-skatten bort hvis aksjene ikke var solgt innen fem år etter utflyttingen. Regelen er opphevet, og den står som fasit i H2022 oppgave 4 fordi settet ble laget før det. I dag faller skatten bare bort hvis du flytter tilbake innen tolv år med aksjene i behold. <b>Gal.</b></p><p><b>Steg 3 — verdifall etter utflyttingen (C).</b> Skatten fastsettes endelig ut fra verdien dagen før utflytting. Faller aksjene senere, settes den ikke ned. <b>Gal.</b></p><p><b>Steg 4 — selskapet flytter (D).</b> Blir selskapet hjemmehørende i en stat utenfor EØS, som Sveits, skattlegges gevinst på selskapets eiendeler som om de var realisert dagen før (skatteloven § 10-71). Utflyttingen kan altså utløse norsk skatt uten at Nora flytter. Kursets fasiter går lenger: H2022 oppgave 4 og H2024 oppgave 10 sier at det gjøres opp på begge nivåer, selskapet for eiendelene og aksjonærene for aksjene, og det er det svaret som har gitt poeng. Lovteksten nevner bare selskapets eiendeler. Uansett hvilken av de to du legger til grunn, er påstanden <b>gal</b>.</p><p><b>Kontroll:</b> A er den eneste påstanden som beskriver gjeldende rett. B bygger på en opphevet regel, C strider mot at skatten fastsettes endelig, og D overser at selskapets egen utflytting utløser skatt etter § 10-71. ✓ Merk også hvorfor Nora Invest AS har tall: med en latent gevinst på 7 000 000 er hun godt over bunnfradraget på 3 000 000, så en utflytting ville faktisk utløst skatt, og B og C handler om en skatt som finnes.</p>",
      traps: [
        null,
        "Femårsregelen, som er fasit i H2022 oppgave 4, ble opphevet 29. november 2022. I dag faller skatten bare bort hvis hun flytter tilbake innen tolv år med aksjene i behold.",
        "Exit-skatten fastsettes endelig ut fra verdien dagen før utflytting. Senere verdifall setter den ikke ned.",
        "Selskapets utflytting utløser skatt selv om Nora blir boende: etter skatteloven § 10-71 skattlegges gevinst på selskapets eiendeler som om de var realisert når selskapet flytter ut av EØS, og kursets fasiter (H2022 oppgave 4, H2024 oppgave 10) gjør i tillegg opp aksjonærene for aksjene.",
      ],
    },
  ],
};
