/* Kapittel 8 — Formuesskatt som avkastningsskatt: verdsetting, utbytte og de rikeste */
window.EDU_DATA.chapterTasks[8] = {
  minutes: 66,
  tasks: [
    {
      id: "k8-1",
      topic: "Ekvivalensen",
      points: 3,
      body: "<p>Kari har en finansformue på kr 8 000 000 ved inngangen til året [eksempeltall]. Formuen gir 4 % avkastning, som realiseres ved periodens slutt. Formuesskatten er 1,0 % [dagens regel] og faller på formuen ved <b>periodens begynnelse</b>. Se bort fra bunnfradrag og verdsettingsrabatt.</p><p>Hvor høy må en skatt på kapitalavkastningen være for at de to skattene skal gi nøyaktig samme proveny?</p>",
      options: ["20,0 %", "25,0 %", "26,0 %", "33,3 %"],
      answer: 1,
      solution: "<p><b>Steg 1 — formuesskattens proveny.</b> Grunnlaget er formuen ved inngangen: 8 000 000 × 1,0 % = <b>kr 80 000</b>. Beløpet er fast og avhenger ikke av hva formuen kaster av seg.</p><p><b>Steg 2 — avkastningsskattens grunnlag.</b> Den treffer avkastningen, ikke beholdningen: 8 000 000 × 4 % = <b>kr 320 000</b>.</p><p><b>Steg 3 — sett provenyene like.</b> 320 000 × t = 80 000 gir t = 80 000/320 000 = <b>25,0 %</b>. Med formelen: t = τ<sub>w</sub>/r = 1 %/4 % = 25 %.</p><p><b>Kontroll:</b> 8 000 000 × 0,04 × 0,25 = 80 000, nøyaktig formuesskatten. ✓</p><p>Formuen stryker seg på begge sider, så svaret avhenger bare av forholdet mellom satsen og avkastningen. Samme rute som H2025 oppgave 9, der 1,0 % og 5 % ga 20 %. Fordi r står i nevneren, stiger den ekvivalente satsen bratt når avkastningen faller: ved 2 % avkastning tilsvarer en formuesskatt på 1,0 % en avkastningsskatt på 50 %.</p>",
      traps: [
        "Nevneren er blåst opp med formuesskattesatsen: 80 000/(8 000 000 × 5 %). Grunnlaget for avkastningsskatten er avkastningen alene, 4 %.",
        null,
        "Skatten lagt på formuen ved periodens slutt: 8 000 000 × 1,04 × 1,0 % = 83 200, delt på 320 000. Oppgaven sier uttrykkelig periodens begynnelse.",
        "Avkastningen etter formuesskatt, 3 %, brukt i nevneren: 80 000/240 000. Ekvivalensen måler de to skattene mot samme grunnlag før skatt.",
      ],
    },
    {
      id: "k8-2",
      topic: "Ekvivalensen baklengs",
      points: 3,
      body: "<p>Et land har i dag en skatt på kapitalavkastning på 30 % og vurderer å bytte den ut med en formuesskatt som gir like mye i proveny [eksempeltall]. En skattyter har kr 10 000 000 ved inngangen til året, og avkastningen er 3 %. Formuesskatten skal falle på formuen ved <b>periodens slutt</b>.</p><p>Hvilken formuesskattesats gir samme proveny som dagens avkastningsskatt?</p>",
      options: ["0,87 %", "0,90 %", "0,93 %", "1,00 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — dagens proveny.</b> Avkastningen er 10 000 000 × 3 % = 300 000, og skatten på den er 300 000 × 30 % = <b>kr 90 000</b>.</p><p><b>Steg 2 — formuesskattens grunnlag.</b> Skatten faller på formuen ved periodens slutt, altså etter at avkastningen er lagt til: 10 000 000 × 1,03 = <b>kr 10 300 000</b>.</p><p><b>Steg 3 — løs for satsen.</b> 10 300 000 × τ<sub>w</sub> = 90 000 gir τ<sub>w</sub> = 0,873786 %, altså <b>0,87 %</b>. Med formelen: τ<sub>w</sub> = t × r/(1 + r) = 0,30 × 0,03/1,03 = 0,87 %.</p><p><b>Kontroll:</b> gå den andre veien. 90 000/10 300 000 = 0,873786 %, og formelen t × r/(1 + r) gir det samme. ✓</p><p>Falt skatten i stedet på inngående formue, ville svaret vært τ<sub>w</sub> = r × t = 0,03 × 0,30 = 0,90 %. Tre hundredeler av et prosentpoeng skiller de to, og det eneste som avgjør, er setningen om tidspunktet. H2021 oppgave 3 spurte på nøyaktig denne måten, med t = 22 % og r = 3 % på utgående formue, og svaret var 0,64 %.</p>",
      traps: [
        null,
        "Formelen for inngående formue brukt: 0,03 × 0,30 = 0,90 %. Tidspunktet i oppgaveteksten er oversett, og det er hele forskjellen mellom de to rutene.",
        "Justeringen for periodens slutt gjort feil vei: ganget med 1,03 i stedet for delt på 1,03.",
        "Dagens norske formuesskattesats hentet fra hukommelsen i stedet for regnet ut av ekvivalensen. Svaret følger av oppgavens tall, ikke av norsk sats.",
      ],
    },
    {
      id: "k8-3",
      topic: "Avkastning etter formuesskatt",
      points: 3,
      body: "<p>Jonas kjøper børsnoterte aksjer for kr 5 000 000 ved inngangen til året, mottar kr 300 000 i kontantutbytte ved årets slutt og selger aksjene for kr 5 000 000 [eksempeltall]. Formuesskatten er 1,0 % og faller på formuen ved inngangen til året, og børsnoterte aksjer verdsettes til 80 % av markedsverdien, altså en rabatt på 20 % [dagens regel]. Se bort fra bunnfradrag, skjerming og skatt på kapitalavkastning.</p><p>Hva er Jonas' avkastning etter formuesskatt?</p>",
      options: ["4,80 %", "5,00 %", "5,20 %", "6,00 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — avkastningen før formuesskatt.</b> Kjøpspris og salgspris er like, så kapitalgevinsten er null, og hele avkastningen er direkteavkastningen: r = 300 000/5 000 000 = <b>6 %</b>.</p><p><b>Steg 2 — formuesskatten.</b> Grunnlaget er formuesverdien, ikke markedsverdien: 5 000 000 × 0,80 = 4 000 000. Skatten blir 4 000 000 × 1,0 % = <b>kr 40 000</b>.</p><p><b>Steg 3 — avkastningen etter.</b> (300 000 − 40 000)/5 000 000 = 260 000/5 000 000 = <b>5,2 %</b>. Nevneren er det han faktisk investerte, ikke formuesverdien.</p><p><b>Kontroll med formelen:</b> r − τ<sub>w</sub>(1 − ρ) = 6 % − 1,0 % × 0,80 = 6 % − 0,8 prosentpoeng = 5,2 %. ✓</p><p>Fratrekket er altså 0,8 prosentpoeng, uansett hvor høy avkastningen er. Oversatt til en avkastningsskatt: 0,8/6 = 13,3 %. Uten rabatten ville den vært 1,0/6 = 16,7 %. Verdsettingsrabatten er en direkte reduksjon i den ekvivalente avkastningsskatten.</p>",
      traps: [
        "Rabatten lagt til i stedet for trukket fra: formuesverdien satt til 5 000 000 × 1,20 = 6 000 000 og skatten til kr 60 000.",
        "Formuesskatten regnet av markedsverdien, altså rabatten glemt: 5 000 000 × 1,0 % = kr 50 000.",
        null,
        "Avkastningen før formuesskatt. Spørsmålet er hva som er igjen etter at skatten er betalt.",
      ],
    },
    {
      id: "k8-4",
      topic: "Verdsetting",
      points: 3,
      body: "<p>Kapitalmarkedet er effisient, og alle investeringer i samme risikoklasse gir samme avkastning. En norsk investor har et alternativ i denne risikoklassen som gir 8 % avkastning før formuesskatt [eksempeltall]. Han vurderer en investering som gir en evigvarende kontantstrøm på 6 mill. kr i året. Formuesskatten er 1 % [eksempeltall, men nær dagens sats], faller på markedsverdien ved periodens begynnelse og treffer alle aktiva likt. Se bort fra verdsettingsrabatt, bunnfradrag og skatt på kapitalavkastning.</p><p>Hva er investeringen verdt for ham?</p>",
      options: ["60 mill. kr", "66,7 mill. kr", "74,25 mill. kr", "75 mill. kr"],
      answer: 3,
      solution: "<p><b>Steg 1 — alternativkostnaden etter formuesskatt.</b> Formuesskatten er en skatt på personen, ikke på aktivumet: han betaler den også på alternativet. Avkastningen der faller fra 8 % til 8 % − 1 % = <b>7 %</b>, og det er dette kravet den nye investeringen skal måles mot.</p><p><b>Steg 2 — sett opp betingelsen.</b> Formuesverdien er markedsverdien V, så skatten er 0,01V og netto kontantstrøm 6 − 0,01V. Kravet blir (6 − 0,01V)/V = 0,07.</p><p><b>Steg 3 — løs.</b> 6/V − 0,01 = 0,07, altså 6/V = 0,08, som gir V = 6/0,08 = <b>75 mill. kr</b>. Legg merke til at 0,01 stryker seg: V = CF/r, nøyaktig verdien uten formuesskatt.</p><p><b>Kontroll:</b> sett V = 75 tilbake inn. Formuesskatten er 0,75, netto kontantstrøm 6 − 0,75 = 5,25, og avkastningen 5,25/75 = 7 %, nøyaktig alternativkostnaden. Prisen er selvkonsistent. ✓</p><p>Dette er poenget i H2025 oppgave 3 d: skatten senker kontantstrømmen og avkastningskravet like mye, så betalingsviljen er den samme som for en investor uten formuesskatt. Hadde alternativet <i>ikke</i> vært rammet av formuesskatt, ville kravet stått på 8 %, og verdien blitt 6/0,09 = 66,7 mill. Utelukkingsregelen er å telle justeringene: én justering i telleren og ingen i nevneren gir galt svar.</p>",
      traps: [
        "Formuesskatten trukket fra to ganger i telleren: (6 − 0,02V)/V = 0,08, altså 6/0,10.",
        "Den halve justeringen: kontantstrømmen redusert for formuesskatt, men avkastningskravet fortsatt 8 %. Det er å sammenligne et tall etter skatt med et krav før skatt.",
        "Verdien uten formuesskatt redusert med formuesskattesatsen: 75 × 0,99. Magefølelsen om at skatten må ta litt av verdien.",
        null,
      ],
    },
    {
      id: "k8-5",
      topic: "Utbytte til formuesskatt",
      points: 3,
      body: "<p>Erna eier alle aksjene i et unotert selskap med formuesverdi kr 4 000 000 [eksempeltall]. Hun har ingen midler utenfor selskapet og må ta utbytte for å betale formuesskatten. Formuesskatten er 1,0 % og eierskatten på utbytte er 37,84 %, altså 22 % oppjustert med faktoren 1,72 [dagens regel]. Se bort fra skjermingsfradrag, aksjerabatt og bunnfradrag.</p><p>Hvor stort brutto utbytte må hun ta ut for at det som er igjen etter eierskatt, akkurat dekker formuesskatten?</p>",
      options: ["kr 51 282", "kr 55 136", "kr 64 350", "kr 70 785"],
      answer: 2,
      solution: "<p><b>Steg 1 — regningen som skal dekkes.</b> 4 000 000 × 1,0 % = <b>kr 40 000</b>. Dette er beløpet som må ligge i hånden <i>etter</i> at eierskatten er betalt.</p><p><b>Steg 2 — hva et utbytte gir netto.</b> Av et bruttoutbytte D beholder hun D × (1 − 0,3784) = 0,6216D.</p><p><b>Steg 3 — løs.</b> 0,6216D = 40 000 gir D = 40 000/0,6216 = <b>kr 64 350</b>. Utbyttet må brutto-regnes, altså deles på (1 − t<sub>e</sub>), ikke ganges med (1 + t<sub>e</sub>).</p><p><b>Kontroll:</b> eierskatt 64 350 × 37,84 % = 24 350, og 64 350 − 24 350 = 40 000, nøyaktig formuesskatten. ✓</p><p>Den effektive belastningen er 64 350/4 000 000 = 1,61 % av formuesverdien, ikke 1,0 %. Formelen er τ<sub>w</sub>/(1 − t<sub>e</sub>) = 1,0 %/0,6216 = 1,61 %. Med 5 % avkastning svarer det til en avkastningsskatt på 1,61/5 = 32,2 %, mot 20 % for formuesskatten alene. Det er dette forelesningen bygger sitt hovedargument på for eiere uten likvide midler. H2025 oppgave 6 er samme regnestykke med eierskatt 50 %, der formuesskatt kr 1 000 krever kr 2 000 i utbytte.</p>",
      traps: [
        "Oppjusteringen glemt: 40 000/(1 − 0,22). Eierskatten er 22 % av et oppjustert grunnlag, altså 37,84 %, ikke 22 %.",
        "Skatten lagt oppå i stedet for brutto-regnet: 40 000 × 1,3784. Test den: kr 55 136 gir 34 273 etter eierskatt, og da mangler kr 5 727 på formuesskatten.",
        null,
        "Formuesskattesatsen 1,1 % brukt, som først gjelder for formue over kr 21 500 000: 44 000/0,6216. Ruten er ellers riktig.",
      ],
    },
    {
      id: "k8-6",
      topic: "Effektiv skatt",
      points: 3,
      body: "<p>En investor eier et unotert selskap som tjener kr 100 i året før skatt, i all framtid. Diskonteringsrenten er 12,22 %, så markedsverdien er 100/0,1222 = kr 818. Den gjennomsnittlige effektive selskapsskatten i norske selskaper er 13,1 %, og et unotert selskap verdsettes for formuesskatt til om lag 35 % av markedsverdien [eksempeltall fra forelesningen]. Formuesskatten er 1,1 % og eierskatten 37,84 % [dagens regel]. Eieren tar utbytte for å dekke formuesskatten, og selskapet har ingen gjeld.</p><p>Hvor stor andel av bruttoinntekten på kr 100 går til skatt til sammen?</p>",
      options: ["13,1 %", "16,2 %", "18,2 %", "24,7 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — selskapsleddet.</b> 100 × 13,1 % = <b>kr 13,10</b>. Merk at det er den effektive satsen som brukes, ikke den nominelle på 22 %.</p><p><b>Steg 2 — formuesskatten.</b> Formuesverdien er 818 × 0,35 = 286,30, og skatten 286,30 × 1,1 % = <b>kr 3,15</b>.</p><p><b>Steg 3 — utbyttet som må til, og skatten på det.</b> D = 3,15/(1 − 0,3784) = 5,07, og eierskatten er 5,07 × 37,84 % = <b>kr 1,92</b>.</p><p><b>Steg 4 — summen.</b> 13,10 + 3,15 + 1,92 = 18,17, altså <b>18,2 %</b> av bruttoinntekten på 100. Forelesningen runder mellomresultatene og skriver 18,1 %.</p><p><b>Kontroll med det børsnoterte tilfellet:</b> verdsettes selskapet til 80 % av markedsverdien, blir formuesverdien 654,40, formuesskatten 7,20, utbyttet 11,58 og eierskatten 4,38. Sum: 13,10 + 7,20 + 4,38 = 24,68, altså 24,7 %. ✓ Hele forskjellen mellom 18,2 og 24,7 kommer fra verdsettingen, ikke fra selskapsskatten eller eierskatten.</p><p>En portefølje med en tredel børsnotert og to tredeler unotert, som er omtrent sammensetningen hos topp 1 %, gir (24,7 + 2 × 18,2)/3 ≈ 20 %. Det ligger nær de om lag 22 % SSB-forskningen måler for denne gruppen, mot 33 % for dem mellom 90. og 99. prosentil. Årsaken til at kurven faller på toppen er lav effektiv selskapsskatt og lav formuesverdsetting av unoterte aksjer, ikke omgåelse av utbytteskatten.</p>",
      traps: [
        "Bare selskapsskatten. Formuesskatten og eierskatten på utbyttet som finansierer den er utelatt.",
        "Utbytteskatten glemt: 13,10 + 3,15 = 16,25, som med uavrundede mellomresultater er 16,2 %. Formuesskatten kan ikke betales uten at det tas utbytte, og utbyttet beskattes selv.",
        null,
        "Regnet med børsnotert verdsetting, 80 % av markedsverdien, i stedet for de 35 % som gjelder unoterte selskaper.",
      ],
    },
    {
      id: "k8-7",
      topic: "Lav avkastning",
      points: 3,
      body: "<p>La W = kr 4 000 000 være markedsverdien av et aksjefond ved periodens begynnelse, og la r = 0,5 % være avkastningen i et svakt år, som realiseres ved periodens slutt [eksempeltall]. Formuesskatten er τ<sub>w</sub> = 1,0 % og faller på formuesverdien ved <b>periodens begynnelse</b>. Aksjefond verdsettes til 80 % av markedsverdien, altså med en rabatt på 20 % [dagens regel]. Se bort fra bunnfradrag.</p><p>Hvor høy må en skatt t på avkastningen være for at de to skattene skal gi samme proveny? Oppgi svaret med én desimal.</p>",
      options: [
        "62,5 %",
        "160,0 %",
        "160,8 %",
        "200,0 %",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — formuesskattens proveny.</b> Grunnlaget er formuesverdien ved inngangen, ikke markedsverdien: 4 000 000 × 0,80 = 3 200 000, og skatten er 3 200 000 × 1,0 % = <b>kr 32 000</b>.</p><p><b>Steg 2 — avkastningen en avkastningsskatt ville truffet.</b> 4 000 000 × 0,5 % = <b>kr 20 000</b>. Avkastningen regnes av det fondet faktisk er verdt; rabatten gjelder bare formuesskatten.</p><p><b>Steg 3 — sett provenyene like.</b> 20 000 × t = 32 000 gir t = 32 000/20 000 = <b>160,0 %</b>. Med formelen: t = τ<sub>w</sub>(1 − ρ)/r = 1,0 % × 0,80/0,5 % = 160 %.</p><p><b>Kontroll:</b> 20 000 × 1,60 = 32 000, nøyaktig formuesskatten. ✓ Formuen krymper også: etter avkastning og formuesskatt har eieren 4 000 000 + 20 000 − 32 000 = 3 988 000, mindre enn han startet med.</p><p>En sats over 100 % er ikke en regnefeil. Den sier at formuesskatten tar mer enn hele avkastningen, og at resten må betales av selve formuen. Det skjer hver gang r er lavere enn τ<sub>w</sub>(1 − ρ), her 0,8 %. Ved null avkastning finnes det ingen avkastningsskatt som gir samme proveny. Ved negativ avkastning ville en avkastningsskatt med fradrag for tap gitt penger tilbake, mens formuesskatten fortsatt er kr 32 000. Det er dette forelesningen mener med at formuesskatten ikke spør om det er noe å skatte av.</p>",
      traps: [
        "Brøken snudd: avkastningen delt på formuesskatten, 20 000/32 000 = 62,5 %. Ekvivalensen er formuesskatt = t × avkastning, så formuesskatten står i telleren.",
        null,
        "Skatten lagt på formuen ved periodens slutt: 4 020 000 × 0,80 × 1,0 % = 32 160, og 32 160/20 000 = 160,8 %. Oppgaven sier periodens begynnelse.",
        "Rabatten glemt: formuesskatten regnet av markedsverdien, 4 000 000 × 1,0 % = 40 000, og 40 000/20 000 = 200,0 %.",
      ],
    },
    {
      id: "k8-8",
      topic: "Samlet skatt på rente",
      points: 3,
      body: "<p>Hanne har kr 2 000 000 på en høyrentekonto ved inngangen til året. Kontoen gir 3 % rente, som godskrives ved årets slutt [eksempeltall]. Renteinntekter skattlegges som alminnelig inntekt med 22 % [dagens regel]. Hanne har så mye annen formue at bunnfradraget allerede er brukt opp, og hun er under innslagspunktet for toppsatsen, så hver krone på kontoen øker formuesskatten med 1,0 % av innskuddet ved inngangen til året [dagens regel]. Bankinnskudd har ingen verdsettingsrabatt.</p><p>Hvor stor andel av renteinntekten går til skatt når inntektsskatten og formuesskatten på innskuddet regnes sammen? Oppgi svaret med én desimal.</p>",
      options: [
        "23,0 %",
        "48,0 %",
        "55,3 %",
        "56,3 %",
      ],
      answer: 2,
      solution: "<p><b>Steg 1 — renteinntekten.</b> 2 000 000 × 3 % = <b>kr 60 000</b>.</p><p><b>Steg 2 — inntektsskatten.</b> 60 000 × 22 % = <b>kr 13 200</b>.</p><p><b>Steg 3 — formuesskatten på innskuddet.</b> Grunnlaget er innskuddet ved inngangen til året, uten rabatt: 2 000 000 × 1,0 % = <b>kr 20 000</b>. Regnet som avkastningsskatt er det 20 000/60 000 = 33,3 %, altså τ<sub>w</sub>/r = 1 %/3 %.</p><p><b>Steg 4 — samlet skatt i prosent av renten.</b> 13 200 + 20 000 = 33 200, og 33 200/60 000 = <b>55,3 %</b>. De to satsene kan legges sammen fordi begge er regnet av den samme renten før skatt: 22 % + 33,3 % = 55,3 %.</p><p><b>Kontroll:</b> etter skatt sitter Hanne igjen med 60 000 − 33 200 = 26 800, som er 26 800/2 000 000 = 1,34 % av innskuddet. Og 1 − 1,34 %/3 % = 55,3 %. ✓</p><p>Legg merke til hvor raskt dette stiger når renten faller: ved 2 % rente blir samlet skatt 22 % + 50 % = 72 %, og med toppsatsen 1,1 % blir det 22 % + 55 % = 77 %. Et bankinnskudd er det aktivumet formuesskatten rammer hardest, fordi det verken har rabatt eller høy avkastning. Regner du i tillegg med inflasjon, kan realavkastningen etter skatt fort bli negativ.</p>",
      traps: [
        "Satsene lagt rett sammen: 22 % + 1,0 % = 23,0 %. Formuesskattesatsen er en andel av formuen, ikke av renten; regnet av renten er den 1 %/3 % = 33,3 %.",
        "Formuesskatten lagt på det som er igjen etter inntektsskatten, slik eierskatt legges oppå selskapsskatt: 22 % + 78 % × 33,3 % = 48,0 %. Formuesskatten er et fast beløp på kr 20 000 og blir ikke mindre av at renten er skattlagt.",
        null,
        "Formuesskatten regnet av innskuddet ved årets slutt: 2 060 000 × 1,0 % = 20 600, og (13 200 + 20 600)/60 000 = 56,3 %. Grunnlaget er formuen ved inngangen til året.",
      ],
    },
    {
      id: "k8-9",
      topic: "Samlet skatt, portefølje",
      points: 3,
      body: "<p>Ingrid har ved inngangen til året kr 2 000 000 i bankinnskudd med 3 % rente og kr 3 000 000 i et aksjefond [eksempeltall]. Fondet stiger 8 % i løpet av året, og hun selger alle andelene ved årets slutt og realiserer gevinsten. Renter skattlegges med 22 %. Gevinsten på fondet skattlegges med 22 % etter oppjustering med faktoren 1,72, altså 37,84 % [dagens regel]. Se bort fra skjermingsfradraget.</p><p>Formuesskatten er 1,0 % av formuesverdien ved inngangen til året. Aksjefond verdsettes til 80 % av markedsverdien og bankinnskudd til 100 % [dagens regel]. Ingrid har annen formue som alene er større enn bunnfradraget på kr 1 900 000, og samlet formue er under innslagspunktet for 1,1 %, så hver krone i banken og fondet beskattes med 1,0 % av formuesverdien.</p><p>Hvor stor andel av den samlede avkastningen på de to plasseringene går til skatt, når skatten på avkastningen og formuesskatten på de to plasseringene regnes med? Oppgi svaret med to desimaler.</p>",
      options: [
        "36,67 %",
        "43,01 %",
        "48,01 %",
        "49,34 %",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — avkastningen.</b> Renter 2 000 000 × 3 % = 60 000 og fondsgevinst 3 000 000 × 8 % = 240 000. Samlet <b>kr 300 000</b>.</p><p><b>Steg 2 — skatten på avkastningen.</b> Renteskatt 60 000 × 22 % = 13 200. Gevinstskatt 240 000 × 1,72 × 22 % = 240 000 × 37,84 % = 90 816. Samlet <b>kr 104 016</b>.</p><p><b>Steg 3 — formuesskatten.</b> Formuesverdiene ved inngangen er 2 000 000 for banken og 3 000 000 × 0,80 = 2 400 000 for fondet, til sammen 4 400 000. Formuesskatten er 4 400 000 × 1,0 % = <b>kr 44 000</b>. Bunnfradraget er allerede brukt opp av den andre formuen og skal ikke trekkes fra her.</p><p><b>Steg 4 — samlet andel.</b> 104 016 + 44 000 = 148 016, og 148 016/300 000 = <b>49,34 %</b>.</p><p><b>Kontroll, plassering for plassering:</b> banken betaler 13 200 + 20 000 = 33 200 av 60 000, altså 55,33 %. Fondet betaler 90 816 + 24 000 = 114 816 av 240 000, altså 47,84 %. Vektet med avkastningen: 0,2 × 55,33 % + 0,8 × 47,84 % = 49,34 %. ✓ Vektene er andelene av avkastningen, 60 000/300 000 og 240 000/300 000, ikke andelene av formuen.</p><p>Legg merke til rekkefølgen: banken har lavest skatt på selve avkastningen (22 % mot 37,84 %), men høyest samlet skatt, fordi den har lav avkastning og ingen verdsettingsrabatt. Formuesskatten utgjør 20 000/60 000 = 33,3 % av renten, men bare 24 000/240 000 = 10,0 % av fondsgevinsten.</p>",
      traps: [
        "Oppjusteringen glemt: fondsgevinsten skattlagt med 22 %, 240 000 × 22 % = 52 800, og (13 200 + 52 800 + 44 000)/300 000 = 36,67 %.",
        "Bunnfradraget trukket fra enda en gang: (4 400 000 − 1 900 000) × 1,0 % = 25 000, og (104 016 + 25 000)/300 000 = 43,01 %. Oppgaven sier at den andre formuen allerede dekker bunnfradraget.",
        "Rabatten brukt også på bankinnskuddet: (2 000 000 + 3 000 000) × 0,80 × 1,0 % = 40 000, og (104 016 + 40 000)/300 000 = 48,01 %. Bankinnskudd har ingen verdsettingsrabatt.",
        null,
      ],
    },
    {
      id: "k8-10",
      topic: "Utbytte med skjerming",
      points: 3,
      body: "<p>Siri eier alle aksjene i et unotert selskap. Aksjenes formuesverdi etter verdsettingsrabatten er kr 20 000 000, og hun har ingen annen formue og ingen gjeld. Formuesskatten er 1,0 % av nettoformuen over bunnfradraget på kr 1 900 000; formuen hennes er under innslagspunktet for 1,1 % [dagens regel, 2026]. Hun har ingen likvide midler og må ta utbytte fra selskapet for å betale formuesskatten.</p><p>Aksjenes skjermingsgrunnlag er kr 2 000 000, og hun har ingen ubenyttet skjerming fra tidligere år. Anta at skjermingsrenten er 3,6 % [eksempeltall, satsen for 2025]. Den delen av utbyttet som overstiger skjermingsfradraget, oppjusteres med 1,72 og skattlegges med 22 % [dagens regel].</p><p>Hvor stort bruttoutbytte må Siri ta for at det som er igjen etter eierskatt, akkurat dekker formuesskatten? Rund av til hele kroner.</p>",
      options: [
        "kr 247 354",
        "kr 265 701",
        "kr 277 920",
        "kr 291 184",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — formuesskatten.</b> (20 000 000 − 1 900 000) × 1,0 % = <b>kr 181 000</b>. Dette beløpet må ligge i hånden etter eierskatt.</p><p><b>Steg 2 — skjermingsfradraget.</b> 2 000 000 × 3,6 % = <b>kr 72 000</b>. Denne delen av utbyttet er skattefri.</p><p><b>Steg 3 — eierskatten som funksjon av utbyttet D.</b> Skattepliktig er D − 72 000, og skatten er (D − 72 000) × 1,72 × 22 % = 0,3784 × (D − 72 000). Skjermingen trekkes fra <i>før</i> oppjusteringen.</p><p><b>Steg 4 — løs.</b> Kravet er D − 0,3784 × (D − 72 000) = 181 000. Skjermingen sparer 72 000 × 0,3784 = 27 244,80 i skatt, så 0,6216 × D = 181 000 − 27 244,80 = 153 755,20, og D = 153 755,20/0,6216 = <b>kr 247 354</b>.</p><p><b>Kontroll:</b> skattepliktig utbytte er 247 354 − 72 000 = 175 354, eierskatten 175 354 × 37,84 % = 66 354, og 247 354 − 66 354 = 181 000, nøyaktig formuesskatten. ✓</p><p>Skjermingen senker det nødvendige utbyttet med 291 184 − 247 354 = 43 830 kroner, fordi den skjermede delen går rett til formuesskatten uten å beskattes. Brutto-regningen gjelder bare den skattepliktige delen. H2025 oppgave 6 ba deg se bort fra både skjerming og bunnfradrag, og H2024 oppgave 7 nevnte dem ikke; når oppgaven tar dem med, regner du formuesskatten og skjermingen hver for seg først, og løser for D til slutt.</p>",
      traps: [
        null,
        "Skjermingen trukket fra etter oppjusteringen: skatten satt til 22 % × (1,72 × D − 72 000) = 0,3784 × D − 15 840, som gir D = (181 000 − 15 840)/0,6216 = 265 701. Skjermingsfradraget trekkes fra utbyttet før det oppjusteres.",
        "Bunnfradraget glemt: formuesskatten satt til 20 000 000 × 1,0 % = 200 000, og D = (200 000 − 27 244,80)/0,6216 = 277 920.",
        "Skjermingen glemt: hele utbyttet skattlagt, D = 181 000/0,6216 = 291 184. Det er riktig rute når oppgaven ber deg se bort fra skjerming, men ikke her.",
      ],
    },
    {
      id: "k8-11",
      topic: "Provenynøytral omlegging",
      points: 3,
      body: "<p>To investorer eier hver sin formue ved inngangen til året [eksempeltall]. Anne har kr 15 000 000 i en plassering som gir 2 % avkastning. Bjørn har kr 5 000 000 i en plassering som gir 10 % avkastning. I dag betaler begge formuesskatt på 1,0 % av formuen ved inngangen til året. Se bort fra bunnfradrag, verdsettingsrabatter og all annen skatt.</p><p>Staten vurderer å erstatte formuesskatten med en proporsjonal skatt t på avkastningen, slik at de to til sammen betaler like mye skatt som i dag. Hvilken sats t gir det? Oppgi svaret med én desimal.</p>",
      options: [
        "16,7 %",
        "25,0 %",
        "30,0 %",
        "50,0 %",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — provenyet i dag.</b> Anne: 15 000 000 × 1,0 % = 150 000. Bjørn: 5 000 000 × 1,0 % = 50 000. Samlet <b>kr 200 000</b>.</p><p><b>Steg 2 — samlet avkastning.</b> Anne: 15 000 000 × 2 % = 300 000. Bjørn: 5 000 000 × 10 % = 500 000. Samlet <b>kr 800 000</b>.</p><p><b>Steg 3 — løs for t.</b> 800 000 × t = 200 000 gir t = 200 000/800 000 = <b>25,0 %</b>.</p><p><b>Kontroll:</b> den formuesvektede gjennomsnittsavkastningen er 800 000/20 000 000 = 4 %, og ekvivalensen τ<sub>w</sub>/r med denne avkastningen gir 1 %/4 % = 25 %. ✓</p><p><b>Hvem vinner, og hvem taper?</b> Med avkastningsskatten betaler Anne 300 000 × 25 % = 75 000, altså 75 000 mindre enn i dag. Bjørn betaler 500 000 × 25 % = 125 000, altså 75 000 mer. Summen er fortsatt 75 000 + 125 000 = 200 000. Formuesskatten legger byrden på den med lav avkastning: for Anne tilsvarer den en avkastningsskatt på 50 %, for Bjørn bare 10 %.</p><p>Dette er kjernen i uenigheten mellom pensumartiklene. Adam og Miller kritiserer at formuesskatten treffer normalavkastningen hardt og meravkastningen ikke i det hele tatt. Magma-artikkelen fører den samme egenskapen som et argument <i>for</i> skatten, med støtte i en simuleringsstudie: den flytter kapital fra lavavkastende til høyavkastende eiere. Ekvivalensen τ<sub>w</sub> = r × t gjelder for hver enkelt bare når alle har samme avkastning.</p>",
      traps: [
        "Snittet av de to avkastningene uten vekting: (2 % + 10 %)/2 = 6 %, og 1 %/6 % = 16,7 %. Bjørns avkastning teller like mye som Annes, selv om Anne har tre ganger så stor formue.",
        null,
        "Snittet av de to individuelle ekvivalente satsene: Anne 1 %/2 % = 50 %, Bjørn 1 %/10 % = 10 %, og (50 % + 10 %)/2 = 30,0 %. Et snitt av satser gir ikke samme proveny; det er kronene som skal summeres.",
        "Annes ekvivalente sats, 1 %/2 % = 50 %, brukt for begge. Den ville gitt 800 000 × 50 % = 400 000, dobbelt så mye som i dag.",
      ],
    },
    {
      id: "k8-12",
      topic: "Unotert mot børsnotert",
      points: 3,
      body: "<p>Kapitalmarkedet er effisient, slik at alle investeringer i samme risikoklasse gir samme avkastning. En norsk investor kan kjøpe børsnoterte aksjer i en risikoklasse som gir 8 % avkastning før skatt [eksempeltall]. Formuesskatten er 1,0 % av formuesverdien ved periodens begynnelse, og børsnoterte aksjer verdsettes til 80 % av markedsverdien [dagens regel].</p><p>Han vurderer i stedet å kjøpe alle aksjene i et unotert selskap i samme risikoklasse. Det gir en evigvarende kontantstrøm til eieren på kr 4 000 000 i året. Den unoterte aksjen verdsettes etter selskapets bokførte verdier, og formuesverdien etter rabatt er kr 16 000 000 hvert år, uansett hva han betaler for aksjene. Formuesskatten trekkes fra den årlige kontantstrømmen. Se bort fra bunnfradrag, gjeld og skatt på utbytte og gevinst.</p><p>Hva er det høyeste beløpet han er villig til å betale for det unoterte selskapet?</p>",
      options: [
        "48,0 mill. kr",
        "48,8 mill. kr",
        "50,0 mill. kr",
        "53,3 mill. kr",
      ],
      answer: 3,
      solution: "<p><b>Steg 1 — alternativkostnaden etter formuesskatt.</b> Formuesskatten treffer også alternativet. På de børsnoterte aksjene trekker den 1,0 % × 0,80 = 0,8 prosentpoeng fra avkastningen, så kravet blir 8 % − 0,8 % = <b>7,2 %</b>.</p><p><b>Steg 2 — netto kontantstrøm fra det unoterte selskapet.</b> Formuesskatten er 16 000 000 × 1,0 % = 160 000, et fast beløp fordi formuesverdien ikke følger prisen. Netto: 4 000 000 − 160 000 = <b>kr 3 840 000</b>.</p><p><b>Steg 3 — verdien.</b> V = 3 840 000/0,072 = <b>kr 53 333 333</b>, altså 53,3 mill. kr.</p><p><b>Kontroll:</b> betaler han 53 333 333, gir investeringen 3 840 000/53 333 333 = 7,2 % etter formuesskatt, nøyaktig det samme som alternativet. ✓ En utenlandsk investor uten formuesskatt ville verdsatt selskapet til 4 000 000/0,08 = 50 000 000.</p><p>Den norske investoren er altså villig til å betale <i>mer</i> enn utlendingen. Nøytralitetsresultatet fra H2025 oppgave 3, V = CF/r, forutsetter at formuesskatten treffer investeringen og alternativet likt. Her er formuesverdien av det unoterte selskapet 16 000 000/53 333 333 = 30 % av prisen, mot 80 % på børsen, og den lave verdsettingen gjør det unoterte selskapet billigere å eie. Det er verdsettingsforskjellen, ikke formuesskatten som sådan, som vrir kapitalen mot unoterte aksjer.</p>",
      traps: [
        "Den halve justeringen: kontantstrømmen redusert for formuesskatt, men avkastningskravet fortsatt 8 %: 3 840 000/0,08 = 48,0 mill. Alternativet rammes også av formuesskatten, så kravet er 7,2 %.",
        "Formuesskatten regnet som 1,0 % av markedsverdien V, slik som i H2025 oppgave 3, i stedet for av den oppgitte formuesverdien: (4 000 000 − 0,01 × V)/V = 0,072 gir V = 4 000 000/0,082 = 48,8 mill.",
        "Nøytralitetsresultatet V = CF/r brukt uten å sjekke forutsetningen: 4 000 000/0,08 = 50,0 mill. Det gjelder bare når formuesskatten treffer investeringen og alternativet i samme forhold til markedsverdien.",
        null,
      ],
    },
    {
      id: "k8-13",
      topic: "Unoterte aksjer",
      points: 3,
      body: "<p>Leif eier alle aksjene i et unotert selskap. Aksjene har en markedsverdi på kr 60 000 000. Den skattemessige formuesverdien, som bygger på selskapets bokførte verdier, er kr 25 000 000, og unoterte aksjer verdsettes til 80 % av denne [dagens regel]. Aksjene gir 7,5 % avkastning regnet av markedsverdien [eksempeltall]. Leif har så mye annen formue at hver krone her beskattes med toppsatsen på 1,1 % [dagens regel], og formuesskatten faller på formuen ved inngangen til året.</p><p>Hva er formuesskatten på aksjene regnet som en skatt på avkastningen av dem, altså den ekvivalente avkastningsskatten? Oppgi svaret med to desimaler.</p>",
      options: [
        "0,37 %",
        "4,89 %",
        "6,11 %",
        "11,73 %",
      ],
      answer: 1,
      solution: "<p><b>Steg 1 — formuesverdien.</b> 25 000 000 × 0,80 = <b>kr 20 000 000</b>, en tredel av markedsverdien.</p><p><b>Steg 2 — formuesskatten.</b> 20 000 000 × 1,1 % = <b>kr 220 000</b>.</p><p><b>Steg 3 — avkastningen.</b> Den regnes av det aksjene faktisk er verdt: 60 000 000 × 7,5 % = <b>kr 4 500 000</b>.</p><p><b>Steg 4 — ekvivalent avkastningsskatt.</b> 220 000/4 500 000 = <b>4,89 %</b>.</p><p><b>Kontroll med formelen:</b> t = τ<sub>w</sub> × (formuesverdi/markedsverdi)/r = 1,1 % × (20/60)/7,5 % = 4,89 %. ✓</p><p>Sammenlign med en eier av børsnoterte aksjer med samme markedsverdi og avkastning: 60 000 000 × 0,80 × 1,1 % = 528 000, og 528 000/4 500 000 = 11,73 %. Den unoterte eieren har under halvparten av den ekvivalente satsen. Det er en av de to grunnene til at den effektive skattesatsen faller på toppen av fordelingen, der om lag to tredeler av formuen ligger i unoterte aksjer. Den andre er lav effektiv selskapsskatt.</p>",
      traps: [
        "Formuesskatten delt på markedsverdien i stedet for på avkastningen: 220 000/60 000 000 = 0,37 %. Det er formuesskatten som andel av formuen, ikke som andel av avkastningen.",
        null,
        "Rabatten på 20 % glemt: 25 000 000 × 1,1 % = 275 000, og 275 000/4 500 000 = 6,11 %.",
        "Aksjene verdsatt som om de var børsnoterte, til 80 % av markedsverdien: 60 000 000 × 0,80 × 1,1 % = 528 000, og 528 000/4 500 000 = 11,73 %. Unoterte aksjer verdsettes etter bokførte verdier, ikke etter markedsverdi.",
      ],
    },
    {
      id: "k8-14",
      topic: "De rikeste",
      points: 3,
      body: "<p>SSB-forskningen bak forelesning 8 måler effektiv skattesats som betalt skatt i prosent av bruttoinntekt, der selskapenes overskudd og selskapsskatt regnes med hos eierne. I 2004–2018 var satsen om lag 33 % for dem mellom 90. og 99. prosentil, om lag 22 % for topp 1 % og mellom 9 og 17 % for topp 0,1 %.</p><p>Hvilken forklaring på at den effektive satsen faller på toppen, legger forelesningen og Bjerksund, Hopland og Schjelderup til grunn?</p>",
      options: [
        "De rikeste har om lag to tredeler av formuen i unoterte aksjer, som verdsettes langt under markedsverdien i formuesskatten, og selskapene deres betaler en effektiv selskapsskatt godt under 22 %.",
        "De rikeste har mesteparten av formuen i børsnoterte aksjer, og verdsettingsrabatten på 20 % holder formuesskatten deres nede.",
        "Unoterte aksjer er unntatt fra formuesskatt, så de rikeste betaler formuesskatt bare på bolig, bankinnskudd og børsnoterte aksjer.",
        "De rikeste unngår eierskatten ved å føre utbyttet ut til skatteparadis, slik at bare selskapsskatten blir igjen.",
      ],
      answer: 0,
      solution: "<p><b>Riktig er A.</b> Regnestykket til Bjerksund, Hopland og Schjelderup tar et selskap som tjener kr 100 før skatt og er verdt 818 i markedet. Med effektiv selskapsskatt 13,1 %, formuesskatt 1,1 % og utbytte tatt ut bare for å dekke formuesskatten, blir samlet effektiv skatt 24,7 % når selskapet er børsnotert og verdsettes til 80 % av kursen, men 18,2 % når det er unotert og verdsettes til om lag 35 % av markedsverdien. Formuesverdien er 818 × 0,80 = 654,4 i det første tilfellet og 818 × 0,35 = 286,3 i det andre.</p><p><b>Mekanismen.</b> Formuesskatten virker som en skatt på avkastningen med sats τ<sub>w</sub> × (formuesverdi/markedsverdi)/r. Er formuesverdien lav i forhold til markedsverdien, blir den ekvivalente satsen lav, og det samme blir utbyttet som må tas ut for å betale den, og dermed eierskatten. Lav effektiv selskapsskatt trekker i samme retning.</p><p><b>Kontroll mot tallene:</b> en portefølje med en tredel børsnotert og to tredeler unotert gir (24,7 % + 2 × 18,2 %)/3 = 20,4 %, nær de om lag 22 % som måles for topp 1 %. ✓</p><p>Konklusjonen er at den lave verdsettingen av unoterte aksjer gjør formuesskatten til et lite treffsikkert omfordelingsverktøy nettopp på toppen, der formuen er størst.</p>",
      traps: [
        null,
        "Sammensetningen er snudd: om lag to tredeler av formuen på toppen ligger i unoterte aksjer, og børsnotert eierskap gir tvert imot den høyeste effektive satsen i regnestykket, 24,7 % mot 18,2 %.",
        "Unoterte aksjer er formuesskattepliktige. De verdsettes etter bokførte verdier med 20 % rabatt, som i snitt gir om lag 35–40 % av markedsverdien. Skatten er lav fordi grunnlaget er lavt, ikke fordi den mangler.",
        "Forelesningens forklaring handler om regler som følges, ikke om unndragelse: lav formuesverdsetting og lav effektiv selskapsskatt. Skatteparadis er et eget tema i kapittel 13, og et alternativ som peker på dem som hovedforklaring her, er galt.",
      ],
    },
    {
      id: "k8-15",
      topic: "Formuesskatt over tid",
      points: 3,
      body: "<p>Tone plasserer kr 1 000 000 i et fond og lar pengene stå i 30 år. Fondet gir 6 % avkastning i året før skatt [eksempeltall]. Formuesskatten er 1,0 % av formuen ved inngangen til hvert år og betales av fondet ved slutten av året. Se bort fra verdsettingsrabatt, bunnfradrag og all annen skatt.</p><p>Hvor mange prosent lavere er verdien etter 30 år enn den ville vært uten formuesskatt? Oppgi svaret med én desimal.</p>",
      options: [
        "24,8 %",
        "26,0 %",
        "30,0 %",
        "32,9 %",
      ],
      answer: 0,
      solution: "<p><b>Steg 1 — vekstfaktoren med formuesskatt.</b> Formuen W gir 0,06 × W i avkastning, og skatten er 0,01 × W av formuen ved inngangen. Formuen vokser derfor med faktoren 1 + 0,06 − 0,01 = <b>1,05</b> i året.</p><p><b>Steg 2 — sluttverdiene.</b> Med formuesskatt: 1 000 000 × 1,05<sup>30</sup> = <b>kr 4 321 942</b>. Uten: 1 000 000 × 1,06<sup>30</sup> = <b>kr 5 743 491</b>.</p><p><b>Steg 3 — reduksjonen.</b> 1 − 4 321 942/5 743 491 = 1 − 0,7525 = 0,2475, altså <b>24,8 %</b>. Direkte: 1 − (1,05/1,06)<sup>30</sup>.</p><p><b>Kontroll med ekvivalensen:</b> τ<sub>w</sub>/r = 1 %/6 % = 16,7 %, og en skatt på en sjettedel av avkastningen hvert år gir 6 % × (1 − 1/6) = 5 % etter skatt, samme vekstfaktor 1,05. ✓</p><p>Et årlig trekk på én prosent av formuen blir til en fjerdedel av sluttverdien over 30 år. Det er kumulasjonen Adam og Miller peker på: den samme formuen beskattes om igjen hvert år, så den effektive skatten på framtidig konsum stiger jo lenger konsumet utsettes. Tapet blir også større jo lavere avkastningen er, fordi formuesskatten da er en større del av avkastningen.</p>",
      traps: [
        null,
        "Formuesskatten trukket av formuen etter avkastning, altså ved årets slutt: 0,99<sup>30</sup> = 0,7397, som gir 26,0 %. Oppgaven sier 1 % av formuen ved inngangen til året, og da er vekstfaktoren 1,06 − 0,01 = 1,05, ikke 1,06 × 0,99 = 1,0494.",
        "Lineær regning: 30 × 1,0 % = 30,0 %. Skatten tas hvert år av en formue som både har vokst og allerede er redusert av tidligere års skatt, så prosentene kan ikke summeres.",
        "Riktige sluttverdier, men forskjellen delt på verdien med formuesskatt i stedet for verdien uten: 5 743 491/4 321 942 − 1 = 32,9 %. Spørsmålet er hvor mye lavere verdien er enn uten skatt, så nevneren er 5 743 491.",
      ],
    },
  ],
};
