/* Kapittel 8 — Formuesskatt som avkastningsskatt: verdsetting, utbytte og de rikeste */
window.EDU_DATA.chapterTasks[8] = {
  minutes: 22,
  tasks: [
    {
      id: "k8-1",
      topic: "Ekvivalensen",
      points: 3,
      body: "<p>Kari har en finansformue på kr 8 000 000 ved inngangen til året [eksempeltall]. Formuen gir 4 % avkastning, som realiseres ved periodens slutt. Formuesskatten er 1,0 % [dagens regel] og faller på formuen ved <b>periodens begynnelse</b>. Se bort fra bunnfradrag og verdsettingsrabatt.</p><p>Hvor høy må en skatt på kapitalavkastningen være for at de to skattene skal gi nøyaktig samme proveny?</p>",
      options: ["20,0 %", "25,0 %", "26,0 %", "33,3 %"],
      answer: 1,
      solution: "<p><b>Steg 1 — formuesskattens proveny.</b> Grunnlaget er formuen ved inngangen: 8 000 000 × 1,0 % = <b>kr 80 000</b>. Beløpet er fast og avhenger ikke av hva formuen kaster av seg.</p><p><b>Steg 2 — avkastningsskattens grunnlag.</b> Den treffer avkastningen, ikke beholdningen: 8 000 000 × 4 % = <b>kr 320 000</b>.</p><p><b>Steg 3 — sett provenyene like.</b> 320 000 × t = 80 000 gir t = 80 000/320 000 = <b>25,0 %</b>. Med formelen: t = τ<sub>w</sub>/r = 1 %/4 % = 25 %.</p><p><b>Kontroll:</b> 8 000 000 × 0,04 × 0,25 = 80 000, nøyaktig formuesskatten. ✓</p><p>Formuen stryker seg på begge sider, så svaret avhenger bare av forholdet mellom satsen og avkastningen. Samme rute som H2025 oppgave 9, der 1,0 % og 5 % ga 20 %. Fordi r står i nevneren, stiger den ekvivalente satsen bratt når avkastningen faller: ved 2 % avkastning tilsvarer en formuesskatt på 1,0 % en avkastningsskatt på 50 %.</p>",
      traps: [
        "Nevneren er blåst opp med formuesskattesatsen: 80 000/(8 000 000 × 5 %). Grunnlaget for avkastningsskatten er avkastningen alene, 4 %.",
        null,
        "Skatten lagt på formuen ved periodens slutt: 8 000 000 × 1,04 × 1,0 % = 83 200, delt på 320 000. Oppgaven sier uttrykkelig periodens begynnelse.",
        "Avkastningen etter formuesskatt, 3 %, brukt i nevneren: 80 000/240 000. Ekvivalensen måler de to skattene mot samme grunnlag før skatt.",
      ],
    },
    {
      id: "k8-2",
      topic: "Ekvivalensen baklengs",
      points: 3,
      body: "<p>Et land har i dag en skatt på kapitalavkastning på 30 % og vurderer å bytte den ut med en formuesskatt som gir like mye i proveny [eksempeltall]. En skattyter har kr 10 000 000 ved inngangen til året, og avkastningen er 3 %. Formuesskatten skal falle på formuen ved <b>periodens slutt</b>.</p><p>Hvilken formuesskattesats gir samme proveny som dagens avkastningsskatt?</p>",
      options: ["0,87 %", "0,90 %", "0,93 %", "1,00 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — dagens proveny.</b> Avkastningen er 10 000 000 × 3 % = 300 000, og skatten på den er 300 000 × 30 % = <b>kr 90 000</b>.</p><p><b>Steg 2 — formuesskattens grunnlag.</b> Skatten faller på formuen ved periodens slutt, altså etter at avkastningen er lagt til: 10 000 000 × 1,03 = <b>kr 10 300 000</b>.</p><p><b>Steg 3 — løs for satsen.</b> 10 300 000 × τ<sub>w</sub> = 90 000 gir τ<sub>w</sub> = 0,873786 %, altså <b>0,87 %</b>. Med formelen: τ<sub>w</sub> = t × r/(1 + r) = 0,30 × 0,03/1,03 = 0,87 %.</p><p><b>Kontroll:</b> gå den andre veien. 90 000/10 300 000 = 0,873786 %, og formelen t × r/(1 + r) gir det samme. ✓</p><p>Falt skatten i stedet på inngående formue, ville svaret vært τ<sub>w</sub> = r × t = 0,03 × 0,30 = 0,90 %. Tre hundredeler av et prosentpoeng skiller de to, og det eneste som avgjør, er setningen om tidspunktet. H2021 oppgave 3 spurte på nøyaktig denne måten, med t = 22 % og r = 3 % på utgående formue, og svaret var 0,64 %.</p>",
      traps: [
        null,
        "Formelen for inngående formue brukt: 0,03 × 0,30 = 0,90 %. Tidspunktet i oppgaveteksten er oversett, og det er hele forskjellen mellom de to rutene.",
        "Justeringen for periodens slutt gjort feil vei: ganget med 1,03 i stedet for delt på 1,03.",
        "Dagens norske formuesskattesats hentet fra hukommelsen i stedet for regnet ut av ekvivalensen. Svaret følger av oppgavens tall, ikke av norsk sats.",
      ],
    },
    {
      id: "k8-3",
      topic: "Avkastning etter formuesskatt",
      points: 3,
      body: "<p>Jonas kjøper børsnoterte aksjer for kr 5 000 000 ved inngangen til året, mottar kr 300 000 i kontantutbytte ved årets slutt og selger aksjene for kr 5 000 000 [eksempeltall]. Formuesskatten er 1,0 % og faller på formuen ved inngangen til året, og børsnoterte aksjer verdsettes til 80 % av markedsverdien, altså en rabatt på 20 % [dagens regel]. Se bort fra bunnfradrag, skjerming og skatt på kapitalavkastning.</p><p>Hva er Jonas' avkastning etter formuesskatt?</p>",
      options: ["4,80 %", "5,00 %", "5,20 %", "6,00 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — avkastningen før formuesskatt.</b> Kjøpspris og salgspris er like, så kapitalgevinsten er null, og hele avkastningen er direkteavkastningen: r = 300 000/5 000 000 = <b>6 %</b>.</p><p><b>Steg 2 — formuesskatten.</b> Grunnlaget er formuesverdien, ikke markedsverdien: 5 000 000 × 0,80 = 4 000 000. Skatten blir 4 000 000 × 1,0 % = <b>kr 40 000</b>.</p><p><b>Steg 3 — avkastningen etter.</b> (300 000 − 40 000)/5 000 000 = 260 000/5 000 000 = <b>5,2 %</b>. Nevneren er det han faktisk investerte, ikke formuesverdien.</p><p><b>Kontroll med formelen:</b> r − τ<sub>w</sub>(1 − ρ) = 6 % − 1,0 % × 0,80 = 6 % − 0,8 prosentpoeng = 5,2 %. ✓</p><p>Fratrekket er altså 0,8 prosentpoeng, uansett hvor høy avkastningen er. Oversatt til en avkastningsskatt: 0,8/6 = 13,3 %. Uten rabatten ville den vært 1,0/6 = 16,7 %. Verdsettingsrabatten er en direkte reduksjon i den ekvivalente avkastningsskatten.</p>",
      traps: [
        "Rabatten lagt til i stedet for trukket fra: formuesverdien satt til 5 000 000 × 1,20 = 6 000 000 og skatten til kr 60 000.",
        "Formuesskatten regnet av markedsverdien, altså rabatten glemt: 5 000 000 × 1,0 % = kr 50 000.",
        null,
        "Avkastningen før formuesskatt. Spørsmålet er hva som er igjen etter at skatten er betalt.",
      ],
    },
    {
      id: "k8-4",
      topic: "Verdsetting",
      points: 3,
      body: "<p>Kapitalmarkedet er effisient, og alle investeringer i samme risikoklasse gir samme avkastning. En norsk investor har et alternativ i denne risikoklassen som gir 8 % avkastning før formuesskatt [eksempeltall]. Han vurderer en investering som gir en evigvarende kontantstrøm på 6 mill. kr i året. Formuesskatten er 1 % [eksempeltall, men nær dagens sats], faller på markedsverdien ved periodens begynnelse og treffer alle aktiva likt. Se bort fra verdsettingsrabatt, bunnfradrag og skatt på kapitalavkastning.</p><p>Hva er investeringen verdt for ham?</p>",
      options: ["60 mill. kr", "66,7 mill. kr", "74,25 mill. kr", "75 mill. kr"],
      answer: 3,
      solution: "<p><b>Steg 1 — alternativkostnaden etter formuesskatt.</b> Formuesskatten er en skatt på personen, ikke på aktivumet: han betaler den også på alternativet. Avkastningen der faller fra 8 % til 8 % − 1 % = <b>7 %</b>, og det er dette kravet den nye investeringen skal måles mot.</p><p><b>Steg 2 — sett opp betingelsen.</b> Formuesverdien er markedsverdien V, så skatten er 0,01V og netto kontantstrøm 6 − 0,01V. Kravet blir (6 − 0,01V)/V = 0,07.</p><p><b>Steg 3 — løs.</b> 6/V − 0,01 = 0,07, altså 6/V = 0,08, som gir V = 6/0,08 = <b>75 mill. kr</b>. Legg merke til at 0,01 stryker seg: V = CF/r, nøyaktig verdien uten formuesskatt.</p><p><b>Kontroll:</b> sett V = 75 tilbake inn. Formuesskatten er 0,75, netto kontantstrøm 6 − 0,75 = 5,25, og avkastningen 5,25/75 = 7 %, nøyaktig alternativkostnaden. Prisen er selvkonsistent. ✓</p><p>Dette er poenget i H2025 oppgave 3 d: skatten senker kontantstrømmen og avkastningskravet like mye, så betalingsviljen er den samme som for en investor uten formuesskatt. Hadde alternativet <i>ikke</i> vært rammet av formuesskatt, ville kravet stått på 8 %, og verdien blitt 6/0,09 = 66,7 mill. Utelukkingsregelen er å telle justeringene: én justering i telleren og ingen i nevneren gir galt svar.</p>",
      traps: [
        "Formuesskatten trukket fra to ganger i telleren: (6 − 0,02V)/V = 0,08, altså 6/0,10.",
        "Den halve justeringen: kontantstrømmen redusert for formuesskatt, men avkastningskravet fortsatt 8 %. Det er å sammenligne et tall etter skatt med et krav før skatt.",
        "Verdien uten formuesskatt redusert med formuesskattesatsen: 75 × 0,99. Magefølelsen om at skatten må ta litt av verdien.",
        null,
      ],
    },
    {
      id: "k8-5",
      topic: "Utbytte til formuesskatt",
      points: 3,
      body: "<p>Erna eier alle aksjene i et unotert selskap med formuesverdi kr 4 000 000 [eksempeltall]. Hun har ingen midler utenfor selskapet og må ta utbytte for å betale formuesskatten. Formuesskatten er 1,0 % og eierskatten på utbytte er 37,84 %, altså 22 % oppjustert med faktoren 1,72 [dagens regel]. Se bort fra skjermingsfradrag, aksjerabatt og bunnfradrag.</p><p>Hvor stort brutto utbytte må hun ta ut for at det som er igjen etter eierskatt, akkurat dekker formuesskatten?</p>",
      options: ["kr 51 282", "kr 55 136", "kr 64 350", "kr 70 785"],
      answer: 2,
      solution: "<p><b>Steg 1 — regningen som skal dekkes.</b> 4 000 000 × 1,0 % = <b>kr 40 000</b>. Dette er beløpet som må ligge i hånden <i>etter</i> at eierskatten er betalt.</p><p><b>Steg 2 — hva et utbytte gir netto.</b> Av et bruttoutbytte D beholder hun D × (1 − 0,3784) = 0,6216D.</p><p><b>Steg 3 — løs.</b> 0,6216D = 40 000 gir D = 40 000/0,6216 = <b>kr 64 350</b>. Utbyttet må brutto-regnes, altså deles på (1 − t<sub>e</sub>), ikke ganges med (1 + t<sub>e</sub>).</p><p><b>Kontroll:</b> eierskatt 64 350 × 37,84 % = 24 350, og 64 350 − 24 350 = 40 000, nøyaktig formuesskatten. ✓</p><p>Den effektive belastningen er 64 350/4 000 000 = 1,61 % av formuesverdien, ikke 1,0 %. Formelen er τ<sub>w</sub>/(1 − t<sub>e</sub>) = 1,0 %/0,6216 = 1,61 %. Med 5 % avkastning svarer det til en avkastningsskatt på 1,61/5 = 32,2 %, mot 20 % for formuesskatten alene. Det er dette forelesningen bygger sitt hovedargument på for eiere uten likvide midler. H2025 oppgave 6 er samme regnestykke med eierskatt 50 %, der formuesskatt kr 1 000 krever kr 2 000 i utbytte.</p>",
      traps: [
        "Oppjusteringen glemt: 40 000/(1 − 0,22). Eierskatten er 22 % av et oppjustert grunnlag, altså 37,84 %, ikke 22 %.",
        "Skatten lagt oppå i stedet for brutto-regnet: 40 000 × 1,3784. Test den: kr 55 136 gir 34 273 etter eierskatt, og da mangler kr 5 727 på formuesskatten.",
        null,
        "Formuesskattesatsen 1,1 % brukt, som først gjelder for formue over kr 21 500 000: 44 000/0,6216. Ruten er ellers riktig.",
      ],
    },
    {
      id: "k8-6",
      topic: "Effektiv skatt",
      points: 3,
      body: "<p>En investor eier et unotert selskap som tjener kr 100 i året før skatt, i all framtid. Diskonteringsrenten er 12,22 %, så markedsverdien er 100/0,1222 = kr 818. Den gjennomsnittlige effektive selskapsskatten i norske selskaper er 13,1 %, og et unotert selskap verdsettes for formuesskatt til om lag 35 % av markedsverdien [eksempeltall fra forelesningen]. Formuesskatten er 1,1 % og eierskatten 37,84 % [dagens regel]. Eieren tar utbytte for å dekke formuesskatten, og selskapet har ingen gjeld.</p><p>Hvor stor andel av bruttoinntekten på kr 100 går til skatt til sammen?</p>",
      options: ["13,1 %", "16,2 %", "18,2 %", "24,7 %"],
      answer: 2,
      solution: "<p><b>Steg 1 — selskapsleddet.</b> 100 × 13,1 % = <b>kr 13,10</b>. Merk at det er den effektive satsen som brukes, ikke den nominelle på 22 %.</p><p><b>Steg 2 — formuesskatten.</b> Formuesverdien er 818 × 0,35 = 286,30, og skatten 286,30 × 1,1 % = <b>kr 3,15</b>.</p><p><b>Steg 3 — utbyttet som må til, og skatten på det.</b> D = 3,15/(1 − 0,3784) = 5,07, og eierskatten er 5,07 × 37,84 % = <b>kr 1,92</b>.</p><p><b>Steg 4 — summen.</b> 13,10 + 3,15 + 1,92 = 18,17, altså <b>18,2 %</b> av bruttoinntekten på 100. Forelesningen runder mellomresultatene og skriver 18,1 %.</p><p><b>Kontroll med det børsnoterte tilfellet:</b> verdsettes selskapet til 80 % av markedsverdien, blir formuesverdien 654,40, formuesskatten 7,20, utbyttet 11,58 og eierskatten 4,38. Sum: 13,10 + 7,20 + 4,38 = 24,68, altså 24,7 %. ✓ Hele forskjellen mellom 18,2 og 24,7 kommer fra verdsettingen, ikke fra selskapsskatten eller eierskatten.</p><p>En portefølje med en tredel børsnotert og to tredeler unotert, som er omtrent sammensetningen hos topp 1 %, gir (24,7 + 2 × 18,2)/3 ≈ 20 %. Det ligger nær de om lag 22 % SSB-forskningen måler for denne gruppen, mot 33 % for dem mellom 90. og 99. prosentil. Årsaken til at kurven faller på toppen er lav effektiv selskapsskatt og lav formuesverdsetting av unoterte aksjer, ikke omgåelse av utbytteskatten.</p>",
      traps: [
        "Bare selskapsskatten. Formuesskatten og eierskatten på utbyttet som finansierer den er utelatt.",
        "Utbytteskatten glemt: 13,10 + 3,15 = 16,25, som med uavrundede mellomresultater er 16,2 %. Formuesskatten kan ikke betales uten at det tas utbytte, og utbyttet beskattes selv.",
        null,
        "Regnet med børsnotert verdsetting, 80 % av markedsverdien, i stedet for de 35 % som gjelder unoterte selskaper.",
      ],
    },
  ],
};
