/* Kapittel 9 — Nøytralitet, skattearbitrasje og bedriftens tilpasning */
window.EDU_DATA.chapterTasks[9] = {
  minutes: 22,
  tasks: [
    {
      id: "k9-1",
      topic: "Begrenset rentefradrag",
      points: 3,
      body: "<p>En bedrift bruker kapital K og har inntektsfunksjonen F(K), med F′(K) &gt; 0 og F″(K) &lt; 0. Renten er 7 % [eksempeltall] og betales på hele kapitalen, men bare andelen α = 0,4 av rentekostnaden er fradragsberettiget (manualen skriver denne andelen A). Overskuddsskatten er 30 % [eksempeltall].</p><p>Hvilket marginalprodukt må den siste kapitalkronen gi for at den skal være verdt å bruke?</p>",
      options: ["8,80 %", "5,57 %", "7,00 %", "10,00 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — verdien etter skatt.</b> Rentekostnaden opptrer to ganger med to roller: hele rK er en utbetaling, men bare αrK gir fradrag. V = F(K) − rK − t[F(K) − αrK].</p><p><b>Steg 2 — deriver.</b> dV/dK = F′(K) − r − t[F′(K) − αr] = 0.</p><p><b>Steg 3 — samle leddene med F′(K).</b> F′(K)(1 − t) = r − tαr = r(1 − αt), altså F′(K) = r(1 − αt)/(1 − t).</p><p><b>Steg 4 — sett inn tallene.</b> Faktoren er (1 − 0,4 × 0,30)/(1 − 0,30) = 0,88/0,70 = 1,2571, og kravet 7 % × 1,2571 = <b>8,80 %</b>, altså 25,7 % høyere marginalprodukt enn de 7 % som ville holdt uten skatt.</p><p><b>Kontroll i kroner.</b> Med K = 1 000 000 og et marginalprodukt på 8,8 % er inntekten 88 000 og renten 70 000. Fradraget er 0,4 × 70 000 = 28 000, grunnlaget 88 000 − 28 000 = 60 000 og skatten 60 000 × 30 % = 18 000. Igjen: 88 000 − 70 000 − 18 000 = <b>0</b>, nøyaktig marginen. ✓</p><p><b>Kontroll av grensene.</b> Uttrykket er lineært i α, med 10,00 % ved α = 0 og 7,00 % ved α = 1. Da skal α = 0,4 gi 10,00 − 0,4 × 3,00 = 8,80 %. ✓ Kravet ligger alltid mellom r og r/(1 − t). H2020 oppgave 3b ba om nøyaktig denne utledningen.</p>",
      traps: [
        null,
        "Teller og nevner er byttet om, r(1 − t)/(1 − αt), og det gir et krav lavere enn renten selv, som ingen innstramming i fradragsretten kan produsere.",
        "Full fradragsrett antatt, α = 1, slik at kravet kollapser til r og hele begrensningen i oppgaven er oversett.",
        "Ingen fradragsrett antatt, α = 0, altså r/(1 − t), som er den øvre grensen og ikke svaret ved α = 0,4.",
      ],
    },
    {
      id: "k9-2",
      topic: "Nøytral overskuddsskatt",
      points: 3,
      body: "<p>Samme bedrift, men nå er hele rentekostnaden fradragsberettiget, altså α = 1. Renten er fortsatt 7 % [eksempeltall]. Skatten på overskudd heves fra 22 % [dagens regel] til 35 % [eksempeltall].</p><p>Hva er bedriftens avkastningskrav F′(K) etter satsøkningen?</p>",
      options: ["4,55 %", "9,45 %", "10,77 %", "7,00 %"],
      answer: 3,
      solution: "<p><b>Steg 1 — skriv opp verdien.</b> Med fullt rentefradrag er skattegrunnlaget selve overskuddet: V = F(K) − rK − t[F(K) − rK] = (1 − t)[F(K) − rK].</p><p><b>Steg 2 — deriver.</b> dV/dK = (1 − t)[F′(K) − r] = 0. Siden (1 − t) er positiv for enhver sats under 100 %, kan den strykes: <b>F′(K) = r = 7,00 %</b>, uavhengig av t.</p><p><b>Steg 3 — hvorfor.</b> Å maksimere andelen (1 − t) av overskuddet er det samme som å maksimere overskuddet, så lenge alle kostnadene ved kapitalen er fradragsberettigede. En ren overskuddsskatt er derfor nøytral: den endrer ikke hvilke prosjekter som lønner seg, bare hvor mye eieren sitter igjen med.</p><p><b>Kontroll i kroner.</b> K = 1 000 000 og et marginalprodukt på 7 %: inntekt 70 000, rente 70 000, grunnlag 0, skatt 0, netto 0 ved både 22 % og 35 %. Et prosjekt som gir 8 %, altså 10 000 i overskudd, gir 7 800 etter 22 % skatt og 6 500 etter 35 %, positivt i begge tilfeller. ✓ Rangeringen er den samme før og etter skatt, som er selve nøytralitetsdefinisjonen. Dette er utledningen H2020 oppgave 3a ba om.</p><p>Merk kontrasten til oppgaven foran: det er begrensningen i rentefradraget, ikke skattesatsen, som skaper kilen.</p>",
      traps: [
        "Renten etter skatt, r(1 − t) = 7 % × 0,65, brukt som avkastningskrav, altså et etter-skatt-tall satt inn i en sammenligning før skatt.",
        "Skattesatsen lagt oppå renten som et påslag, 7 % × 1,35, som om skatten traff kapitalkostnaden i stedet for overskuddet.",
        "r/(1 − t) = 7 %/0,65, som er kravet når renten ikke gir fradrag i det hele tatt, mens fradragsretten her er full.",
        null,
      ],
    },
    {
      id: "k9-3",
      topic: "Formelgjenkjenning",
      points: 3,
      body: "<p>Bedriften maksimerer V = F(K) − rK − t[F(K) − αrK]. Hele renten rK betales, men bare andelen αrK er fradragsberettiget, med 0 &lt; α &lt; 1.</p><p>Hvilket av uttrykkene beskriver bedriftens tilpasning?</p>",
      options: [
        "F′(K) = r(1 − αt)/(1 − t)",
        "F′(K) = r(1 − t)/(1 − αt)",
        "F′(K) = rα/(1 − t)",
        "F′(K) = r/[(1 − t)α]",
      ],
      answer: 0,
      solution: "<p><b>Utledningen.</b> F′(K) − r − t[F′(K) − αr] = 0 gir F′(K)(1 − t) = r(1 − αt), altså F′(K) = r(1 − αt)/(1 − t).</p><p><b>Grensetesten, som er hele utelukkingsrutinen.</b> Sett α = 1: da er alle kostnader fradragsberettigede, og kravet må kollapse til r. Sett α = 0: da er ingenting fradragsberettiget, og kravet må bli r/(1 − t). Bruk r = 8 % og t = 25 % [eksempeltall], så er de to grensene 8,00 % og 8 %/0,75 = 10,67 %.</p><p><b>Uttrykk for uttrykk, med α = 0,6.</b> Det riktige gir 8 % × 0,85/0,75 = 9,07 %, pent mellom grensene. Det andre gir 8 % × 0,75/0,85 = 7,06 %; det passerer α = 1-testen, men ved α = 0 gir det r(1 − t) = 6,00 %, altså et lavere krav enn renten når fradraget forsvinner helt. Det tredje gir 8 % × 0,6/0,75 = 6,40 %, og ved α = 1 gir det 10,67 %, som er svaret for ingen fradragsrett. Det fjerde gir 8 %/(0,75 × 0,6) = 17,78 %, mer enn det dobbelte av renten.</p><p><b>Kontroll.</b> Kravet skal ligge mellom 8,00 % og 10,67 % for enhver α mellom 0 og 1, og det skal falle når α stiger, siden mer fradrag betyr lavere krav og dermed mer kapital. Bare det første uttrykket oppfyller begge deler. ✓ H2025 oppgave 7a ga tre poeng for nettopp denne gjenkjenningen, med fire nesten like brøker.</p>",
      traps: [
        null,
        "Teller og nevner byttet om: uttrykket overlever α = 1-testen, men gir ved α = 0 et krav på r(1 − t), lavere enn renten, som er umulig når fradragsretten er borte.",
        "Begge grensene snudd: uttrykket gir r/(1 − t) når fradraget er fullt og null krav når fradraget er borte.",
        "Kravet vokser når fradragsretten bedres og går mot uendelig når α går mot null, altså riktig mekanisme lest i feil retning.",
      ],
    },
    {
      id: "k9-4",
      topic: "Egenkapitalkravet",
      points: 3,
      body: "<p>Et selskap kan finansiere den neste kapitalkronen med gjeld G eller egenkapital E, slik at K = E + G. Gjeldsrenten er 5 % [eksempeltall] og gir fullt fradrag. Egenkapitalen har samme alternativkostnad, 5 %, fordi eieren kunne plassert pengene til 5 % et annet sted, men den kostnaden er ingen utbetaling og gir derfor ikke fradrag. Skattesatsen er 22 % [dagens regel].</p><p>Hvor stort marginalprodukt må den egenkapitalfinansierte kronen gi?</p>",
      options: ["6,41 %", "3,90 %", "5,00 %", "6,10 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — de to derivasjonene.</b> V = F(E + G) − r(G + E) − t[F(E + G) − rG]. Etter gjeld: ∂V/∂G = F′<sub>G</sub> − r − t(F′<sub>G</sub> − r) = (1 − t)(F′<sub>G</sub> − r) = 0, altså F′<sub>G</sub> = r. Etter egenkapital mangler leddet trG, fordi ingen rente betales: ∂V/∂E = F′<sub>E</sub> − r − t·F′<sub>E</sub> = 0, altså F′<sub>E</sub>(1 − t) = r.</p><p><b>Steg 2 — tallene.</b> F′<sub>G</sub> = 5,00 % og F′<sub>E</sub> = 5 %/0,78 = <b>6,41 %</b>. Egenkapitalkronen må tjene 1/0,78 = 1,2821, altså 28,2 % mer enn gjeldskronen.</p><p><b>Kontroll i kroner.</b> Med E = 1 000 000 gir 6,41 % en inntekt på 64 103. Skatten er 64 103 × 22 % = 14 103, og etter skatt står det igjen 50 000, nøyaktig alternativkostnaden på 5 % × 1 000 000. ✓ Den gjeldsfinansierte kronen: inntekt 50 000, rente 50 000, grunnlag 0, skatt 0, netto 0, altså akkurat marginen ved 5,00 %. ✓</p><p><b>Konsekvensen.</b> Siden F er konkav, faller marginalproduktkurven, og et høyere krav gir et lavere kapitalnivå: E* &lt; G*. Merk at dette er en skatteregel og ingen finansiell naturlov: ga systemet fradrag også for en beregnet egenkapitalrente, ville de to kravene vært like. H2025 oppgave 7b og H2020 oppgave 3c spør om dette.</p>",
      traps: [
        null,
        "r(1 − t) = 5 % × 0,78, altså gjeldens rente etter skatt, som er et etter-skatt-tall satt inn i en sammenligning før skatt.",
        "Gjeldskravet F′<sub>G</sub> = r, som er riktig for den lånefinansierte kronen, men egenkapitalen mangler nettopp fradraget som får de to t-ene til å stryke hverandre.",
        "Skattesatsen lagt oppå renten som et påslag, 5 % × 1,22, i stedet for å dele renten på (1 − t).",
      ],
    },
    {
      id: "k9-5",
      topic: "Skattearbitrasje",
      points: 3,
      body: "<p>Du låner kr 2 500 000 til 4,5 % [eksempeltall] og plasserer hele beløpet i et papir med samme risiko som lånet, også til 4,5 %. Rentene på lånet er fradragsberettigede i alminnelig inntekt med 22 % [dagens regel], mens avkastningen på papiret er skattefri, og prisen på papiret har ennå ikke rukket å tilpasse seg.</p><p>Hva er den årlige gevinsten etter skatt?</p>",
      options: ["Kr 0", "Kr 24 750", "Kr 53 325", "Kr 112 500"],
      answer: 1,
      solution: "<p><b>Steg 1 — kostnadssiden.</b> Renten er 2 500 000 × 4,5 % = 112 500. Fradraget er verdt 112 500 × 22 % = 24 750, så kostnaden etter skatt er 112 500 × 0,78 = <b>87 750</b>.</p><p><b>Steg 2 — inntektssiden.</b> Papiret gir 112 500 uavkortet, siden avkastningen ikke skattlegges.</p><p><b>Steg 3 — netto.</b> 112 500 − 87 750 = <b>24 750</b> hvert år, uten innskutt egenkapital og uten risiko, fordi de to sidene har samme rente og samme risiko.</p><p><b>Kontroll med formelen.</b> Årlig gevinst = r × L × (t<sub>fradrag</sub> − t<sub>avkastning</sub>) = 112 500 × (0,22 − 0) = 24 750. ✓ Det er 0,99 % av lånebeløpet, altså nøyaktig renten ganget med satsdifferansen: 4,5 % × 22 % = 0,99 %. Gevinsten er utelukkende satsdifferansen, ikke rentenivået.</p><p><b>Slik lukkes posisjonen.</b> Skattlegges avkastningen symmetrisk som alminnelig inntekt, mottar du 87 750 mot 87 750 i kostnad, altså null. Det er konstruksjonen i det norske duale systemet. Og finnes papiret likevel, bys prisen opp til avkastningen har falt til 4,5 % × 0,78 = 3,51 %, som gir 2 500 000 × 3,51 % = 87 750 skattefritt mot 87 750 i kostnad, altså null igjen. Fallet fra 4,5 % til 3,51 % er den implisitte skatten.</p>",
      traps: [
        "Symmetri antatt, altså at også avkastningen på papiret skattlegges som alminnelig inntekt med 22 %, og da er gevinsten borte.",
        null,
        "Marginalskatten på lønn, 47,4 %, brukt som fradragsverdi (112 500 × 47,4 %), men et rentefradrag er verdt 22 øre per krone uansett hvor høy marginalskatten er.",
        "Hele avkastningen på papiret regnet som gevinst, uten at rentekostnaden etter fradrag på kr 87 750 er trukket fra.",
      ],
    },
    {
      id: "k9-6",
      topic: "Nøytralitetsbrudd",
      points: 3,
      body: "<p>Et skattesystem er nøytralt når rangeringen mellom to plasseringer er den samme før og etter skatt. En bolig har en effektiv skattesats på 10 % og gir 5,0 % avkastning før skatt. En næringsinvestering med samme risiko har en effektiv skattesats på 30 % [eksempeltall for begge satsene].</p><p>Hvor høy avkastning før skatt må næringsinvesteringen minst gi for at investoren skal velge den framfor boligen?</p>",
      options: ["6,43 %", "4,50 %", "5,00 %", "7,14 %"],
      answer: 0,
      solution: "<p><b>Steg 1 — boligen etter skatt.</b> 5,0 % × (1 − 0,10) = <b>4,50 %</b>.</p><p><b>Steg 2 — sett opp kravet.</b> Investoren sammenligner avkastning etter skatt, så næringsinvesteringens x må oppfylle x × (1 − 0,30) ≥ 4,50 %.</p><p><b>Steg 3 — løs.</b> x ≥ 4,50 %/0,70 = <b>6,43 %</b>.</p><p><b>Kontroll.</b> 6,4286 % × 0,70 = 4,50 %, akkurat likt med boligen. ✓</p><p><b>Hva bruddet koster.</b> En næringsinvestering som gir 6,0 % før skatt, altså mer enn boligens 5,0 % og dermed mer verdt for samfunnet, blir likevel valgt bort: 6,0 % × 0,70 = 4,20 % er mindre enn 4,50 %. Samfunnet taper det ene prosentpoenget, og ingen har gjort noe galt, for begge parter følger prisene de faktisk møter. Legg merke til at nivået ikke er problemet: hadde begge aktiva hatt 30 % effektiv sats, ville rangeringen før skatt overlevd, og systemet vært nøytralt til tross for høy skatt.</p>",
      traps: [
        null,
        "Boligens avkastning etter skatt sammenlignet direkte med næringsinvesteringens avkastning før skatt, altså uten at de 30 prosentene er trukket fra.",
        "Nøytralitet lest som lik avkastning før skatt, mens kravet er lik rangering etter skatt, og det krever ulik avkastning før skatt når de effektive satsene er ulike.",
        "Boligens avkastning før skatt oppjustert med næringssatsen, 5,00 %/0,70, slik at det er glemt at også boligen beskattes, med 10 %.",
      ],
    },
  ],
};
